### ISSUE TITLE
Widget padding

### ISSUE THREAD

**Issue by asant0s** [8bitPit/Niagara-Issues#1002]
The padding on the widget area is forcing text to wrap

**To Reproduce**
1. Add Google at a glance widget
2. Remove all other date and time items
3. Save
4. Observe text wrapping due to lack of space

**Smartphone (please complete the following information):**
 - Device: pixel 3a
 - Android version: Android 10

**Screenshots**
![Screenshot_20190918-063014](https://user-images.githubusercontent.com/31213353/65141595-ed607700-d9de-11e9-99f0-d6eb697f7648.png)

**Comment by 8bitPit** [comment]
To give the widget more space you can type in "/widget filled" in Niagara's search. This is still an experimental feature, though.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.

**Comment by craPkit** [comment]
@8bitPit that's a nice feature! How do I reset this setting? 😉

**Comment by 8bitPit** [comment]
@craPkit Either type in "/widget default" or remove the widget. In the future you could also type in "/widget filled" a second time to reset the widget's width.

**Comment by cauerego** [comment]
wanted to add that instead of opening a new issue, i was glad to find this and let you know that this also helped to resolve my very similar issue, right now: https://photos.app.goo.gl/WYXXnq1y91CypHuZ8

this actual issue i've resolved before by manually resizing up the widget.

but, as a curious person, i just wonder if this experimental feature was implemented as a correction to this bug and for how long it'll stay like this since the issue was closed promptly.

**Comment by 8bitPit** [comment]
The option to maximize the widget's size is still experimental, because it's not ideal for every widget. The left and right side of the widget can't be tapped anymore, because the widget area overlaps with the scrollbar.
