### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by NovaStorm64** [8bitPit/Niagara-Issues#1048]
I know this says bug report or something, but installing Niagara my RAM usage seems to have increased from 1.3 GB to 1.5.
Seeing as the app is very simple I was wondering if some sort of patch could make it less memory intensive, as my Moto G4 isn't a very high end phone and I installed as a replacement to the questionable G now launcher.
Thanks for your patience, keep up the good work. This app is so different that I hope it becomes even more successful.

**Comment by NovaStorm64** [comment]
![Screenshot_20191106-165644](https://user-images.githubusercontent.com/53978071/68319573-6ebab880-00b6-11ea-82a9-82f5e6502e1b.png)
Here's a screenshot, set it to 3 hours and it jumps up.

**Comment by 8bitPit** [comment]
Thanks for letting me know @NovaStorm64. Generally speaking, memory consumption of apps doesn't affect your phone's battery or performance. (You'd only notice performance hick-ups if other apps have to be restarted, because they got "kicked out of memory".)  
 In fact - If Niagara consumed less memory it would be slower and more power hungry, because loading stuff like app icons into memory takes time and needs power. 
Btw, here's an interesting article about memory consumption: https://www.androidauthority.com/how-much-ram-do-you-need-in-smartphone-2019-944920/

**Comment by NovaStorm64** [comment]
Thanks, I now understand better. That article was interesting!
Apologies for blaming your app, the only (very small) thing wrong with it is that its in early access still. Thanks for correcting my query.
I look forward to testing new features in the future, so keep up the good work 👌

**Comment by 8bitPit** [comment]
@NovaStorm64 thank you very much 😄

**Comment by NovaStorm64** [comment]
Hello again,
I've recently discovered that despite your advice, Niagara's memory usage has increased surprisingly with the homescreen notification support feature turned on, as shown by the two non Niagara processes below. Wouldn't it be possible to check at launch if pro is purchased and close the process?
And when I disable notifications in the launcher it doesn't even show up in running services in dev options
You don't have to do anything on this, but an acknowledgement would be appreciated.
![Screenshot_20200606-221622](https://user-images.githubusercontent.com/53978071/83954759-f1217b80-a843-11ea-89d6-30f1b56f4595.png)

**Comment by 8bitPit** [comment]
Hi @NovaStorm64 these processes are not bound exclusively to Niagara Launcher, you can read more about that here: https://niagaralauncher.helpscoutdocs.com/article/17-memory-consumption
