### ISSUE TITLE
Dual/Multiple Clocks on Home Screen

### ISSUE THREAD

**Issue by anarendiran** [8bitPit/Niagara-Issues#1056]
**Is your feature request related to a problem? Please describe.**
For people living/traveling abroad it will be very useful to be able to see the time in their home country apart from the time in local country.

**Describe the solution you'd like**
On the home screen I would like to see another Clock displaying time at a chosen Timezone. This time can be displayed right besides the local time display currently in the launcher.

**Comment by 8bitPit** [comment]
Hi @anarendiran, I believe widgets are perfectly suited for this task. Because only a small percentage of Niagaras user base would use a dual clock, I don't want to integrate this directly into Niagara, but still offer the choice of having one by placing a third-party widget on the home screen and hiding Niagara's clock.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.

**Comment by anarendiran** [comment]
Third part widgets are a solution to the problem indeed. I had tried some before opening this issue, nothing suited well. You can place multiple instances of widgets like [this one](https://play.google.com/store/apps/details?id=com.chibatching.worldclockwidget&hl=en_IE). Unfortunately Niagar launcher allows only one widget atm.
