### ISSUE TITLE
Scrollable wallpaper with multiple screens

### ISSUE THREAD

**Issue by lotagejt** [8bitPit/Niagara-Issues#1080]
Hi! I just bought the lifetime version. Can i ask if there is a way for live wallpapers to be scrollable when i use Niagara? With other launchers i swipe to the left and to the right but with Niagara When i do that only the alphabet of the apps is accessible and the screen is frozen.
I would like a solution as this is the only thing i am missing! I use. Klwp a lot that's why i like this feature.

**Comment by 8bitPit** [comment]
Hi @lotagejt, thank you very much for your support. Making the wallpaper scrollable on Niagara is quite tricky, because on every place you touch/swipe something will happen (e.g. scrolling the app list, opening the app action menu). It would be really hard to scroll through your wallpaper if you have pinned a couple of favorites.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
