### ISSUE TITLE
payment problem

### ISSUE THREAD

**Issue by Xpmmm** [8bitPit/Niagara-Issues#1104]
I have purchased the advanced version of the software and successfully deducted the money, but there is no normal update.
![20191223_161206](https://user-images.githubusercontent.com/59162856/71346617-3e19da00-25a3-11ea-9d88-c8848a379886.jpg)

**Comment by Montell2099** [comment]
> I have purchased the advanced version of the software [...] but there is no normal update.

Do you mean you haven't received any Play Store update since your purchase? I don't think that's the case when purchasing pro, you use the same build as everybody else but you get some kind of identifier that gives you access to the pro features — but I might be wrong.

When you scroll to the bottom of the app list, does it say "Niagara Pro" above "Launcher Settings"?

Try downloading & installing [the latest APK from here](https://github.com/8bitPit/Niagara-Issues/releases/download/v0.11.0-alpha/Niagara_Launcher_v0.11.0.apk)  and see if that makes any difference.

**Comment by Xpmmm** [comment]
I tried again. You can upgrade by buying a trial version, but you can't upgrade by buying a one-time upgrade

**Comment by 8bitPit** [comment]
Hi @Xpmmm, sorry that you can't receive your purchase. Does following these steps help: https://hackmd.io/@C1BuMppiTYazZhBH13jY3g/SyKlUgEkL

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
