### ISSUE TITLE
Hello, changing icons.

### ISSUE THREAD

**Issue by yk2020** [8bitPit/Niagara-Issues#1123]
Hello, 

I'm unable to change icons for all my apps & shortcuts. 

It shows error.

**Comment by disacrol** [comment]
Hi, please provide more details: which device, Android version / ROM, which icon pack, etc.

**Comment by yk2020** [comment]
Hello,

I am using Lg G8 thin Q (I think it's pie version). I don't have an icon
pack.
But I would like to be able to select from files for changing icons,
please. :)

**Comment by disacrol** [comment]
Oh, so not exactly an error. You're probably getting a popup message due to not having any icon pack installed, suggesting you to donwload one from play store.

This is the only way Niagara currently allows for icon customization. There is already a request to allow selecting ad-hoc pictures for icons, see #581.
