### ISSUE TITLE
Make more productictive as well

### ISSUE THREAD

**Issue by dhruvaec** [8bitPit/Niagara-Issues#1126]
In Home screen add an Task manager or to do list. Which could help on more attractable feature to focus on the productive.

**Comment by Martin5001** [comment]
I think there are too many to-do apps already,  no need for another :D

**Comment by disacrol** [comment]
What about a list of upcoming events from your calendar? Or do you mean ad-hoc tasks created within Niagara?

**Comment by dhruvaec** [comment]
For example try that LESS PHONE LAUNCHER, They had an Task Manager (that we
can add, what do we want to do? And Focus on that.


HERE IS YOUR MESSAGE FROM
DHRUVA PATEL G K
THANK YOU,

**Comment by disacrol** [comment]
I'm not sure that's the kind of feature expected on a minimalistic launcher like Niagara, but @8bitPit could further comment on this.

**Comment by 8bitPit** [comment]
I'm sorry, but this feature is not impactful enough in my opinion, because you can use dedicated apps for that.

Niagara's four feature criterias:
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.
