### ISSUE TITLE
Pro version payment without Google Play Services

### ISSUE THREAD

**Issue by martindeveloper** [8bitPit/Niagara-Issues#1137]
**Is your feature request related to a problem? Please describe.**
I have been using Niagara on my Android based DAP Fiio M11 Pro which works great and I like to support development by getting the Pro version of Niagara. But sadly Fiio's Android version does not include Google Play Services, so I'm unable to buy Pro version.

**Describe the solution you'd like**
Support Pro payment thru different channels - maybe PayPal payment and getting some serial key which may be put into Niagara? Not sure what options are available.

**Comment by Martin5001** [comment]
I think some alternative store would be a better choice than a serial key (Amazon, Galaxy store,...)

**Comment by martindeveloper** [comment]
Yeah, that would be nice. I think Amazon should be most widely available, so sounds like a solid way to go for me.

**Comment by 8bitPit** [comment]
Thank you very much! This is quite a difficult task, unfortunately, because of:
1.	Google
Google doesn’t allow other payment methods for apps published on Google Play. If I integrated Amazon’s billing SDK, I would have to offer different apks – one for Google Play and one for Amazon.
> Developers offering products […] on Google Play must use Google Play In-app Billing as the method of payment, except for the following cases:
Payment is solely for physical products
Payment is for digital content that may be consumed outside of the app itself (e.g. songs that can be played on other music players).
[Source: https://play.google.com/about/monetization-ads/payments/]

2.	Taxes
It’s legally insecure to offer online purchases globally without any expert help. For example, value added tax is not the same in every country (In the US, even every State has its own laws: https://support.google.com/googleplay/android-developer/answer/138000?hl=en

**Comment by p4t44** [comment]
It is possible to get Niagara Pro if you use microG with a patched play store APK. I have successfully purchased it without GPS.

**Comment by khao-soi** [comment]
> It is possible to get Niagara Pro if you use microG with a patched play store APK. I have successfully purchased it without GPS.

What "patched play store" do you mean? I'm on LOS with MicroG and cannot get my pro license activated.
