### ISSUE TITLE
Search: Press search on Keyboard to open first app

### ISSUE THREAD

**Issue by pradyw** [8bitPit/Niagara-Issues#114]
Is it possible to launch 1st result of search apps function by pressing search button of keyboard?

**Comment by 8bitPit** [comment]
That is possible, but could be confussing for people that just want to close the keyboard when pressing the button.

**Comment by pradyw** [comment]
But keyboard is closes by back button

**Comment by tiniwings** [comment]
+1 For this. It really help to handle the mobile with one hand. Its always pain to stretch the finger :(

**Comment by prediscover** [comment]
+1

**Comment by Shinra04** [comment]
I think this is a great a idea. The search results should be displayed in order of frequency of apps opened so that the one you use most shows up and hitting search with open the one you want (most of the time).

I don't understand why the current response is to minimise the keyboard. A simple tap on back does that.

**Comment by jakcharvat** [comment]
I personally support this idea unless searching the web with the bar gets implemented. If it does I would prefer the enter to open the first search result...

**Comment by Shinra04** [comment]
There's a difference between the "Apps search" bar, and the "Web search" bar; meaning, tapping search/enter can easily have different results on each of these.

**Comment by 8bitPit** [comment]
Done

**Comment by Shinra04** [comment]
It's a neat little trick. Thanks for implementing it. :)

**Comment by 8bitPit** [comment]
You're welcome.
