### ISSUE TITLE
Favourites page app list and clock widget transparency (image mockup in description)

### ISSUE THREAD

**Issue by takkischitt** [8bitPit/Niagara-Issues#1155]
On favourites page, provide an option for us to set a % transparency fade on apps (and/or the option for the fade to apply to the clock etc too) after a certain amount of seconds e.g. 50% fade/transparency after 5 seconds to both apps list and clock

This would allow a more minimalist look and show off wallpapers/live wallpapers. Once interaction with the screen has occurred again, apps, clock etc would return to the default set transparency (allow this to be configurable too e.g. Default favourites page transparency = 15%).

Please see the example below...

![example](https://user-images.githubusercontent.com/60218230/72979885-37b09500-3dd1-11ea-8ddf-fbd6775eb873.png)

**Comment by 8bitPit** [comment]
Thank you very much for your request and mockup, but I fear adding too much customization options would take away Niagara Launchers simplicity. I consider a feature necessary if it fulfills these four criteria: 

Simple · Easy to configure and easy to use. As few settings & toggles as possible.
Impactful · Either appealing for many or necessary for some.
Universal · Has to work everywhere: in every country, on all phones.
Independent · Doesn’t add complexity if it’s not being used.

In my opinion this request would violate rule 1 & 3, because it would need a toggle/slider and I believe this feature would only be appreciated by only a few.

**Comment by takkischitt** [comment]
Hi Peter, thanks for the response. What about just simplifying it completely and having a single switch to enable 75% favourites page fade/transparency after 5 seconds.

**Comment by disacrol** [comment]
@8bitPit you probably mean 1 & **2** 😉

Yes, this is very specific and more fit for users that seek more complete customization options. I wouldn't mark this issue as problematic though, more like 'low priority' feature. This could be implemented in simpler ways, just as stated in the last comment.

Just a suggestion of course.

**Comment by 8bitPit** [comment]
How about giving the option to move the whole list further down, so you can completely hide all your favorites?

**Comment by takkischitt** [comment]
So like a swipe up to see favourites/clock & favourites? Not sure that would suit me. I'd still like to have some visibility of the clock/apps. Is the transparency an bit of a pain to implement?

**Comment by 8bitPit** [comment]
No, adding a transparency effect wouldn't be much work, but I don't really see the advantages of it. When hiding the app names, you can already see pretty much all of the wallpaper. Furthermore, if you want to present your wallpaper, you can also show your lock screen. Finally this feature would be against Niagara principles (1&2 - Thanks for correcting me @disacrol):

Simple · Easy to configure and easy to use. As few settings & toggles as possible.
Impactful · Either appealing for many or necessary for some.
