### ISSUE TITLE
Tapping clock only shows alarms

### ISSUE THREAD

**Issue by ccocallas** [8bitPit/Niagara-Issues#1160]
**Is your feature request related to a problem? Please describe.**
While I find the ability to instantly access my clock's alarms very useful, I also have to use the timer and stopwatch functions quite often. In order to access these other clock features, I have to scroll to the 'C's, select Clock, and then choose the function I want (if it didn't open already as the last-accessed default).

**Describe the solution you'd like**
When I open the clock manually (as described above), a list of the clock's functions (including the alarm function) appears at the bottom of the screen. I would like a similar list of functions to be made available when tapping the clock's numbers from the Home screen. And it wouldn't bother me at all if tapping the clock's numbers from the Home screen always took me to the alarms by default...as long as the other functions were also made available!

 - I believe my suggestion would satisfy all of these requirements!
Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
Beautifully explained, thank you very much for your submission. Are you using a Samsung device by any chance? I'm asking because afaik handles the intent to open the clock a little different than [Googles clock app](https://play.google.com/store/apps/details?id=com.google.android.deskclock). If you use theirs, you can switch to the stopwatch mode, for example after tapping on Niagara's time widget. If you don't want to switch, you may have to wait until https://github.com/8bitPit/Niagara-Issues/issues/676 has been implemented.

**Comment by ccocallas** [comment]
Yes, my phone is a Samsung. Per your suggestion, I downloaded the Google Clock app and set it as the default. Thanks for the solution!

**Comment by 8bitPit** [comment]
Great, glad it helped. I'll close this issue but leave #676 open.
