### ISSUE TITLE
Multiple widgets / Widget in swipe actions

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1165]
I have a suggestion related to the new swipe action - adding related apps feature, which I really like.
 ~~1) I think the "edit" icon might be confused with the Edit mode or with the long tap options such as Rename, uninstall etc. So I suggest using "plus" icon instead.~~

I think it would be nice if widgets could be added to the swipe menu too. This would make it somewhat similar to Windows live tiles - you could see the information provided by the widget without need to open the app itself but still with a clean homescreen.

It could look something like this (sorry for the mixed language):
![Screenshot_20200203-140759](https://user-images.githubusercontent.com/35201200/73657770-45003600-4693-11ea-9611-1f0624cf11b1.png)

**Comment by 8bitPit** [comment]
Thank you very much for your suggestion and mockup, [I totally agree, this could be great](https://github.com/8bitPit/Niagara-Issues/issues/117#issuecomment-464157151)!

**Comment by Martin5001** [comment]
Also when adding the widget there, a list of available widgets could be divided into two main groups:
1) Suggested widgets – widgets from the particular app of which swipe actions are edited (Editing Chrome swipe actions –> Chrome widgets)
2) Widgets from other apps – all other widgets (for flexibility – users can add widgets which do not come from the particular app but are somehow related

**Comment by 8bitPit** [comment]
@Martin5001 neat idea!

**Comment by bl4ckv0id666** [comment]
I support this function. And I have got an idea:
Now: If swipe right on the icon -> show the icon shortcuts and the selected applications and shortcuts.
Future: double tap the icon -> show the selected widget (It would be better if this widget would be resizable because some widgets will be wrong sized or ratio is not right. For example Smart launcher 5 shows malformed widgets and this widget not resizable.)

**Comment by 8bitPit** [comment]
@bl4ckv0id666 I'm not a huge fan of double taps, because to recognize double taps you have to wait after the user single taps something if she will tap the same item again shortly after. As a result, every app launch has to be delayed. However, the swipe action menu will be scrollable, it will show both widgets, notifications, app actions and shortcuts.

**Comment by Rod911** [comment]
@Martin5001 ticket can be closed?

**Comment by Martin5001** [comment]
Yeah, thanks for reminding me
