### ISSUE TITLE
Option to reverse alphabetical order

### ISSUE THREAD

**Issue by frederickrl** [8bitPit/Niagara-Issues#1166]
I would love to see an option for the alphabetical order for app search be reversed.

As of now. Whenever I swipe on edge I always begin at the bottom as it seems to be more consistent.

I would love to hear everyone's opinion on this as I feel that this would make the experience a lot more consistent for some user, and it also should not be too hard to implement

**Comment by Martin5001** [comment]
I usually scroll from top to bottom, but as I come to think of it, it's probably only because I'm following the current alphabetical order. So to me your suggestion makes sense and I think I would get used to it pretty quickly. But I think on smaller phones, where it is easier to reach the top of the screen, it should be kept as it is now. But I personally very much agree with you.

**Comment by 8bitPit** [comment]
Thanks for your idea @frederickrl, but it already was suggested some time ago: https://github.com/8bitPit/Niagara-Issues/issues/102
For the sake of simplicity, I'm trying to keep the numbers of toggles as low as possible and closed the issue, I hope you can understand. Sorry.

**Comment by frederickrl** [comment]
@8bitPit I understand the mission of your launcher. Thank you for your time! :)

**Comment by 8bitPit** [comment]
@frederickrl really appreciated, thanks!
