### ISSUE TITLE
UI/UX: Small enhancement of icon shape option

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1174]
When you go to icon settings, there is option to make them circled, which is not supported on every device however.

Would it be possible to detect whether the device supports it or not and grey out the button and show the "not supported" text accordingly?

I know it is a small enhancement but I think it would feel much better. The user wouldn't have to try the option to see it doesn't work ‐> more fluid, not frustrating experience.

**Comment by 8bitPit** [comment]
Theoretically it would be possible, although it's not easy: You'd have to look at the icons shape to check if the system supports it, afaik there's no better way. Initially, the toggle should be replaced by the option to customize the icons shape: #448. However I noticed Android removed this option from their launcher and on stock Android 10, maybe because of this: https://www.androidcentral.com/googles-pixel-themes-app-thatll-debut-pixel-4
That's why I want to wait a bit, before I'll continue on icon customization options.
