### ISSUE TITLE
Community Gallery for Customization 

### ISSUE THREAD

**Issue by GeekLiberty** [8bitPit/Niagara-Issues#1184]
It would be great to tap into a repository of setups outside of r/niagaralauncher. Being able to upload layouts with automatic tagging for wallpapers, icon layout, widget, text, etc, so it takes some work out of customization, and inspires other to upload their own themes. 
So I could upload something like this setup, and another Niagara user could apply it from the gallery. 

![Screenshot_20200214-121639](https://user-images.githubusercontent.com/60677023/74565747-c1fa9d80-4f26-11ea-96c8-9e586151f156.jpg)

**Comment by Martin5001** [comment]
I think that from psychologycal perspective this could help Niagara to spread, because it would give people a call to action - a reason to share.

If backup option was implemented (#222), it could be used to share icon pack, widgets layout, wallpaper etc., and thus effectively sharing the whole setup - maybe a link to Play store could be provided as a placeholder in case user has not the widgets installed, and it would be placed automatically after installation. (Microsoft launcher does something similar with all MS apps, which have their icons on the home screen but are not installed until user taps the icon and downloads them.)
Also share links can contain more information than just text, which is displayed on Facebook, Messenger, etc as a thumbnail so this could bring attention. And I think sharing a link with a thumbnail would be better than having a gallery in the app, because it could be viewed by all people on social networks, not just Niagara users. So you would basically share a screenshot with description and some kind of link to open and set Niagara accordingly to have the same setup.

So I personally like this idea but of course it´s on 8bitPit to decide.

**Comment by 8bitPit** [comment]
I like the idea very much, but offering a platform to upload wallpapers is not an easy task. It requires more server capacity and a moderation team. Moreover, legal issues may arise for licensed wallpapers, for example.

**Comment by GeekLiberty** [comment]
> I like the idea very much, but offering a platform to upload wallpapers is not an easy task. It requires more server capacity and a moderation team. Moreover, legal issues may arise for licensed wallpapers, for example.

First of all, thanks for replying to both of my feature requests. I feel like I am being valued as a customer through and through!

For the time being, could you potentially implement a feature that creates a shareable list of the icon packs, wallpaper name/app, widget and layout order for others to download? Basically, what if you had a share button that generated a slightly blurred screenshot of the layout, with a QR code containing a list of playstore links for the setup in the lower left corner. Then have an import function that allows me to scan a friends QR code to view a list of the links, followed by a "initialize setup" step. My line of thinking is that this would be a good temporary solution for a community gallery, allowing people to dictate how they share their setup with others, or much like how snapchat and instagram users share their profiles with QR codes generated in app.

**Comment by GeekLiberty** [comment]
> I think that from psychologycal perspective this could help Niagara to spread, because it would give people a call to action - a reason to share.

I think phone customization has the potential to be more accessible for everyone, so being easily able to apply the same setup as my friend from school or family member would be free advertising for Niagara Pro.

**Comment by 8bitPit** [comment]
Really cool ideas, thanks again @GeekLiberty. I assume this feature will take quite some time to implement and my release schedule is currently tightly packed :) I can imagine this may be implemented in 2021.

**Comment by 8bitPit** [comment]
Sorry, there's still so much else to do. To better plan ahead and give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that are unlikely to be implemented this or next year (2021 & 2022). This is one of those, unfortunately. I'm sorry.
