### ISSUE TITLE
Better application name recognition to group them more adaptive

### ISSUE THREAD

**Issue by bvn13** [8bitPit/Niagara-Issues#1203]
Seems, it would be better to get all first letters from all words of application name to group all applications in them.

For instances:
1) "Play Music" have to be placed in "P" and "M" both. The same for "Play Музыка".
2) I prefer to get "Заметки Google Keep" app by its name "keep" so it should be grouped into "K"
3) "Office Lens" -> into group "L"

So I ask you to change grouping algorithm this way: take first letter of all single words from application name and place application into several groups according these letters.

**Comment by 8bitPit** [comment]
I fear that people will be confused about this. It seems unnatural to me that some apps would be listed only once and others twice. However if you haven't memorized the first letter of each app yet, you can use Niagara's app search. It shows Play Music when searching for "Play" or "Music". Moreover, you can also rename an app if you want to have it listed in another letter section.

**Comment by bvn13** [comment]
@8bitPit could you please implement this feature and hide it with toggling in settings? Or how can I make a pull request?

**Comment by bvn13** [comment]
I ask you because I actually don't remember what are the default names of all apps that I use not so usually. I believe I'm not alone.

**Comment by 8bitPit** [comment]
@bvn13 Sorry, in my opinion this toggle is against Niagara's core principles:

>a feature should be...
Simple · Easy to configure and easy to use. As few settings & toggles as possible.
Impactful · Either appealing for many or necessary for some.
Universal · Has to work everywhere: in every country, on all phones.
Independent · Doesn’t add complexity if it’s not being used

 To me, it's neither simple (because it's not very intuitive) nor impactful (because search can already help in this case). Furthermore. Niagara's not open source so you can't make pull requests unfortunately.
