### ISSUE TITLE
Show feels like measure in weather widget 

### ISSUE THREAD

**Issue by mr-islam** [8bitPit/Niagara-Issues#1204]
Showing the feels like measurement in the weather widget instead of the actual temperature would be more helpful, because the true temperature is not useful practically.

Maybe it could be a choice inside settings?

**Comment by 8bitPit** [comment]
You have a point, displaying the feels like temperature would also make sense. However I want to keep the weather widget as simple as possible (with as few toggles as possible), because displaying the weather is not the main purpose of the launcher in contrast to weather apps. Please also refer to this issue: https://github.com/8bitPit/Niagara-Issues/issues/1084

**Comment by mr-islam** [comment]
Yeah that's a great point about keeping things simple. 

But keeping that philosophy in mind, the feels like temperature should be the default. 

Niagara isn't a weather app, like you said—the weather is for convenience and to quickly check if I should wear a jacket, take an umbrella, etc. 

Keeping that goal in mind, the feels like temperature is the right choice. Right now, the weather widget it more like a decoration since I end up opening a weather app to check the feels like temperature... 

I don't think anyone would be opposed to this change? But then again, with no toggle to choose, I'm sure someone would be disappointed by this change... It's a tough choice

**Comment by 8bitPit** [comment]
You have a point, displaying the feels like temperature would also make sense. However I want to keep the weather widget as simple as possible (with as few toggles as possible), because displaying the weather is not the main purpose of the launcher in contrast to weather apps. Please also refer to this issue: https://github.com/8bitPit/Niagara-Issues/issues/1084

**Comment by terezo** [comment]
Hi. I was just about to fire the same FR with feels like temperature and found this. Feels like is mostly the one variable I look for when checking forecast. E.g. meteoblue use nice palm as an symbol. I would get about with only that value in this use case, to keep UI for the widget the same. Still preffer both values. I think one toggle in weather settings is not a big price for such value.

**Comment by 8bitPit** [comment]
@terezo also thanks for your input. Yeah, a toggle could work, I'll reopen the issue but mark it as low priority.

**Comment by 8bitPit** [comment]
To better plan ahead and give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that are unlikely to be implemented this or next year (2021 & 2022). This is one of those, unfortunately. I'm sorry.
