### ISSUE TITLE
Hide Niagara Pro entry when bought

### ISSUE THREAD

**Issue by awnumar** [8bitPit/Niagara-Issues#1222]
Hey! Thanks for making this launcher.

I bought pro to support the app. It would be nice if the "Niagara Pro" entry at the end of the app list could be removed in this case? Or moved to the settings page. It takes up space and doesn't really provide any functionality.

**Comment by Martin5001** [comment]
Maybe moving it to the About section in Settings could allow using the space for Hidden apps button to be moved here from Settings.

**Comment by craiga007** [comment]
I don't know how many times I have tapped on Niagara Pro instead of Launcher Settings. I think that is because every other entry in the app list is the name of the app to launch, so I tap on Niagara Pro to launch Niagara Launcher Pro. It would make the app simpler overall if Niagara Pro was moved somewhere else like in the About section of Settings.

**Comment by 8bitPit** [comment]
Good idea guys!

**Comment by 8bitPit** [comment]
Done in v0.29
