### ISSUE TITLE
Dynamic & Static Network Icons

### ISSUE THREAD

**Issue by jeffarellano** [8bitPit/Niagara-Issues#1226]
Add some network icons next to, or below the clock. Useful for some user who don't need anymore to swipe down & peek/see status bar. 

Dynamic icon list: 
Current cellular signal. 
Wifi signal. 

Static icon list: 
Charging icon*
Mobile data
Bluetooth 
Hotspot 
Airplane mode 
DND*
Location 
Mute/vibrate*
Flashlight*
Cast
NFC
Battery saver*
Active alarm/s*
Headset icon*

*if possible.

**Comment by kazimShaikh** [comment]
Yes. 
It would be really good to these in upcoming updates.

**Comment by 8bitPit** [comment]
Hi @jeffarellano thanks for your ideas. We're trying to only include the most necessary icons. For the rest, you can peek at Android's notification shade by scrolling up without letting go your fingers. By the way, showing a battery charging indicator is possible, we'll add that probably, because it fits nicely with the battery percentage widget. I created a dedicated a dedicated issue here: https://github.com/8bitPit/Niagara-Issues/issues/1274
