### ISSUE TITLE
KLWP integration improvement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1288]
I think it might be really useful to add one or two more variables to the KLWP integration, which would give the information on how far down the apps list is positioned and also how far the user scrolled. This would allow for some collapsible elements which would roll with scrolling.
(More about the integration here: https://niagaralauncher.helpscoutdocs.com/article/59-klwp-integration)

**Comment by 8bitPit** [comment]
The problem is that Niagara Launchers list is very dynamic. For example, when a notification arrives, the list can get a little longer because of the additional message preview text. This would affect the scroll position as well. Because of this, every item doesn't need to have the same height, so calculating the whole height of the list is close to impossible.

**Comment by Martin5001** [comment]
@8bitPit Sorry I probably confused this a bit, but I meant to get the position of the list start not end. I mean the empty space as on this screenshot:
![Screenshot_20200525-171052_Niagara Launcher](https://user-images.githubusercontent.com/35201200/82825075-d7c71980-9eaa-11ea-9f07-4d4c8ffd3ebb.jpg)

**Comment by 8bitPit** [comment]
That's a pretty special use case though, I don't think this feature would be _impactful_
