### ISSUE TITLE
Swipe Actions listed backwards

### ISSUE THREAD

**Issue by ethangeorge4** [8bitPit/Niagara-Issues#1290]
**Is your feature request related to a problem? Please describe.**
When swiping into quick actions, they seem to be listed backwards. For example, on messages, the person I most recently message appears at the bottom of the list. So I have to scroll to get to that action.

**Describe the solution you'd like**
It would be ideal if they were listed in the reverse order.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
That's a tricky issue. Other launchers invert the whole dialog including the position of shortcuts when the dialog doesn't fit below the app. Because most people place their most used apps at the bottom and shortcuts will be inverted there on other launchers, Niagara Launcher also inverts the list of shortcuts.

Original: 
![Screenshot_20200703-101541](https://user-images.githubusercontent.com/9284845/86447898-4dc66800-bd16-11ea-9cc0-76955066680e.png)

Inverted:
![Screenshot_20200703-101550](https://user-images.githubusercontent.com/9284845/86447895-4b640e00-bd16-11ea-8185-e6e31c9e211e.png)

In Niagara (also inverted):
![Screenshot_20200703-102503](https://user-images.githubusercontent.com/9284845/86448852-a5b19e80-bd17-11ea-9073-c065f236386b.png)
