### ISSUE TITLE
Swipe menu icon shown incorrectly

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1312]
Niagara 0.30.2
Samsung Galaxy J7
Android 9.0
(The affected app is Samsung Internet browser)

Don't know how to reproduce, but maybe it has something to do with Sesame being enabled (Sesame clearly has some effect there, as it changed the order of the shortcuts – but these are the regular non-sesame android app actions.)
![Screenshot_20200606-213902_Niagara Launcher](https://user-images.githubusercontent.com/35201200/83966844-fbcc2700-a8bc-11ea-9ee0-969a9964cd41.jpg)

**Comment by 8bitPit** [comment]
These shortcuts are coming from Sesame, as you supposed. That's because Sesame gives you the option to filter shortcuts and add your own (You can do that by tapping on the edit pen icon > Edit shortcuts) and Niagara Launcher has to ask Sesame which shortcuts should be displayed.  I can't explain why the icon doesn't get displayed properly though, maybe Phil and Steve over at https://github.com/SesameCrew/sesame_issues now more about that.

**Comment by 8bitPit** [comment]
Thanks for submitting it to their issue tracker, I'll close this one.
