### ISSUE TITLE
Can't rename apps nor change their icon

### ISSUE THREAD

**Issue by JVariance** [8bitPit/Niagara-Issues#1314]
**Describe the bug**
I can't rename apps nor change their icon .

**To Reproduce**
1. Go to any app
2. Longpress it
3. In menu go to 'icon/edit name'

**Smartphone (please complete the following information):**
 - Samsung Galaxy S7
 - Android 8.0.0

**Comment by Rod911** [comment]
Can you tell us what version of Niagara you're using and what the error message is?

**Comment by JVariance** [comment]
v0.30.3

**Comment by JVariance** [comment]
do I have to use adb console for the error message?

**Comment by Rod911** [comment]
Since you mentioned that you see an error, I asked you if you could provide us that message.
But since v0.30, the way to update icon or rename apps has changed.
You can tap on the app name on top of the long press menu to edit the name, and tapping the app icon on the top provides you with options to change the app icon.

When clicking "Edit icon/name" in the menu, it's just letting you know how to do so.

**Comment by JVariance** [comment]
Oh, I see. This works.
Thanks for your help.

However, still nothing happens, when I click on the 'edit name/icon' button.
(But there is no error message)
