### ISSUE TITLE
Hide search button/app drawer access 

### ISSUE THREAD

**Issue by oldmanjoe** [8bitPit/Niagara-Issues#1331]
Hello guys!  For my use, I would like to be able to do two things to make it perfect for me: hide / disable the search button and also how I use another app that enables some gestures, the way to access the app drawer is not very cool.  Could they implement alternative forms, like a discreet button or even the conventional Android swipe gesture?

**Comment by Rod911** [comment]
How do you suggest the search menu be opened if the search button is disabled?

You can suggest any new action or upvote existing suggestion about what should happen on swipe up gesture #122.
The current implementation of accessing the apps list seems reasonable and _cool_ enough since once you now where your apps are in the app list, you can skip the swipe action and directly tap on either edges of the screen at a certain location to take you right to your app.

I'll leave this thread open if you have any other feedback/suggestions.

**Comment by oldmanjoe** [comment]
I understand what you say but I wanted the possibility of not having research, simple.  As for scrolling through the list of apps, if I could just scroll from bottom to top, without that alphabetical list of borders, it would be perfect for me.  Thanks for listening.

**Comment by 8bitPit** [comment]
Hi, in my opinion the option to hide the search button is not  [impactful](https://niagaralauncher.helpscoutdocs.com/article/8-niagaras-design-principles) enough to add a toggle for that, sorry. About your second request: You only need the alphabet to open the all apps list, then you can also scroll without it.
