### ISSUE TITLE
Google Reminders and Tasks

### ISSUE THREAD

**Issue by iannido** [8bitPit/Niagara-Issues#1347]
Hi, 

Great work on the launcher! I see that you all created new functionality for an agenda when clicking on the date. 

Any chance a future release can incorporate Google Tasks and Reminders within the agenda with a way to update them? 

I would be happy with some sort of productivity functionality within the launcher! 

Thanks again for your efforts! 

Thanks,
Dom

**Comment by Montell2099** [comment]
I use Google Keep for pretty much everything, the reminders I set there are shown & obviously incorporated within the Google calender.

I'm surprised that there's no integration of reminders from Google Keep in this reworked "At a Glance" section. That would really be helpful & a clean way of keeping track of upcoming reminders.

**Comment by 8bitPit** [comment]
Because each todo app has their own API and Google Keep doesn't have an API at all (vs. one unified calendar API Android provides) and their API requires an active internet connection to sync, it's way more time intensive to integrate todo apps into Niagara Launcher. That's why we currently don't have plans to do that, sorry.
