### ISSUE TITLE
Overlapping agenda items. Show the most recent start hour.

### ISSUE THREAD

**Issue by TomDeSmet** [8bitPit/Niagara-Issues#1359]
The agenda widget is cool but if I have 2 appointments that overlap, for example appointment 1 starts at 2pm and ends at 5pm. And appointment 2 starts at 3pm but already ends at 4pm the first appointment is always shown.

But I'm already there so I'd rather know that I need to hurry or leave sooner for my next appointment that overlaps.

**Comment by 8bitPit** [comment]
We show current events at first, because otherwise the user may have missed that it started.

**Comment by TomDeSmet** [comment]
And what about a (settings) option to show 2 upcoming events on 2 lines in the widget IF (and only if) there is an overlap?
Or maybe they scroll side-to-side? Or maybe just an icon indicator to warn you that you have another appointment?

If you have more than 2 overlapping appointments you just need to learn how to schedule better :D

**Comment by 8bitPit** [comment]
I tested showing multiple events at the same time and multiple lines of text below the date unfortunately doesn't look good at all. Moreover, I fear that scrolling text can bother a lot of users, because it grabs your attention every time you look on the homescreen. I like the idea of showing a special indicator, but Niagara Launcher already shows an indicator when other events start soon or have already started (+1, +2, ... +n). I don't know how to create a second little indicator that is short and can explain by itself that it indicates that another event has also started.

**Comment by TomDeSmet** [comment]
I forgot about the +n icon.
And I agree with your comment on the scrolling.
Let's put a lid on this one.
