### ISSUE TITLE
Design sugestions

### ISSUE THREAD

**Issue by hargreeves540** [8bitPit/Niagara-Issues#1370]
Hello Niagara community. I'm using Niagara for almost almost 2 years and I have been a pro user since the beginning. I have a couple of sugestions to make.

The first request is a aesthetical one. I think it would be positive to give more flexibility to the main screen, with the possibility of the list of favorite apps and the widget aligned to the center or to the right. To be able to have only the list, without any icons (and in this case with larger text, maybe). Finally, have the text (in white) next to the icons without any shadow, as it already happens in the option with dark text.

Congrats on your excellent work and I hope one of these are feasible.

**Comment by 8bitPit** [comment]
Apologies for the late reply @hargreeves540. For the sake of simplicity we try to keep customization options limited to a certain degree, you can read more and we we do that here that here: https://niagaralauncher.helpscoutdocs.com/article/77-missing-customization-features.

**Comment by 8bitPit** [comment]
Here are the parts from the link that are relevant to your suggestions:

### Customizing Accent Color or Text Color  
Niagara Launcher automatically chooses its accent color, which is used for tinting the app list's search button for example, based on your wallpaper. In our opinion, that gives you enough freedom to play around with. Moreover, customizing the text color isn't impactful enough.

### Center or Right Align List
We're not planning on adding different alignment modes for Niagara Launcher's app list, because we're thinking that the left aligned is already sufficient for both left and right handers. Furthermore, new alignment options would mean designing additional layouts for every new feature that changes something on the homescreen which slows down development.
