### ISSUE TITLE
Calendar events are not displayed on main screen

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1378]
When I add future events that are more than 12h, 1, 2 days ahead in the calendar, they don't appear on the screen under the (date, battery..) when the day comes. If I modified the event (s), add a new one or just go to Niagara settings/features/ widget/ calendar/ and disabled and enable (to show upcoming events).They appear again or if the event is less than 12h it display property. So, not sure if it's how it works or if it's a bug.
Second question is  is related to the messages, I want to know if the option to open YouTube videos or the browser (links) from the quick messages display is still available or not. It has been a while since I can not use that option that is very useful. 

Xiaomi mi9t
Android 10
MIUI 12 stable version

**Screenshots**
![Screenshot_2020-10-02-14-31-38-397_bitpit launcher](https://user-images.githubusercontent.com/72170242/94969190-80bbfb80-04bf-11eb-966e-dc5615a30ffe.jpg)
![IMG_20201002_143520](https://user-images.githubusercontent.com/72170242/94969198-84e81900-04bf-11eb-8ea5-d574b28b3563.jpg)
![IMG_20201002_150101](https://user-images.githubusercontent.com/72170242/94969558-338c5980-04c0-11eb-9c10-8e9328c5c4bd.jpg)
![IMG_20201002_150129](https://user-images.githubusercontent.com/72170242/94969571-3b4bfe00-04c0-11eb-97bd-ccf0ad76942e.jpg)

**Comment by 8bitPit** [comment]
Hi! Yeah, calendar events only show up 12h before the event occurs to not clutter up your homescreen. Regarding your second question: Since Android 10, Android is responsible for generating those smart replies, here's how to enable them: https://www.techmesto.com/enable-disable-smart-replies-android-10/#:~:text=Android%2010%20introduced%20the%20Smart,message%20from%20the%20notification%20area.
