### ISSUE TITLE
Show recently used apps when opening "Search apps"

### ISSUE THREAD

**Issue by romavonk** [8bitPit/Niagara-Issues#1438]
When open the "Search apps", show the 5 (e.g.) most recently used apps until you start typing in the search box.

**Comment by xatx14** [comment]
Hey ho,
love the launcher but would like to see the feature requested.
When opening up the search bar - i would love to see the last 5 recent searched apps.
Thanks!

**Comment by 8bitPit** [comment]
Thanks for the request @romavonk. I fear showing recently used apps is a bit redundant because you can already find them in Androids recents/overview  screen. We might show the most used apps though. Until then, I recommend using the Sesame integration, they already show most-used apps: https://help.niagaralauncher.app/article/20-sesame-integration Hope this helps!
