### ISSUE TITLE
Agenda – open event location in maps

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1439]
If an event has location info, it would be useful to have a button (similar to notification actions) to open maps with that location for quick navigation.

**Comment by rcdailey** [comment]
@8bitPit I'd like to appeal the decision to close this (instead of opening a new feature request). Why is any analysis (beyond checking if the respective property on the event is empty) required to provide a user a button on an event to simply open the default map application with the exact string? Leave it to the user to know that it doesn't make sense to try to navigate to a meeting room from their car. 

This would be a relatively easy first step in an iterative approach to implementing this feature and IMHO adds a lot of value. Mostly because it is convenient but also for safety too. It would require less distraction while driving to navigate to an appointment address (in my case, I often forget to start navigation before driving away).

I hope you will reconsider. If the concern is complexity, my suggestion is one way to simplify the logic required. If the concern is value to effort, then you can take this simple first step and improve it (i.e. make it smarter about address vs meeting rooms) later with an iterative/agile approach. I will say that I have yet to see a calendar app that won't show the navigate/open map button for meeting room names. So there is probably no need to come up with an arguably over-engineered solution, as the "simple" approach is something users already expect and are used to.

**Comment by 8bitPit** [comment]
The problem is that the description could also be a link, telephone number, or just a reminder, for example. In my opinion, it would be weird if it would always open a navigation app.

**Comment by rcdailey** [comment]
First of all I don't think we're talking about the description field. We're talking about the "Location" field in the calendar event. Two different things.

Assuming that's what you meant, my counter-argument to that is that you know what it is. You can see it. You can identify it as an address and click the button if it's useful to do so. If it's a room number, don't click the button. The button is there as a convenience if the data allows it to be. No one is required to push it.

I think just because the button doesn't work with some types of data isn't a good reason to not put it there, especially since it's optional, helpful in many cases, and likely not in the way.
