### ISSUE TITLE
Change weather app

### ISSUE THREAD

**Issue by RWHurra** [8bitPit/Niagara-Issues#1445]
I would like to be able to choose a weather app of my own choice. Not the widget, but what app to use when pressing the forecast in the widget. 

Thank you for a great launcher!

**Comment by Just-SKY** [comment]
I think that if you want a different weather app, you could download your favorite from the play store and use the native widgets of the app and close the niagara's weather app.

What I strongly believe is that the next niagara's weather app should be choose carefully because darksky is a very good app. The next app should be equal to darksky or better and not use a cheap app. A cheap app will subtract the app's value.

**Comment by RWHurra** [comment]
Well, I really like the simplicity of the Niagara widget, would just like the option to open the weather app I've always used.

**Comment by 8bitPit** [comment]
Hi @RWHurra 👋 I'm sorry but we don't plan to add that for the following reasons (see: https://github.com/8bitPit/Niagara-Issues/issues/407)
> Because tapping on the weather icon also opens the agenda view (we merged multiple clickable items into one to make tapping on it easier), I fear it would be awkward if there's also a toggle to undo that and open a weather app instead. Furthermore, you can tap on the weather forecast in the advanced view to get a more detailed forecast via Dark Sky's website. If tapping on it would bring you to another weather app instead the data doesn't necessarily match (because of different forecasting methods) which would be an unpleasant user experience as well. That's why I'm closing this issue for now.
