### ISSUE TITLE
Notification buttons – outline to increase contrast

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1449]
I think the notification action buttons could have a bit more contrast to see their shape more clearly. Adding an outline might help. (It depends on the lighting and display brightness, so I'm not 100% sure – it would definitely work for me with my display setting, but not sure for others.)
![20201218_152400](https://user-images.githubusercontent.com/35201200/102628039-6225e200-4149-11eb-8b9b-b3d83c859b15.jpg)

**Comment by 8bitPit** [comment]
The problem is that we use outlined button for quick reply choices: 
![PlayStoreEntry56Notifications](https://user-images.githubusercontent.com/9284845/110514814-f891f000-8107-11eb-8c32-8b110c3ec1a1.png)
However, I'd say the contrast is fine; by the text alone it's clear that the text is a button in my opinion.
