### ISSUE TITLE
Media Widget

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1450]
I use a lot the media widget, and sometimes I think that it needs a redesign. This is just a suggestion, and I understand if you want to keep it like that. This is just an idea. 
The widget can use the color of the album image and the buttons as well, or **album image with semi black color and semi transparent and white buttons**.
The design could be something like that:

![IMG_20201220_203329](https://user-images.githubusercontent.com/72170242/102733483-0d2dcb80-4303-11eb-9c34-d0d1f0c644b9.jpg)
![IMG_20201220_203236](https://user-images.githubusercontent.com/72170242/102733487-0e5ef880-4303-11eb-93fb-d0d6db5df38e.jpg)
![IMG_20201220_203202](https://user-images.githubusercontent.com/72170242/102733489-0f902580-4303-11eb-9758-e649d92421ae.jpg)

**Comment by 8bitPit** [comment]
Thanks for your ideas, @Just-SKY. When designing Niagara's media widget, I tried to make it as much transparent as possible, so to say, to not obscure your wallpaper. Because all Niagara Launcher elements are designed that way, I think Android's widget design with a solid background wouldn't fit. It would be too obtrusive.
