### ISSUE TITLE
Few features i want are 1) 3 finger screen shot, 2) duel screen 3) swipe upwards for app drawer 4) minimal home screen 5) home button is should not open search bar  6) double tap to lock the screen!!

### ISSUE THREAD

**Issue by RockyDSZ** [8bitPit/Niagara-Issues#1471]
#1461 

> `#**Is` your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
Hi, thanks for your requests 😃 
#1: For the sake of simplicity, we don't want to replace system functionalities, but other apps might help you: https://play.google.com/store/search?q=screenshot
#2 Split screen is supported as long your system supports allows third-party launchers to rin in split-screen.
#3 We concluded that launching search was the most requested swipe up action: https://github.com/8bitPit/Niagara-Issues/issues/122
#4 I hope we can already provide one :)
#5 That's because we had a "press home to search" gesture earlier. Now it was replaced by a swipe to search gesture. But when enabled, pressing home still opens search because some users said they prefer that. 
#6 Supported on devices running on Android 9+ or and on all rooted devices: https://help.niagaralauncher.app/article/73-lock-screen-on-older-android-versions
