### ISSUE TITLE
Kwgt widgets update issue

### ISSUE THREAD

**Issue by Aleandr-1987** [8bitPit/Niagara-Issues#1474]
Hi, I have been using Niagara launcher with Kwgt widget for sometime and it worked perfectly. But from couple of days I noticed that whenever I make changes to the widget it won't get applied. Only way it changed was when I restarted Niagara launcher. I tried nova launcher to check if it's Kwgt issue but there it works fine. 
Android ver 10
Miui 12

**Comment by 8bitPit** [comment]
Thank you very much for reporting @Aleandr-1987; we'll look into it!

**Comment by topsy-turvy99** [comment]
Fixed in v1.6

- Widget Freezing Bugfix: We could finally fix the complex widget freezing bug that plagued the launcher for years. It’s not reproducible with every widget and only happens rarely. When it happened, it froze your widgets.

Thanks for fixing this issue, this was one of the bugs in Niagara Launcher that bugged me the most 😁

**Comment by 8bitPit** [comment]
Thanks for updating this thread @Amorphous404; I closed the issue
