### ISSUE TITLE
Switching from annual subscription to a one time payment resets the "Member since" stat

### ISSUE THREAD

**Issue by Runee** [8bitPit/Niagara-Issues#1483]
A very minor quibble, I know, but a bug nonetheless. 

If you start an annual subscription of Niagara Launcher Pro and later on decide to change to the one time fee, the "Member from" stat on the Niagara Pro Screen will show the date the one time fee was purchased and not the date you started your annual subscription.

**Comment by 8bitPit** [comment]
Thanks for noticing. It's a bit tricky to solve this issue. We currently show only the purchase date of the latest valid purchase. If we displayed the date of the first purchase, this could be confusing as well: Imagine if someone redeemed the free trial of Niagara Pro, but canceled their subscription before it renews. A year later, they decided to give Niagara Pro another shot and bought the lifetime version. Here, it wouldn't make sense to show the date of the free trial, because there's a big gap between those two purchases. It's not trivial to calculate if there are gaps in your purchase history, and we'd even have to switch to another Google API to do it (currently we can use Google's frontend API to retrieve the purchase date). So I hope you can understand that it's not worth the effort to fix that bug and I'm sorry that your date got changed.
