### ISSUE TITLE
Have an option of hiding the Alphabets on the apps

### ISSUE THREAD

**Issue by sinziaa** [8bitPit/Niagara-Issues#1509]
Hello, please consider of making an option like that of hiding alphabets on the wallpaper screen in the apps too.

**Comment by barletta** [comment]
If you mean the app drawer then I'd love to have this as well. The space between the letter's sections increase just add up to a lot of wasted space.

**Comment by 8bitPit** [comment]
I'm sorry but for the sake of simplicity and because a toggle for that wouldn't be impactful enough, I believe it's better to not add a toggle. More on Niagara Launcher's design principles here: https://help.niagaralauncher.app/article/8-niagaras-design-principles

**Comment by emiham** [comment]
I'd kindly like to request for this issue to be reopened, as I think there's still a strong case to be made for this. 

Niagara currently displays a single letter to divide the app list into sections by their initial letter. I'm curious about the rationalization of dividing it this way. I can see why you would instinctively want to section a list that is usually pretty long, but since you scroll using the alphabet you're going to be looking at a much smaller subset of the list by the time you're even looking at app names. 

If it's there to provide visual clarity when using the alphabet to scroll, I would argue that seeing the current letter both by the alphabet and in the app names themselves is enough, but if not I would propose showing the letter when you are scrolling, and hide it when you let go and Niagara shows the rest of the apps that start with different letters. 

As for the reason to remove the letters: even in the best case they add a degree of unnecessary (going by the above explanation) clutter, and in the worst case they take up half the app list, the worst case being illustrated below. 

```
A
🍎 Apple

B
🍌 Banana

C
🥥 Coconut
```

I often find myself having to hide apps that are alone in their section, but then being frustrated that they're not where they're supposed to be. On smaller screens the impact of this is even worse. 

I'm only really bringing this up because Niagara is a beacon of good, well thought out design in a field that's saturated with a lot of junk. This is probably the only thing about the app that I don't understand the reasoning for. So as a last statement: thanks for a great app, I've been subscribed since February 2020.

**Comment by 8bitPit** [comment]
I appreciate your kind words and taking the time to explain, @emiham. Yes, it's for clarity, especially for those who have installed several dozen of apps. To keep our number of settings low, we only add a toggle for highly impactful features (**here's why**). I agree that removing the section letters is probably better for some users, but for those I feel the sections are not that annoying to be "worth" a toggle.
