### ISSUE TITLE
Notification blinks upon dismissing

### ISSUE THREAD

**Issue by callmeRam** [8bitPit/Niagara-Issues#1513]
On smartphones (because of limited space) whenever a new notification appears, only one line is used for that recent notification on the screen. Whereas, on tablets, the entire content of that notification can be displayed. This would look good and extra space can be utilized well.

Also, it's really frustrating when
 
For example, lets say i got 20 some notifications of an app, i scroll through and open the 10th notification, later on when i want to go through other notifications , i have to go through the previous ones again. It would be better if the launcher can remember the scroll pos. 

And lastly, when dismissing the notification so that the other can fill is its place, the whole process is time consuming. What i want to say is it takes a whole second for the other notification to fill its space because of the "BLINK" which happens when the user dismisses a notification. Animation can be made more natural and smoother here.

![vidma_recorder_19022021_000325~2.mp4](https://user-images.githubusercontent.com/34789316/108405133-ba12bf00-7246-11eb-9cac-fea4d7d13998.mp4)

Thank you.

**Comment by 8bitPit** [comment]
Thanks for your reports @callmeRam. We only show a couple of lines of the notification to not bloat the user's home screen. Moreover, if a notification contains a lot of text, for instance, a mail with 20 lines, showing all of them on the home screen would be aesthetically unpleasing, in my opinion. Moreover, because notifications are not necessarily listed in chronological order, remembering the scroll position might be confusing and the user might miss notifications that way. I recommend dismissing notifications you've already read. Regarding your third suggestions: I'll try to remove the flicker, thanks for noticing.

**Comment by 8bitPit** [comment]
Fixed in v.1.2
