### ISSUE TITLE
Accent-insensitive search option

### ISSUE THREAD

**Issue by marcinsmialek** [8bitPit/Niagara-Issues#1529]
**Is your feature request related to a problem? Please describe.**
Searching for items with accented letters is unnecessarily difficult.
There should be an option to make them appear when typing without accents, as using them adds extra friction

**Describe the solution you'd like**
A toggle for accent-sensitive / accent-insensitive search and app list letter assignment.
I ask for a switch, because there is a risk that having accent-insensitive search/sort always on might have negative impact when used with some languages.

**Comment by 8bitPit** [comment]
Hi @marcinsmialek, Niagara Launcher already strips accents from app names during the search. If your apps contain é, è, î for example, they'll appear when you type in "e" or "i" respectively.

**Comment by 8bitPit** [comment]
Ah, now I understand. You're using the Sesame integration, right? When you type in a search query and you enabled the integration, we forward it to Sesame and normalizing it. Because our own normalization algorithm works a little different than theirs, applying both wouldn't always give the desired results. That's why we decided to only use theirs but it seems it doesn't support accent-insensitive search. I recommend opening a ticket on their GitHub issue repository about this: https://github.com/SesameCrew/sesame_issues/issues.
