### ISSUE TITLE
Outlook error when clicking on a calendar event in Korean

### ISSUE THREAD

**Issue by fridec13** [8bitPit/Niagara-Issues#1535]
I knew that the similar issue #1162 fixed in v0.31.

But in Korean, I think that issue is not fixed.

I use outlook as default.
When I tap on an event, outlook is not open and show an error.

**Smartphone (please complete the following information):**
 - Device: galaxy s10e
 - Android version: android 11
 - Niagara version: 1.1.1

**Screenshots**
![Screen_Recording_20210310-035535_Niagara Launcher_1.gif](https://user-images.githubusercontent.com/59463154/110523660-c0190300-8155-11eb-9623-f448853fd00a.gif)

**Comment by 8bitPit** [comment]
Thanks for letting us know @fridec13. This is a known issue with Outlook. We believe Outlook causes this issue because we also can't open its calendar events with other calendar widget apps (e.g., Another Widget). If there's an app that can forward you to Outlook from an event, please let us know. To work around the issue, you can install another calendar app (e.g., Google Calendar) and open and edit Outlooks events with it instead.

**Comment by 8bitPit** [comment]
I'm closing the issue;  please let me know if my previous reply didn't help.
