### ISSUE TITLE
Agenda widget – delete events by swiping left

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1547]
If we could swipe to delete events from calendar (similar as with notifications), it would save one extra step of opening the calendar app. And it would improve the experience for those who use calendar events as an alternative to traditional to-do lists (create event – complete task – delete event).

**Comment by 8bitPit** [comment]
I like your idea to assign a swipe action to calendar events. To me, however, deleting events doesn't sound optimal because you'd lose your calendar history after you finished the event.  It's such a bummer, there's no official way to mark an event as "done". More thoughts on this here: https://github.com/8bitPit/Niagara-Issues/issues/1499

**Comment by 8bitPit** [comment]
I'm sorry, Martin, but we have decided not to implement swiping away all-day events.
