### ISSUE TITLE
Inconsistent Weather Information

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1551]
Actually, I love it and tha's why I support it. However, I have to be honest.
I've been checking the weather everyday since the update, and this weather information is basically useless many times, or let's say the information is confusing and frustrating; you never know what is correct. Let see if I can explain myself.
 Lets imagine you wake up and check the weather info of the day. It says that there are 80/90% of possibilities of modarate rain at certain time, u have that in mind knowing the info cound ramain the same or chage through day. As the day goes by the icons and info don't match. The frustration begins to grow. As I show in the images which show the progress of the weather.

![IMG_20210321_141409](https://user-images.githubusercontent.com/72170242/111920874-1429be80-8a57-11eb-9412-3e18a179c390.jpg)
![IMG_20210321_145802](https://user-images.githubusercontent.com/72170242/111920879-17bd4580-8a57-11eb-9532-667c95cf08ba.jpg)
![IMG_20210321_143305](https://user-images.githubusercontent.com/72170242/111920882-1b50cc80-8a57-11eb-99f1-25e6f5542f18.jpg)

Sorry about my ignorance, but at this point I don't know if it is a problem of the the weather provider or the Niagara's weather widget, or it just work like that which is weird.
I think that if the icon conditions are right the % have to decrease or disappear, or if rain % is correct it have to match the icons
I will appreciate if there is at least some consistency in the information.

**Comment by 8bitPit** [comment]
Thanks for reporting and for going so much into detail @Just-SKY. Niagara Launcher only displays the probability of precipitations on forecast items and not the current weather item. I now realize that this might be confusing and may change it. About the mismatching icons and precipitation chance: To determine if that is caused by Niagara Launcher, can you please install the weather app from OpenWeather and check if their weather data also has mismatches? https://play.google.com/store/apps/details?id=uk.co.openweather

**Comment by Just-SKY** [comment]
Ok, I gonna installed

**Comment by Just-SKY** [comment]
About the mismatching icons and precipitatio chance. After comparing the information, the issue is of the weather provider. However, I have a couple of suggesions, I would like you to consider.

First, it would be great if you can add the description of each weather icon somewhere. So, the user could learn meaning of each icon and have a better understanding of Niagara's weather widget. It could be in weather/settings like the screenshot, and the description change as the icons.
![IMG_20210324_202244](https://user-images.githubusercontent.com/72170242/112409381-ff5f5c00-8cde-11eb-9d56-7b143da712ba.jpg)
Second, I undertand Niagara's weather info updates every hour. However, it could be great if you add the options where the users can choose the refresh rate. So, if the conditions are really unstable, the user can choose to increase the weather's refresh rate; the user can choose when to turn it on and off as he needs.In order to better plan the agenda, event, tasks, traffic, or going out somewhere.

Also, by increasing high refresh rate option. Niagara can be able display faster near weather conditions as advertise because it is very difficult for Niagara to do it. It is because Niagara refresh every hour. Like the screenshots where the provider show near rain and Niagara doesn't because it's hour refresh rate.
I know it could affect the battery performance, thats why the usar can choose to turn no and off the high refresh rate.
![IMG_20210324_211129](https://user-images.githubusercontent.com/72170242/112414093-173ade00-8ce7-11eb-966b-15866d1c5563.jpg)
![IMG_20210324_211054](https://user-images.githubusercontent.com/72170242/112414100-1ace6500-8ce7-11eb-89b3-ba47611c83a0.jpg)

**Comment by 8bitPit** [comment]
Thanks for your additional research, @Just-SKY. Niagara Launcher already has an inbuilt mechanism that dynamically lowers the refresh rate to 30 minutes if weather conditions seem to be unstable or if you're launching Niagara's weather forecast. The precipitation event was not shown in Niagara Launcher because it only displays rain events with a precipitation amount of at least 0.25mm/h. However, I plan to lower the threshold as well; 0.1mm sounds more reasonable. 
Regarding the icon descriptions. Because OpenWeather provides us the translated descriptions only combined with the weather data, we can't display them in settings. We originally planned to show them when tapping on an hourly forecast item. However, OpenWeather doesn't provide icon descriptions for minutely forecast items shown in the same spot. To keep the items constable, we don't show descriptions for hourly weather items as well.

**Comment by Just-SKY** [comment]
What I wanted to say wasn't about to show the icon's descriltion on the widget on main screen. I mean, that Niagara can add its own descriltion of the icon that it uses somewhere on the app, so the user can learn them or go there as a reference to know what they mean and better understand. That description doesn't have to be an extra function of the widget or relate it to open weather directly, so it would be something more relate it to Niagara launcher.

**Comment by Just-SKY** [comment]
Sorry I closed it accidentally. Regarding to low the presipition amount, it would be great to make Niagara interactive and productive.
By the way thank for your time and keep this excellent work.

**Comment by 8bitPit** [comment]
Thank you :D I did a few tweaks in [v1.1.3](https://github.com/8bitPit/Niagara-Issues/releases): I lowered the precipitation amount threshold to 0.1mm and added the precipitation probability to the current weather condition item in the hourly forecast widget.

**Comment by Just-SKY** [comment]
Thats great, I and again thanks for your hard work.
