### ISSUE TITLE
Weather: Improve manual location not found error message

### ISSUE THREAD

**Issue by Mivoe13xy0** [8bitPit/Niagara-Issues#1554]
Bug description:
When trying to add the weather location manually I get a no connection error (see screenshot) on wifi and cellular even though I am connected.

Reproduce:
1. Try to add weather location through info widget that is telling Please enter your location for weather on the homescreen
2. Click on Location
3. Click on Fixed location
3. Click on Enter Manually
4. Enter Location (in this case I tested a few different ones e.g. Berlin, Germany; London, GB
5. No connection error even if connected to wifi or cellular

Smartphone Info:
 - Device: OnePlus 5T 
 - Android version: Android 10

Screenshot:
If applicable, add screenshots to help explain your problem. You can paste them here directly.
![image](https://user-images.githubusercontent.com/52064492/112280554-69e3ae00-8c85-11eb-8661-504aee9ad286.png)

**Comment by 8bitPit** [comment]
Thanks for reporting @Mivoe13xy0. For translating the location name into coordinates, we're using Android's Geocoder API. In case it reports an error. In most cases, that's because of a missing internet connection but it could also be "that there is no backend service available." While we can't fix the issue, we could improve the error message and link to a knowledge base article going into further detail on how to work around it. In your case, I recommend entering the coordinates of your city directly:

## I can't enter my location manually.
This could be because your device doesn't come with a Geocoder (a program that translates city names to coordinates). However, you can also directly enter your location's coordinates. To do that, search for your cities coordinates, and enter them like this: 41.304 -81.902 (Which stands for 41°304'N 81°902'E). Leave an empty space between latitude and longitude.
[From https://help.niagaralauncher.app/article/105-weather-widget]
