### ISSUE TITLE
[Feature Request] Ability to add hidden apps on folders

### ISSUE THREAD

**Issue by hotlikewassabi** [8bitPit/Niagara-Issues#1564]
As you all know, there's a feature that lets you add app folders through sliding right on an app in the launcher. (example: https://youtu.be/xwLcB1QEPm4)
But there's one thing that wasn't in mind of the developers (I think)
**Adding hidden apps on folders**. It would be really helpful and could declutter the homescreen so I think it's a good idea! Also, I think it's a bug or intentional thing but when you put apps on a folder and then hide those apps, they stay in the folder. Since you can't add hidden apps in a folder, I thought them still being in the folders is soemthing the developers have forgotten abt

**Comment by Oddward** [comment]
The main purpose of the hidden apps feature is to declutter the full apps list be removing your unused or rarely used apps which is very useful for people with like 100+ apps. It's intentional that hidden apps are not removed from the swipe menu (pseudo-folders)

This is also why hidden apps can easily be searched

It might have been an oversight for the devs to not make it easier to add hidden apps to *folders* (you have to return to app list > add to folder > hide again) but they will probably improve this UX in the future

**Comment by hotlikewassabi** [comment]
Hope so!

**Comment by 8bitPit** [comment]
In v1.2, you can now add them by open the edit pop-up screen, scrolling all the way down, and tap on "Select hidden apps". Hope this helps :D
