### ISSUE TITLE
Apps from removed work profile still visible 

### ISSUE THREAD

**Issue by hemetz** [8bitPit/Niagara-Issues#1583]
After the deletion of the android enterprise container some pinned references to apps are grayed out and can't removed.

**Comment by 8bitPit** [comment]
Thanks for reporting @hemetz. Does a device restart help? Moreover, do these icons show up on your preinstalled launcher as well=

**Comment by hemetz** [comment]
Hi,

No, a restart doesn't fix this issue.
And no, the icon is not shown in another launcher because the app is not installed.

In the meantime I linked my device with another work account and could install the app (outlook) again. Than the favourite app link works and I could remove the app from the favourites.

But I think you will need a workaround for such a Szenario, based on the cloud backup recovery and without the need to delete the config.

Thanks
Stefan

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by 8bitPit** [comment]
Sorry for the late reply Stefan. I tried to reproduce this with a test work profile, but, unfortunately, to no avail. Because you mentioned the cloud backup. Restoring the backup keeps apps that were installed previously but not (yet) to not lose your favorites, for example, more about that here: https://medium.com/niagara-launcher/introducing-auto-backup-a0b35ccaddde. However, the grayed-out apps should disappear after three days and should also be removable on a long press. Removing the app with a long-press wasn't possible in your case, right?

**Comment by hemetz** [comment]
Hi Peter,

right, removing it wasn't possible and i definitely did not wait 3 days -
so i cant check if this will work, but good to know that there is a hidden
service.

thanks
Stefan

Am Mo., 12. Juli 2021 um 17:05 Uhr schrieb Peter Huber <
***@***.***>:

**Comment by 8bitPit** [comment]
We haven't heard that someone else run into this issue, so I believe it was only related to the restore service. I'll reopen this ticket in case this happens again.
