### ISSUE TITLE
Alphabet Letter Font Size

### ISSUE THREAD

**Issue by isaabiyev** [8bitPit/Niagara-Issues#1590]
Dear Team. Please make the letter of the alphabet bigger while searching the app. Just make bigger only the one letter where the finger is at the moment, but keep the size of other letters same. Thanks!

**Comment by 8bitPit** [comment]
Hi @isaabiyev, thanks for your ticket. Niagara Launcher already prominently displays the active letter while scrolling; in my opinion that's already enough:
![photo_2021-05-13_10-55-27](https://user-images.githubusercontent.com/9284845/118103062-c8055580-b3d9-11eb-830c-a739c0d1d96d.jpg)
What do you think?

**Comment by isaabiyev** [comment]
Dear 8bitPit. I think you should better remove that big "N", but instead make that small "n" like big one, but keep it in same place, because while scrolling i look at the small "n".

**Comment by 8bitPit** [comment]
Ah, I see, thanks for the explanation. To scale up the selected letter in the alphabet, we have to push the letters above and below away. Their position would no longer correspond to the hitboxes where you can select them. In my opinion, the current implementation is therefore a little simple because it doesn't have to deal with that problem. I hope my explanation makes sense.
