### ISSUE TITLE
Hide Navigation Bar on Android 12+

### ISSUE THREAD

**Issue by unityastronaut** [8bitPit/Niagara-Issues#1601]
It would be nice having the option to hide the navigation bar, to make your Homescreen more clean and minimalistic. It would be just one toggle like the one for hiding the status bar. Here is a screenshot to show what I am talking about.

(https://user-images.githubusercontent.com/82398591/118159186-040dda00-b41d-11eb-80e4-b3f79c5dcb01.png)

**Comment by 8bitPit** [comment]
Hey @unityastronaut, I just wanted to write that we're not adding this because hiding the navbar would cause the user to swipe two times to access the recent apps screen. However, with Android 12, this is not the case anymore. Because of this, we could even make it the default on Android 12 and don't need the toggle.

**Comment by 8bitPit** [comment]
Update: I tested the new navigation bar hiding behavior on Android 12, but unfortunately, it isn't suitable for permanent hiding. The problem is that it will appear seemingly randomly when you touch and scroll in Niagara Launcher (e.g., when you scroll through your app list).
