### ISSUE TITLE
Automatically remove app in app drawer when it is selected as favorite

### ISSUE THREAD

**Issue by Artt-ies** [8bitPit/Niagara-Issues#1606]
When an app is selected as favorite, another one still exist in the app drawer (which mean there are now duplicate of a single app). For me it feel redundant and I think there shouldn't be duplicate of the same app. I know that I can hide app in the app drawer and the favorite one will still be there, but if I deselect an app from favorite I also need to unhide the app to make it appear on app drawer again, which is a bit annoying.

Making a feature that when select an app to favorite, make the app in app drawer to move up to favorite screen ( I think it shouldn't be consider as hided app, but it just "move up" to the favorite screen), instead of still sitting there in app drawer and create a duplicate on the favorite screen -- and when deselect an app from favorite, move the app down into app drawer.

**Comment by 8bitPit** [comment]
Hey @Artt-ies, thanks for your feedback. The home screen automatically shows suggestions in the favorites list. For consistency, we'd also hide them automatically. However, the user might be confused because the favorites get added automatically, so I prefer that hiding favorites from the app list should still be a manual process. With v1.2,  we now let you directly add favorites from the hidden apps list to fix the issue you mentioned: In the edit favorites list, scroll all the way down and tap on "Select hidden apps."

**Comment by 8bitPit** [comment]
I hope that the new way we handle hidden apps makes a good compromise. Please let us know if you disagree.

**Comment by Artt-ies** [comment]
Ah, I see that could be an issue, because I didn't use suggestion app myself I didn't think of that. I agree that it can cause confusion for some people, and also as you mentioned that I can select app to favorite list directly from hidden app, I use 1.2 beta for a while now but never noticed that there's this feature before, I think it's a nice feature to have though.

There's also another feature I can think of that is kinda have the same "duplicate app" problem is about music widget. The music app that pop up when plug in my head phone is an amazing idea, but when I start playing music, a music widget now pop up above the music app. Now there are 2 way I can access the music apps, which sit directly next to each other (music widget and music app). One of the solution I can think of is a new feature called "embedded widget". Instead of notification, music app now show play pause button and the artist picture under the name of the app. I think it's just a fun idea to think, but I understand that there are a lot variable that make this feature didn't work.

**Comment by 8bitPit** [comment]
Thanks again, @Artt-ies. With the dedicated media widget, we ensure that the player is always clickable, regardless of where the app from where the media is being played from, is. For example, the user could listen to a video playing in his browser, but the browser is positioned at the bottom of his favorites (so the user has to scroll up to reach it). That's why I believe it's better to always show the player at the top, although it's a little redundant. Also, please see: https://github.com/8bitPit/Niagara-Issues/issues/1129
