### ISSUE TITLE
Feature improvements to Google/Niagara button present in bottom right of screen.

### ISSUE THREAD

**Issue by sitikantha-firstgit** [8bitPit/Niagara-Issues#1613]
Current functionality:
1. Editing the Google/Niagara button requires users to know the command search (/Niagarabutton).
2. When editing the actions for gestures, we have only two options:
             Swipe up action and Tap action

Proposed Improved Functionality:
1. Allow for editing the Google/Niagara button settings from the Niagara Settings under the "Enable Google button" option.
2. Add option to assign roles for long press and Horizontal swipes.
3. Rather than having unidirectional swipe (i.e Swipe UP) allow for bidirectional swipe (So the name changes from Swipe UP to Vertical swipe) and the other new one can be Horizontal Swipe.

**Comment by AmitStein98** [comment]
The reason why you have to type in the command is because it's still in beta, it's hidden on purpose until it's ready. I do agree about having horizontal and vertical swipes, but long press is used right now to configure the button and I think that's better.

**Comment by 8bitPit** [comment]
Hey @sitikantha-firstgit, thanks for your suggestions. Amit is right; it's because the button is still in beta. However, we plan to make it an "official" feature soon about more gestures. To keep the button simple and intuitive, I believe only offering one tap and swipe gesture is better; please also refer to this issue: https://github.com/8bitPit/Niagara-Issues/issues/1641.
