### ISSUE TITLE
Support multiple media players

### ISSUE THREAD

**Issue by AmitStein98** [8bitPit/Niagara-Issues#1616]
The android 11 notifications shade allows you to switch between multiple media sources by swiping between them. It would be nice if the niagara media player supported the same thing.

**Comment by Martin5001** [comment]
Just my personal opinion, but I like the Niagara player more minimal. If someone needs more features, the native player in the notifications has that covered. No need to mirror its functionality for me.

**Comment by AmitStein98** [comment]
I feel like you could add this one without hurting the simplicity too much since it doesn't require buttons and as long as you listen through only one app the media player basically functions exactly the same way. It would also help a lot of people, like anyone who has both a music app and a podcast app.

**Comment by Oddward** [comment]
As far as I can tell Niagara's media widget will control whatever app has active playback right now and goes away when there is none, so it works similarly already. If it doesn't properly reflect what's currently playing then it probably needs some changes to properly support the new way Android handles those playback apps

Otherwise, what Martin said is right, there's no need to mirror the same functionality as the notification shade and Peter usually isn't interested in that either

**Comment by 8bitPit** [comment]
I agree; I believe this option wouldn't be that impactful and hope that's okay for you.
