### ISSUE TITLE
Option to move the widget/icons on the y axis

### ISSUE THREAD

**Issue by DarkPlayerr** [8bitPit/Niagara-Issues#1620]
**Is your feature request related to a problem? Please describe.**
I would like to have the icons a bit more on the right, because it doesn't fit my current home screen setup. Having an option to move the app bar where the user wants would be a fix to this problem

**Describe the solution you'd like**
On the resize icons menu make a slider to move it more to the left/right

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible. 
✅ Could be integrated with the already existing height adjustment for the app bar
*Impactful* · Either appealing for many or necessary for some. 
✅ I think that could change setup looks, from having the icons on the same width to a different one
*Universal* · Has to work everywhere: in every country, on all phones.
✅ This is a launcher option, isn't region/device locked
*Independent* · Doesn’t add complexity if it’s not being used.
✅ The default placement could be the one that is used currently

**Comment by Oddward** [comment]
You mean the x-axis? It already lets you move the list on the y-axis

The launcher is full width & left aligned to support some of its main features (swipe gestures, notification previews, easy reachability), i.e. all the space is used, it's not just empty space. There is no real x-axis as it's list-based instead of grid based, they would have to add sliders for customizing the padding, and make sure it works with all those other features
