### ISSUE TITLE
White icons invisible on white pop-up

### ISSUE THREAD

**Issue by asquartz** [8bitPit/Niagara-Issues#1634]
**Describe the bug**
If your app icon is all white, then when you long-press the favourite you get a white icon on a white background which is invisible

**To Reproduce**
1. Set a favourite to be an all white icon (screenshot #1)
2. Long press the favourite to access the pop-up
3. Look at the top left of the pop-up where your white icon will be invisible against the white background (screenshot #2)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XA2
 - Android version:  9

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.
![IMG_20210607_181819](https://user-images.githubusercontent.com/34890493/121063189-e6365980-c7bd-11eb-845c-d8b8547549da.jpg)
![IMG_20210607_181918](https://user-images.githubusercontent.com/34890493/121063181-e3d3ff80-c7bd-11eb-9d39-b7043947fc8b.jpg)

**Comment by 8bitPit** [comment]
Thanks for reporting, @asquartz. If you don't use an icon pack, we automatically add a shadow to the icon to increase its contrast. However, for icon packs, we don't do that because we don't want to alter the icon pack's look. In my opinion, the designer for the icon pack is responsible for making it stand out against all types of backgrounds. In your case, I recommend enabling Niagara Launcher's dark theme (Niagara settings > Look > Dark theme).

**Comment by asquartz** [comment]
I understand the reasoning, and thanks for the reply.  I've gone dark for now, until I find an alternate icon pack.

**Comment by 8bitPit** [comment]
Great, thanks :)
