### ISSUE TITLE
Gestures

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#1638]
**Is your feature request related to a problem? Please describe.**
Allowing for greater functionality .. Niagara a simple clean launcher it would be great to increase the gestures on offer which retain its simplicity while allowing more function 

**Describe the solution you'd like**

Increase the number of gestures something similar to Nova launcher so double tap, two finger swipe up or down etc can be attached to opening apps, shortcuts, widgets or actions. 

Without impacting its simplicity this would add more function. 

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
Hey @Lorestan00, I'm sorry but we don't plan to offer any customizable gestures; here's why: We don't support any two-finger gestures because we want to let you access everything with one hand. Moreover, we also don't support double-tap gestures on apps because to detect a double-tap, we also have to delay app launches (because we have to wait after a tap to check if the user taps again) which is not worth it, in our opinion. Instead, we recommend you add the apps you open the most to your favorites and utilize Niagara's pop-ups for other often-used apps.
