### ISSUE TITLE
FR: Enhance Niagara button with more action directions

### ISSUE THREAD

**Issue by tjsuominen** [8bitPit/Niagara-Issues#1641]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently supported actions are "Swipe up" or "Tap". Would be great to extend the N button utilization by adding Swipe Left, Right and Down. Would positively impact on the UX (utilize it's full potential) and speed phone use due to user assignable activities.

**Comment by Oddward** [comment]
Swiping down would probably be a bit awkward since it's so low, and especially on devices with navigation buttons (capacitive or on-screen)

Swiping right may be similar, but not as bad

Swiping left might be good, but doesn't follow that natural gesture of flicking something up to open/launch - maybe it would fit something like the Google feed which doesn't really work with Niagara's design otherwise 🤔

Right now the button is primarily an action button with an additional action/stash, I don't think it's meant to be another app drawer lol, but it could be useful

**Comment by tjsuominen** [comment]
I don't think adding more directions would hurt or bring 'another launcher' as there's already such implementation. But yeah, that would be a bit overwhelming after giving that some additional thinking time.

**Comment by 8bitPit** [comment]
👍 I'll close this ticket then
