### ISSUE TITLE
Respect Xiaomi's App Lock setting to hide notifications' contents

### ISSUE THREAD

**Issue by bwstefano** [8bitPit/Niagara-Issues#1655]
Xiaomi's Android customization (MIUI) has a feature called App Lock, which allows users to set certain apps to request a password to be accessed. It also permits hiding notifications' contents even if the cellphone is unlocked. [This article shows how it works](https://beebom.com/how-hide-sensitive-content-notifications-miui-9/).

If this setting is on, users will still see notifications' contents in the list of apps in Niagara Launcher:

![Inkedimage_LI](https://user-images.githubusercontent.com/11841075/124526966-aa9da800-ddda-11eb-9902-710ef6940b2a.jpg)

It would be good if Niagara supports this setting and respect it, so it doesn't show content for apps users have defined to hide.

I'm using Niagara Launcher 1.2.4 on a Xiaomi 9 SE with Android 11 and MIUI 12.5.1.

**Comment by Just-SKY** [comment]
That is a MIUI's native option (security apps which works by itself like any other app), so I don't think Niagara could do something about it because Niagara just Lunch apps. It can't control what other app does or does not do.
Also what you are asking si very easy to do 
just **TURN OFF*  *the option that shows the imagine below of each app that you want; as a rasult, Niagara will not be bale to read  them and display them as well. 
Many apps will keep showing their notifications, and bot being display in Niagara. 

![threema-20210706-083235933](https://user-images.githubusercontent.com/72170242/124621567-9e940380-de37-11eb-81b3-3c6855fec031.jpg)

**Comment by bwstefano** [comment]
Turning "Show app icon badges" off did the trick. Thanks, @Just-SKY!
