### ISSUE TITLE
Disable Side Drawer

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#1661]
Please consider below situation

- I have everything what i need in my home screen
- Even secondry apps are added as folder in my home screen
- I dont want any more app

**But as soon as I touch left or right of my screen, I see a list of apps, which reminds me about those app and kills the basic funda of productivity**

### As screen sides are very sensitive for app drawer, please make a switch to completly disable app drawer. I have everything on my home screen. If i really need i will search from swipe up gesture.

Moreover 15% of left and right  area of screen is reserved for app drawer, that bug me sometime unintentional touch. I want really touch protected scrren but on apps.

**Comment by Oddward** [comment]
The launcher is built with decluttering the home screen in mind, so it's not ideal to have everything in the home screen, just the essentials. It's also suggested to hide the apps in the app list that don't need to be there, that way most of the alphabet disappears anyway

It's also designed symmetrically to be used by one hand, left or right, and I've seen other users complain about the left side being touch sensitive but later saying that they actually use it more than they realize & it's convenient when they do 🤔


Maybe the touch region might be too thicc though considering how narrow many phones have gotten

**Comment by notepadnine** [comment]
I really know that.

but pure minimal and productive way will be more happy if we can avoid sensitive touches

**Comment by nimishmathur1997** [comment]
I would really appreciate if developer could add this feature.

I think a **setting to disable the feature that alphabet bar on right takes you straight to your app list** would be a great feature without hampering the basic ideology of the app. Rather add an option to have a button below the favorite apps to take you to the complete app list or some kind of gesture that does it. 

I think this would help increase productivity since it would add a few steps between opening the phone and going straight to that distracting app. Maybe add this as a toggle so basic out of the box experience remains the same but for those who wants this extra productivity tweak can turn it on.

**Comment by 8bitPit** [comment]
Thank you both, @notepadnine & @nimishmathur1997, for your requests. I share @Oddward's sentiments and believe an option to disable the alphabet isn't impactful enough. In my opinion, preventing unintentional touches shouldn't be handled on an app-level; more about that here: https://help.niagaralauncher.app/article/39-left-hand-mode. If the app list distracts you because it contains apps you want to use less, I recommend hiding all of those from the list (Feature Settings > Hidden Apps).

**Comment by notepadnine** [comment]
sorry i can not say more. 

But below is my problem:

My screen after niagra laucnhre is so beautiful that i do not want to loose focus, 

sometime i touch to see under icon notification. and here comes problem.

**Pelse see below screenshot, how it kills beauty.it is all icon hidden app drawer**

i just think about development effort to maka a toggle to disable drawer and then request still happy to see upcoming features :)
![Screenshot_20210712-205044_Niagara Launcher(1)](https://user-images.githubusercontent.com/5180486/125315370-af230d00-e354-11eb-9379-e0879c3f860f.jpg)

**Comment by Oddward** [comment]
Lol, I guess if you want your app list to be completely empty then it makes sense to want it disabled completely, but adding a button to open the app list would be creating an **app drawer** which is what most other launchers have and something Niagara was designed *against* (if I'm not mistaken)

I'm not sure if it's right to say but there are other minimal list-based launchers that use an app drawer instead. They fit this design criteria but with way less features

## potential fix
Alternatively, this feature could be combined with the hide alphabet feature, so maybe hiding the alphabet on favourites would prompt user if they wanna disable touch on alphabet, or a secret command could affect it 🤔 but for this to be a feature there needs to be another (Niagara) way to access the app list

There's probably very few users that want this though. I personally wanted a *swipe up to all apps* option which could also fall into this group of suggestions 👀 but it's a small *nice to have* kinda thing

**Comment by notepadnine** [comment]
**.........o maybe hiding the alphabet on favourites would prompt user if they wanna disable touch on alphabet, ............**

golden words :)

**Comment by k-bhatia2** [comment]
Yes pls add this feature. As a toggle only...so there's an option for those who want all apps..and for those who don't want it. Would really help to stay productive because then we'll be limited only to the favourites or the search. Would really love to see this feature.

**Comment by 8bitPit** [comment]
> There's probably very few users that want this though.

Yeah, that's my main concern. In my opinion, this feature is neither appealing for many nor necessary for some. 

> Yes pls add this feature. As a toggle only...so there's an option for those who want all apps..and for those who don't want it. 

A few years ago, I thought the same as you. However, adding a toggle for all sorts of things can add up quickly and cause more harm than good: https://help.niagaralauncher.app/article/8-niagaras-design-principles.

I'm sorry, but we don't plan to add this feature.

**Comment by bRexo98** [comment]
I would like the option to disable alphabetic search on both sides to be implemented because when i click on the left edge for an icon or whatever i put there and i don't "take aim" it opens the menu app search.I would just need it on the right because on the left I use the samsung edge panel. the same confuses the home.
It would also be nice to be able to change the position of the alphabet search so that even left-handed people can use it with one hand. Luckily I'm right handed.

Congrats on the awesome launcher and keep it up!

**Comment by alex-koroneos** [comment]
> > There's probably very few users that want this though.
> 
> Yeah, that's my main concern. In my opinion, this feature is neither appealing for many nor necessary for some.
> 

I find that the app drawer often encourages me to scroll through the apps and bump into things I really don't need to doing with my phone right now and generally, apps in the drawer are accessed very rarely (for me it's maybe 1 % of the time). 

Being able to disable the app drawer would really enforce the idea of reducing one's phone to the few important functions. Having to search for all other apps would force the user to really have an intention beforehand (at least enough to remember the name).

Also: I am not sure if my intuition is correct on this, but I kind of feel like this could actually reduce the complexity of the app.

**Comment by andrewteg** [comment]
> I find that the app drawer often encourages me to scroll through the apps and bump into things I really don't need to doing with my phone right now and generally, apps in the drawer are accessed very rarely (for me it's maybe 1 % of the time).
> 
> Being able to disable the app drawer would really enforce the idea of reducing one's phone to the few important functions. Having to search for all other apps would force the user to really have an intention beforehand (at least enough to remember the name).
> 
> Also: I am not sure if my intuition is correct on this, but I kind of feel like this could actually reduce the complexity of the app.

I'm on a Pro trial and agree with this whole comment 100% ... I doubt I'll keep Niagra because of the inability to disable the left side.  The $10-30 didn't scare me off but the lack of this feature does to be honest.

As a lefty, I use my big ol' left thumb most of the time, and I guess I fat-finger it because I've ended up in the K's, W's, and Settings on the all app list more than I've hit a few apps so far, so I'd suggest that from a design principle, having the "hidden" app drawer on the left makes it harder for some lefties overall.
