### ISSUE TITLE
Media widget buttons

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1664]
I think that the buttons of the media widget doesn't fit the actual design and look old. I think this would fit better the Niagara design. They are cleaner and more minimal. 

![3](https://user-images.githubusercontent.com/72170242/125882241-93a09ed1-5f69-4e02-aaee-f26baddc048a.jpg)
![1](https://user-images.githubusercontent.com/72170242/125881946-161f9740-9e3f-4fef-94ea-2d166dd8a356.jpg)

**Comment by Montell2099** [comment]
It would be cool to be able to choose between a few different alternatives, each with its own **small** differences, to be able to better match ones setup style. But I do not agree that the current ones look outdated in any means.

**Comment by 8bitPit** [comment]
In my opinion, the buttons already do their job well; I wouldn't change them.  The arrows for the skip to next and previous buttons would work, but I rarely see these icons to be used for that. Moreover, I prefer the outlined version of the play/pause button because they harmonize more with the other buttons (because they're also thin). About the customization options, @Montell2099, sorry, but we don't plan to add new ones anytime soon: https://help.niagaralauncher.app/article/44-feature-requests.
