### ISSUE TITLE
Minimal Niagara setting page

### ISSUE THREAD

**Issue by sandeshdroid** [8bitPit/Niagara-Issues#1667]
**Is your feature request related to a problem? Please describe.**
No. Make Niagara setting page more minimilastic & functional.
 
**Describe the solution you'd like**
1. There should be no need to click Niagara Pro. It can be moved to 1st setting page where Niagara button is present. Pro or Trial or free can be indicated there. 
2. Move every description (like community, Help and Feedback)  , links to "i" button at top. Put only real setting in settings page. It make setting page simple, minimal.

**Comment by sandeshdroid** [comment]
3. Notification preview can be indicated by icon next to battery icon to make it non intrusive.

**Comment by Oddward** [comment]
The settings page is already pretty minimal, 90% of suggestions aren't accepted in order to make sure of this 😅

1. You could be right, but Niagara Pro is very significant as it's the only way the devs can monetize Niagara sustainably (since it has no ads or sells any info or anything of the sort), so they want to make sure users are very aware of it instead of tucking it away in deeper settings

2. The community is also a significant part of Niagara, and Medium is the official blog where big features, events & ideas are explained. Users are far less likely to tap an *i* icon to find such things, and it doesn't fit the right use of that icon

E.g. the *i* icon exists under Advanced settings to take you to Niagara's system app settings

3. Is this also about the settings page? It's not clear


___
Do note that there needs to be a balance between **minimalism** & **simplicity**, if removing important things from settings will make it harder for users to access those things it's probably not worth it
