### ISSUE TITLE
application list

### ISSUE THREAD

**Issue by brammiij** [8bitPit/Niagara-Issues#1668]
- Sorting not only alphabetically, but also by category (preferably customizable);
- Ability to disable alphabet, apps can also be in alphabetical order, but without letters.
Thanks )

**Comment by 8bitPit** [comment]
Hi @brammiij. To keep the launcher simple, we only want to provide one sort option and are not planning to add the customization option to hide the letters because this feature isn't impactful enough in my opinion. More about that here: https://help.niagaralauncher.app/article/44-feature-requests. However, you could categorize your apps with app-list folders: https://help.niagaralauncher.app/article/38-folders.
