### ISSUE TITLE
Media player collapsing, positioning of favourites

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1669]
I am quite fond of Niagara's media player, especially since the recent addition of the cover images' rounded corners.

However, when ending a media session the media player collapses & the app favourites jumps up a notch. This is problematic following the one-handed usage philosophy of Niagara.

– – – – – – – – – – – – – – – – – – – –
**Example 1, media player active**

![Screenshot_20210719-004523](https://user-images.githubusercontent.com/43126233/126152771-47e00dfe-cc43-476e-8b49-a4dd04fbb3bb.png)

– – – – – – – – – – – – – – – – – – – –
**Example 2, media player dismissed and the favourite apps list is now significantly higher up on my screen real-estate**

![Screenshot_20210719-004533](https://user-images.githubusercontent.com/43126233/126152818-32d0ecc0-e0ed-49a5-9f43-b8b48725f866.png)

– – – – – – – – – – – – – – – – – – – –
**Example 3, how I would prefer the favourites to stay in place, and instead let the Niagara widget slide downwards once the media player is dismissed by the user**

![Screenshot_20210719-004548](https://user-images.githubusercontent.com/43126233/126152895-36d2f262-eb4f-40ba-812c-f31f6fcaad97.png)

Instead of having an absolute positioning of the widget—and the favourites list sliding up once the media player is dismissed—I would love to see the opposite. For example, having the favourites stay static (_parent_) and the widget sliding down (_child_), or maybe somewhat in-between if a compromise is needed.

As of now the favourites become harder to reach whilst not having the media player active. This results in me almost **never** having the media player activated, even though I like all aspects of it in itself.

I am using a Pixel 2 on Android 11. Maybe my rather small display and somewhat low-resolution screen enhances this issue to a higher degree.

Cheers!

**Comment by 8bitPit** [comment]
As always, thank you very much for your very detailed report @Montell2099. I prefer the widget to move the favorites instead of Niagara's widget to keep all media player buttons easily reachable with one hand: 

> ## Why does the media widget push favorites to the bottom?
> Instead of occupying the whitespace at the top, Niagara Launcher's media widget pushes down your favorites further down, and here's why: The upper whitespace has the purpose of reaching interactive elements on your home screen easier, including the playback buttons on the media widget. That's why it makes more sense that the widget shows up below the whitespace and doesn't replace it.
[https://help.niagaralauncher.app/article/11-media-widget]

**Comment by cjjadeja** [comment]
Thank you for the explanation @8bitPit (and for developing this extraordinary launcher 🌟).
I totally agree with @Montell2099 here. I will try to explain my point of view to the best of my understanding. Please bear with me.

Your explanation states that "The upper whitespace has the purpose of reaching interactive elements on your home screen easier, including the playback buttons on the media widget. That's why it makes more sense that the widget shows up below the whitespace and doesn't replace it." 

**1. The elements you interact more with, (should) take priority!?** 

The users would definitely be interacting with "Favourites" and " Notifications in favourites" **far more number of times** than with the "Interactive elements" like kwlp widgets in the whitespace. I understand the lingo, but I'd refrain from calling them "interactive elements" because most of the times, those serve a rather more aesthetic purpose and less functional one. 

Whereas, making my thumb travel at the exact same location for opening my "favourite" app or it's notifications multiple times a day, irrespective of whether the music is playing or not, will be more efficient and productive for me (and for all users, why not!?) 

**2. The whitespace justification**

A vast majority of the users use around 50% of their screens for favourites (you may check the "showcase-and-customization" discord channel to confirm). There's more than enough whitespace available on the top to add "Aesthetic elements". Those users who are pro at using kwlp will adjust in no time, all thanks to their creativity (I'm sure even they would love to have favourites locked to a position). But those who do not have anything in their whitespace, shouldn't have to compromise on a having a better UX just because something could have been in that whitespace right? 

I hope my explanation makes sense, and since Niagra is currently focusing more on features that improve the user's efficiency and productivity, this modification is a perfect candidate in my opinion. 

Please don't get me wrong, I absolutely love this launcher, and I'll do anything to make it better! It is my sincere request for you to consider this modification in behaviour of the Integrated Media Widget. 

Let's discuss more if you like. Keep up the good work ✌️

**Comment by Foxtrot1604** [comment]
This is exactly how I would like niagra to implement and very meticulously explained by the user cjjadeja

I hope someone does take a note of it as I am already in love with the niagra

**Comment by Parth7757** [comment]
Nice way of sharing your experience  @cjjadeja it was great to hear about.

**Comment by upnishad09** [comment]
Very well explained. Id also love to have this feature implemented.

**Comment by JayMehta11** [comment]
> Thank you for the explanation @8bitPit (and for developing this extraordinary launcher 🌟). I totally agree with @Montell2099 here. I will try to explain my point of view to the best of my understanding. Please bear with me.
> 
> Your explanation states that "The upper whitespace has the purpose of reaching interactive elements on your home screen easier, including the playback buttons on the media widget. That's why it makes more sense that the widget shows up below the whitespace and doesn't replace it."
> 
> **1. The elements you interact more with, (should) take priority!?**
> 
> The users would definitely be interacting with "Favourites" and " Notifications in favourites" **far more number of times** than with the "Interactive elements" like kwlp widgets in the whitespace. I understand the lingo, but I'd refrain from calling them "interactive elements" because most of the times, those serve a rather more aesthetic purpose and less functional one.
> 
> Whereas, making my thumb travel at the exact same location for opening my "favourite" app or it's notifications multiple times a day, irrespective of whether the music is playing or not, will be more efficient and productive for me (and for all users, why not!?)
> 
> **2. The whitespace justification**
> 
> A vast majority of the users use around 50% of their screens for favourites (you may check the "showcase-and-customization" discord channel to confirm). There's more than enough whitespace available on the top to add "Aesthetic elements". Those users who are pro at using kwlp will adjust in no time, all thanks to their creativity (I'm sure even they would love to have favourites locked to a position). But those who do not have anything in their whitespace, shouldn't have to compromise on a having a better UX just because something could have been in that whitespace right?
> 
> I hope my explanation makes sense, and since Niagra is currently focusing more on features that improve the user's efficiency and productivity, this modification is a perfect candidate in my opinion.
> 
> Please don't get me wrong, I absolutely love this launcher, and I'll do anything to make it better! It is my sincere request for you to consider this modification in behaviour of the Integrated Media Widget.
> 
> Let's discuss more if you like. Keep up the good work ✌️

Really a detailed and proper explanation by @cjjadeja . I would like to look forward on this

**Comment by piyushbz** [comment]
Yes, having the favorites moving around is pretty annoying!!

**Comment by Oddward** [comment]
The post sounds like it's insinuating that the media widget is perpetually there by default and then when it's dismissed it moves the favourites up, but it's actually the opposite. Wherever the favourites list starts without the media widget is it's current anchor point, and the media widget temporarily moves the faves downwards during a media session so that your whole list doesn't go higher than the anchor point you've set, and at the end of a media session it goes back to its original position.

If its original position is too high you should move the whole list lower (long-press  > move widget)

**Comment by cjjadeja** [comment]
> The post sounds like it's insinuating that the media widget is perpetually there by default and then when it's dismissed it moves the favourites up, but it's actually the opposite. Wherever the favourites list starts without the media widget is it's current anchor point, and the media widget temporarily moves the faves downwards during a media session so that your whole list doesn't go higher than the anchor point you've set, and at the end of a media session it goes back to its original position.
> 
> *(Nothing to do with klwp etc)*
> 
> If its original position is too high you should move the whole list lower (long-press  > move widget)

Ah, if you say it that way, when the media is playing, the favourites "shift" downwards. The problem here is favourites keep shifting when there is media playback. I hope this makes it clear? Please feel free to discuss.

**Comment by Oddward** [comment]
@cjjadeja I wouldn't call it whitespace, the interactive elements are the Niagara widget/custom widget etc, and there's the selected music apps which appear at the top as well when playing audio, making the list longer

So is the suggestion to have the media widget appear elsewhere, or for it to be smaller/less obtrusive to the layout? I'm for a smaller option, but many users wanna see the whole widget and repositioning it anywhere else still holds the issue of an interactive item in the favourites being harder to reach - if it's below users need to scroll down to control playback, if it's above it becomes too high to reach, and since it's a vertical list there's only above & below

Many use KLWP to avoid this

And just to be sure, you can disable the media widget if you don't want it on the screen, otherwise it has to go somewhere. Alternatively u can do what I do & make a music folder at the top with a music widget in it (can assign as music app too)

**Comment by cjjadeja** [comment]
Hi @Oddward , I think I didn't simplify the suggestion enough, resulting in this confusion. 

Let me simplify my suggestion.

The suggestion is _**NOT**_ to have the media widget appear elsewhere, or for it to be smaller/less obtrusive to the layout. 

In simple words, the suggestion is to **keep the favourites in their places irrespective of whether media is playing or not.** 

Here's are a few images to help you explain my suggestion:

1. Present behaviour - Media player moves the favourite down from their original location.

![IMG-20211203-WA0000.jpg](https://user-images.githubusercontent.com/65491088/144482513-615cf72b-00b3-4c28-9713-65d58eb3afbe.jpg)

2. Suggested behaviour - Media player appears above the favourite **without** moving the position of the favourites. 

![IMG-20211203-WA0001.jpg](https://user-images.githubusercontent.com/65491088/144482670-6a84b23d-f6aa-4587-b5dc-c8bbd985c4af.jpg)

I hope this helps explain my suggestion with more clarity. I appreciate you taking your time out for this. :) Let's discuss more if required.

**Comment by Oddward** [comment]
@cjjadeja ah, for the Niagara widget to shift upwards then. I think it was addressed in the knowledge base article for the same reason that similar to how the current way makes the favourites inconsistent, the suggestion makes the widgets above inconsistent 🤔

I don't particularly mind either way, but I think it makes more sense for the fixed anchor point of the list to be at the top and everything shifts downwards, coz depending on your phone users will wanna have an upper limit for reachability (I like to slide my list quite low)

Is the suggestion for aesthetics, usability, or maybe both?

**Comment by cjjadeja** [comment]
@Oddward absolutely right :) _The current way makes the favourites inconsistent, the suggestion makes the widgets above inconsistent._

I'd vote for the "favourites" to be consistent at the cost of "Widget" to be inconsistent, because users interact with the favourites 100s of times a day, but widgets, only a few 10s of times a day. I hope I'm making sense.

**Comment by ayushsharma140** [comment]
That makes total sense. It's definitely more helpful with the favourites locked in their positions.

**Comment by ayushsharma140** [comment]
> Thank you for the explanation @8bitPit (and for developing this extraordinary launcher 🌟). I totally agree with @Montell2099 here. I will try to explain my point of view to the best of my understanding. Please bear with me.
> 
> Your explanation states that "The upper whitespace has the purpose of reaching interactive elements on your home screen easier, including the playback buttons on the media widget. That's why it makes more sense that the widget shows up below the whitespace and doesn't replace it."
> 
> **1. The elements you interact more with, (should) take priority!?**
> 
> The users would definitely be interacting with "Favourites" and " Notifications in favourites" **far more number of times** than with the "Interactive elements" like kwlp widgets in the whitespace. I understand the lingo, but I'd refrain from calling them "interactive elements" because most of the times, those serve a rather more aesthetic purpose and less functional one.
> 
> Whereas, making my thumb travel at the exact same location for opening my "favourite" app or it's notifications multiple times a day, irrespective of whether the music is playing or not, will be more efficient and productive for me (and for all users, why not!?)
> 
> **2. The whitespace justification**
> 
> A vast majority of the users use around 50% of their screens for favourites (you may check the "showcase-and-customization" discord channel to confirm). There's more than enough whitespace available on the top to add "Aesthetic elements". Those users who are pro at using kwlp will adjust in no time, all thanks to their creativity (I'm sure even they would love to have favourites locked to a position). But those who do not have anything in their whitespace, shouldn't have to compromise on a having a better UX just because something could have been in that whitespace right?
> 
> I hope my explanation makes sense, and since Niagra is currently focusing more on features that improve the user's efficiency and productivity, this modification is a perfect candidate in my opinion.
> 
> Please don't get me wrong, I absolutely love this launcher, and I'll do anything to make it better! It is my sincere request for you to consider this modification in behaviour of the Integrated Media Widget.
> 
> Let's discuss more if you like. Keep up the good work ✌️

That makes total sense. It's definitely more helpful with the favourites locked in their positions.

**Comment by Montell2099** [comment]
It's now a bit more than 2 years later since I created this thread, and I recently upgraded my Pixel 2 to a Pixel 7a — which means I now have a lot more vertical screen real-estate on my hands.

I'm glad that at least something small has been done to mitigate this issue, with v1.8.0, but as far as I've read & tested myself you seem to only be allowed a _tiny_ portion of margin between the bottom of the screen & where your favorites are located. At least if you want the media widget to push the clock upwards while keeping the favorites list totally static.

The only way to change this is to use comically small icons as a workaround to use the Niagara media widget **and** always keeping your favorite's list at the exact same position (for muscle memory and pure consistency). I think the solution you implemented is quite unintuitive as well and should, in my opinion, be a simple toggle amongst the Niagara media widget settings.

Many phones these days have basically a 1:2 aspect ratio. Giving us, the users, the option to allocate some of that huge screen real-estate for slightly larger icons _and_ a bit of margin at the bottom would definitely be pleasant.


I have two screen recordings showcasing my experience with this, but cannot seem to upload either images/videos in this thread from my phone. Might give it a try from my computer in a bit. I love Niagara launcher & your style of the media widget, but having the favorites list jump around to different locations — depending on if the media widget is active or not — is a deal-breaker for me. Hence why I unfortunately haven't used it for many years, but I'll always keep paying you yearly for this wonderful launcher because you get everything else right that a launcher should do. ❤️

Kind regards
