### ISSUE TITLE
Suggestion: Change pop-up theme from Material design to Glassmorphism

### ISSUE THREAD

**Issue by Shinra04** [8bitPit/Niagara-Issues#1674]
I believe it would further enhance the launcher's design language. The black pop-ups feel, relatively speaking, way more visually heavy. I feel having it as an option rather than being mandatory would benefit a wider audience.

Reference image attached.
![tia4160047825748916665](https://user-images.githubusercontent.com/43073817/126868386-25a5d74c-be32-4e1e-8b53-44b61414fa76.png)

**Comment by Montell2099** [comment]
I like the glass style pop-up design & it could work, but I would like to see the apps presented in a list, rather than a grid, if you have <3–4 icons — just as it is today.

**Comment by Just-SKY** [comment]
I agree that Glassmorphism is definitely more attractive, and it is visually less heavy than black. 

#Montell2099, he is just talking about the background and not the apps' order.

**Comment by Montell2099** [comment]
> #Montell2099, he is just talking about the pop-up background and not the apps' order.

I was just trying to say that a grid layout could be cool with ~3–4+ apps. :)

**Comment by Oddward** [comment]
@Just-SKY you can use the dark theme instead of the black amoled theme, it has less contrast and is generally better (one of the best dark themes I've seen tbh)

About the blur, when it was discussed before Peter was interested in it but as it stands now 3rd party launchers don't have access to hardware acceleration & the method used by some is pretty hacky (you basically need to have normal & blurred images of everything & play around with that)

Android 12 beta was exploring some better native blur support which would allow 3rd party launchers to properly support blur but as it was removed in the latest beta before final release it doesn't seem likely to make it into any OEM's hands, so it's unlikely atm 🤔

**Comment by tjsuominen** [comment]
On Samsung OneUI 3.x that has been implemented at least when pull-down the notifications. But yeah, that's S.

**Comment by Shinra04** [comment]
> About the blur, when it was discussed before Peter was interested in it but as it stands now 3rd party launchers don't have access to hardware acceleration & the method used by some is pretty hacky (you basically need to have normal & blurred images of everything & play around with that)

In that case, we could instead have a (coloured?) gradient tint (lighter or darker depending on background) from left to right (left being darker for visibility), since one of the comments mentioned how there's so much empty space to the right of the pop-ups. This will still create an effect of glassmorphism.

**Comment by Shinra04** [comment]
This launcher seems to have blur done right, or does it use too many resources?

https://play.google.com/store/apps/details?id=com.luutinhit.ioslauncher

**Comment by Maxr1998** [comment]
As @Oddward already described, blurring is much more complicated than it sounds. Real Gaussian blur (as opposed to fake blurring through a semi-transparent, white overlay) requires access to the underlying content (aka the wallpaper) as well as quite resource-intensive calculations on the individual pixel values.
In principle, there would be two options for that:
1. hand off those calculations to the system to have them hardware-accelerated (which is what iOS does afaik)
2. pre-process the (static) wallpaper, cache the blurred result, and draw the wallpaper yourself

On Android, the launcher however simply draws its content on top of the wallpaper (which is drawn by the system itself), and cannot directly access the layers below. It *can* theoretically get the currently applied wallpaper and do (2), but that doesn't work for live wallpapers (The IOS 15 Launcher linked above does exactly that, but instead of live wallpapers it shows the blurred static system wallpaper which is rather odd).

Android 12 was supposed to introduce hardware-accelerated blurring, but it only works on the window level and isn't useful for us within the launcher. So, as long as the OS doesn't support this properly, we can't either.

**Comment by tjsuominen** [comment]
Samsung does this smoothly when pulling down. Yet, I would expect live wallpapers could be a challenge. Still, would love to see implemented properly. Yet fully understand that this pretty much also Android challenge.

**Comment by Maxr1998** [comment]
I think Samsung also does this on the OS level with hardware acceleration. You mean the notification dropdown, right?

**Comment by tjsuominen** [comment]
Now that the 'Tint' for Niagara has been implemented, I'd still prefer 'blurred tint', but I think that's not an option. As for the pure blurring, I have understood it's not an option currently with Niagara. Hopefully the ability to adjust Tint color etc. comes handy.

**Comment by Shinra04** [comment]
Could this be opened again? Ratio launcher seems to have implemented it rather nicely. The custom widgets look pretty too. 

![Screenshot_20220617-083743_Ratio.png](https://user-images.githubusercontent.com/43073817/174217005-5578d2b4-be25-43bc-aa64-3d47f808a1f7.png)

**Comment by Oddward** [comment]
@Shinra04 reopened based on what? The circumstances preventing Niagara from implementing it haven't changed AFAIK. Refer to Max's comment above

**Comment by Oddward** [comment]
@Shinra04 It's not about live wallpapers or static, it's about the fact that real-time blurring requires hardware acceleration which 3rd party launchers don't have access to atm, and the workaround is too hacky to use (explained a bit by Max above, basically pre-processing & storing multiple versions of the wallpaper image, or just using a white overlay for a cheap effect)

Google was originally reported to be opening up hardware acceleration to 3rd party launchers before A12 iirc but ultimately they didn't, lets hope it happens some time soon

**Comment by Shinra04** [comment]
> @Shinra04 It's not about live wallpapers or static, it's about the fact that real-time blurring requires hardware acceleration which 3rd party launchers don't have access to atm, and the workaround is too hacky to use (explained a bit by Max above, basically pre-processing & storing multiple versions of the wallpaper image and swapping them around, or just using a white overlay for a cheap effect)
> 
> Google was originally reported to be opening up hardware acceleration to 3rd party launchers before A12 iirc but ultimately they didn't, lets hope it happens some time soon

Is this "hacky" workaround going to lead to 100+ MB added space? If so then I get it. But if the concern is only that the blur effect itself looks bad, then I'd ask Mr Peter to reconsider. Also, thank you for the quick reply.

**Comment by Oddward** [comment]
@Shinra04  The devs typically avoid hacky solutions and prefer having proper native support, especially when it's likely to come (soon™)

It might not be **that** heavy but it'll probably add some overhead and can affect performance and add complexity to the codebase (which would also add up with other similar requests)

**Comment by topsy-turvy99** [comment]
Hope Android 14 provides proper API to make blur possible in Niagara Launcher 😅

**Pop-up Menu:**
![HiShoot_20220831_054215](https://user-images.githubusercontent.com/96917972/187569270-b9ce485e-5b4b-454e-95ff-16ba0e783441.png)
**Pop-up Folder:**
![HiShoot_20220831_054819](https://user-images.githubusercontent.com/96917972/187569421-001f8739-1b2e-4aa3-8573-bf1d9eb1340f.png)
**App List:**
![HiShoot_20220831_052546](https://user-images.githubusercontent.com/96917972/187569508-85294f82-3fe2-43d1-89f5-7a0d1300f239.png)
**Niagara Settings:**
![HiShoot_20220831_051545](https://user-images.githubusercontent.com/96917972/187569548-15c14d55-00b2-478c-95b0-0fe6f741cc90.png)
