### ISSUE TITLE
Options in app pop-ups are using the wrong icon shape.

### ISSUE THREAD

**Issue by ceiphr** [8bitPit/Niagara-Issues#1678]
**Describe the bug**
I was switching between different icon shapes in Pixel's style settings and Niagara's settings when I noticed the icon shapes for pop-up options were wrong. By this, I mean, I am using circle, but the shapes of the options are squircle.

Also, it seems that these option icons are being treated as legacy icons. Is that intended? It makes the icons smaller.

**To Reproduce**
1. Change the icon shape in Niagara/system settings.
2. See pop-up options.

Note: I'm not entirely sure how to reproduce this. But it is also important to mention that clearing Niagara's cache and restarting didn't help.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android version: Android 11

**Screenshots**

![Screenshot_20210803-125729](https://user-images.githubusercontent.com/21004034/128056241-7cdcdc24-b59a-4b8f-9e7a-48b5bc9717ae.png)

*See Firefox's New tab/New private tab options.*

**Comment by Just-SKY** [comment]
The native icon shapes of your pixel work independently from Niagara Launcher. When your change icons shapes in pixel's settings, it affects all system icons (apps' icon and apps' shortcut icons, etc. ). 
 However, Niagara's icon shapes affects only apps and not apps' shorcuts like (Firefox's New tab/New private tab options). 

As result that's why there are many times inconsistencies between icon shapes because the Niagara can't change those "shortcut" icon shapes. That is why Niagara has implemented a way to have consistent icon shapes because other brands don't allow their user to choose icon shapes natively (as píxel does).  That's way you see one icon shape (system) within another icon shape (Niagara). 

Go to Niagara's settings > look > icon shape and disable the option shown below. 

![1](https://user-images.githubusercontent.com/72170242/128096064-8c98619e-4ae1-48ea-9c69-a51d1ab5808a.jpg)

As a rasult,  the icons shortcuts will have their original form. You will not see icon shape within icon shape. However, their shapes (icons and shortchuts) are not gonna be the same unless you make them match using pixel's native settings. If not, you can enable the option again to have consistente icon shapes. 
Hopefully it helps.

**Comment by ceiphr** [comment]
@Just-SKY Thank you for clarifying. I appreciate it. I should mention that one part of my issue is that my system icon shape and Niagara's are both configured to "circle" right now. 

What you mentioned does help with the system icons in Niagara icons, but some option icons are stale from when I was using "squircle" icons and clearing Niagara's cache hasn't helped. Is there some system app I can clear the cache of to reset these option icon shapes?

**Comment by ceiphr** [comment]
A quick update on this:

I think this could be related to sesame integration. After disabling sesame, the bug becomes worse.

![Screenshot_20210808-121536~2.png](https://user-images.githubusercontent.com/21004034/128645287-f6e9a15e-a4cf-421e-90ab-0bdacd899f54.png)

IIRC, prior to installing sesame, I didn't notice this problem.

**Comment by 8bitPit** [comment]
We refactored our icon shape system with this year's iconic update. Are the icons now getting shaped properly?
