### ISSUE TITLE
Niagara Configuration Backup

### ISSUE THREAD

**Issue by Laurenzana** [8bitPit/Niagara-Issues#1700]
Having a Niagara Backup as a feature in the pro version to save a Niagara Configuration. Would encourage keeping Niagara as the main launcher when switching phones.

**Comment by Montell2099** [comment]
Yes, I have been waiting for this feature for so long. Would be great if they implemented a way to manually backup all your current favourites—including their designated icons and everything—so that you can easily jump between setups and feel comfortable knowing that you have a solid backup if you want to try out a new icon pack, for example.
