### ISSUE TITLE
Full-width widgets that has controls to the right are unusable

### ISSUE THREAD

**Issue by chiranjeebhub** [8bitPit/Niagara-Issues#1714]
### Describe the bug

I have added a custom widget and then made it full width with "Fill Screen" option. 
But, the widgets that have widget controls to the right are unusable because it invokes the aplhabet list 

For Example, a simple search widget has a search button to the right but if i click it, it will not work.  it will invoke the app list instead 

Tested with following widgets of the apps that i currently have on my phone:

1. Google Search
2. Gmail
3. Google News
4. Google Calendar
5. Google Drive
6. Google Keep
7. YouTube Music
8. Outlook
9. Netflix
10. Audible
11. Flipboard
12. Alexa 

Here's the screenshots of some of the widgets that i mentioned above
https://drive.google.com/drive/folders/1YdVtVhufnQMCcjJ0l9NFYMNk-wiKV9Gv?usp=sharing

### Steps to reproduce

1. Add a Custom Widget (ex: Audible)
2. Long press on that widget and select the option "Fill Screen" from the menu
3. This will make the widget full-width
4. Try clicking on the right most widget control, in case of Audible widget that is a Bookmark button.
5. When clicked on it, It will invoke the alphabets and app list, instead of bookmarking the current timestamp.

### Device name

Redmi K20 Pro

### Android version

Android 10

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/16790416/134568911-b02c7527-353e-4faf-9af3-217f696effa4.mp4

**Comment by Maxr1998** [comment]
Thanks for the heads-up, I'll give this a look.

**Comment by 8bitPit** [comment]
Hi there. We decided to keep the widget as it is, because you don't want the widget to always take precedence over the alphabet. For example, if you use Googles add a glance widget and enable full screen mode to not cut off the date.  However it doesn't offer any touch targets at the edges (the widget is transparent), so you'd expect that tapping on the alphabet also let's you scroll through it. However what we did is having added a warning in the latest Niagara launcher version. We recommend to not activate full screen mode if it has buttons at the edges.
