### ISSUE TITLE
Sort Order in Summary Section

### ISSUE THREAD

**Issue by stanidesis** [8bitPit/Niagara-Issues#1728]
### Is your feature request related to a problem?

I believe you currently sort by which app has the latest notification, even though the notifications are grouped by app (and not by hour/day).

This means every time you swipe away the top-most notif from a single app, the summary may rearrange and force the user to scroll through a new order to find the app whose notifs they were just skimming through. 

### Describe the solution you'd like

I request Niagara sort the notifications by alphabetical app name rather than which app presented the latest notification.

This allows users to dismiss individual notifications without redrawing the entire list of content, and makes it easier for users to scroll to a specific spot on the list, e.g. Wall Street Journal notifications all the way at the bottom, Instagram near the top, etc.

**Comment by Maxr1998** [comment]
We simply mirror the order of the system notification bar, so I think it makes sense to keep it the way it is. But I'll wait for more input from @8bitPit.

**Comment by Maxr1998** [comment]
I've talked about this with Peter and we came to the conclusion that this isn't really how the notification summary is meant to be used. Ideally, after you got your summary, you check the contents, and afterwards use the "close" button to remove the rest of the notifications, so that the next summary only contains new entries.
Additionally, as I already said, the summary simply mirrors the system's notification bar, which doesn't allow said customization either.
