### ISSUE TITLE
Disable side drawer

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#1743]
### Is your feature request related to a problem?

Making another copy to request feature. Few more month experience without this feature.
https://github.com/8bitPit/Niagara-Issues/issues/1661

 I have disabled notification for all app execept favourite apps. I had not opened my notification drawer since ages. I love homescreen the way it looks and accidental touch on side drawer loose that.  
 
 The way Niagra is designed is so perfect. Just a look on homescreen and you know wether you need to check apps or not.It is so time saving. That too good with Niagra Icon set.
 
 Now if I could get remove side drawer or change gesture by touch to long press will send me in NIRVANA for android.

**Please consider this toggle**. All other things I have already achieved either by third party app or KWGT.

### Describe the solution you'd like

Simple toggle to disable or remove side drawer.It also make other people not to flirt with my mobile.

**Comment by Maxr1998** [comment]
I think the original issue you linked (#1661) already answers this, we're not planning to introduce a toggle like that.

Honestly, I believe allowing users to disable touches on the alphabet (or even the all apps list completely) would do more harm than good, as I'm already expecting people to accidentally disable it and then be confused about where their apps went. And as Peter said in the previous thread, a toggle like that doesn't match with our design principles either.

**Comment by notepadnine** [comment]
can you derive kids mode from it :)

**Comment by bRexo98** [comment]
I would like the option to disable alphabetic search on both sides to be implemented because when i click on the left edge for an icon or whatever i put there and i don't "take aim" it opens the menu app search.I would just need it on the right because on the left I use the samsung edge panel. the same confuses the home.
It would also be nice to be able to change the position of the alphabet search so that even left-handed people can use it with one hand. Luckily I'm right handed.

Congrats on the awesome launcher and keep it up!
