### ISSUE TITLE
Suggestion: Allow user to set custom widgets instead of having only default time and music widget

### ISSUE THREAD

**Issue by Shinra04** [8bitPit/Niagara-Issues#1745]
Since we're limited to only 1 custom widget in the favorites (aside from widgets in pop-up folders), it would be a godsend to be able to customise which widget we get to use in place of the stock time, date, and music widgets.

**Comment by JONI350** [comment]
Agreed, even tho i love the time and music widget i really need the music widget to have the like and dislike functionality, also its nice to have it always on screen tho

**Comment by TFackler** [comment]
Hello,

sadly we feel like this suggestion goes against decisions we made in the past. We only allow a single custom widget, because it fits our design philosophy the best. Being able to replace the default widgets with custom ones feels like a workaround to get more widget on the home screen, which we are against.

We also feel like our default configuration should fit the broadest user group, so changing the music widget's features is not something we plan on doing right now.

Closed.
