### ISSUE TITLE
WhatsApp chat notifications are not displayed correctly

### ISSUE THREAD

**Issue by pratyakshm** [8bitPit/Niagara-Issues#1771]
### Describe the bug

WhatsApp chat notifications are not displayed in proper chronological order. The chat notification is supposed to display the latest notification followed by older ones, but it shows the opposite behavior where the oldest unread text is displayed.

### Steps to reproduce

1. Make two people text you at two different times.
2. Even if you received A's text two days before B's text (B's text being the most recent one), it still displays A's chat notification rather than B's notification which is the newer chat.

### Device name

Samsung Galaxy M31s

### Android version

Android 11

**Comment by timm0e** [comment]
Hey :wave: 

Thank you for your bug report :pray: 

This issue is caused by WhatsApp itself: Android allows apps to provide a summary of their notifications, and Niagara Launcher displays said summary in the app list. Somehow WhatsApp does not display the latest notification in their summary, so Niagara Launcher displays it wrong.

We have hoped for a long time that WhatsApp would fix this on their end, but until now, they didn't. 

As a result, we'll try to fix this in Niagara Launcher :+1:

**Comment by pratyakshm** [comment]
Thank you for this! 🥰
<details><summary> I had to do this, I am sorry.</summary>

### Niagara Launcher team when they see that WhatsApp isn't fixing a high hitting bug:
<p ><img src="https://user-images.githubusercontent.com/54220235/169286136-a3d8da69-77dc-4c2f-8052-7df0ef7059b2.png" width="450" height="250"></p> 

</details>

**Comment by 8bitPit** [comment]
@pratyakshm I just stumbled upon this issue and noticed we already fixed this issue. Could you confirm if it's always the most recent chat that displays in our WhatsApp notification preview?

**Comment by pratyakshm** [comment]
Hi @8bitPit! Confirming that this bug is fixed, thus I'll be closing this issue. Thanks for your work!

**Comment by 8bitPit** [comment]
Awesome; thank you for letting me know, and Happy Holidays!

**Comment by pratyakshm** [comment]
Happy holidays to you and rest of the Niagara Team, Peter! 🍾
