### ISSUE TITLE
Weather is not working

### ISSUE THREAD

**Issue by maskyad** [8bitPit/Niagara-Issues#178]
My location is ative, the setting is on. But the weather don't appear on main screen.

**Comment by dsunildatta** [comment]
Yes same issue noticed.

**Comment by Happyfeet01** [comment]
Here also

**Comment by Sacchid** [comment]
Same here.
Location access is given and GPS is on.

**Comment by Happyfeet01** [comment]
It seems the update runs after 6 hours again.

**Comment by aditya369007** [comment]
There is a weather option?
How do I enable it?

**Comment by Shinra04** [comment]
Update your app.
The weather option is buggy at the moment though.

**Comment by stuartglossop** [comment]
Same here

**Comment by 8bitPit** [comment]
I am using Google's Awareness API and it doesn't let you choose a manual location / the refresh reate / show forecasts. I would have to use another weather provider for that, so it's not that easy.

**Comment by 8bitPit** [comment]
This won't be fixed anymore, because Google's weather API will be shut down soon:
> This method is deprecated as of August 07, 2019, and will be turned off on January 31, 2020. Google does not offer alternate functionality for the Weather contextual signal. ([source](https://developers.google.com/android/reference/com/google/android/gms/awareness/state/Weather))

However, I'm switching to a paid weather provider that offers much higher quality data and can be used without location services. I hope it's understandable that users have to pay on a regular basis to use this service, because I have to pay the provider monthly or per weather refresh.
