### ISSUE TITLE
Optional Niagara button placement 

### ISSUE THREAD

**Issue by bruor** [8bitPit/Niagara-Issues#1795]
### Describe the solution you'd like

Trying to use Niagara as a lefty, the only thing that doesn't allow for single handed use on a larger device is the Niagara button itself. 

Please consider an option for left/center/right placement.

**Comment by Oddward** [comment]
@bruor it's explained in [this article](https://help.niagaralauncher.app/article/39-left-hand-mode) that they'd rather not mirror the UI & the button might be a part of that. AFAICT, moving the button over to the left can potentially interfere with the favourites list, especially if one has many favourites, and the point of the overall symmetry in the UI is so that everyone can use the launcher with either their left or right hand (i.e. if one is preoccupied it's usable with the other) so if the button is moved to the left it'll have the same limitation for you in cases where you need to use it with your right hand

Do you find the feature necessary for you?

**Comment by 8bitPit** [comment]
Hey @bruor, thanks for the feedback. Max (codev) and I are both lefties and can use the button comfortably. We're not planning on offering an alternative position because if your device is so wide that you can't reach the bottom third of the screen easily with one hand the layout of other apps (e.g. apps that also use a floating action button or an app bar) would force you two use your phone with two hands either way.
