### ISSUE TITLE
Niagara's weather widget

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1798]
### Is your feature request related to a problem?

I like the weather widget itself, and I consider the extra weather info is unnecessary and unreliable. **It just clutter my agenda,** and I **hate to scroll in order to watch future events**. I prefer my agenda clean and pristine. Sometimes, it is a mess when I have several events. That's is why I don't use the weather widget, I would like to use it again. 
 
![Screenshot_2021-12-30-20-47-25-935_bitpit launcher](https://user-images.githubusercontent.com/72170242/147800804-66468ac5-f09c-424e-b821-dcab56400296.jpg)

### Describe the solution you'd like

I just want my agenda and the weather widget without extra information or just give the info of closer events.
**Or at least, to have the opportunity if I want between the first or second image**
I am 100% sure that more people will find the second image more appealing. Also, it suits more the Niagara's principles. 

![Screenshot_2021-12-30-20-48-08-782_bitpit launcher_1](https://user-images.githubusercontent.com/72170242/147800819-fa769978-1753-49a0-a365-ce9264e178dd.jpg)

**Comment by timm0e** [comment]
Thanks for your submission :+1: 

We have discussed this internally, and came to the conclusion that we won't implement a toggle for this. While I totally see your point, it's basically a toggle to disable half of the weather feature. 
Since we want to keep the number of toggles as low as possible to avoid complexity, this seems not impactful enough to deserve a toggle.
