### ISSUE TITLE
Pop-up folder enhancement

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#1802]
Pop-up folders are one of the best things about Niagara and i feel we could add more flexibility to them.. currently people using widgets are limited to using only one widget per pop-up folder.. 

Solution

Provide two types of pop-up folders

1. The usual list style we currently have

2. A grid type with swipe able pages inside the pop-up folders
The apps can have notification dots rather than the entire notifications..

**Comment by timm0e** [comment]
> A grid type with swipe able pages inside the pop-up folders
The apps can have notification dots rather than the entire notifications..

Hey :wave: 

The grid theme already came up when designing the current pop-ups: https://github.com/8bitPit/Niagara-Issues/issues/13
It was, however, quickly dismissed, since it interferes with our goal of enabling one-handed throughout the launcher.

Furthermore, as you've pointed out, it would completely wreck our current notification system. Additionally, it would break the whole list launcher theme, so it's very unlikely that this will be implemented.

Is there a specific use-case you have in mind that isn't possible within the current list layout?
