### ISSUE TITLE
Music app doesn't show up in favourites list automatically 

### ISSUE THREAD

**Issue by PemikM** [8bitPit/Niagara-Issues#1817]
### Describe the bug

Music app doesn't show up automatically in the favourites list when phone connects to Bluetooth speaker. It shows after I open some app and then go back to Niagara by swiping from the bottom.

I have suspicion that this behaviour started after updating to Niagara 1.5.2

### Steps to reproduce

1 connect phone to Bluetooth speaker
2 music app doesn't show up
3 open any app
4 swipe from the bottom to return to Niagara
5 music app is shown

### Device name

Pixel 4a(5g)

### Android version

Android 12

**Comment by TFackler** [comment]
Hey @PemikM ,

I just wanted to check in with you and see if you still experience the issue. 

Have you tried to replicate the issue on the newer versions of Niagara? You could join the [Niagara Beta](https://help.niagaralauncher.app/article/107-beta-tester) to get early access to version 1.6, which should be available in the PlayStore somewhat soon.

**Comment by TFackler** [comment]
As a quick follow up:

With Android 12 you need a new kind of permission to interact with bluetooth devices, which is probably where the issue you are experiencing comes from. That should be fixed with version 1.6.x. You can get that version now by joining our [beta program](https://help.niagaralauncher.app/article/107-beta-tester).

**Comment by PemikM** [comment]
I can confirm that this issue was solved in 1.6.0.
