### ISSUE TITLE
Most used apps on the search page

### ISSUE THREAD

**Issue by noideahowtocode** [8bitPit/Niagara-Issues#1832]
### Is your feature request related to a problem?

Nope, just a feature request. 

### Describe the solution you'd like

As of now, opening the search page shows the 5 most recently installed apps. I think it would be better to show the 5 most used apps or at least having an option to choose this behaviour.

**Comment by TFackler** [comment]
Hello there,
thank you for your request.

We currently show recently installed apps automatically, since a user might not have memorized the name yet and is thus trying to find it using the search. Your most used apps appear below your manually selected favorites on your home screen, where they can be accessed more easily :) 

Therefore we unfortunatly won't be adding this feature.
