### ISSUE TITLE
Suggestion For Niagara Search: Include Recent Apps, Most Used Apps

### ISSUE THREAD

**Issue by Amorphous404** [8bitPit/Niagara-Issues#1833]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

![IMG_20220123_140533_444](https://user-images.githubusercontent.com/96917972/150670840-ba40e284-e95f-42a7-b9d3-e5a028eb052b.jpg)

Present Niagara Search Only Shows Recently Installed Apps not sure 4-5  
apps for 3 days, which is pretty useless, add 2 more categories recent apps, and frequent that an user can change from the three categories, the default can be set to recent apps, or the user last selected category, in nova it shows 8 apps, considering as Niagara 6 apps per category will be good, it will inhance Niagara search function

**Comment by TFackler** [comment]
Hello and thank you for your suggestion.

In regards to your request:
- **Frequently used apps** show up automatically below your manually selected favorites, thus we are not fond of additionally displaying them in the search.
- **Recently installed apps** will have their own section in the future, therefore we won't add more these to the search.
- We don't feel like **recently updated apps** are something people will often search for. We currently show recently installed apps automatically, since a user might not have memorized the name yet and is thus trying to find it using the search. This does not apply to recently updated apps.

We hope this gave you some insights into our decision.

**Comment by topsy-turvy99** [comment]
> Hello and thank you for your suggestion.
> 
> In regards to your request:
> 
> * **Frequently used apps** show up automatically below your manually selected favorites, thus we are not fond of additionally displaying them in the search.
> * **Recently installed apps** will have their own section in the future, therefore we won't add more these to the search.
> * We don't feel like **recently updated apps** are something people will often search for. We currently show recently installed apps automatically, since a user might not have memorized the name yet and is thus trying to find it using the search. This does not apply to recently updated apps.
> 
> We hope this gave you some insights into our decision.

1. I know, it shows up below favourites but, some users like me already have 8 apps in favorites, that's stops the frequently used app from apprearing, and personally, i don't like other apps messing up my setup on home screen, i suggested the search because it easy to call the search page, and the location i suggested doesn't hurt Niagara's priciple.
2.  I wasn't talking about recent updated apps, i was talking about recently used apps.
3. It's great that recently installed apps will have it's own section, but can it also not include recently updated apps combined?
Example:
1.Youtube
(Recently Updated)
2.Telegram
(Recently Installed)
3.Brave Browser
(Recently Installed)
4.Termux
(Recently Installed)
5.Maps
(Recently Updated)

From what i understand, a quick switch to change the option in search panel, wouldn't be hard to implement, as Niagara already have the algorithm  to suggest, recently installed and frequently used apps.

I hope, you'll reconsider this, this are little QOL Things, Which Some Users Want, i have switched to Niagara for a long time now, still have to rely on Nova Launcher, For This Few Little Things 😔

**Comment by TFackler** [comment]
In regards to your points:

1. Please see the following from my [comment](https://github.com/8bitPit/Niagara-Issues/issues/1890#issuecomment-1086618468). The request feels like a workaround, since if you really use those apps a lot, they should be in your favorites. Maybe using folders could help with this?

> Niagara's feature of showing most used apps in the favorites and the user favoriting their most used apps are some of the fundamentals of our vision. That's why Niagara automatically shows frequently used apps on your home screen and why there are suggestions of frequently used apps when editing your favorites.

2. Could you try to elaborate on the use case of a feature like that? I feel like using the launcher to navigate to recently used apps instead of using Android's built in stack of recently used apps would just be slower.

3. Again I don't seem to grasp the benefits of such a feature, would you mind elaborating what you usually do, that would benefit from a section with recently updated apps?

**Comment by topsy-turvy99** [comment]
> In regards to your points:
> 
> 1. Please see the following from my [comment](https://github.com/8bitPit/Niagara-Issues/issues/1890#issuecomment-1086618468). The request feels like a workaround, since if you really use those apps a lot, they should be in your favorites. Maybe using folders could help with this?
> 
> > Niagara's feature of showing most used apps in the favorites and the user favoriting their most used apps are some of the fundamentals of our vision. That's why Niagara automatically shows frequently used apps on your home screen and why there are suggestions of frequently used apps when editing your favorites.
> 
> 2. Could you try to elaborate on the use case of a feature like that? I feel like using the launcher to navigate to recently used apps instead of using Android's built in stack of recently used apps would just be slower.
> 3. Again I don't seem to grasp the benefits of such a feature, would you mind elaborating what you usually do, that would benefit from a section with recently updated apps?

1. it's not necessary though, i was just looking for way it can be presented in search via a switch toggle without messing the favourites. i don't mind if it's not added.

2. recent used apps is lowkey very useful feature, that's how pixel launcher user dock space to show recently open apps, i used nova it was there right with a swipe in search, or the app drawer suggestion.
 i had an idea that aligns with the newly introduced popup at applist for recently installed apps, 
it would be cool and without hurting Niagara's principle, a option to create popup recent folder in favorites that will show the recently open apps, it's handy, we don't have to scroll through all the apps in recents menu that Android provides to look for recent apps just tap go to home screen and tap on the pop up or swipe it it will show the recently opened apps.

here's a demonstration from nova launcher: the apps you see when i swipe in the search menu are recently open apps

https://user-images.githubusercontent.com/96917972/161384194-65d83ab1-f132-4fc6-ba8e-59d987b8f5c1.mp4


3. i don't have very good reason for it, you can drop that 😅

the second option is very handy, i hope you will give a look into it

Thank You

**Comment by topsy-turvy99** [comment]
> In regards to your points:
> 
> 1. Please see the following from my [comment](https://github.com/8bitPit/Niagara-Issues/issues/1890#issuecomment-1086618468). The request feels like a workaround, since if you really use those apps a lot, they should be in your favorites. Maybe using folders could help with this?
> 
> > Niagara's feature of showing most used apps in the favorites and the user favoriting their most used apps are some of the fundamentals of our vision. That's why Niagara automatically shows frequently used apps on your home screen and why there are suggestions of frequently used apps when editing your favorites.
> 
> 2. Could you try to elaborate on the use case of a feature like that? I feel like using the launcher to navigate to recently used apps instead of using Android's built in stack of recently used apps would just be slower.
> 3. Again I don't seem to grasp the benefits of such a feature, would you mind elaborating what you usually do, that would benefit from a section with recently updated apps?

Just to explain myself better, u created a simple mockup, at the bottom of favorites list a user can add a recently used popup, tapping/swipping will show the recently used apps, just like the new recently installed apps,

you the do the same for most used apps too, but I'm okay without it, but recently used apps will be great feature, it's much faster going to homescreen and opening the app, then to scroll through the all the opened apps in native recents menu

![Frame(17)](https://user-images.githubusercontent.com/96917972/162598216-aa86904b-5067-4a66-826c-b58f559a84c2.jpg)
![Frame(18)](https://user-images.githubusercontent.com/96917972/162598223-3fdffb24-873c-45cb-83a0-74fe71b9b5d6.jpg)

**Comment by topsy-turvy99** [comment]
> In regards to your points:
> 
> 1. Please see the following from my [comment](https://github.com/8bitPit/Niagara-Issues/issues/1890#issuecomment-1086618468). The request feels like a workaround, since if you really use those apps a lot, they should be in your favorites. Maybe using folders could help with this?
> 
> > Niagara's feature of showing most used apps in the favorites and the user favoriting their most used apps are some of the fundamentals of our vision. That's why Niagara automatically shows frequently used apps on your home screen and why there are suggestions of frequently used apps when editing your favorites.
> 
> 2. Could you try to elaborate on the use case of a feature like that? I feel like using the launcher to navigate to recently used apps instead of using Android's built in stack of recently used apps would just be slower.
> 
> 3. Again I don't seem to grasp the benefits of such a feature, would you mind elaborating what you usually do, that would benefit from a section with recently updated apps?

Or if feasible like i suggested earlier, recent app can be added to Niagara Search, were we can switch the search to show the recently installed app or the recently used app like nova,

Currently i figured out a different approach to make search more useful using the Niagara search which helps me achieve that, as well as i can more advance search with the seasame integrated apps and i can use contacts shortcut too, and not being limited to only 3apps

Hopefully with time Niagara search will get more advance 😇

https://user-images.githubusercontent.com/96917972/167495042-e2fb601b-b0c1-4c42-97fb-f6f19cf7ae6c.mp4

**Comment by psychowood** [comment]
Came here to post this very same feat request, so I'm +1 this one.

What about making the number of recent items in home page (after the favorites) configurable? Something like "show the last N items after favorites"=

**Comment by topsy-turvy99** [comment]
> If I have understood this correctly the one feature still requested is a quick way to access recently used apps (similar to what Nova seems to do).
> 
> First of all thanks for all the suggestions and effort that went into this request. The workaround of using Nova's search with the Niagara button is really smart :)
> 
> Sadly the option of an automatically updating folder at the end of the favorites is not something we want to add. This feature would definitely require an additional toggle and we don't think a large enough userbase would use this built in way of accessing recently used apps.

This seemed like a neet idea, don't necessarily have to add a toggle, if a user sets only 7 favorites apps m, then the recently used app popup folder will show up.

I personally think users will like it, if it isn't hard to implement this would be useful feature to add, you can probably take polls from Niagara community i.e discord, telegram, if not you'll probably have the stats on many users regularly use the feature.

**Comment by AndyL964** [comment]
I like it better when the Recently Installed apps were found in the search.

Recently searched apps can be shown while the search box is empty.

Frequently used apps could use a pop-up folder so as to not clutter up the favorites list. After all, Niagara does encourage having at max 8 apps there.

**Comment by TFackler** [comment]
> I like it better when the Recently Installed apps were found in the search.

Recently installed apps can still be found in the search, you just have access to even more recently installed apps in the folder at the bottom of the all apps list.

> Recently searched apps could join the above to be listed in search results while the search box is empty.

That's the same idea we came up with some time ago and we liked it so much we are working on something among those lines ;)

> Frequently used apps could use a pop-up folder so as to not clutter up the favorites list. After all, Niagara does encourage having at max 8 apps there.

The thing with this kind of "overflow" for recommended apps is that the majority of users don't use that many apps frequently. So we struggle to find more good recommendations in the first place. So we don't think this will add a lot of value to the home screen.
Our (probably unsatisfactory) recommendation would be to build this by behaviour by hand.

**Comment by AndyL964** [comment]
> Recently installed apps can still be found in the search, you just have access to even more recently installed apps in the folder at the bottom of the all apps list.

Yeah, I just noticed. But the popup folder is a bit excessive though showing apps that I've installed from a month ago. Does it disappear as you install more rather than with time?

> The thing with this kind of "overflow" for recommended apps is that the majority of users don't use that many apps frequently. So we struggle to find more good recommendations in the first place. So we don't think this will add a lot of value to the home screen. Our (probably unsatisfactory) recommendation would be to build this by behaviour by hand.

Right so if they don't use them frequently wouldn't it be better to have them hidden away in a single popup folder than clutter up their favourites list?

**Comment by 8bitPit** [comment]
I'm sorry but we don't plan to incorporate recently used apps into our search or home screen. For what it's worth, Niagara Launcher [v1.10](https://github.com/8bitPit/Niagara-Issues/releases) now shows recently searched, frequently searched, and newly installed apps when you open search and have yet to enter a query.
