### ISSUE TITLE
Force some language setting regardless of OS settings

### ISSUE THREAD

**Issue by d0i** [8bitPit/Niagara-Issues#1849]
### Is your feature request related to a problem?

Hi, I'm using Niagara Launcher with Japanese Locale settings. It's mostly good, but it has a slight annoying effect due to some i18n features. Some of application names (mostly OS native applications, such as 'camera')  are handled in i18n-ish way and goes to counter-intuitive location. In camera app case, it goes to K. My guess is, it has a Japanese name 'カメラ' and its alphabet notation   'KAMERA' is used in Niagara's context. I rather prefer all applications to use its English name than this complex behavior and I believe it's more intuitive to most of international users in CJK region.

As some of applications has such Alphabet-Japanese and Unicode-Japanese, some only has Unicode-Japanese, some doesn't have localized names, I have to search at most three locations for new applications: English (C in Camera case), Kanji/Non-alphabet ('#' in Camera-case) and Alphabet-Japanese (K in Camera case).

### Describe the solution you'd like

I appreciate if Niagara Launcher can have application-local language setting that overrides OS locale settings. (or 'force English' for simplicity)

**Comment by Maxr1998** [comment]
Hmm yes, that's not ideal. If the transliterator were more context-aware, it would ideally interpret カメラ as camera and put it into the "C" category. Additionally, Kanji should also be transliterated, but I'm not sure why they aren't right now. It could be that the OS isn't smart enough to analyze the correct reading and therefore doesn't transliterate it at all.

Back to your original request: While it is possible for Niagara Launcher to force English locale on the app itself by entering `/localeen` in the search bar, that afaik wouldn't affect the application names returned by the system. For that to change, I think you have to really set the whole system to English (which isn't a solution either).

I think our only option would be to improve the transliterator so that you didn't have to search in multiple sections.

**Comment by d0i** [comment]
Thanks for the informations. I think this is not a critical issue so if there's no easy solution I can just get used to the behavior for now.

**Comment by Maxr1998** [comment]
Alright, I'll close this issue then and instead open an internal ticket to improve the transliterator as described above.
