### ISSUE TITLE
It is necessary to improve the home screen function.

### ISSUE THREAD

**Issue by whaaatsup** [8bitPit/Niagara-Issues#1855]
### Is your feature request related to a problem?

I think the function of displaying some apps on the home screen only when Bluetooth earphones are connected is a really good function, but this makes the list of home screen apps very long and annoying, so I'm not using it much.

### Describe the solution you'd like

So it would be nice to provide a function to hide the app on the home screen while connected to Bluetooth earphones.

**Comment by TFackler** [comment]
Hello there,

I am not quite sure that I understand your proposal completely. 

I undestood it like this:
You would like to have an option to only show the Music apps (you have selected) to appear on the home screen, when you plug in your headphones / connect your bluetooth headphones. 
If this is what you want then sadly we won't implement this, since we don't think it would improve usuability a lot. The Music apps are already shown above your regular favorites as to make access to them easier, so it should not make that much of a difference to hide the remaining favorites.

Should you have questions or if I misunderstood your request, feel free to reach out.
