### ISSUE TITLE
Moving the Niagara button

### ISSUE THREAD

**Issue by Harishkabish** [8bitPit/Niagara-Issues#1857]
### Is your feature request related to a problem?

No, not at all, ability to move the Niagara button around the screen would be convenient and fun without consuming resources. It would also help in customisation to place the button in relation to wallpaper pattern. Press and hold to move the button would do, no separate menu in settings would be required.

### Describe the solution you'd like

Ability to move the Niagara button around the screen would be convenient and fun without consuming resources. It would also help in customisation to place the button in relation to wallpaper pattern. Press and hold to move the button would do, no separate menu in settings would be required.

**Comment by TFackler** [comment]
Hello,

we don't think your proposed feature would be impactful enough as to implement it. We don't think a lot of users would use this feature.

For more information about our design principles, please check out [this article.](https://help.niagaralauncher.app/article/8-niagaras-design-principles).

**Comment by luxiel** [comment]
I disagree. Being left-handed, it is weird to have the button pinned to the right side of the screen,

**Comment by TFackler** [comment]
Allowing the button to be moved freely seems counterintuitive and against our design principles of uniform and easy usage.

@luxiel allowing users to change the button location to be left instead of right would require an additional toggle, that we feel is not necessary since most devices are small enough to be able to reach the button on the opposite side and most other apps also only provide the floating action button to the right. Therefore we won't add a left-handed mode for the Niagara Button.
