### ISSUE TITLE
TickTick widget initialization is slow as hell

### ISSUE THREAD

**Issue by Felipe-Juan** [8bitPit/Niagara-Issues#1859]
### Describe the bug

Always after turning on the cell phone, the TickTick widget that I put takes more than a minute to function properly. 

I can interact with the widget; it's not frozen or something like that. Only it doesn't update and it's still necessary always restart the launcher after waiting for that time.

I've tested it with several widgets and they seem to be just the ones from TickTick. I also checked in another launcher if the same thing was happening, and not.

### Steps to reproduce

1. Put some TickTick widget 
2. Restart your phone

### Device name

Xiaomi Mi6 (with Lineage OS 18.1)

### Android version

Android 11

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/85803620/154806549-6c2a99eb-774b-4d08-9b87-4e4836d18f36.mp4

**Comment by TFackler** [comment]
Hi there,

this sounds like a bug that we know of and have been working on to try and fix it for a while now. 
The bug should not appear anymore in the newest version of Niagara, the [Spring Update](https://medium.com/niagara-launcher/spring-clean-your-home-screen-889e58d60708). 

> Widget Freezing Bugfix: We could finally fix the complex widget freezing bug that plagued the launcher for years. It’s not reproducible with every widget and only happens rarely. When it happened, it froze your widgets.

(from our [Medium Post](https://medium.com/niagara-launcher/spring-clean-your-home-screen-889e58d60708) about the Spring Update)

It's not yet released on the Play Store, but you could join the [Niagara Beta](https://help.niagaralauncher.app/article/107-beta-tester) to get it early.

Should your issue not be fixed in the new version, please reach out again.
