### ISSUE TITLE
Scroll up to view app list

### ISSUE THREAD

**Issue by luridfox** [8bitPit/Niagara-Issues#1863]
### Is your feature request related to a problem?

have another option to get to your list of apps

### Describe the solution you'd like

Instead of clicking on the right side of the screen to see your list of apps, could there be an option to scroll up to go into your app list, then maybe be able to pull it down to close the app list?

I would also like if you click and hold a letter on the right side to be able to see the apps in the letters above and below.  I know I can have that if I just click and let go, it just would make it more smooth and simple.

**Comment by Oddward** [comment]
I've wanted this feature before too lol, just to more easily get to the top most apps, but one of the main ideas behind the alphabet which the launcher is designed around is to skip the step of opening an app drawer and more quickly get to any app you need, this request kinda just comes between that. And it can't be default behaviour since it'd be pretty divisive - remember Niagara is vertical so scrolling up & down is pretty frequent especially with many faves -  so it'll need more toggles, toggles are rarely ever added unless it's considered significant enough - see the [design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)

Do you think it's important or just nice to have?

**Comment by luridfox** [comment]
sorry for the late reply, I personally think it would be pretty important and nice. If so, the alphabet could be not visible on the screen for that. I have learned to use it as is, but I would personally like that.
