### ISSUE TITLE
希望支持多种字体//customize different fonts

### ISSUE THREAD

**Issue by zbodo** [8bitPit/Niagara-Issues#1875]
### Is your feature request related to a problem?

中文用户希望更改字体时能够为汉字与英文字母各自自定义不同的字体。
---
Chinese users want to be able to customize different fonts for Chinese characters and English letters when changing fonts.

### Describe the solution you'd like

I want to be able to customize different fonts for Chinese characters and English letters when changing fonts. -- from google translate

**Comment by TFackler** [comment]
This feature will likely not be implemented at this point in time, since we don't feel like the impact it would have is worth the additional settings options. Also users could search for a font, which looks good for both the chinese and latin alphabet.

Please refer to [Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles).

There are some questions we would like to ask though:
1. How many users do you think would use this feature?
2. How many app names on average are written using chinese letters?
3. Could you please provide some screenshots showing the issue you have?
