### ISSUE TITLE
App on Huawei AppGallery

### ISSUE THREAD

**Issue by xAvatar6969** [8bitPit/Niagara-Issues#1882]
### Is your feature request related to a problem?

I'd like to have Niagara Pro on my new Huawei device which hasn't got Google Mobile Services for pay Niagara Pro.

### Describe the solution you'd like

Make the app available on Huawei AppGallery, so people can easly download Niagara Launcher and buy Pro.

**Comment by timm0e** [comment]
Hey :wave: 

This topic is already on our radar: https://github.com/8bitPit/Niagara-Issues/issues/1482

The solution we're currently considering would, however, not use the Huawei AppGallery, but use a completely independent service to work on all devices.

Would a solution like this also solve your problem?

**Comment by xAvatar6969** [comment]
> Hey 👋
> 
> This topic is already on our radar: #1482
> 
> The solution we're currently considering would, however, not use the Huawei AppGallery, but use a completely independent service to work on all devices.
> 
> Would a solution like this also solve your problem?

Yeah it would solve the main problem (having pro on Google-free devices), but I think that using the AppGallery would be easier and safer than making a paid-version apk (it could be easly downloaded from the internet without paying). Also it would reach more users.

**Comment by timm0e** [comment]
Thanks for your response :pray: 

> Yeah it would solve the main problem (having pro on Google-free devices)

That's great!

We will probably roll out our own solution before looking into 3rd party app stores, since it's more universal and also caters more towards our privacy-oriented users. But I wouldn't rule out that we might appear on the Huawei AppGallery in the future in some form.

Since your main problem would be solved with our solution, I will close the issue for now :ok_hand:
