### ISSUE TITLE
Suggest often used apps in search results.

### ISSUE THREAD

**Issue by Foxbat24N** [8bitPit/Niagara-Issues#1890]
If you can add feature which suggests 2-3 often used apps in search results then it would be nice. I know one can enable to suggest them on home screen but to declutter my home screen I haven't used this. 

If possible... As it is not that important. 😂
![Screenshot_2022_0329_061555.gif](https://user-images.githubusercontent.com/96849717/160510810-31df3416-1d29-4083-b827-ecedfc6970f0.gif)

**Comment by topsy-turvy99** [comment]
> If you can add feature which suggests 2-3 often used apps in search results then it would be nice. I know one can enable to suggest them on home screen but to declutter my home screen I haven't used this.
> 
> If possible... As it is not that important. 😂 ![Screenshot_2022_0329_061555.gif](https://user-images.githubusercontent.com/96849717/160510810-31df3416-1d29-4083-b827-ecedfc6970f0.gif)

I previously requested a switch on the top right corner of search to switch between three option
1.recently installed apps (which got it's own section withv1.6) 👍
2.recently used apps. (Which i would still love to see getting implemented in Niagara)
3.most used apps. ( But I'm okay without it not being added to search)

What i feel is since recently installed apps got it own section, it will be better if it Suggested recently used apps like the pixel launcher or nova launcher, 

As for most used apps can be easily set to favorites or within a popup folder in favorites

****************************

I have an different approach for recently used apps too, like how the recently installed app got implemented in popup folder way, it would be cool and handy, if we could create a pop up folder for recently used in favorites app list.

**Comment by TFackler** [comment]
Hello @Foxbat24N ,

Niagara's feature of showing most used apps in the favorites and the user favoriting their most used apps are some of the fundamentals of our vision. That's why Niagara automatically shows frequently used apps on your home screen and why there are suggestions of frequently used apps when editing your favorites.

We don't think it really fits with what we want Niagara to be and therefore we won't be adding this.

**Comment by TFackler** [comment]
In regards to what @topsy-turvy99 said, please refer to #1833

**Comment by TFackler** [comment]
I will close this issue since there aren't any new points and the discussion has moved to https://github.com/8bitPit/Niagara-Issues/issues/1833 for the most part.
