### ISSUE TITLE
Press kit needs updating

### ISSUE THREAD

**Issue by Sparrow34tr** [8bitPit/Niagara-Issues#1892]
### Describe the solution you'd like

The materials in the press kit are old, I think the press kit needs to be updated to attract new users.

Eg.
![eg1](https://user-images.githubusercontent.com/61355386/160655088-2128efc5-b2bb-4ff2-ae98-0634f4020cee.png)

**Comment by TFackler** [comment]
Hi @Sparrow34tr ,

first of all thank you very much for looking out for us :)

We think our press kit is still up-to-date and we even add new images and resources for every major update.
If you stumbled upon this because Niagara looks a bit different (bigger font and icons, the screen feels a bit more cramped, etc.) on some images, that's because they are meant to be used as thumbnails and such, and therefore need to be a bit bigger to keep things readable.
