### ISSUE TITLE
SMS, Call, and Email Shortcuts don't work in search

### ISSUE THREAD

**Issue by matthewkeating** [8bitPit/Niagara-Issues#1893]
To recreate the issue:

1. Install Sesame
2. Search on a contact name
3. Swipe right on the contact name
4. Try to tap SMS, Email, or Call

Expected behavior: The default SMS, phone, or email app is opened and prepopulated with the contact's info.

Observed behavior: Tapping the shortcuts does nothing.

**Comment by Oddward** [comment]
It works for me on v1.6.2. Can you specify which device you're on? If it's Xiaomi MIUI you prolly need to enable the extra permission to open overlays in the app's system settings (long-press Sesame > tap App info > Other permissions > Display pop-up windows while running in the background

**Comment by topsy-turvy99** [comment]
> It works for me on v1.6.2. Can you specify which device you're on? If it's Xiaomi MIUI you prolly need to enable the extra permission to open overlays in the app's system settings (long-press Sesame > tap App info > Other permissions > Display pop-up windows while running in the background

same thing here, swipe right on contacts on Niagara search for contacts shortcut appears, but tapping on it does nothing, even tried adding the shortcut to favorites, it never worked.

i tried in nova search, it works flawlessly there, even the added shortcut to desktop works.

and one more thing, since Niagara is limited to only the first 3 top sources,
rearranging for search works,

but when the contact swipe addon action shortcut is rearranged in sesame, it still remains the same with the phone, messages and email shortcut.

Niagara v1.6.3
Sesame v 3.6.7
OS: LineageOS 19.1 Android 12.1

**Comment by Oddward** [comment]
Actually I might've been mistaken about that, I think my contact shortcuts contain the device's contact shortcuts coz they're still there regardless of my Sesame toggles 🤔 

If you're referring to the **Contacts Actions Add-on** setting in Sesame I don't think it's part of the integration, it seems new and wasn't included in the integration when the Niagara team was working with the Sesame team for this feature. And now unfortunately since the Sesame team's isn't motivated to work on their app any more and the integration might become redundant in the future I don't think it'll be *fixed* (i.e. file opening support and contacts actions add-on).

I'll check the details and confirm

**Comment by matthewkeating** [comment]
@Oddward Thanks for the reply. To answer your question about my device, I have a Pixel 4a 5g running Android 12.

To answer your question about workaround, unfortunately, I don't know if this works. Being able to use search to locate a contact is central to my workflow. Since I couldn't get that to work, I did not buy the pro version. I just now made Niagara my default launcher to test your workaround but, since the trial has run out, I can't test it.

Anyway, thank you for the help. Good luck.

**Comment by Oddward** [comment]
@matthewkeating  I believe most of Sesame's features should still work the same without the pro integration, but Niagara's search requires the pro integration for more features like the web search and quicksearch atm.

Try to follow the steps nonetheless if you can. I used that method to edit an app's Sesame shortcuts because for some reason when I try to do it through the Sesame app itself sometimes the shortcuts option for that app is grayed out

Also, there's some info in the knowledge base about the [missing Sesame features](https://help.niagaralauncher.app/article/20-sesame-integration#:~:text=Frequently-,Asked,-Questions)

**Comment by Amorphous404** [comment]
> @Oddward Thanks for the reply. To answer your question about my device, I have a Pixel 4a 5g running Android 12.
> 
> To answer your question about workaround, unfortunately, I don't know if this works. Being able to use search to locate a contact is central to my workflow. Since I couldn't get that to work, I did not buy the pro version. I just now made Niagara my default launcher to test your workaround but, since the trial has run out, I can't test it.
> 
> Anyway, thank you for the help. Good luck.
> 
> 

![Screenshot_2022-12-13-17-21-48-40_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/96917972/207310701-96a526d8-9ae6-466e-aa54-3a69c0714b96.jpg)
https://help.niagaralauncher.app/article/20-sesame-integration#:~:text=Frequently-,Asked,-Questions

I'm also excited to inform you that the team is working on native Contact search feature

**Comment by matthewkeating** [comment]
> I'm also excited to inform you that the team is working on native Contact search feature

Very excited to see it. When complete, I'll definitely be trying Niagara again. Thanks for the update!
