### ISSUE TITLE
Please Provide A Way To Disable The New Snap Animation On App List Scroll

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1898]
### Is your feature request related to a problem?

Yes, The New Snap Animation On App List Scroll

### Describe the solution you'd like

The New Snap Animation When Vibration Is Turned On Make Sense, And I'm Okay With That, Other Will Enjoy Vibration And The New Animation Along With It, But Not All Users Like Vibration, I Personally Will Never Use It. The previous animation on app scroll was clean and fluid that one of the top reason i switched to Niagara
, please make the new snap animation on letters gets turned off when the vibration is turned off, or a secret command to fall back to previous style will do the trick, reverted back to v1.5.3 for time being 😅

https://user-images.githubusercontent.com/96917972/161220624-4ba9ff79-bd66-4130-8932-415fcdf15a6c.mp4

**Comment by TFackler** [comment]
Hey again :)

Sadly detecting whether the vibrations are on or off is rather complicated, since there are very factors to it, some of which we don't have access to. Therefore your proposal of using the older more linear scroll animation when the vibration is off is not possible.
We won't be switching back to the old animation, but since you feel like it is laggy, we will be looking into the fps count and see if we stumble upon anything.

**Comment by topsy-turvy99** [comment]
> Hey again :)
> 
> Sadly detecting whether the vibrations are on or off is rather complicated, since there are very factors to it, some of which we don't have access to. Therefore your proposal of using the older more linear scroll animation when the vibration is off is not possible. We won't be switching back to the old animation, but since you feel like it is laggy and we had someone else point out something similar (#1895), we will be looking into the fps count and see if we stumble upon anything.

to be clear, my device supports vibration, it works fine, and the snap app scrolling was quite laggy during the initial beta, now it's much stable for me with the latest build, i turned on the fps counter from developer option and checked right now, it doesn't drop,

what I'm asking is when the Allow Haptic Feedback Is Turned Off In Niagara Settings, It Should fall back to previous simple animation,

the reason I'm asking is i don't feel comfortable, with the new snap animation, it just doesn't feel right, ik it's personal preference but that is what i was used too for a very long time, and that was the sole reason for me to jump to Niagara from Nova (nova too allows app list scrolling but the fluidity and quick access that Niagara provides is way too flawless, now with the snap animation, I'm really off about it, a simple command to resort back to previous animation if the vibration is turned off in Niagara setting) will do the trick.

Thank You 🙂

**Comment by TFackler** [comment]
Hello again,

we are glad the lagginess disappeared :)

We feel like the new scrolling animation is better than the old one, since it makes precise navigation easier. Adding a toggle is not an option either, since that would go against our principle of simplicity. There are not a lot of requests to change the animation back, therefore we feel the request is also lacking impact.

Sadly we won't fulfill your request.

**Comment by topsy-turvy99** [comment]
I just hoped the snap animation gets turned of when the allow vibration feedback is turned off, but anyways I'll try to get along with it, but please do improve the scroll further, it's smooth now, but sometimes it jutters, idk what's causing it, but hope it will get improved overtime 🙂


You can close the ticket.
