### ISSUE TITLE
Dismissing media widget stopped working in Niagara 1.6.x

### ISSUE THREAD

**Issue by PemikM** [8bitPit/Niagara-Issues#1899]
### Describe the bug

It is not possible to dismiss media widget by swiping right or left in Niagara 1.6.x. Even for apps for which it was working in previous Niagara versions (in my case Stellio player and Google podcasts). It is possible to dismiss it after Niagara restart or after disabling or enabling the widget in Niagara settings.

### Steps to reproduce

1. Launch some media app
2. Let it play something
3. Go to home screen
4. Pause the playing
5. Swipe right or left on the widget. There is some animation but the widget is not dismissed.

6. Restart Niagara or disable and enable the media widget.
7. Swipe on the widget and it is dismissed.

### Device name

Pixel 4a(5g)

### Android version

Android 12

**Comment by timm0e** [comment]
Thanks a lot for your bug report :blush: 

You're not the only one with that issue. We can confirm the issue and hope to provide a solution soon. :+1:

**Comment by tjsuominen** [comment]
Great and hopefully this gets fixed. This has bugged me every morning when Spotify wakes me up through Google alarm.

**Comment by PemikM** [comment]
Fixed in 1.6.4. Great job. 👍

**Comment by 8bitPit** [comment]
Thanks :)
Fun fact: It wasn't even a bug but an intentional change by Spotify, probably a reaction to Android's media player behavior changes. Anyway, we added a workaround to still swipe the player away. On top of that, you can also swipe the player while it is playing; dismissing it will cause the track to stop automatically.
