### ISSUE TITLE
Smaller Font Size

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1921]
### Is your feature request related to a problem?

The 1.6.2 font is smaller than the 1.5.3 (previous), and actually it is getting frustrating. The previous font size was better. Actually, I suffer visual problems and smaller means a problem, and visual problems are on the menu now a days. You must think about this kind of things before making this kind of decisions. If maybe you think that it is not a deal, it could be a big deal for people with visual problems. At least, I think that if want to make it smaller, you could give the user the opportunity to decide their font size.

I consider this aspect important cuz their are tons of people with visual problems. I really appreciate if you consider it. This could make the use Niagara a nightmare for many. Minimalism, productivity, and accessibility should go hand on hand. This should be on the main list.
I know maybe you are gonna tell me is planned, but now it should be a must. Sorry, if I sound rude, but this is getting frustrating AF now. 

### Describe the solution you'd like

Give the user the opportunity to set font size, as the icons.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Sorry to hear that. What the recent changes do is just try to normalize custom font sizes to be more in line with the standard font size because custom fonts can vary quite a bit in size. 

The base font size hasn't been changed, Niagara just follows the system font size & tweaks custom font size, and devices have a font size setting in the system settings for the same reasons you're highlighting. It might be in display settings or accessibility settings. Please try to enlarge it there and see if it works for you
