### ISSUE TITLE
Hide Recently Installed Popup

### ISSUE THREAD

**Issue by DitriSenapati1** [8bitPit/Niagara-Issues#1922]
### Is your feature request related to a problem?

After the new spring update it just feels unlike Niagara to not provide a way to disable the Recently Installed pop up.
For users who need a more cleaner setup I think there should be a way to hide it from the launcher. This is wierd since according to your Guidelines a new feature should not bother anyone else not using it however it is.

P.S. I already opened an issue regarding this but I was referred to an issue that was not even my primary focus.

### Describe the solution you'd like

A toggle in the Features section to disable it.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Foxbat24N** [comment]
It we can use swipe gesture in search also then why doesn't recently installed folder permanently be placed in search results instead of bottom of app list.😁😁😁

I mean this could be an alternative.

https://user-images.githubusercontent.com/96849717/163451464-44bc4749-eef1-4e8e-a9f7-ba961b653529.mp4

**Comment by Oddward** [comment]
You just recently opened an issue about this which was marked as a duplicate - #1920 - please don't keep opening the same issue again, you can request a previous one to be reopened if there are valid reasons. 

The previous one could be renamed to better fit the intended request instead of making it more vague, I'll close this and rename that one.
