### ISSUE TITLE
Support for other language sorting

### ISSUE THREAD

**Issue by sunghokim1030** [8bitPit/Niagara-Issues#1924]
### Describe the solution you'd like

When using this launcher, it is romanized based on Korean and sorted in English. Please support the sorting in other languages, such as Korean, along with sorting in English.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Niagara opts to categorize everything into the Latin alphabet to keep the alphabet to a reasonable size. Otherwise, it could be difficult to navigate it with just one hand. Also, since many apps with English names don't have an alternative name available for the user's target language, keeping it as Latin allows the mix of different language names to be grouped together and easy to navigate. 

Ultimately, Niagara's alphabet system isn't good if too many characters are cramped together. 

You can also rename certain apps to rearrange them in the app list, e.g. by adding the letter you want in front. [How to edit app icons and names](https://help.niagaralauncher.app/article/97-edit-app-icons-and-names)

---
To transliterate Japanese, Korean and Chinese words into Latin, Niagara uses [Android's transliteration engine](https://developer.android.com/reference/android/icu/text/Transliterator), which is not implemented by Niagara devs. If you notice any apps that are transliterated badly, I recommend applying this little workaround: Prepend the letter you want to arrange it in by renaming it: https://help.niagaralauncher.app/article/97-edit-app-icons-and-names
