### ISSUE TITLE
Add traditional Chinese version 

### ISSUE THREAD

**Issue by xillinnq** [8bitPit/Niagara-Issues#1927]
### Is your feature request related to a problem?

Hello, I like this app very much, I hope to add a traditional Chinese version. 

The current version has a lot of Simplified Chinese mixed with Traditional Chinese, which is used by people from two different countries in reading. 

Although it can be read, it will be very uncomfortable. (Like the feeling of Americans listening to Japanese speaking English) In addition, the traditional Chinese ethnic group is also a big market.

### Describe the solution you'd like

It is suggested that Simplified Chinese and Traditional Chinese can be separated into two versions. 
If the team is willing, I will be happy to assist in translating Traditional Chinese and some Simplified Chinese.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Thanks for the offer, @xillinnq . Niagara's translated versions are actually a community effort and anyone can contribute to translations over on Crowdin. More info here: https://help.niagaralauncher.app/article/80-help-translate 

Note that the launcher's language setting will follow the system's language setting, so if there's a system setting for Traditional Chinese instead of Simplified Chinese make sure the system is set to that and see if the translations are good.
