### ISSUE TITLE
Recently Installed Pop-up folder

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1928]
### Is your feature request related to a problem?

Recently installed apps disappear from the "Recently Installed Pop-up folder" when they are hidden from the app list. I know that you are gonna tell me that if I hide an app, it would make sense to hide it from the recently installed folder. 
However, if a user move the new app to a folder and hide the app from the app list, it will disappear.  So it could be very inconvenient.

![2](https://user-images.githubusercontent.com/72170242/164299667-4cf64d97-60fc-4eb9-834b-f8075896033e.jpg)
![1](https://user-images.githubusercontent.com/72170242/164299695-45d9862a-823f-4a76-b434-8119e71d908a.jpg)

### Describe the solution you'd like
Keep showing the apps even when they are hidden from the app list, or if they already in a folder. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by timm0e** [comment]
Hey 👋 

Thanks for your submission!

The hidden apps feature is designed to hide bloatware and other apps that you don't want to see on your home screen. For this reason, we want to keep the apps hidden wherever possible.

Since this feature would conflict with said design goal, we do not plan to implement it 😣
