### ISSUE TITLE
Dark mode not implementing on Recently installed & niagara settings icon.

### ISSUE THREAD

**Issue by Foxbat24N** [8bitPit/Niagara-Issues#1929]
Dark mode should be implemented on following icons -
1. Recently installed
2. Niagara Settings
3. Notification summary
4. Add widgets
5. Sort apps by usage
Etc.
![Screenshot_2022_0421_013218.png](https://user-images.githubusercontent.com/96849717/164312942-95028be0-6219-4420-9314-cb3a653999ca.png)
![Screenshot_2022_0421_013202.png](https://user-images.githubusercontent.com/96849717/164312972-b130b193-4efc-439a-8baf-c6416ea322d1.png)

**Comment by timm0e** [comment]
Hey 👋 

While we would love to make Niagara's icons more uniform with icon packs like these, we sadly can not implement a simple dark mode like this, since it would have to work with every icon pack. 
Peter has already experimented with light icons on dark backgrounds, but he told me it just didn't look good.

We already have #1595, which might be implemented in a way that allows icon packs to override Niagara's own icons (but this is just an idea at this point).
