### ISSUE TITLE
Provide Location near weather widget.

### ISSUE THREAD

**Issue by Foxbat24N** [8bitPit/Niagara-Issues#1954]
Dear Team,
It would be great if you can provide location near the weather widget. It might be placed on the red lines in given screen shot.
![Screenshot_20220508_174949.jpg](https://user-images.githubusercontent.com/96849717/167295826-e227989d-c541-413a-abcf-d24a320d3beb.jpg)

Like in the other widget...
![Screenshot_2022_0508_175009.png](https://user-images.githubusercontent.com/96849717/167295844-80285956-01d3-4f26-b8ac-82aac22986e7.png)

And if your weather service provider - Open weather provides you AQI of the location then you may implement this also.

Thanks.

**Comment by Oddward** [comment]
Hey. This features seems unnecessary as the user knows their location at all times, so it goes against its minimalism. There are even requests to have less content in the agenda than there currently is. Do you think it's useful for most users to see that info there? Maybe only for travelers. 

For now if you want a more detailed view of the weather info I recommend getting the OpenWeather app as well, in which case long-pressing the weather in the agenda will open the OpenWeather app.

**Comment by topsy-turvy99** [comment]
> Hey. This features seems unnecessary as the user knows their location at all times, so it goes against its minimalism. There are even requests to have less content in the agenda than there currently is. Do you think it's useful for most users to see that info there? Maybe only for travelers. 
> 
> For now if you want a more detailed view of the weather info I recommend getting the OpenWeather app as well, in which case long-pressing the weather in the agenda will open the OpenWeather app.

https://user-images.githubusercontent.com/96917972/167822573-7fcbc81f-fe96-4137-9ef4-d2a71875d291.mp4

Hey, this is a weather widget from meta launcher,

instead of opening the weather app or link on long tapping, a separate weather page can be incorporated into the launcher, to show rest of the weather info without one needing to install the weather app, meta launcher does the same which also pulls the data from openweather.com, we don't have to install the weather app, all the information are provided when we tap on the widget,

If one want to open the Open weather app, he can use the open weather icon at the bottom to open the app just like it open weather website

I hope you'll look into incorporating something similar into Niagara Launcher,

Thank You

**Comment by Oddward** [comment]
@topsy-turvy99 the point of the Niagara widget and agenda are to have everything in a single place with a simple minimal view, adding all of these things doesn't add to that. Looks like the data in your example weather page is already in the agenda too: detailed weather for the day + 1 week of weather overview (and another request thinks it's too much info for a simple agenda 🤔 )

The location name is arguably useful as travelers might need it, we'll have to see, but I believe most users are either fine with the amount of information displayed or get another app/custom widget to have a more rich experience that's outside of the scope of the launcher. 

The shortcut to the OpenWeather app is built in because that's the data source so it'll have the same data set to display to the user, and you can contact their team through it in case of any region issues/inaccuracies.

**Comment by topsy-turvy99** [comment]
I mean those data in the screen recording i shared are presented without needing to install the open weather app, like sunset time, sunsrise time, windspeed etc

I thought the same can be incorporated Which will launch upon long tapping instead of one needing to install the open weather app 😅

**Comment by TFackler** [comment]
Hey there,

we have a couple of questions regarding the nature of the features you requested :)

### Adding the Air Quality Index:
What would you (personally) use this information for? 
We only see the it being useful if the air quality would fluctuate quite heavily and users using the quality to determine whether they should leave their homes, etc. .

### Adding the current location to the weather widget:
What is the reason you'd like to see this information every time you look at the weather?
The location would only be useful if the user has selected the automatically updating location and wants to check whether Niagara does this properly. Otherwise the user should be aware of the location they chose. Are you perhaps experiencing any issues with the automatically updating location?

### More detailed weather screen
@topsy-turvy99 
We don't feel like showing weather information to that degree of detail is something that Niagara Launcher should be responsible for, that's what weather apps are for :)
As @Oddward stated, we support the shortcut to the OpenWeather app for the purpose of showing users more detailed information should they want to.

**Comment by topsy-turvy99** [comment]
Okay, no worries i just demanded it because i don't use the one weather app, and use a different weather app that uses the one weather api, but sadly long tapping will only open the one weather app, if one has it installed.

Since this weather thing was discussed, i thought I'll share my idea here.

You can close the ticket.

**Comment by Oddward** [comment]
@topsy-turvy99 sunset and sunrise are available in the agenda with those icons of the *sun on the horizon* between the hourly weather states

![Screenshot_20220517-093151_Niagara Launcher.png](https://user-images.githubusercontent.com/22635314/168754913-527665bf-1b14-4815-aa98-153619b0148f.png)

@TFackler I think showing the location would benefit those who're actively travelling to ensure they have the right info on-the-go, but as this is not a common request maybe it's not that important 🤔

**Comment by topsy-turvy99** [comment]
Oh great, how did I miss it, thank you 👍, yeah location will be good addition, not on homescreen but on the agenda panel in a minimal way, to make sure if it got the right location

**Comment by TFackler** [comment]
As @Oddward stated, the only real use-case for displaying the location would be users who travel far and often. We feel like that user group would be rather small and even then the current location would not add much value, while all other users would be effected by this change.
Therefore we don't think the current location to the weather is something we want to add.
