### ISSUE TITLE
Option to keep Niagra widget auto centered

### ISSUE THREAD

**Issue by nightshade427** [8bitPit/Niagara-Issues#1974]
### Is your feature request related to a problem?

When adding a favorite or media player and notifications pop into widget the widget stays in place and no longer centered causing lots of manual recentering when adding favorites etc.

### Describe the solution you'd like

It would be pretty cool if there was option 'keep centered' for the Niagra widget. This would make it easy to add favorites and keep widget centered without have to recenter the widget everytime. Same for when media player or notifications pops into widget, it would keep widget centered.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hey @nightshade427 can you please demonstrate the request with the help of a video :)

**Comment by nightshade427** [comment]
Can't really leave a video but you can replicate pretty easily.

1. Add three app favorites to home screen (Niagra widget)
2. Center Niagra widget vertically on screen
3. Add 3 more app favorites 

Notice the top of the Niagra widget didn't move and now the widget is no longer centered requiring manual reposition to center align vertically again.

**Comment by Amorphous404** [comment]
Not sure if I'm getting it right, but let me try after vertically repositioning/moving Niagara widgets/apps to the centre, when you add any new apps to the list, you want the widgets to automatically move up? 

![IMG_20221218_235500.jpg](https://user-images.githubusercontent.com/96917972/208313304-5c75714f-81b3-4add-96df-39a1123432fe.jpg)

**Comment by nightshade427** [comment]
Yep, keep itself auto centered vertically.

**Comment by Amorphous404** [comment]
Sorry the team won't be working/changing the behaviour, as it will definitely require us to add a toggle for the behaviour, which isn't "impactful" enough.

Impactful:  It is either appealing for many or necessary for some.
https://help.niagaralauncher.app/article/8-niagaras-design-principles

Regarding the music player with v1.8.0, if you move Niagara widget past its default position, when the music widget shows up it will move the Niagara widgets/music up instead of pushing the favorites down.
