### ISSUE TITLE
Apps fade in when unlocking phone.

### ISSUE THREAD

**Issue by Majorzen51** [8bitPit/Niagara-Issues#1978]
### Describe the solution you'd like

Favourited apps and widgets fade into the home screen when unlocking the phone.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Which phone is this? Please provide more details as a lot of things are device-specific

**Comment by Majorzen51** [comment]
It's not an issue, I want it as a feature when unlocking the home screen.

**Comment by Oddward** [comment]
You mean like the current launcher load in animation? A lot of users already think the fade in effect is too much or too frequent, this doesn't seem like it would be a positive feature or worth a toggle (see [Niagara's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles))

The animation currently happens when the launcher restarts, maybe you could set it up to restart at those times with Tasker or something 🤔
