### ISSUE TITLE
Toggle off recently installed apps & Niagara settings

### ISSUE THREAD

**Issue by akanjans** [8bitPit/Niagara-Issues#1985]
### Is your feature request related to a problem?
The "recently installed apps" and "Niagara settings" shortcuts are always visible when all apps are cleanly organised in folders and then hidden. Both shortcuts are redundant (settings can be accessed elsewhere) but clutter up the screen. This goes against the vision of this launcher to create a simple, clean UX. 

Example of the 'alphabet' after all apps are nicely organised and then hidden:
![Screenshot_20220704-100055_Niagara Launcher](https://user-images.githubusercontent.com/102547880/177110553-ef8650a4-8d79-4b7b-a818-dfd09aa088af.jpg)

### Describe the solution you'd like
I want to be able to hide the "Recently installed apps" and the "Niagara settings" shortcut. When both are disabled, the "Niagara launcher" heading should also be invisible. 

To me, just one setting that disables the entire "Niagara launcher" section with both shortcuts at the same time would be fine. 

I appreciate that you are very hesitant to provide too many toggle options. But ever since introducing pop-up folders which enable the awesome feature to hide all apps and clean up the alphabet, these shortcuts have become a real pain. I hope you agree that an additional setting is a worthy trade-off given the current bloaty situation. In the end, the main value Niagara launcher provides for users is not its simple customisability, but the cleanness of the resulting interface.

### Alternative solution

If you really do not want to add a setting, I would also be happy if you simply do not show the "Niagara launcher" section when opening the "Pop-up folders" section (diamond icon). This way, both Niagara shortcuts are still available, but only when you actively navigate towards the Niagara launcher section at the bottom of the alphabet (dot icon).

**Comment by Oddward** [comment]
Please refer to issue #1682 about those icons and Peter's comment on it, or #1920 with more of my attempt at explaining. 

I'll close this as a duplicate

**Comment by akanjans** [comment]
Thanks for your reply. I noticed those issues before posting and in hindsight, I should have referenced them. I apologise. 

I think this ticket deserves additional consideration for the following reasons:

* Ticket #1682 argues that people might not find the Niagara settings again if it's not at the bottom of the alphabet. It also argues that the feature is not worth an additional toggle in the settings menu. The alternative solution I propose takes both considerations into account: You can keep the Niagara Launcher section at the bottom of the alphabet and simply only show it when a user actively navigates to it (the dot icon in the alphabet) instead of also showing it when a user navigates towards the pop up folders (diamond icon). This is actually a more consistent user interface. When I navigate to favourites, I only see the favourites, not the pop up folders that follow immediately after when all apps are hidden. But when I navigate to pop up folders at the moment, the Niagara section is also shown on screen. That is weird and unnecessary. What do you think of this solution? Is it  an easy fix? 

* Ticket #1920 argues that the problem isn't in anyone's way because it only occurs when someone decides to hide all apps 'for some reason'. I'm showing that there is a very legit use case for hiding all your apps in pop-up folders. I know other people who do as well. It's not a fringe use case. 

* The content of this ticket is not covered by the other two tickets, since this ticket refers to hiding the entire Niagara Launcher section. Not just the settings or just the recently installed apps.

I know this issue's name is a bit unfortunate because it mentions a toggle, which is not necessary for the 'alternative solution'. 

Would you consider the alternative solution and reconsider opening this ticket again?

**Comment by Oddward** [comment]
@akanjans generally if the topic is a duplicate you should comment on the pre-existing ticket and request it be opened again providing your additional comments, that makes it easier to track the whole discussion and reduces redundancy. Also makes it easier to point to that thread if there's another duplicate.

This isn't a fringe use case but it's a way of using Niagara that kind of goes against its design. The folders are expected to be used to e.g. group/categorize some hidden apps to declutter which you likely won't remember whenever you need them, and then apps that you use now and then remain in the apps list where the alphabet is useful. The entire launcher was built around the alphabet navigation, that's why a full on alternative categories system isn't in place as it's a very different system. The incentive is also mostly aesthetic which isn't a priority when it's nit-picky and pretty out of the way

But I did bring it up to the devs and I invite you to post your comment in the original thread as well
