### ISSUE TITLE
Improve home button action

### ISSUE THREAD

**Issue by Rod911** [8bitPit/Niagara-Issues#199]
Currently the the home button brings up the search and 'G' swipe does Google search, you could change the home button action to toggle between favorites and the all apps. 

The app search and Google search should be integrated into one 'Search' button available on both favorites and the apps list. 

This 🔎 option could be later improved to include results from messages, contacts[, mail, notifications, settings, music, play store, etc] (as optional settings of course).

This would in my opinion improve the search experience since the 'G' is only visible in favorites and app search only in the app list.

I'm not sure if i want to change from the search bar on top to search icon on bottom on the apps list, I'll let you tinker with it.

**Comment by Shinra04** [comment]
- Why would you need a toggle between Favorites and all apps? The scroll is beautifully implemented for this reason.
- Integrating both the search features doesn't seem necessary at the moment. Searching for apps is just a tap away, and anything online is a swipe away. This differentiation keeps things from getting chaotic in my opinion. 
- This idea is pretty good, but idk how much the launcher would have to intrude on permissions for that. Still sounds convenient though.
- The G search only in the Favorites screen is fine because you can always go back to it in 1 tap. The apps search too, 1 tap away.

**Comment by Toontje** [comment]
It's even easier than that. My workflow is as follows: Home button searches for apps, Google icon on the keyboard (GBoard) searches on Google. All under one button. Nothing to change.

**Comment by Shinra04** [comment]
That's a thoughtless suggestion.

**Comment by Toontje** [comment]
Explain

**Comment by Pietje7** [comment]
And how about the Home button for lockscreen (as one of the options for the Home button). I use it in Nova and think it's way better than the actual on/off button.

**Comment by 8bitPit** [comment]
> And how about the Home button for lockscreen (as one of the options for the Home button). I use it in Nova and think it's way better than the actual on/off button.

See: https://github.com/8bitPit/Niagara-Issues/issues/63

**Comment by 8bitPit** [comment]
> Currently the the home button brings up the search and 'G' swipe does Google search, you could change the home button action to toggle between favorites and the all apps.

Personally, I prefer the "press home to search" option, so you can open app search even faster. Furthermore you can already go to all apps pretty quickly by tapping on the salphabet / the edges of the screen. 

The app search and Google search should be integrated into one 'Search' button available on both favorites and the apps list.

> This 🔎 option could be later improved to include results from messages, contacts[, mail, notifications, settings, music, play store, etc] (as optional settings of course).

Yeah. Since the post was created, several other issues about that were made, I'll link to those and close this one: https://github.com/8bitPit/Niagara-Issues/issues/336 & https://github.com/8bitPit/Niagara-Issues/issues/58
