### ISSUE TITLE
App Switcher

### ISSUE THREAD

**Issue by abhy-kumar** [8bitPit/Niagara-Issues#1992]
### Describe the bug

The app switcher gesture on Niagara is slower and more unreliable than competing launchers like Nova. I know Google is repsonsible for this, and Nova gets around this by a hack through accessibility permission and detecting when the bar has been interacted with to open the app switcher ASAP, something which I sorely miss on Niagara, for a launcher's main purpose is management between apps. 

### Steps to reproduce

1. Swipe up from the bottom bar to access app switch

### Device name

Oneplus 9R

### Android version

Android 12

**Comment by Oddward** [comment]
Thanks for the suggestion, but Niagara devs don't prefer to implement hacky solutions and this issue is device-specific. Many launcher devs are more actively trying to get the Android team to fix some long-running issues by communicating directly with them, although we can bring it up to the table again (will update if there's a change)
