### ISSUE TITLE
Apps with special characters are shown under # in the alphabet

### ISSUE THREAD

**Issue by Runee** [8bitPit/Niagara-Issues#2002]
### Describe the bug

Having apps that start with a special character such as Æ, Ø, Å, Ö, Ä, etc. lumps everything together under # (numbers) at the top of the alphabet. An app starting with Ø for instance should be under the letter Ø, not #. 

### Steps to reproduce

1. Install an app starting with a special letter (Ø, Æ, Å, etc.)
2. Try locating it on the alphabet
3. You will find that if is under #. 

### Device name

OnePlus 7 pro 

### Android version

Android 10

**Comment by Oddward** [comment]
This isn't a bug, it's intentional. Text is converted to English characters based on its transliteration (using Android's native feature) to ensure the alphabet doesn't get too long as some languages or character sets can be too long and make the alphabet navigation system too difficult to use, and special characters are placed under the # section. If you want it to be under a different letter - e.g. based on a sound - you can rename it (long-press > tap title) and add that letter at the front.
