### ISSUE TITLE
Add to Category multiselect

### ISSUE THREAD

**Issue by AndyL964** [8bitPit/Niagara-Issues#2031]
### Is your feature request related to a problem?

Add to category only allows one selection at a time. If you want to both add an app to a pop-up folder and hide it from the app list, this can take about 8 taps.

### Describe the solution you'd like

Make it possible to select multiple options when using Add to Category function.

If a pop-up folder is chosen, the launcher can go through them one by one in case you want to reorder the app lists.

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
You can already add multiple apps to a popup folder by:

Long tap on the folder icon>Edit Folder Popup>Select the apps that you want to add to that particular folder.

And the feature to auto hide apps that are already added to a popup folder has already been requested in #1604, you can drop a 👍 there

**Comment by AndyL964** [comment]
You're talking about editing a pop-up folder. I'm talking about adding an app to various folders + hiding them. Having to do it separately for each folder would take a lot of unnecessary taps.

**Comment by topsy-turvy99** [comment]
It will be difficult to implement i guess, since when adding an app to a category, it doesn't directly adds it to the popup.

Eg: when you long app an app>add to category>choose the desired category i.e folder> it opens up the edit page for that particular category.


Can you please share a use case which apps you like to add to various folders?

And to hide the apps that are added to the folder, a clean and simple auto hide toggle has been requested and the devs are giving a thought about it (shared above)

For example: when you add an app to a category>popup folder, it will automatically hide the app from applist, when you remove the app from the popup folder the apps will be visible again in app list without a user having to hide the apps that are added to folder.

**Comment by AndyL964** [comment]
Not really, just go through the respective edit pages of each selection one by one.

Examples could include Netflix (both streaming and games) and Steam (both shopping and messaging).

I can't deny an auto-hide won't be helpful though, but that's only for hidden apps; what about the Music apps feature?

**Comment by topsy-turvy99** [comment]
To Select All The Music Apps In One Go

Niagara Settings->Features->Music Apps

Or

Long Tap on any app you want to set as music app->Add to category->Music Apps->Now the music selection page will open up-> select all the apps you want to set as music app.

**Comment by AndyL964** [comment]
You can already do that with hidden apps and other pop-up folders as well.

The way I see it is that the "Add to category" function makes it easier to add a few apps here and there rather than a whole bunch in a single place.

So what I'm saying is if you just want to add like 1 app to 5 different folders, it would make it much easier to select them all and go through them one by one rather than having to trigger the function again between each addition.

**Comment by Amorphous404** [comment]
Sorry, we don't plan to support this.
