### ISSUE TITLE
Niagara settings icons change to random icons when scrolling to bottom

### ISSUE THREAD

**Issue by ThePhantomGM** [8bitPit/Niagara-Issues#2033]
### Describe the bug

Niagara settings, recently launched, and Niagara pro shortcuts change icons to random icons in the currently used icon pack, in this case whitcons. It usually happens after using an app for a while and going back to the home page.

### Steps to reproduce

1. Use any app for a while, 10-15 minutes
2. Go back to the home screen
3. Scroll all the way down using the alphabet
4. The icons will be seen as random icons from the icon pack for 1-2 seconds

### Device name

Poco M4 pro 4G

### Android version

Android 11

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/66557032/187088502-631ec721-5a70-4dbc-9385-3777717419a6.mp4

**Comment by ThePhantomGM** [comment]
> Are you on the latest Niagara v1.7.4 beta?
> If yes, then this is an intended behaviour to make the icons load faster on demand in the background.

The video is recorded using the 1.7.2 version but the same thing happens even when I updated to the latest version, even if it's intended I would not call it the most visually pleasing "feature".

**Comment by topsy-turvy99** [comment]
it's not much noticeable and rarely happens, so shouldn't bother the users much, and ig there is no other way to fix or else devs would have fixed it already (but still if the devs find a way they will definitely improve the behaviour)
But the good thing is the icons load faster than previous niagara versions.


And this is the actual response from the dev regarding the behaviour:

This is kind of intended. Niagara Launcher loads the icons on demand and in the background. Usually, it will load an icon so fast that you won't notice it, but there seems to be a lot of other work going on on this phone, or the phone has low-end specs. We show a random app icon while loading the right icon because switching from one icon to another isn't as noticeable as switching from nothing to an icon (that only works if the icon loads within a few milliseconds, though, which it mostly does).

**Comment by 8bitPit** [comment]
@ThePhantomGM, thanks for reporting, and @topsy-turvy99 for explaining why Niagara Launcher does that. The alternative would be to show no icon at all, but then replacing the icon is more noticeable in normal behavior.
