### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2039]
### Is your feature request related to a problem?

While searching by alphabet is great it works on muscle memory of the app or games name. Searching by categories would allow for app game discovery which reveals app games you may not have considered. 

### Describe the solution you'd like

Simple unobtrusive implementation... firstly allow users to categorise apps into games, productivity, photos etc. Some automation based on googled categorisation would be helpful to do some of the heavy lifting. 

Once categorised, different categories are denoted by a simple icons e.g. game controller for games appear above the alphabet, perhaps with an option to appear on the other side of the screen to create clear separation with alphabet searching. 

Clicking a category opens the category in list view or folder. 

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
I personally waited for some **direct categorisation feature** in Niagara Launcher to simplify the process, now with the latest version we have the add to category option, it's great 👍 but i personally feel it's not that intuitive, I still think a dedicated option to assign category to each app for a launcher like Niagara would be great feature and should be looked into, and I hope Niagara users will appreciate this feature too

**Suggestion:**

- A Dedicated page in Niagara Settings named "App Categories"
- Wherein there will be the list of all the categories names, where user can add/modify the category list.

- At the bottom of the list there will be two buttons

1) Opens up the Assign category page
- where users can assign a category for each app by tapping on the app (just like the new edit icon manually page)

2) Reset Category Button
- Which will clear app category from all the apps users assigned

**Here's a rough mockup i made to demonstrate the feature:**

**1) App Category Settings Page:**

![HiShoot_20220901_235631.png](https://user-images.githubusercontent.com/96917972/187990978-fb65549e-040e-46ae-8c75-3acd507f4bf1.png)

**2) Niagara Settings>App Category>Assign App Category Page**

![HiShoot_20220901_235739.png](https://user-images.githubusercontent.com/96917972/187991347-3cfd011d-276c-4d21-b031-8e2571bd0f37.png)

**3) Edit Popup Folder Page>At the buttom there will option to select the category i.e Internet, Shopping etc (just like app shortcuts)**

![HiShoot_20220901_235810.png](https://user-images.githubusercontent.com/96917972/187992010-1ca3129c-2477-4b86-b652-76c8e8085716.png)

**4) How it would end up looking at the edit Pop-up folder page**

![HiShoot_20220901_235829.png](https://user-images.githubusercontent.com/96917972/187992218-1df8996a-0300-4583-ac8f-2610ad966f99.png)

**5) " " " looking in Pop-up Folder**

![HiShoot_20220902_003600.png](https://user-images.githubusercontent.com/96917972/187993155-6253bd7a-acaf-49cc-b31c-ceeb20f119cf.png)

**Comment by topsy-turvy99** [comment]
Here's Another method/demonstration inspired from Ratio Launcher search button for allowing users to switch between different categories via Niagara App List "Search Button" (The tap action will still allow users to search the apps) which i feel perfectly aligns with Niagara one hand mode style.

I think this feature also aligns with #1763, and also help the users asking for a way to sort the apps based on category in Niagara.


1) Niagara app list Search button swipe up to switch between different categories:

![HiShoot_20220902_041515.png](https://user-images.githubusercontent.com/96917972/188032299-a749f27d-e437-483f-bb6c-3f3945b868b0.png)

2) Opening the category apps in list based fashion "navigating apps via app list scroll has a different feeling, which i miss when using a popup folder 😅"

![HiShoot_20220902_041528.png](https://user-images.githubusercontent.com/96917972/188032323-109b2f31-f309-4da2-857f-e3e2a60a7e54.png)


3) Here's the original screen recording from ratio launcher, it feels amazing to trigger to swipe up button with a subtle vibration feedback.

[]()https://play.google.com/store/apps/details?id=com.bllocosn

https://user-images.githubusercontent.com/96917972/188032711-e149bc5f-f754-4851-9f9e-56ab9a3a669d.mp4

**Comment by Just-SKY** [comment]
I don't see the purpose of this. We have folders which are basically the same my friend. 
If you want games just create a folder "games" with all your games. 
If you want banking, entertainment, social, etc. You just create a folder for all of them. So, you are asking for same thing with different name. 
This is just an unnecessary way to create folders.

**Comment by topsy-turvy99** [comment]
Folder & Categories are two different things 😅

**Comment by Lorestan00** [comment]
Sure I get what your saying. I didn't realise categories already existed but as the poster above says better ways it could be implemented. I actually wanted a quick way to access categories or folders from above the alphabet, like the favourites icon currently  but for categories or folders. This way you can quickly click on a icon of a controller denoting games or document icon for productivity. At the moment you need to scroll through you favourites to go through folders or categories which is slow

**Comment by Foxbat24N** [comment]
I couldn't utilise the category feature.  For example I've all my banking apps inside Google pay pop up but when assigning an app to this category this folder/category (Google app) is not shown there in the category list.

Also I am sceptical that developers will not include this in future that is why I resist myself to create an issue for this on GitHub.

I have to take many steps to do this only because making a different folder is not making any sense to me. I took a primary app as a category and put each related app inside it.

**Comment by topsy-turvy99** [comment]
> I couldn't utilise the category feature.  For example I've all my banking apps inside Google pay pop up but when assessing an app to this category this folder/pop up (Google pay) is not shown there in the category list.
> 
> Also I am sceptical that developers will include these in future that is why I resist myself to create an issue for this on GitHub. 😅
> 
> One can see in the attached video that I have to take many steps to do this only because to create a different folder is not making any sense to me. I took a primary app as a category and put each related app inside it.
> 
> https://user-images.githubusercontent.com/96849717/193429515-017b6374-148a-41af-9895-6931768a90e6.mp4
> 

Seems like another option to select an app under add to category can be added

Or the category based option (point no 4: select category mockup that i shared)

**Comment by topsy-turvy99** [comment]
> I couldn't utilise the category feature.  For example I've all my banking apps inside Google pay pop up but when assessing an app to this category this folder/pop up (Google pay) is not shown there in the category list.
> 
> Also I am sceptical that developers will include these in future that is why I resist myself to create an issue for this on GitHub. 😅
> 
> One can see in the attached video that I have to take many steps to do this only because to create a different folder is not making any sense to me. I took a primary app as a category and put each related app inside it.
> 
> https://user-images.githubusercontent.com/96849717/193429515-017b6374-148a-41af-9895-6931768a90e6.mp4
> 

Seems like another option to select an app under add to category can be added

Or the category based option (point no 4: select category mockup that i shared)

**Comment by Oddward** [comment]
It's been mentioned a lot of course, but it's not very compatible with Niagara. Folders were basically developed as an offshoot of this (before that there was only app pop-ups to pin other apps under them).

The launcher is based on and was designed around the alphabet navigation system, a categories system is a very different system altogether and requires a host of other design and testing paradigms and more settings (e.g. a whole page like Typsy suggested). There's no intention to bloat the app so much and make it more complex for users and developers, such features usually should enhance what Niagara already does instead of changing it entirely. 

Atm folders work better with Niagara and work like a second categorical alphabet/list when they're consolidated to the bottom of the app list (which is easy to get to by just tapping the diamond at the bottom of the alphabet). The "Add to category" feature however could still be tweaked and optimized for a smoother experience, so it's useful to highlight any confusion, problems or shortcomings everyone has with that feature & folders in general. 

Also seems like Niagara has its own approach to categorization which is to have some specific simple ux for different types of apps, e.g. music apps have a system, calendar apps have a system, maybe apps like games or email can have a category or filter or shortcut of some kind.

#970 #13 (we better continue there for future discussions)

### alt
There's an idea of possibly generating or automatically renaming/theming new folders based on your apps or what apps you place in a category, but no real plan atm afaik. 

### alt2
I also like @topsy-turvy99 idea of choosing category/type in the Edit folder page, I feel like the Edit pages are a decent place to experiment/add stuff without cluttering the UI/UX overall
