### ISSUE TITLE
Shortcut icons ignore custom icon applications

### ISSUE THREAD

**Issue by neilkirklin** [8bitPit/Niagara-Issues#2044]
### Describe the bug

Shortcuts that come with apps, like "New Task", "Compose", "Search", have their own icons inside pop-ups. These icons can be customized manually in the same way as any other icon. However, any changes made do not actually get applied - the shortcut icon stays the same.

### Steps to reproduce

1. Reveal pop-up window for any application that has its own shortcuts (such as Chrome)
2. Hold down on a shortcut
3. In the configuration menu that appears, tap on the icon of the shortcut
4. Choose any custom icon from the list
5. Check if the icon is applied (it is not)

### Device name

TCL 10 Pro

### Android version

Android 11

**Comment by Amorphous404** [comment]
Third party launchers can't change/modify the original in-app shortcuts added by the app (however it is a bug that Niagara still provides the option to modify it, when you tap on the icon), however you can modify it if you add them as shortcut in other areas of the Launcher i.e favorites & app list

**Comment by 8bitPit** [comment]
Hey, @neilkirklin, thanks for the report. It's intentional that shortcuts only show custom icons when added to favorites or app list but not inside the parent's app pop-up; here's why: https://help.niagaralauncher.app/article/148-shortcut-theming-limitations. So, it was a bug that the manual icon chooser opens when tapping on a shortcut icon in the app options menu - we've now fixed the bug.
