### ISSUE TITLE
Sort apps based on notifications

### ISSUE THREAD

**Issue by sammukhgupta** [8bitPit/Niagara-Issues#2067]
### Is your feature request related to a problem?

1. Folder popups having a list of apps.
2. Notification header is shown on the homescreen under the folder (for included app)
3. Wanting to see the notification details, click on the folder, however need to scroll to find the app

### Describe the solution you'd like

Under the folder popups the apps with notifications should come on top. Once the notification is read / dismissed the app sequence goes back to initial setup.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Will the suggested change have much of an effect in making it easier to view notifications? Apps with notifications have a clear visual indicator (arrow & notif preview) so it should be very quick to find even if you need to scroll. Having the list rearrange so often could also be confusing.

**Comment by sammukhgupta** [comment]
I feel it will make it easier to check notification details and dismiss. For example, I have all the work apps in a work folder popup. It has about 15-20 apps. When getting notifications opening it does not immediately show the notification details, instead I have scroll through the list. Using the notification shade seems easier for now and am not using the notification functionality in the launcher at all for apps in folders now. And since this is for the popups and list goes back to normal when dismissed. It will just like the music app functionality, where on bluetooth connect event the music apps come up. Similarly on notification event the notification apps come up at least in the folders.

**Comment by Oddward** [comment]
One of the reasons notifications alerts aren't given special priority and bubbled up or grouped is because it's seen as redundant as the notification tray does exactly that and is easily accessible, Niagara aim is to highlight notifications of your important apps or the ones you choose to show in faves/on top. If it's about catching up to a lot of notifications the notification shade is probably more ideal

I mostly use Niagara's view anyway coz the interface is nicer for interacting with/reading those notifications, but it's often easier to check random updates in the shade.

Seems like the notification summary was developed as an offshoot of this idea. See issue #152 and the article [Notification section](https://help.niagaralauncher.app/article/35-notification-section). Devs are generally not in favour of regularly shifting favourites, but maybe this is more like the Sort apps by usage feature. 

Main issue is probably that it won't be a good default for users so it'll require extra configuration options.

**Comment by 8bitPit** [comment]
Merged with #152.
