### ISSUE TITLE
Touched so many areas of development as Launcher but more I need

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2081]
### Is your feature request related to a problem?
Editing post
All I want a progressive developing home screen. Even you can see
![image](https://user-images.githubusercontent.com/5180486/194755514-c4742300-3750-46bf-8319-438c409f9c17.png)

**This image is same since launched.** 
Do not we deserve a little more customization or option op toggle after 3 year of company
![image](https://user-images.githubusercontent.com/5180486/194756362-7283256e-9946-4cf4-9ff5-eee75fabe50e.png)

I am not comparing Google iteratively working on cosmetics to beat other OSes

**Comment by Oddward** [comment]
I'm not sure if this is a joke or not. You reviewed 4+ years of issues and determined that no development has been made and no user requests were ever entertained? You can peruse Peter's [Niagara launcher Medium blog](https://medium.com/niagara-launcher) for a quick preview of feature updates over time, and go through the [feature list](https://help.niagaralauncher.app/article/40-niagara-pro-features) linked in the app, not including minor updates, changes and bug fixes. 

It's stated in the Feature request article what kind of requests will not be accepted as it's not a focus for the launcher and there's no intention to bloat the app's settings for its main audience for a set of minor conveniences. To make development more streamlined, Issues are closed if they don't align with design principles or they're not feasible to do within a reasonable time frame (they can be reopened/revisited later). If you're not satisfied with the progress or the design policies it can't be helped, but most feature updates arrive through user suggestions and discussions, and take time to develop (design > implement > test > repeat > release > maintain etc), so your claim of "no development" and rejecting all requests is unwarranted. The app's development doesn't live and die on github issues alone.

What's your goal with this issue? You could've sent an email or talk in the chat communities if it's not about a bug report or suggestion and just to get the devs' attention 🤔 You checked the box that said you read the Feature request article but there's no specific topic to address here

**Comment by notepadnine** [comment]
Sure it is joke . But you guys sideline working on the main feature of niagra launcher the IDLE screen, It is same since launched. No feature provided to enhance the look of static screen. 

I am been member of your pro since launched. I am not going anyway away from android. But I do support you by buying yearly subs(3.1$ in my country)

**Comment by Foxbat24N** [comment]
Personally I don't have any issue with Niagara's home screen... And I like it also but what I suggest is that Niagara should work on its own widgets. Yes I know they did a great job in widget section and it would be same on me if I asked more but because of the topic on which I am commenting. I want to present some suggestions and these are just suggestions not demands...😅😅 I love this app so much.. it is near perfect and I believe that developers are more creative than me in this field.

Suggestions -
1. If there is more than one events then it should be shown in motion i.e. one after another in few sec. (But if it consumes battery then there is no need)

2. Embedded note app - yup here I am asking too much and it's illogical also, it is beyond the purview of a launcher I think. But I don't know why some people if not many asked this feature and I am one of them. 😅 Actually it goes with Niagara's look and theme as it is a list launcher and may be we want a to-do- list embedded in a list launcher.

And though Niagara is a launcher and not a weather app but it works like a weather app which was one of the unique/best pro feature then why not noted.

3. Stack widget like samsung's one UI 5 (if not everywhere then only on home screen) - it's been a long time we have asking for this & I acknowledge that developers are not fan of widgets and it drains battery as well but widgets are trending. This may be a gimmick like apple's dynamic Island but it helps apple to sell their products and so does this feature will, I believe. 🙏 With due respect. @8bitPit 

At last, I believe developers are more creative and knowledgeable than me. Seriously their "Icon Assistant features" astonished me about their creative imagination. Salute. It was a solution to a problem not just a useless feature, ethers provide in the name of update 

Thanks for the good work team.
And apologies if I have offended anyone, I mean, I know this project is your brain child and I have no right to tell you what will attract customers or not. Therefore, sorry for crossing that line.

💛💛💛💚

**Comment by notepadnine** [comment]
1. I seriously agree their ICON feature(Even though I did not use as pro member) is way more futuristic than all launcher available today
2. For a todo list I have already raised request, and they agreed. But it is not started. Also I offer them to add some syn like todoist, g task
3. A note embedded within favorite(Best if alter position) is way more  beautiful than anyone can imagine

Still I do agree also that Niagra team @8bitPit have created(a big task) something which I even could not think of. For boring note I tried all launcher from play store(Only those which comes in search for term "Launcher")
