### ISSUE TITLE
Dynamically tint icon pack based on original app icon color

### ISSUE THREAD

**Issue by banasiak** [8bitPit/Niagara-Issues#2091]
### Is your feature request related to a problem?

I love the clean look of using Niagara launcher with the Whicons icon pack. The consistency is amazing. However, for me at least, it seems more difficult to quickly recognize the app I'm looking for with the absence of color.

### Describe the solution you'd like

It would be amazing if there was a simple option to dynamically tint icon pack icons based on the primary color found in the original app icon. For example, the Messages icon would be tinted blue and the YouTube icon would be tinted red. I hypothesize that this would still offer a clean look while providing a mental shortcut that could reduce cognitive complexity when trying to find the right app in the list.

I would love to whip up some proof-of-concept code and give it to you under a permissive license if that is something you're interested in.  Thanks for considering this!

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
Thanks for the suggestion, @banasiak, and for your kind offer. For now, I recommend an outlined icon pack that comes with tinted icons, such as [LineX](https://play.google.com/store/apps/details?id=com.jndapp.line.x.iconpack) or [Linebit](https://play.google.com/store/apps/details?id=com.edzondm.linebit).  While we don't plan to add tint to third-party icon packs because it would only look for a handful of icon packs, we're working on our own icon pack and will experiment with tinted icons. Happy Holidays!

**Comment by wimstefan** [comment]
Why not using Icon Pack Studio? It's designed for exactly that purpose.

**Comment by banasiak** [comment]
@8bitPit Thanks for considering this. I'm excited to see the Niagara icon pack when it's ready!

@wimstefan I discovered Icon Pack Studio after opening this issue. It does mostly what I want it to do and that is what I'm using at the moment. Thanks for the suggestion.
