### ISSUE TITLE
English is displayed instead of Korean 

### ISSUE THREAD

**Issue by HASH0000FFprint** [8bitPit/Niagara-Issues#2118]
### Describe the bug

The system language is Korean, but English is displayed. 

### Steps to reproduce

Install version 1.8.1 or higher on your Galaxy device 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

FOLD 3(oneui 5.0), 4(one ui 4.1.1)

### Android version

Android 12, 13

**Comment by 8bitPit** [comment]
Hi @HASH0000FFprint, thank you very much for reporting. This is because our app is currently only translating 69% into Korean. We set a threshold of 70% to decide which languages we use (so that the displayed language is consistent), and Korean is just slightly below because we had to add lots of new phrases in v1.8.0. Unfortunately, I can't speak or write Korean; it would be wonderful if you could help us out and translate a couple of phrases: https://niagaralauncher.app/translate

**Comment by HASH0000FFprint** [comment]
So if it exceeds 70%, it will be seen in Korean, right?

**Comment by 8bitPit** [comment]
Yup

**Comment by 8bitPit** [comment]
Thanks for helping with the translations @HASH0000FFprint :D I included your strings along with all other Korean translations in our latest release.
