### ISSUE TITLE
F-Droid search

### ISSUE THREAD

**Issue by aquaplanet** [8bitPit/Niagara-Issues#2122]
### Is your feature request related to a problem?
No

### Describe the solution you'd like

When searching for an app by pulling up, you also have the option to search on the web and play store. F-Droid would be a great addition to this list of options. No idea even if it is possible. Could be extended to all store apps Niagara launcher detects on the phone. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for the suggestion :)

This does sound useful and in fact we already have something similar in Niagara. The "Search for more apps" option doesn't necessarily open Google Play but your default app-marketplace app. If you use F-Droid primarily you can set it as your default in Android and then Niagara will automatically open it instead.

If you use multiple marketplaces at the same time you might want to not set a default at all, then Niagara will prompt you each time which app it should use.
[Here](https://help.niagaralauncher.app/article/112-reset-default-app) is how you can reset the default (most likely the app you are searching for is 'Google Play Store').

Because we already have this functionality and we feel like it would bloat the search quite a bit to add an option for each marketplace app installed on the device we sadly won't add this feature.

**Comment by dinesh-58** [comment]
Hi, I use [Droidify](https://github.com/Droid-ify/client) instead as an F-Droid client. Droidify doesn't show up as an option to select which app to open, when searching for apps from Niagara. Do you know how to have it listed there / register Droidify as an app marketplace, and how Niagra handles app searches? I wanted to have some more background info before creating a feature request for this on the Droidify repo. I assume it's not as simple as allowing the app to handle `play.google.com` links?
