### ISSUE TITLE
关于应用搜索

### ISSUE THREAD

**Issue by djdjfjfkeocj** [8bitPit/Niagara-Issues#2133]
### Is your feature request related to a problem?

应用搜索我希望可以关键词搜索
例如：当我搜索“邮箱”时可以跳出“QQ邮箱”
而不是必须要搜索应用的开头，如“QQ”

### Describe the solution you'd like

应用搜索我希望可以关键词搜索
例如：当我搜索“邮箱”时可以跳出“QQ邮箱”
而不是必须要搜索应用的开头，如“QQ”

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
**Translation**:

**Is your feature request related to a problem?**

Application search I hope to be able to search by keywords
For example: when I search for "email", I can jump out of "QQ mailbox"
Instead of having to search for the beginning of the application, such as "QQ"

**Describe the solution you'd like**

Application search I hope to be able to search by keywords
For example: when I search for "email", I can jump out of "QQ mailbox"
Instead of having to search for the beginning of the application, such as "QQ°

**Comment by Amorphous404** [comment]
Hey @djdjfjfkeocj if possible kindly try to post your issues/feature request in English, so that other users can take part in the conversation. (You can use Google Translate app)

About your request, it's already possible to search apps with keyword.

![Screenshot_2022-12-15-06-42-01-18_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/207750259-4726f358-a423-4588-8823-89b251420d04.jpg)

**Comment by djdjfjfkeocj** [comment]
thanks
