### ISSUE TITLE
Adjust home screen Y layout

### ISSUE THREAD

**Issue by prylarer** [8bitPit/Niagara-Issues#2156]
### Is your feature request related to a problem?

When using on one hand and and apps located in the middle of the phone it's hard to reach the icons.

### Describe the solution you'd like

 If you could adjust home screen starting from the bottom, reaching the apps with thumb was possible.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Sorry we don't plan to change/add an option to change the behaviour.

Here's the original response from @Maxr1998 (co-developer) regarding the issue:

Probably not. The current location is kinda a compromise, because if you have many apps for a given letter, there should more of them be shown preferably.  
Thus, you can't put it too low or you'd need to scroll a lot more often after "superscrolling".

Using a different top position for different letters might seem like an easy solution, but unfortunately this feels very jarring in practice when it's jumping around and makes it much harder to read the current letter during the scroll process.

[]()https://www.reddit.com/r/NiagaraLauncher/comments/uwo6n9/request_question_possible_to_adjust_where_the_app/izrmyhh?utm_medium=android_app&utm_source=share&context=3

**Comment by Amorphous404** [comment]
Merged with #1721
