### ISSUE TITLE
Show notification count

### ISSUE THREAD

**Issue by udayrajkule** [8bitPit/Niagara-Issues#217]
Hey add the notification dot or no. on app

**Comment by 8bitPit** [comment]
What do you mean by that?

**Comment by udayrajkule** [comment]
Exp. If msg come on whatapp then corner of the WhatsApp icon show the no. Of msg

**Comment by zamber** [comment]
For what purpose? The launcher already shows you new messages in chat apps. Adding numbers to the icon could clutter the interface.

Plus it adds a whole slew of issues with styling. How would you ensure that the corner number maches your icon pack? More requests for overlays matching every icon pack imaginable?

**Comment by 8bitPit** [comment]
Maybe I could add a number next to the App name

**Comment by 8bitPit** [comment]
I tried it out, but unfortunately it looks weird show the count next to the name, because most of the time the notification's description reads: "x messages from y chats" or something similar, so the counter would be redundant. I'll close the issue for now, but please let me know if you have further ideas or disagree with my opinion.
