### ISSUE TITLE
Left side gesture for triggering Niagara Search.

### ISSUE THREAD

**Issue by sangampanda** [8bitPit/Niagara-Issues#2173]
### Is your feature request related to a problem?

Both the left and right sides of the screen trigger the app list, which all might not need. So even though it is made this way to maintain consistency, it's useless for those who just want to access from one side.

### Describe the solution you'd like

I want to trigger Niagara search on the gestures on the left side of the screen, or you can provide more options if you like to expand the idea. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Hey there, thanks for reaching out 👋 

If I understood you correctly, you would like to tap on the alphabet on the home screen to open the all-apps list, and when you tap on the other side of the phone, it should open the search instead. If I misunderstood, feel free to let me know :)

The main issue I see with this suggestion is that this would make using Niagara less intuitive, since tapping the different sides leads to different outcomes. This would especially be an issue with one-handed use in mind. You wouldn't be able to switch with which hand you'd use Niagara spontaneously, and we would need to add a toggle for left-handed people.

Both of those effects are why we sadly don't feel like this is a good addition.

I would recommend you to turn on 'swipe up to search' (Niagara Settings > scroll down to Advanced > 'Swipe up to search'), this way you can access the search easily from the home screen with a quick swipe. I hope this helps :)

**Comment by Amorphous404** [comment]
I feel the request is kinda similar to #2089
