### ISSUE TITLE
Allow changing app sort name without affecting display name

### ISSUE THREAD

**Issue by Piroro-hs** [8bitPit/Niagara-Issues#2175]
### Is your feature request related to a problem?

Camera app on my phone (for example) is localized as "カメラ" (=kamera) and shown under index K. I want it to be listed under C without altering its name.

### Describe the solution you'd like

Add option to edit app's name which is only used for sorting.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hello @Piroro-hs, Thank you for your suggestion; Sorry, after careful consideration, we decided not to implement the proposed feature because we don't find it impactful enough.
• [Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)


We recommend renaming these apps so they get listed in your preferred letter.
• Long press on the app -> Tap on the app name in the context menu.
