### ISSUE TITLE
Extended Privacy for Premium Users

### ISSUE THREAD

**Issue by p34c3-n-l0v3** [8bitPit/Niagara-Issues#2179]
### Is your feature request related to a problem?

First of all - thanks for the great launcher! Makes the Google Pixel experience a lot better! And I would like to say that it is good to see that you seem to at least care about data privacy. Since you have a readable and nicely summarized overview instead of throwing 1000 pages at us that no one reads and understands. I was also willing to pay the (to be honest really high price) of 30 bucks for the launcher. But I get and completely like the idea to support useful and well written software that improves your daily live. After all you need to get something out of it and the users want new features and a stable and secure experience (especially in case of a launcher). Still there is of course some data collected which brings me to my request below.

### Describe the solution you'd like

I thought about this: could there be the option for pro users that the app is not collecting any data? Or at least give the paying users the option to opt out of it completely? I think it would be something that you could attract many more users with who would be using the launcher and especially and more importantly use the pro version. I think even money wise it could be of benefit. And you could advertise the launcher with that unique selling point. What are your thoughts on this?

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
I'm glad to know that you're having a good experience with the launcher :), Regarding user data collection we collect it only to improve and optimize the launcher experience and we are transparent about the all the data we collect, rest assured we don't misuse or sell the data we collect.

We already do provide the opt-out option for both pro & non-users to restrict the data you share with us "Niagara Settings -> Advanced -> Analytics -> Share error and usage report", so that only the necessary data is shared with us so the launcher works as expected i.e Verifying if a user has pro subscription etc.

You can also go through this simplified/summary version of our privacy policy: 

[Privacy Policy Summary](https://help.niagaralauncher.app/article/109-privacy-policy-summary)

If you have any concerns or want to delete any data we have on you from our servers at any given point of time, please feel free to write us a mail at support@niagaralauncher.com. and we'll be happy to help.

**Comment by Amorphous404** [comment]
I think your request is similar to https://github.com/8bitPit/Niagara-Issues/issues/1648

Merged with #1648
