### ISSUE TITLE
关于MIUI手势

### ISSUE THREAD

**Issue by djdjfjfkeocj** [8bitPit/Niagara-Issues#2184]
### Is your feature request related to a problem?

众所周知，MIUI手势只支持MIUI系统桌面。
但是，我希望niagara launcher可以像lawnchair一样调用安卓13的原生手势，从而在小米手机上用上全面屏手势。谢谢！

The following is a machine translation, which may not be allowed, please forgive me.

As we all know, MIUI gestures only support the desktop of MIUI system.
However, I hope that niagara launcher can call the native gesture of Android 13 like lawnchair, so as to use the full-screen gesture on Xiaomi mobile phone. thank you

### Describe the solution you'd like

众所周知，MIUI手势只支持MIUI系统桌面。
但是，我希望niagara launcher可以像lawnchair一样调用安卓13的原生手势，从而在小米手机上用上全面屏手势。谢谢！

The following is a machine translation, which may not be allowed, please forgive me.

As we all know, MIUI gestures only support the desktop of MIUI system.
However, I hope that niagara launcher can call the native gesture of Android 13 like lawnchair, so as to use the full-screen gesture on Xiaomi mobile phone. thank you

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
> As we all know, MIUI gestures only support the desktop of MIUI system.

Yes, on some Xiaomi Devices/MIUI version they fully integrated gesture navigation into their System Launcher, thus preventing users of third-party launchers (Niagara Launcher, Nova Launcher etc.) from enabling gesture navigation. This seems to be a conscious decision by Xiaomi and not something we can work around or fix. If you wish to use third-party launchers in combination with gesture navigation in the future, please [contact Xiaomi](https://www.mi.com/global/support/contact/), requesting for gesture navigation to be brought back. However, you can [download these apps](https://play.google.com/store/search?q=Gesture%20navigation) to get a similar feel as gesture navigation on any Android version.


> However, I hope that niagara launcher can call the native gesture of Android 13 like lawnchair, so as to use the full-screen gesture on Xiaomi mobile phone. thank you

Regarding the root method that Lawnchair offers to switch to their recents via Quickswitch app, Unfortunately, we decided against supporting it, since Niagara Launcher isn't based on Launcher3 (the reference Launcher implementation in Android). Thus it would be very time-consuming to implement and would only work for a tiny part of the user base. That's why we decided against supporting it.

For more information, refer to this Niagara Help article:
[Gesture Navigation Issues](https://help.niagaralauncher.app/article/7-gesture-navigation)

**Comment by khewweifeng** [comment]
> ### Is your feature request related to a problem?
> 众所周知，MIUI手势只支持MIUI系统桌面。 但是，我希望niagara launcher可以像lawnchair一样调用安卓13的原生手势，从而在小米手机上用上全面屏手势。谢谢！
> 
> The following is a machine translation, which may not be allowed, please forgive me.
> 
> As we all know, MIUI gestures only support the desktop of MIUI system. However, I hope that niagara launcher can call the native gesture of Android 13 like lawnchair, so as to use the full-screen gesture on Xiaomi mobile phone. thank you
> 
> ### Describe the solution you'd like
> 众所周知，MIUI手势只支持MIUI系统桌面。 但是，我希望niagara launcher可以像lawnchair一样调用安卓13的原生手势，从而在小米手机上用上全面屏手势。谢谢！
> 
> The following is a machine translation, which may not be allowed, please forgive me.
> 
> As we all know, MIUI gestures only support the desktop of MIUI system. However, I hope that niagara launcher can call the native gesture of Android 13 like lawnchair, so as to use the full-screen gesture on Xiaomi mobile phone. thank you
> 
> ### Feature Request Procedure
> * [x]  I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

从 MIUI 13 开始。。。我就决定放弃 MIUI 了 。。。 系统优化没弄好 还禁这个那个的
