### ISSUE TITLE
Move All-Day Events to bottom of the day within Agenda

### ISSUE THREAD

**Issue by chriscam85** [8bitPit/Niagara-Issues#2207]
### Is your feature request related to a problem?

Similar to prioritizing non All-Day Events for the calendar widget, please also deprioritize the all-day events in the Agenda view.

### Describe the solution you'd like

All-Day events should be listed under non all-day events in Agenda view.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @chriscam85, Thank you for your suggestion. However, we've decided not to modify the current behavior of our agenda panel. In order to provide a coherent experience for our users, we follow the standard approach used by other calendar applications and widgets.

![All Day events.jpg](https://user-images.githubusercontent.com/96917972/233120741-b50278f2-ef2e-40c1-8c62-4f48d746a552.jpg)
