### ISSUE TITLE
Slide folders to the right

### ISSUE THREAD

**Issue by danielgava** [8bitPit/Niagara-Issues#2212]
### Describe the solution you'd like

Please add an option to open a widget or a certain app when sliding folders to the right. For example, one could choose a most used application from that folder to put in the "quick open" option via right swipe.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @danielgava, I appreciate your input. It appears that your request bears a resemblance to an issue that has already been raised - #2198. In order to avoid redundancy and promote a thorough discussion of the feature, coul you please forward the discussion suggestion in that particular thread? 

Thank you.


🔗 Merged with #2198
