### ISSUE TITLE
The 'Recent Apps' view gesture (swipe up from bottom) breaks when on homescreen

### ISSUE THREAD

**Issue by jimvekemans** [8bitPit/Niagara-Issues#2215]
### Describe the bug

Using Samsung Galaxy S23 Ultra, I can only switch between apps when I am already in an app.
When I get to the homescreen, the functionality to see my recent apps and to swtich apps breaks; meaning swiping up from the bottom when in the launcher doesn't show my list of apps that are open.

This breaks a core android functionality and multiple times a day this bugs me, didn't happen on my previous 2 phones so I presume it's because of android 13, can't be sure though since the other phones won't receive android 13.

Software info:
One UI Version: 5.1
Android Version: 13
Kernel version: 5.15.41

### Steps to reproduce

- Have gestures enabled instead of dedicated navigation buttons
- Go to homescreen
- Launch settings app
- Go to homescreen
- Try swipe up to show list of apps

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Samsung Galaxy S23 Ultra

### Android version

Android 13

**Comment by Amorphous404** [comment]
Hi @jimvekemans . If you're referring to one-second delay, it is from Samsung, not us; they added it to all third-party launchers. We assume they added the delay because some launchers react to the "home button press" action (e.g., to open app search), which is easier for the user to trigger that way.

To know more about this issue, please refer to this article:
[Recent Apps Screen & Gesture Navigation Issues](https://help.niagaralauncher.app/article/114-recent-apps-screen-issues)

Could you please share the name of the third-party launcher where you tested it?

**Comment by jimvekemans** [comment]
Hi @Amorphous404, I was not aware of this limitation. I will close this issue since it is not related to Niagara Launcher.
