### ISSUE TITLE
Auto close a pop-up folder 

### ISSUE THREAD

**Issue by n0d3** [8bitPit/Niagara-Issues#2218]
### Describe the solution you'd like

When an app that is contained in a pop-up folder is launched close the pop-up automatically. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @n0d3, If you launch an app and close it within 3 seconds, Niagara Launcher will return you to the last position i.e pop-up folder instead of the main home screen. This behavior is intentional and saves you time when you accidentally tap on the wrong app.

[Pressing home doesn't show favorites](https://help.niagaralauncher.app/article/86-pressing-home-doesnt-show-favorites)
