### ISSUE TITLE
Allow browser "apps" to be moved off the favourites list

### ISSUE THREAD

**Issue by nagisa** [8bitPit/Niagara-Issues#2220]
### Is your feature request related to a problem?

When I was using grid-based launchers in the past, I used to have my browser create shortcuts to websites I frequent for faster access. This appears to be a part of [Progressive Web Apps](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen) functionality (see link for the flow). These websites then open up in a webview like environment, rather than a full browser. For websites oriented at publishing longer-form content this is a huge step towards a more distraction-free experience.

Both the grid-based launchers and Niagara share a limitation that these shortcuts can only show up on the homescreen and favourites list respectively (if you try to remove or move one such, they can only be deleted entirely.) However, on grid launchers you can create dozens of them and they still fit fine in a single page. Niagara makes the recommendation to have the favourites list relatively short, so it can add frequently used or otherwise notable apps at the end of the list. Thus having many or even any PWA shortcuts is not as feasible.

### Describe the solution you'd like

It would be great if Niagara allowed these shortcuts go into the list of regular applications, rather than being forced to stay on the favourites list. Besides the other benefits inherent to PWAs this, combined with efficient navigation model of Niagara, still allows accessing these applications much faster than going through a browser proper. This would probably make the experience more consistent too as the PWAs wouldn't behave in their own special way compared to regular apps with regards to their uninstall experience.

This is in part a duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1719, which was closed with a suggestion to reopen it if somebody felt strongly about the feature still. I don’t care particularly much if these shortcuts are favourited by default, as long as unmarking them as a favourite doesn't mean they are getting deleted entirely.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @nagisa, I have reopened the existing issue #1719. Could you please forward your suggestion on the same thread so that we can have a comprehensive discussion in one place? This will make it easier for us and other users to follow the conversation. Thank you for your cooperation.


With regard to

>Both the grid-based launchers and Niagara share a limitation that these shortcuts can only show up on the homescreen and favourites list respectively (if you try to remove or move one such, they can only be deleted entirely.) However, on grid launchers you can create dozens of them and they still fit fine in a single page. Niagara makes the recommendation to have the favourites list relatively short, so it can add frequently used or otherwise notable apps at the end of the list. Thus having many or even any PWA shortcuts is not as feasible.

While Niagara launcher, by default adds PWAs/Shortcuts to the favorites page, users can easily move them to the app list. Unlike other launchers, once a shortcut is added and listed in the app list, it functions like an installed app. These shortcuts are indexed in Niagara's search, and can be grouped in pop-ups, etc.

To add a shortcut to the app list:

-> Add the PWA/Shorcut to the favorite page 
-> Long press on the shortcut 
-> Show in app list
**i) Sure **
- Removes the shortcut from the favorite page and moves it to the app list
**ii) Cancel **
- Doesn't remove the shortcut from the favorite page and create a copy of the same in the app list
