### ISSUE TITLE
Niagara button on the left

### ISSUE THREAD

**Issue by cchowgule** [8bitPit/Niagara-Issues#2222]
### Describe the solution you'd like

I read the article on why no left hand mode but it would be great to be able to have the option to put the Niagara button on the left. It would make it possible for me to use the launcher one handed.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @cchowgule, Thank you for your suggestion. This option has already been requested, and we decided against adding it since we don't find it impactful enough.

Impactful:  It is either appealing for many or necessary for some.
[Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)

Here's a response from the dev team #1857:

> allowing users to change the button location to be left instead of right would require an additional toggle, that we feel is not necessary since most devices are small enough to be able to reach the button on the opposite side and most other apps also only provide the floating action button to the right. Therefore we won't add a left-handed mode for the Niagara Button.

https://github.com/8bitPit/Niagara-Issues/issues/1857#issuecomment-1146165495

**Comment by fengtastik** [comment]
As a fellow lefty, I'd like to second this request. I'll note that about 10-12% of the people in the world are left handed. I'll also note that the explanation offered in this thread is a bit insulting... 

A Niagra design principle is that "Impactful: It is either appealing for many or necessary for some." And for lefties to use the Niagra button it's necessary to be able to move it to where we can reach it one handed. But our necessity is either(1) not important, or (2) we are not considered the 'some.' 

Put another way, it's more important for right handed people to have one less setting in a settings menu than it is for left handed people to be able to use what I presume is a flagship feature of the product.

**Comment by Amorphous404** [comment]
Hi @fengtastik, Thanks for your feedback. I apologize if my response came across as disrespectful. My intention was not to offend anyone.

The reason why we did not consider it "[impactful](https://help.niagaralauncher.app/article/8-niagaras-design-principles)" is because we have not received a considerable amount of requests for this option or feedback indicating that left-handed users are having difficulty in its current form. Most likely, the button is easy to interact with on most phones.

Also, implementing this change poses technical limitations, such as disrupting the app's symmetry and interfering with the app list scroller and favorites apps, which is critical to our users (Allowing users to access their apps with either hand easily, which is the core feature of our launcher). Furthermore, the floating button on the right is the standard position in Android and is consistent across different apps.

Moreover, I would like to highlight that both our main and co-developer are left-handed, and we understand the importance of accommodating diverse user needs. However, due to the reasons mentioned above, we have decided not to make the change at this time. If we receive more requests and feedback indicating the need for left-aligned button placement, we will reassess our decision and explore potential solutions to relocate the button without impacting the application's performance.
