### ISSUE TITLE
App Gestures

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#2223]
### Is your feature request related to a problem?

To make Niagara launcher more minimal and productive. 

### Describe the solution you'd like

I've been subscribed to Niagara quite some time now (years) . I recently tried Nova launcher to test something and found something I didn't know I needed so much, and I think I must be implemented in order to keep Niagara launcher as a competitive launcher.

 I'm talking about gestures (being specific, Im talking about "icon's UP and DOWN gestures), to be honest, I don't know how much this has been requested, and If not, I'm gonna do it. 

I believe this specific gestures would fit perfectly the Niagara's principles. This could be achieve by dividing the app's horizontal bar into two parts left half trigger the app gestures and the other half (right) the app pop-up and messaging.  

![Nova](https://user-images.githubusercontent.com/72170242/226238452-abbcf90e-c9cc-46d4-b9ec-b90a9455ecea.jpg)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
https://user-images.githubusercontent.com/96917972/227946734-398b7d18-493f-4579-9951-fe9ce5bb8293.mp4

Hi @Just-SKY, We appreciate your suggestion, but as discussed in our Telegram group, it is not feasible to implement the proposed gesture function in Niagara Launcher because the whole horizontal area is utilized for launching the app in Niagara. In contrast, Nova Launcher only uses the app area. Additionally, the swipe up and down gestures are already assigned for the notification drawer and the Niagara search, respectively.

Dividing the horizontal area is not a viable solution, as it could result in unintended issues. It is important to note that the primary goal of Niagara Launcher is to allow users to launch their apps with ease using just one hand. Therefore, we need to ensure that any changes made to the launcher are aligned with this core objective.

We suggest using the App popup feature to add shortcuts for cases like this. These shortcuts can be easily accessed by right-swiping on the app. You can find more information on this feature in our [Folders & Pop-ups](https://help.niagaralauncher.app/article/115-pop-ups) knowledge base article.
