### ISSUE TITLE
Keyboard doesn't consistently show up when swiping up on homescreen whilst picture-in-picture content is being rendered

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#2231]
### Describe the bug

Watch YouTube for example, press home screen & the watch window shapes down and becomes picture-in-picture content. As you're swiping down on the home screen to search, the keyboard doesn't consistently show up.

### Steps to reproduce

Go to YouTube, watch a video, press the home screen button, swipe up to start a search, watch how the keyboard somehow just decides to say "nah", and never pop up — still leaving the search bar indicator highlighted like it's ready to search.

Try it a few times, perhaps whilst going back & forth somewhat fast between the actions. I'd be surprised if this is an isolated incident.

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Pixel 2

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_20230325-225745](https://user-images.githubusercontent.com/43126233/227755768-5fdb817a-30cf-487e-bdbf-45ca831fe01a.png)

Screen recording:

https://user-images.githubusercontent.com/43126233/227782984-2ed29ca8-3ae1-4180-8ff4-5c0e47539e67.mp4

**Comment by Amorphous404** [comment]
Hi @Montell2099, Thank you for reporting. It seems like a system issue since it is not limited to Niagara Launcher. Do you experience the same issue with other apps that utilize picture-in-picture mode? Also, it is unclear which keyboard you are using. Perhaps you could try using a different keyboard to see if that resolves the issue?

PS: I couldn't reproduce this bug on my end with
- VLC Picture-in-Picture
- Google Gboard, Microsoft Swift Key
- Niagara v1.8.15

**Comment by Montell2099** [comment]
Hello @Amorphous404!

"_Problem occurs with other launchers_" only got displayed by mistake, since I'm not yet familiar with this new report form.

I am using Microsoft SwiftKey. I'm a bit busy at the moment, but I'll try to see if I can reproduce this soon with different keyboards and/or media players being active.

Cheers for the quick response!

Kind regards
