### ISSUE TITLE
Calendar colors do not update

### ISSUE THREAD

**Issue by AplusKminus** [8bitPit/Niagara-Issues#2234]
### Describe the bug

I have a Synology NAS at home which serves my private and shared calendars. As with many calendar systems it is possible to associate a color with a calendar. This color is correctly synced with my Android device as it shows up in both my calendar app as well as Niagara's calendar widget.

I have recently changed the colors of my calendars at the source (in the NAS). The updated colors are picked up correctly by my calendar app. The Niagara calendar widget however still displays the original colors.

I fear that the only way to update the colors is to recreate the calendar accounts in the OS, which I do not want to do due to the many side-effects this will have.

Please either add an option to refresh the colors from the source or fix whatever bug is responsible for not updating the colors.

### Steps to reproduce

1. Have a calendar, whose color you can control at its source, displayed in Niagara's calendar widget.
2. Change the color of the calendar.
3. (Optional) verify the color change in any calendar app.
4. View any upcoming event of that calendar in the Niagara calendar widget.
5. Check the color. Expected: the color is the updated color. Observed: the color did not change.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 7

### Android version

Android 13

**Comment by Amorphous404** [comment]
Hi @AplusKminus, Thank you for bringing this to our attention. Actually the Andorid Calender API is responsible for providing/syncing the correct event information to the calendar widgets app like Niagara Agenda Panel that utilizes this API. Could you please check which color does [YourCalender Widget](https://play.google.com/store/apps/details?id=de.mash.android.calendar) app shows for those respective events?

**Note:** Calender apps won't face such issues as they are logged in with the email id and have direct access to the calendar events unlike the apps/widgets that use the Calender API.

**Comment by Amorphous404** [comment]
In addition, it might be worth trying these troubleshooting steps;

Calendar apps don't necessarily make changes to your calendar available to other apps immediately. Here are some steps that might help:

- If you're using Google Calendar, open Google Calendar and tap on the three dots on the top right and then on Refresh. Other calendar apps should provide a similar way to open and refresh your calendar. 

- Restart your device, open your calendar app afterward, and repeat the first step.

- If the events were added recently, wait a few hours
- Clear the data of your calendar app (if the previous steps didn't help)

- Ensure you have more than 10% storage available on your Google Drive account; otherwise, Google calendar events might not sync.

Source: [Niagara Calendar's Widget](https://help.niagaralauncher.app/article/76-calendar-faq)

**Comment by AplusKminus** [comment]
Hi @Amorphous404, thank you for your quick reply!
Just to emphasize this once:

- My issue is about _calendar_ colors, not _event_ colors. Niagara handles _event_ colors correctly.

However, I have now solved the issue by re-creating the calendar sync account. I figured out that the calendar colors did not sync correctly. I unfortunately tricked myself into believing the sync of the colors works correctly, which it does not.

Niagara is not at fault, therefore I am closing this issue.
