### ISSUE TITLE
Hide status bar clock with root access

### ISSUE THREAD

**Issue by VincentJoshuaET** [8bitPit/Niagara-Issues#225]
Is this possible?

_Sent from my Redmi Note 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by VincentJoshuaET** [comment]
[Also, can we reduce the space/gap here?](https://i.imgur.com/6WWVV3p.jpg)

**Comment by Scorpionk1** [comment]
In the phone configuration as administrator you have the option to hide the status bar icons without root access.

**Comment by zamber** [comment]
It may be that Redmi does not expose that option. In that case consider flashing a ROM that has that feature. Either ways it's not a launchers resposiblity to manage system options by leveraging (otherwise pointless) root permissions.

Regarding the gap, what gap? The screenshot does not tell us which gap you don't like. Create a new issue for the gap with a better explanation.

❌ - Candidate for closing.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
