### ISSUE TITLE
Pinned media widget & multiple players

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2258]
### Is your feature request related to a problem?

While the current media widget is fine it is limited to showing just one music player unlike android media player notification which allows you to scroll between other live players e. G. YouTube and Spotify in the example below

![Screenshot_20230423_040318_GitHub](https://user-images.githubusercontent.com/81394097/233817571-63764eab-34e0-471d-bbaf-22289f85a652.jpg)
![Screenshot_20230423_040324_GitHub](https://user-images.githubusercontent.com/81394097/233817576-695ce716-5b3f-4d2b-aaf4-7c3d136efe72.jpg)

### Describe the solution you'd like

It woudl be great if the media widget mirrored how androids default notfication media player works allowing you to scroll between live players

Also and this I think would need to be optional but being able to pin the media player so it is always available (assuming there is media app running in the background) and can't be accidentally swiped away would be fantastic.

These changes would allow for immediate access to music, podcasts etc all the time

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Lorestan00, Thank you for your suggestion. But I am unsure whether third-party applications have the capability to stack media sessions. Additionally, even if they do, I do not believe it aligns with [Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles) and could potentially complicate the media widget.

With regards to pinning the media widget, please refer to this article:
• [Integrated Media Widget
](https://help.niagaralauncher.app/article/11-media-widget#:~:text=Why%20doesn%27t%20the,last%20media%20session)

> Why doesn't the Media widget stay on the screen all the time?

The idea is that Niagara's adaptive home screen only shows you the information you need right now. In our opinion, the media widget takes up too much space to be always visible. Moreover, Android 11 already keeps the media player in the quick settings/notification shade (you might have to expand it), so you can also resume it that way. On top of that, we cannot use Android's API for "standby" media sessions because it's a system API (to be more precise, most media players only allow the system to access their last media session).



I will keep this issue open for a member of the dev team to review and address as needed.

**Comment by 8bitPit** [comment]
Hi @Lorestan00, yeah, unfortunately, we don't have access to all the inactive media players, unlike the system/notification shade. I fear that we cannot properly mirror the behavior of Android's notification shade.
