### ISSUE TITLE
Inbuilt weather widget doesn't work

### ISSUE THREAD

**Issue by D3ZOXY** [8bitPit/Niagara-Issues#2262]
### Describe the bug

Inbuilt weather widget can't show the weather.

Error message: NoWeatherDataException(st missing).
Error occurred with Niagara Launcher v1.9.2 on a OnePlus device which runs Android 13 on 2023-04-26T06:37:12Z. My crash user id is '9057317a-fe17-4bf7-b8e2-28af17f51ed0'.

I'm rooted.

### Steps to reproduce

1. Enable weather widget.
2. Set a location.
3. Tap on home screen date widget.
4. Tap on "Can't show weather".

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

OnePlus 9 Pro (T-Mobile)

### Android version

Android 13

### Screenshots / Screen recordings

Logs
[26-04_09-45-42.txt](https://github.com/8bitPit/Niagara-Issues/files/11329848/26-04_09-45-42.txt)

**Comment by Amorphous404** [comment]
Hi @D3ZOXY, Thank you for taking the time to report the issue, and apologize for the delayed response. The error you are experiencing with the weather widget is most likely due to the Launcher not being able to verify your Pro subscription status. This can occur when there is an unstable internet connection or if the Niagara/Weather provider (OpenWeather) is unable to connect to its server.

Please ensure you have a stable internet connection and are not using any VPN/DNS/Ad-blocker services that may interfere with the connection to the server.

If the issue still persists, please contact us via email at "support@niagaralauncher.com," along with your [purchase order number](https://help.niagaralauncher.app/article/18-looking-up-order-number).
