### ISSUE TITLE
Support for Multiple weather providers

### ISSUE THREAD

**Issue by ImagineRetro** [8bitPit/Niagara-Issues#2264]
### Is your feature request related to a problem?

Oneweather has been very inaccurate, atleast at my location. So, in this regard there are better weather providers that do better and for that we should be allowed to change our weather provider app, and from the calendar weather section the app opened should change along with selected weather provided.

### Describe the solution you'd like

There could be an option to change our weather provider app, and from the calendar weather section the app opened should change along with selected weather provided.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @ImagineRetro, Thank you for reporting the issue and sharing your suggestion. I'm sorry, but we don't plan on adding support for multiple weather providers to keep the process simple for our users. Additionally, It's also not a good idea since we will have to maintain the support as well as have to pay all other weather providers. If you notice the weather data is accurate for your location. It's advised to report it to our weather provider (OpenWeather) so they can improve the service for your area.

Here's how:
-> Install and Open the [OpenWeather](https://play.google.com/store/apps/details?id=uk.co.openweather) app 
-> Tap on the settings icons in the top right corner -> Different weather 
-> Fill in the details and send your feedback.


Just a heads up, we are planning to switch to Apple Weather (DarkSky); hopefully, our new weather provider will be more accurate for your location.
See #1966
