### ISSUE TITLE
Two columns on the outer screen

### ISSUE THREAD

**Issue by kohbo** [8bitPit/Niagara-Issues#2268]
### Describe the bug

After the update two days ago, which changed the app list to have two columns, names are cut off.

### Steps to reproduce

1. Update to Version 1.9.5
2. Open the app list

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Samsung Launcher

### Device name

Samsung Fold 4

### Android version

Android 13

### Screenshots / Screen recordings

![Screenshot_20230506_085926_Niagara Launcher](https://user-images.githubusercontent.com/6541769/236632160-8bf172f6-3c1e-417e-93f0-953bab35070f.jpg)

**Comment by kohbo** [comment]
Issue was resolved by restarting the launcher. Keeping issue open because it still shouldn't have happened.

**Comment by Amorphous404** [comment]
Hi @kohbo, I'm glad to hear that restarting your device has resolved the issue. 

Truncated app names make sense; which is why we typically display apps in a single column on regular phones and outer screens. However, it is unusual that it did not automatically switch to a single column in your case. We will close this issue for now so we can direct our focus on other issues. If you encounter this problem again, please do not hesitate to notify us.

**Comment by Amorphous404** [comment]
• Fixed a bug with the two-column mode still being enabled after folding a foldable device.

Fixed in [Niagara Launcher v1.9.6](https://github.com/8bitPit/Niagara-Issues/releases/tag/1.9.6)
