### ISSUE TITLE
Recently installed / recently used apps section

### ISSUE THREAD

**Issue by sfosdal** [8bitPit/Niagara-Issues#227]

**Comment by stalloone** [comment]
Either bottom or top, as someone who often installs several apps at the time, i'm really waiting for that feature to be added!

**Comment by quincy97** [comment]
Instead of a new section. I would suggest to highlight with an icon somewhere at the new application. With that it suits the theme of this launcher as simplicity. I'll try to come out with a simple design when I'm free as for brainstorm idea

**Comment by 8bitPit** [comment]
@quincy97 that's also a good thought. Additionally Niagara could automatically scroll to the app in the app list. But I don't know how long to highlight the app. If you do it only as long it wasn't opened, the user could have a hard time finding it the second time. Whereas marking it for longer could be annoying. Another idea would be showing new installed apps in search.

**Comment by rd836** [comment]
Please do make sure this is an _option_, for those who don't want anything extra added to main screen automatically.

**Comment by 8bitPit** [comment]
@rd836 new apps will most likely show up in search, when you didn't type in a search term yet. I think that wouldn't bother you.

**Comment by ssssamstrup** [comment]
I like the idea of showing them in search before anything has been input.

A nice implemntation might be to show new apps, understood as apps that have been installed but haven't been opened yet. An app could then be removed x days after it has been opened the first time. A suggestion could be 7 days.


This would create a hidden place to see new apps (keeping the launcher elegant) and make it able to download some apps, test them and be able to uninstall unwanted apps without having to search through the launcher for them.

I think that be a nice hidden feature. The first time a new app installed agfter Niagara has been set as launcher a popup could notice you about the hidden area, so new users will know when they need it.

**Comment by rd836** [comment]
Just a reminder that if I install an app, I know it is there.
I don't need to program to remind me.

**Comment by 8bitPit** [comment]
@ssssamstrup 
>A nice implemntation might be to show new apps, understood as apps that have been installed but haven't been opened yet. An app could then be removed x days after it has been opened the first time. A suggestion could be 7 days.

Yeah, I think this would work well, too. But I believe most of the time, there is not much difference between the installation date and first opened date. However, simply checking the installation date would be less work for me, because Niagara already stores that in its database 😉.

> I think that would be a nice hidden feature. The first time a new app is installed after Niagara is activated as launcher, a popup could notice you about the hidden area, so new users will get notified when they need it.

Great idea!

**Comment by 8bitPit** [comment]
@rd836 Yes it is related, but I don't to always show a folder to the user when he recently installed an app, because that could bother him/her. In my opinion, showing recently installed apps in the search area is more elegant.

**Comment by ssssamstrup** [comment]
Yeah, if there isn’t a technical way to do it, then a x days delay after installation (or perhaps just showing the last x installed apps that fits the screen, without scroll) would be a better solution. It’s definetly a more »nice« than »need« to have feature.

The reason for my original idea was that I sometimes batch install a bunch of apps to test which ones actually works or which work best, for my intended use. In those cases, I’ll try 1 app for some time, before going to the next one, and then the »x days since app opened« would be really useful. 😊

All the best,

—Sune Amstrup

Strategisk grafisk designer og billedkunstner
Planlægger POST Design Festival 2019
Forbedrer arbejdsvilkår med Visuelt Forum

**Comment by 8bitPit** [comment]
Thanks for the explanation @ssssamstrup. I would say, I'll first try out the algorithm that is quickly to implement and depending on the feedback refine it or switch to the algorithm you suggested.

**Comment by ssssamstrup** [comment]
Cool! Really enjoying the launcher every day and it’s lovely to see these small improvements trickle in!

All the best,

—Sune Amstrup

Strategisk grafisk designer og billedkunstner
Planlægger POST Design Festival 2019
Forbedrer arbejdsvilkår med Visuelt Forum

**Comment by cauerego** [comment]
before launcher app already gives a very simple and elegant way of doing it, for reference and mockup.

it's also a fine alternative if you really miss the feature. i'm using it, anyway.

**Comment by 8bitPit** [comment]
@cauerego But doesn't Android handle recently used apps elegantly with the recents menu?

**Comment by ssssamstrup** [comment]
Yeah, I think it’s a bit redundant for recent apps as well. It’s useful for newly installed ones.

**Comment by cauerego** [comment]
which recents menu? on play store? what if my Android doesn't have a play store? 😁🤣

in fact, before launcher is bugging out on me. the list doesn't get updated. but there are other options out there (do let me know if you know of one without ads, specially interested to know of a spin off service, which lists apps without intrusive ads!).

i had 2 points:

there is need for such a thing, but there are alternatives. i don't need this function in Niagara.

before launcher ux for it is simple enough. if you ever implement this, sometimes it's fine to go vanilla.

**Comment by 8bitPit** [comment]
@cauerego 

> which recents menu? on play store? what if my Android doesn't have a play store? 😁🤣

No no, I meant Android's native recents screen that got a revamp on Android 9. The one that opens when pressing square (three button navigation) or swiping up slightly (gesture navigation).

**Comment by cauerego** [comment]
ooh. forgot about that!

i think it also serves a slightly different function. it's more akin to a list of current (rather than just recent) opened apps, which can be cleared. and it doesn't include shortcuts used.

but yeah, perhaps that's why i didn't really care so much for the "recently used" part of this issue, to begin with. 😁

**Comment by Rod911** [comment]
Recently installed apps now show up in the search screen.
Closing.

**Comment by dustinkerstein** [comment]
I was just curious, is it possible to disable this feature currently? Or change how long the apps are shown for? Thanks!
