### ISSUE TITLE
Apps are not sorted by ASCII code.

### ISSUE THREAD

**Issue by LyonsDo** [8bitPit/Niagara-Issues#2274]
### Describe the bug

It's probably better to describe this as a feature request rather than a bug.

Essentially I would like a quite simple custom sort option for items displayed in the app list.

Some people might like the primary sort key to be non-alphabetic but personally I have no need of that.

What I would like is an edible/customizable secondary sort key
within the primary.

Generally TeX has various solutions for this sort of issue - see e.g.
https://latex.net/sorting-glossaries-with-bib2gls/

In the home screen alphabetic list of apps they correctly display under their initial letter. Within that, they display lexicographically but it's not clear how the ordering is done, it's not ASCII.

I have for example a list
ColorNote
COmms
Contacts

The first and last are apps and the centre one deliberately starts with two capital letters.  I expected this to move to the top of the list (my first attempt was C_omms but that didn't work).

It's an import of tagged folders that I spent quite a bit of time creating in JINA before I came across Niagara.

As they are multi-app items I want them first in their respective lists.

There's probably a better way to do this in Niagara but they are a legacy item that I need to import. And in any case the sort order should be fixed.

### Steps to reproduce

Just create a few folders with different
capitalisations and see how they sort

E.g Note, NOte, NoTe etc

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Other 3rd-party launcher(s) tested

Nova 7

### Device name

Google Pixel 7 pro 

### Android version

Android 13

### Screenshots / Screen recordings

IMHO not necessary.

**Comment by Amorphous404** [comment]
Hi @LyonsDo, I don't have much technical knowledge, but I wanted to let you know that the apps in the app list by default are sorted based on usage, with the most frequently used apps appearing at the top of their respective letter. However, if you prefer the standard sorting method instead, you can go to:
-> Niagara settings
-> Advanced
-> Turn off "Sort all app list by usage"

Please let me know if my response didn't address your question o. I would be happy to pass it on to our development team so that they can assist you further.

**Comment by LyonsDo** [comment]
Yes I knew that thanks and have turned off sorting by usage

**Comment by marcinsmialek** [comment]
It's not that simple,
especially with non-Latin alphabets, which shouldn't be sorted by ASCII code. On top of that, some people, including me, might prefer case-insensitive sorting.

I wouldn't call it a bug, unless the sorting is incorrect for some culture. 
For example French accent sorting is a common bug in software.

One way to get around this issue might be custom reordering option, or an option to have folders before the regular items.

I'd recommend submitting a feature request, which clearly states what you want to achieve and why - how it might benefit you and more people without adding confusion to the rest of audience. Then follow it by some suggestions. I think I might like it too.

**Comment by LyonsDo** [comment]
Thanks for the reply. I agree that sorting in general is complex.

But any individual language has a default sort code and I'd argue that that
should be the Niagra default too.

What I've done is to rename my folders using a colon so Tools
becomes T: Tools and that floats it above Tasker etc.  There's only one
case where that didn't work for me - the app idiotically named M'Tam which
I just renamed to MTam.

My structuring is starts from Jina tagging of the apps.  That automagically
generates folders and I find it useful to have them in the app list.  Which
of course is no longer strictly speaking an app list, it's a list of sets
of apps followed by a subset of the apps that aren't favourites by are
worth individual mention.

It would be nice to have some options on how to sort that list.  As you
say, case (in)sensitive would be a good option.  There's also unicode but I
doubt if anyone would find that useful :-)

Best,

Donal.

**Comment by TFackler** [comment]
Hi there 👋

That's a rather interesting way to go about organizing your apps :O

As marcinsmialek has pointed out sorting apps by ASCII code can lead to a very unintuitive sorting order. In addition to that we want to support other alphabets too and simply removing diacritics to convert letters into ASCII could lead to even more confusion. Therefore we do not want to sort apps case sensitive or by their ASCII code.

I also think that your use case is rather specific and I don't think it warrants a toggle of sorts, since the impact would be too little.
Your workaround sounds like a smart solution to the problem though :)

Should there be a lot more people interested in using Niagara alongside JINA folders we might revisit this issue.

**Comment by LyonsDo** [comment]
Thanks for the mail.

Surely any language you want to support has a default sort order?
This of course won't be ASCII since even European languages have non-ascii
characters (the Spanish ñ as in mañana being a common issue).

Anyway, Niagra is a nice product and I understand your concern about adding
fring functionality.

Best,

Donal.

**Comment by TFackler** [comment]
See also: #455
