### ISSUE TITLE
Widget search 

### ISSUE THREAD

**Issue by Infinity984** [8bitPit/Niagara-Issues#2290]
### Is your feature request related to a problem?

No. Not to a problem 

### Describe the solution you'd like

Please add a way where we can search widgets when we are adding them, it would be very helpful!

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by GalenMarek1138** [comment]
Hello,

I don't see any images or comments other than the title for what this is about, but, I just wanted to add that the off-white rounded bar at the top of the widget list looks like a search bar but isn't. (See below screenshot.)

Not really a bug, not really a feature request, but we've been conditioned to think white bars like this are search bars.
Not that I actually want to search for a widget, because they're all different names, and a search bar for that wouldn't really be helpful. But, all the same, it still looks like it's supposed to be a search bar.

Thank you.

![Screenshot_20240609_140643_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/171977196/e08eb04b-9674-46e1-85ae-b7edffbfb2fb)
