### ISSUE TITLE
When icons are hidden on home screen they are the same length as the text.

### ISSUE THREAD

**Issue by IAMGeeCee** [8bitPit/Niagara-Issues#2292]
### Describe the bug

If you turn on hide text on home screen in the looks section, when you tap the icon the box that appears to highlight it is still the length of the text. I'm not sure whether this is meant to be like this. But it annoys me. Please fix.

### Steps to reproduce

1. Open settings 
2. Go to looks
3. Select hide text on home screen

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung Galaxy a3 2013

### Android version

Android 6.0 (Marshmallow)

**Comment by Amorphous404** [comment]
Hi @IAMGeeCee, Thank you for getting in touch! Yes, this is an intended behavior. The "Hide names of favorites" option only serves an aesthetic purpose, i.e., showcase the wallpaper and doesn't deactivate the app launch trigger area. This enables users to launch their favorite app with one hand conveniently. If this function were disabled, users would need to stretch their fingers to reach the app icon in order to launch the app, which could be less intuitive. Therefore, we have no plans to disable this function.
