### ISSUE TITLE
Material You Themed icon packs: Backward compatibility 

### ISSUE THREAD

**Issue by trustosas** [8bitPit/Niagara-Issues#2297]
### Is your feature request related to a problem?

With the android 12 update to the launcher, it is able to theme itself to match the wallpaper. The fetched accent color (it's even broadcasted to KWGT) can be used to theme icons in dynamic material you icon packs to support themed icons in versions lower than Android 12. Lawnchair and Hyperion implement this. The icons are integral to a Material You UI. Epik and Pix material you light / dark are material packs that work for Android 11 and below.

Here's how it looks on lawnchair 
https://i.ibb.co/tBQQT4K/Screenshot-20230530-175435.jpg

### Describe the solution you'd like

Themed icons on Material You themed icon packs for Android versions below 12. Because a lot of devices won't get the update. It should be the default behavior.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @trustosas, Thanks for your suggestion. We’ll update you once we decide to add that feature.

**Comment by 8bitPit** [comment]
I'm sorry @trustosas, but we do not plan to make third-party Material You icon packs backward compatible for two reasons: - Almost two-thirds of our user base has Android 12 or newer
- Our Anycon packs are already backward-compatible
Because of this, I believe the impact of the feature would be too low to justify the effort required to add it.
