### ISSUE TITLE
Bluetooth media widget (Plug & Play)

### ISSUE THREAD

**Issue by Vierron** [8bitPit/Niagara-Issues#2310]
### Describe the solution you'd like

It would be nice if you added the function of the appearance of the music widget on the desktop when the headset is connected (something similar to the appearance of the application icon when connecte(it would be nice to add a switch in the settings, because it may not be to everyone's taste, and it would be turned off by default)

2. The feature that I would like to see in the application is the style of the widget in the style of your launcher so that it is also simple, for example, a music widget.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Vierron, Thank you for your suggestion! However, it is technically not possible to display the integrated music widget exclusively when connected to a Bluetooth device. This is due to a limitation in Android, as it doesn't allow third-party apps to access standby media sessions. Even if the widget were to appear, it wouldn't display any content.

In case you are unaware, you can enable the media widget to be visible when you have active media sessions:
Long press Niagara Wigdet -> Show media widget

For more info, you can refer to this article:
[Integrated Media Widget](https://help.niagaralauncher.app/article/11-media-widget)

**Comment by Amorphous404** [comment]
However, here's a tip you can use, assign the native music widget to each music app pop-up, for example, Spotify widget to Spotify app, so you can quickly start your music sessions and control the media when you connect a Bluetooth device.

Demo:
https://github.com/8bitPit/Niagara-Issues/assets/96917972/0e8f4384-6135-4e1e-89cf-3472e5ba93de

**Comment by Amorphous404** [comment]
Bluetooth media widget (Plug & Play)
