### ISSUE TITLE
Add button to dismiss "Set as default launcher" message

### ISSUE THREAD

**Issue by KlingonDragon** [8bitPit/Niagara-Issues#2325]
### Is your feature request related to a problem?

#2323 
This should not require a secret command.

### Describe the solution you'd like

There should just be a button to hide it.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Thanks for your suggestion! Sorry, I don't think adding a "Dismiss" button to turn off the prompt completely will be a good idea; There is a possibility that some users might accidentally dismiss the prompt, and they may have difficulty setting Niagara as their default launcher, especially if they are unfamiliar with the process of changing launchers. Additionally, the user base that use Niagara in combination other launcher is relatively small.

If one chooses to use it this way for any reason, we provide this secret command to dismiss it.

However, to understand your perspective behind your request, could you kindly elaborate on the specific advantages of having a button instead of relying on the secret command? 

However, i would love to know your reason behind the request, could you please let me know?

Could you kindly expand on the specific benefits that arise from having a button in place, as opposed to a secret command?

However, I would love to know, what specific benefits do you see in having a button in

**Comment by Amorphous404** [comment]
Thanks for your suggestion! Sorry, I don't think adding a "Dismiss" button to turn off the prompt completely will be a good idea; There is a possibility that some users might accidentally dismiss the prompt, and they may have difficulty setting Niagara as their default launcher, especially if they are unfamiliar with the process of changing launchers. Additionally, the user base that use Niagara in combination other launcher is relatively small.

If one prefers to use it this way for any reason, we have this secret command in place that allow the users disable the prompt. 

However, I would love to know, what benefits do you see in having a button in place, as opposed to a secret command?

**Comment by KlingonDragon** [comment]
Despite searching the help pages, I couldn't find the secret command. Having a button would make it easy for people who can't find it (or don't look for it) to hide the message.
Sometimes it's not possible to change a default launcher and not finding a way to dismiss it could be very frustrating.

The button doesn't necessarily have to be built into the message. Adding it to the settings menu could also work.

**Comment by Amorphous404** [comment]
Thank you for your explanation! From my perspective, if someone isn't looking for this option, they shouldn't be bothered by not having the "Dismiss" button. It's also worth mentioning that we only consider adding an option if there is significant demand and it aligns with our design guidelines:
[Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)

I apologize, but currently, we do not have plans to include the button or an option to dismiss the prompt in Niagara settings. However, if we change our stance in the future, we will update the issue accordingly.

Thanks,

**Comment by Amorphous404** [comment]
- Merged with #949
