### ISSUE TITLE
Niagara Launcher 2.0.0?

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#2399]
### Is your feature request related to a problem?

Hi, when do you think Niagara Launcher version 2.0.0 will be released to see the changes?

### Describe the solution you'd like

Hi, when do you think Niagara Launcher version 2.0.0 will be released to see the changes?

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Niagara Launcher will not get a 2.0 version soon since we believe that to be a significant milestone.

We might bump the version number to 2.0 once we feel that Niagara Launcher is finished. We still have many ideas and improvements, and our active community also shares lots of feedback we want to implement. 
Therefore, we will continue to increase Niagara Launcher's version whenever there is a big update. This means Niagara goes from 1.9.x to 1.10.x, from 1.19.x to 1.20.x, and so on for the foreseeable future.
