### ISSUE TITLE
Searching no longer queries middle of app names

### ISSUE THREAD

**Issue by shardrunner** [8bitPit/Niagara-Issues#2451]
### Describe the bug

Since the newest version, I can no longer search for "FairEmail" by typing "mail" in the searchbar.
I suspect it currently only searches for the start of the app name, starting with capitalized letters or after white spaces.
For example, "email" or "fair" both work as search terms.

### Steps to reproduce

1. Pull up search bar
2. Search for a term not capitalized in the middle of an app name.
3. Expect the app to be found.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Google Pixel 4a

### Android version

Android 13

**Comment by TFackler** [comment]
Thanks for the report.

We have changed the behavior to what it was before. As long as your query is longer than 3 characters, we check whether the query is contained in the app's name for a match to be shown. 

For shorter queries, we feel that trying to match against word-breaks as we call them ,makes more sense since otherwise a lot of apps would match the query and thus be cluttering the results.
