### ISSUE TITLE
Move alphabet to the left

### ISSUE THREAD

**Issue by eruizc-dev** [8bitPit/Niagara-Issues#2474]
### Is your feature request related to a problem?

I've always been a one-hand user, and last week I decided to switch from mostly using my dominant right hand to the left as a way to give it less importance to the phone, while keeping my right hand free for other tasks, and hopefully breaking some bad habits.

I realized that it was getting harder for me to find and open applications; my conclusion was that I could no longer tap on the letter like I used to, and now I must find the letter, draw a horizontal line across the screen, tap it, and hope I was accurate enough which most times I wasn't and had to scroll up or down adding yet another step to the process. The other option was to stretch my finger all over the screen, but that's even worse.

### Describe the solution you'd like

A setting that allows me to move the alphabet to the left

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by eruizc-dev** [comment]
Main problem I see is the design balance; the alphabet fills what otherwise would be empty space on the right. By moving the alphabet to the left you may also want to at least shift the apps a bit, at worst move the icons to the right or even align the apps to the right. Essentially mirroring the current design.

**Comment by NiagaraSupport** [comment]
Hello and thank you for your report. You might find [this](https://help.niagaralauncher.app/article/39-left-hand-mode) helpful for your issue. In theory the app shouldn't be much harder to use left-handed than right-handed.

**Comment by eruizc-dev** [comment]
Thanks for sharing the article!

However I've seen a difference in how Niagara is used in that article compared to how I use it: I think of an app and tap on that letter instead of scrolling to it. I feel it saves so much time and avoids seeing other apps that may take my attention away. The problem I have is that since the alphabet is on the right I must mirror it in my head before I tap on the letter I want, which is prone to errors.

I've made an experiment in which I think of a letter and try to tap on it: first I tried with my right hand and got 18 correct out of 20 attempts, those 2 were off by one letter. Secondly I tried with my left hand and got only 14 correct, and the remaining 6 missed by one letter.

Thus the problem I'm facing is that using Niagara with my left hand drops my accuracy from 90% to 70%.

**Comment by Auroria-code** [comment]
I agree, as a left-handed person, that apparently does not the alphabet as well as I thought I would, I see myself looking over to the right side for guidance. I too use tapping when I for some reason have the phone in my right hand. But just guessing the placement on the right takes more time than just scrolling.

I thought about the mirroring thing too, as I thought about ideas how to move over the alphabet. It seemed fine to me, as it is done to get workflow. I'd rather have a "clumsy" look (which I don't think it is), then have Niagara not work for me as well as it does for everyone else only because I am left-handed. 

I would just do this change myself only for myself, but since your project isn't open source asking for it is my only option.
