### ISSUE TITLE
Anycons: wrong categorization

### ISSUE THREAD

**Issue by pasqualedante** [8bitPit/Niagara-Issues#2488]
### Describe the bug

Anycon assign wrong icon to some app:
Monefy isn't banking app but finance app;
Soldo isn't banking app but only credit card manager;
IO Public isn't a shop app but a Italy multi purpose service app. 

### Steps to reproduce

Apply Anycon and see

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Redmi Note 9

### Android version

Android 12

**Comment by Manu99it** [comment]
You can assign icons manually

**Comment by NiagaraSupport** [comment]
Hey there, 
I'll go ahead and close this ticket, as since then, enough time should have passed for the Anycons algorithm to improve (see [here](https://help.niagaralauncher.app/article/147-app-categorization#:~:text=Improving%20the%20categorization%20algorithm) for more info on how the decision-making works).
