### ISSUE TITLE
Multiple quick action buttons

### ISSUE THREAD

**Issue by Morgy93** [8bitPit/Niagara-Issues#2524]
### Is your feature request related to a problem?

This is an improvement idea from https://github.com/8bitPit/Niagara-Issues/issues/2491

### Describe the solution you'd like

I'd love to be able to have more of these quick action buttons:

![image](https://github.com/8bitPit/Niagara-Issues/assets/7961978/5be0cf9c-f7b4-467c-8ce3-f126793bccb6)

It could be some kind of widget at the bottom where you can configure the buttons position and quantity as you'd like.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, I noticed the use case of this request is somewhat similar to #2525. Which, correct me if I am wrong, is more quick access options in general. Since the answer in 2525 might also be applicable here and potentially solve this issue, I'll close this one. Feel free to address concerns about this topic over there.

**Comment by NiagaraSupport** [comment]
I closed it because i see the use case of both tickets to be the same, namely quick access to several apps through the Button, which might have been fixed with using pop up folders. Apologies if this missed your point and feel free to elaborate on it.
Currently adding multiple buttons clashes with the same principle as adding multiple swipe gestures. We try not to overload the launcher with functionality, even optional settings, unless they are impactful enough to warrant it.
