### ISSUE TITLE
更换壁纸问题

### ISSUE THREAD

**Issue by 214433567** [8bitPit/Niagara-Issues#2535]
### Describe the bug

我是iqoo手机，也就的vivo，在系统相册切换壁纸并退出后，打开后台界面还是原来的壁纸，必须要重启才能解决问题。在之前的版本就有这个问题了。

### Steps to reproduce

https://github.com/8bitPit/Niagara-Issues/assets/155669938/16f29a01-8112-47f6-8329-e381093542e1

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

IQOO Neo7 Racing

### Android version

Android 13

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/155669938/0233e191-a096-4144-85ab-1e961d728e54

**Comment by NiagaraSupport** [comment]
Hello there, thank you for your report.
Since I am not fluent in Mandarin, I'll use a translator; please excuse any potential errors in that translation.
I am sorry to say that this isn't something we can fix, as we don't have access to what is displayed in the background of the recent app screen. Vivo may be able to help here. I appreciate your understanding.

您好，感谢您的报告。
由于我的普通话不太流利，所以我会使用翻译；请原谅翻译中的任何潜在错误。
很抱歉，这不是我们可以解决的问题，因为我们无法访问最近的应用程序屏幕背景中显示的内容。 Vivo 或许可以在这方面提供帮助。感谢您的理解。
