### ISSUE TITLE
Translation to native language

### ISSUE THREAD

**Issue by MKoen** [8bitPit/Niagara-Issues#254]
A big part of the settings and the notification window are hard coded in English.

Please make this support the user's native language.

Since I'm from Belgium, I'd love to translate the app to Dutch. Just give me a list of the stuff that needs to be translated, and it'll be done in no time.

**Current translation volunteers:**

- Dutch (me - @MKoen )
- Urdu (@587saboor )
- Swedish (@Montell2099 )
- German (@UESPAsputnik )
- Czech (@LukasB79 )
- French (@mrouland )
- Polish (@frixu )
- Spanish (@rafaric )
- Italian (@xRayJiN )
- Portuguese (European) (@disacrol )
- Catalan (Spanish) (@sohaibeb )
- Spanish (@mare-413 )
- Simplified Chinese (@f0rb1d )
- Finnish (@koenek )
- Hindi (@madhurtewani )
- Turkish (@alicagatay )
- Russian (@Ajlewka13 )
- Hungarian (@pvojnisek )
- Tamil (@purushothamn )

**Comment by 587saboor** [comment]
@8BitPit also I can translate to Urdu (English letters tho)

**Comment by Montell2099** [comment]
I'd be willing to contribute with a Swedish translation if need be.

**Comment by 8bitPit** [comment]
@MKoen, @587saboor & @Montell2099  thank you. I did not setup any Translation management system for Niagara yet, but I will.

**Comment by UESPAsputnik** [comment]
I'd be willing to help with the German translation.

**Comment by MKoen** [comment]
@8bitPit Awesome, let us know when the translation is available, and we'll help you with pleasure.

**Comment by MKoen** [comment]
Whoops, accidentallyclosed this issue. Reopening it...

**Comment by 587saboor** [comment]
@MKoen lol

**Comment by LukasB79** [comment]
I'd be willing to help with the Czech translation.

**Comment by mrouland** [comment]
Hello, I'd be willing to help with the French translation.

**Comment by rafaric** [comment]
I can help with Spanish translation

**Comment by ModProg** [comment]
I could do a pull request looking into this, I'd just need to know how it should be implemented, as how would the dev like translations to work.

**Comment by xRayJiN** [comment]
I can help with Italian translation

**Comment by disacrol** [comment]
Count me in for European Portuguese (pt-pt) translation.

**Comment by sohaibeb** [comment]
I'd like to help translating into _Catalan_; _Spanish_ too if needed :)

**Comment by bachhuberdesign** [comment]
Love the app -- I can help translate into Chinese (simplified and traditional, zh-CN and zh-HK respectively).

**Comment by mare-413** [comment]
i can help with spanish translation if needed

**Comment by f0rb1d** [comment]
Hello, Simplified Chinese translator here!

**Comment by koenek** [comment]
I can work on the Finnish translation

**Comment by G-B-C** [comment]
Hi, I can help with Brazilian Portuguese translation!

**Comment by madhurtewani** [comment]
Hi, I can do Hindi (hi-IN) translation.

**Comment by alicagatay** [comment]
Hi I can help with Turkish translation.

**Comment by 8bitPit** [comment]
Thanks a lot for volunteering everyone.
I’m almost done with settings up the translation management system :)
The service is called Crowdin and you can also log in with your GitHub account:
I tried my best to provide helpful context (documentation & screenshots) for every string, please take a look: https://crowdin.com/project/niagara-launcher

**Comment by Ajlewka13** [comment]
Hi, I can help with Russian translation.

**Comment by MKoen** [comment]
@8bitPit please increase the char limit, it's now set to 200 but some strings to translate are already bigger then 200.

**Comment by 8bitPit** [comment]
@MKoen Sorry, I didn't know that Crowdin also takes the length of xml tags into account. Should be fixed now.

**Comment by disacrol** [comment]
@8bitPit Is the char limit strict? WIll the UX likely be 'broken' if any translated string is longer?
For example:
![original](https://user-images.githubusercontent.com/36055540/49696268-ae73da00-fb9f-11e8-90a9-5709923b7d4f.png)
"Add" translates to "Adicionar" in Portuguese. No shorter term (maybe "Juntar"). But if I strictly respect the char limit, I'll have to translate it to just "Adicionar", since "Adicionar favoritos" will not fit. This will do, since I believe the user has enough context on that dialog to understand "Add" means "Add favorites", but I will likely have to get a bit more creative in other cases.

**Comment by 8bitPit** [comment]
@disacrol good thought. For button labels I set the char limit to 20 chars, so "Adicionar favoritos" would barely fit (19 chars). I agree, just "Adicionar" would also work in that case. I will do some testing today, to better estimate char limits. Sometimes the UI wouldn't be broken, but I believe button labels longer than 20 chars wont look appealing to the user.

**Comment by disacrol** [comment]
I deleted my post hoping it would be unnoticed, I missed the "CHAR_LIMIT" annotation in the end, I was looking at the number of chars of the original, my bad.
I'll keep "Adicionar favoritos" for now.

**Comment by alicagatay** [comment]
Hello, I don't understand a thing. Currently, I am making a Turkish
translation and I don't know which order should I put the %1$s sign into
the translation. Like should I put it in order or should it be the same as
in the English version? For example, should I use the exact values for
exact buttons( such as using %1$s for the word Agree and continue, or
should I write it in order as I write the translation? I am asking this
because the order of the words can change due to languages differences
between Turkish and English.

**Comment by disacrol** [comment]
Nothing between <xliff:g and </xliff:g> should be translated. Other than that, I can and should adapt the text around it - before <xliff:g and after </xliff:g> - according to your language.
In my case, I also had to handle that specific string, because "Tap Agree and continue to agree to Niagara Launcher's Privacy policy and Terms of Service" in Portuguese had to be rephrased as something like "Tap Agree and continue to agree to the Privacy policy and Terms of Service of Niagara Launcher".

**Comment by Vv2233Bb** [comment]
Can I translate to Lithuanian?

**Comment by pvojnisek** [comment]
I would make the Hungarian translation

**Comment by pvojnisek** [comment]
@8bitPit would you please give some info about how to make the translation? I could not find string files not translation tool link. Tnx!

**Comment by 8bitPit** [comment]
thx @purushothamn

**Comment by 8bitPit** [comment]
I'll close this issue, but feel free to comment if you want to translate Niagara in a language which isn't available yer.
Thank you everyone for helping!

**Comment by Gauteweb** [comment]
I'd love to help translate to Norwegian.

**Comment by 8bitPit** [comment]
Thank you very much @Gauteweb :) Here's how you can participate: https://help.niagaralauncher.app/article/80-help-translate

**Comment by Gauteweb** [comment]
> Thank you very much @Gauteweb :) Here's how you can participate: https://help.niagaralauncher.app/article/80-help-translate

OK, so this is strange. Norwegian is marked as 100% finished, but Niagara is in english on my device (Oneplus Nord 2 5G). I have systems settings to Norwegian Bokmål (we have two written languages, "bokmål" and "nynorsk").

**Comment by 8bitPit** [comment]
@Gauteweb oh, thanks for reporting. Do the translations show up if you switch to Nynorsk?

**Comment by Gauteweb** [comment]
> @Gauteweb oh, thanks for reporting. Do the translations show up if you switch to Nynorsk?

That is not an option on my phone, only Bokmål.

**Comment by 8bitPit** [comment]
Oh okay. I can select to both written languages but I it doesn't apply the translations either. I think I have found the culprit, there are several ways to categorize Norwegian strings: https://stackoverflow.com/questions/5153674/android-localization-question/5155857. ![image](https://user-images.githubusercontent.com/9284845/140614821-1e9453fc-1203-4a24-b687-f36887fe8f92.png). I'll fix this with the next update; thanks again for pointing it out @Gauteweb!
