### ISSUE TITLE
bring back press home to search

### ISSUE THREAD

**Issue by kusti420** [8bitPit/Niagara-Issues#2547]
### Is your feature request related to a problem?

swipe up to search is buggy when using 3 button navigation. you have to press the home button sometimes like upwards of 3-4 times for it to function properly

### Describe the solution you'd like

add back the press home to search feature that used to be present back in the day. around version 0.21 but it was removed not long after that

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Hi there,

Swipe up to search and pressing / swiping to go home opening search are two different features and should work independently from one another. So, even when you have 3-button navigation enabled, you should still be able to swipe up anywhere on your screen to enter a search.

Pressing home to open search might feel like it functions weirdly, but that is most likely because when you enter the favorites screen by pressing home, we assume that additional taps on home are miss clicks / the user tapped too often but only wants to go home. If you wait a moment before tapping home again, it will open search as usual.

**Comment by kusti420** [comment]
swiping up isnt the solution for a feature youve removed. if i liked that gesture bs i would be using gesture navigation
