### ISSUE TITLE
Add rotation / Landscape mode toggle

### ISSUE THREAD

**Issue by saulens22** [8bitPit/Niagara-Issues#255]
Hello everyone.
I like this launcher a lot :) the only thing that would make it better is rotation support. When using apps horizontally, going home and launching another app, it would be more pleasant :)

**Comment by 8bitPit** [comment]
Thanks, currently home screen rotation is only available for tablets. The phone screen's is just too small for displaying the scrollbar.

**Comment by vip3rousmango** [comment]
Just an idea, what if while horizontal the scroll bar is also horizontal...? Would love to see this on phones as well.

**Comment by saulens22** [comment]
What about concatenating scrollbar letters? For example, A-D, E-H and so on.

**Comment by disacrol** [comment]
@vip3rousmango I like this idea. Is it that problematic to implement?

**Comment by elesesso** [comment]
Yes please. Rotate with horizontally justified scroll. This option immediately indicates custom launch as well. Only thing holding me from committing.

**Comment by 8bitPit** [comment]
@saulens22 & @vip3rousmango neat ideas, the latter one could feel unintuitive to use though, because you're scrolling horizontally with your fingers but vertically in the list.
Moreover, displaying the scrollbar isn’t the only problem, there is also not vertical space left for the app list, only 5-7 apps are visible at once, while wasting a lot of space on the left & right.

**Comment by disacrol** [comment]
Using Niagara on landscape is likely sporadic anyway, and whoever wants to enable rotation should get used to that compromise.

Regarding the wasted area: how about music widget / clock / weather on the left hand side and favorites / most used on the right? May look weird at first but I see no other option.

Not that I personally bother too much myself since I usually prefer using in my phone in portrait most times, but I foresee many users that would love the alternative.

**Comment by damianlavalle** [comment]
I say add landscape mode and forget trying to stick to the whole alphabet scroll thing. Once you're in landscape, trying to keep single handed operation is pointless and alot of wasted space as you said, so let's assume a single handed operator is ready multi-task and use both hands. Then the options open up at a whole new level. You can stick to the whole scroll by splitting the alphabet on each side and pin apps or you could simply switch to a traditional icon list or anything really. Landscape can be a whole new launcher and I don't know about everyone else but I'd be fine with it so long as there is landscape option because right now I can't switch to this launcher because I need landscape for when I'm in my car.

**Comment by saulens22** [comment]
> Moreover, displaying the scrollbar isn’t the only problem, there is also not vertical space left for the app list, only 5-7 apps are visible at once, while wasting a lot of space on the left & right.

My suggestion for this:
1. Alphabet scroll - clock - single column list - alphabet scroll (in favorites)
2. Alphabet scroll - two column scroll - alphabet scroll (in all apps)

Also, it's not a problem for me as I mainly use it with smallest icon sizes / text size, so it might fit more apps. Don't know about other user preferences though.

**Comment by 8bitPit** [comment]
I like your ideas @damianlavalle & @saulens22. An alternate UI (e.g. adding another row would currently interfere with swipe gestures the layout) would cost a lot of work thought.

**Comment by pvojnisek** [comment]
Landscape mode would help for lots of us. If it would be possible to enable/disable the function the user was able to decide knowing the limitations.
Personally it's an essential function for me in a launcher.

**Comment by MyChiMan** [comment]
Hey guys, I think every idea has great merit. Tbh as long as there is some form of landscape for phone available you would appease many users and gain new ones (which is the point right?)

We believe in you!

**Comment by will8428** [comment]
Yes please then.

**Comment by lennart-k** [comment]
Hi, I just wanted to say that in my opinion Niagara Launcher already looks perfectly fine with forced landscape.
I think the A-Z scrollbar is already pretty compatible with landscape mode
and even if not,
it's still better than forced vertical layout.
What about just making a settings category called `Experimental settings`?

**Comment by disacrol** [comment]
@8bitPit maybe a command? /rotate?

**Comment by 8bitPit** [comment]
Hmm, yeah maybe ;)
You can also use another app for that by the way: https://play.google.com/store/apps/details?id=org.crape.rotationcontrol

**Comment by rumatoest** [comment]
I still wonder how most launcher developers ignoring landscape mode? Probably it is somehow related to "vertical video witnesses" sect. 

Landscape mode were available on Nokia N8 and even before that model. I bet that screen height on 3.5" display in landscape mode is way more less that in modern smartphones. But still it was usable.
 
There are many use cases when it is more convenient to work in landscape mode including using phone in a car, watching videos and connecting your phone to TV.  And it is very annoying when you need to open launcher and you have to lean you head to shoulder just to make yourself more compatible with such UI orientation. Which  is by the way is extremely unacceptable if you are driving now.

It is much better to have landscape orientation even if it will be not so handy as portrait than do not have it at all. It is not a big issue to add an configuration option which is opted off by default.

P.S. It almost the same as blocking "non chrome" browsers from using web services only because developers test everything in chrome.

**Comment by 8bitPit** [comment]
My design philosophy is _all or nothing_. I don't say that Niagara Launcher doesn't get a landscape mode in the future, it may get one. But then I'd like to really think about it and try to polish it.

**Comment by y0c4** [comment]
It might be better to start from scratch and build a new launcher designed for tablets as they have different challenges and use cases to a phone. Secondly this would mean less time and focus on the phone launcher, which would be a shame imo.

Cheers
Christian.

**Comment by damianlavalle** [comment]
Here's an Idea. Designing an making a tablet launcher that is identical to
landscape mode on the phone launcher. I know it's alot of work but that
would be an "all or nothing" approach that would cover a good amount of
more devices and users. The UI would have to be clean and simple enough to
not over crowd a phone in landscape, and by extension a tablet would also
be clean and simple.

Maybe I'm over simplifying it. Since they can be vastly different in actual
size, but if you did decide to tackle tablets, the gamut in screen size is
so wide that you might as well include the phones in landscape mode.

Anyway, just my 2¢

**Comment by 8bitPit** [comment]
> Designing an making a tablet launcher that is identical to
landscape mode on the phone launcher. 

So you mean the landscape mode of other (grid-based) launchers, or am I misunderstanding you?

**Comment by will8428** [comment]
Hi..  Haven't been using Niagara as I guess I hadn't found a workaround or another launcher without excessive app drawer and homescreen duplicity..




Sent with Xperia Email


---- Peter Huber wrote ----


Designing an making a tablet launcher that is identical to
landscape mode on the phone launcher.

So you mean the landscape mode of other (grid-based) launchers, or am I misunderstanding you?

**Comment by tothak** [comment]
Hi Everyone,
Where are we currently with this request?
I also would love to have the rotation at least as an option (so I could turn it on in launcher settings). To be honest, I don't really care if there is a lot of wasted space, I can handle it ;)
Regards,
Akos

**Comment by 8bitPit** [comment]
Hey @tothak, I can't say if this feature will ever be implemented. We're planning on redesigning the landscape layout for tablets (https://github.com/8bitPit/Niagara-Issues/issues/841) but I don't know if it will also work on smaller devices. By the way, you can also enforce Niagara Launcher to landscape orientation with the help of a third-party app on Google Play: https://help.niagaralauncher.app/article/21-landscape-mode

**Comment by 8bitPit** [comment]
Toggle added in v1.4.1: https://medium.com/niagara-launcher/niagara-unfolded-928606673609

**Comment by apgodshall** [comment]
so... I have a tablet.  How do I get landcape mode to work?

**Comment by 8bitPit** [comment]
@apgodshall here's how: go to _Niagara's settings_ > _Features_ > and enable _Allow home screen rotation_
