### ISSUE TITLE
Allow selecting Niagara Button icon from all installed icon packs

### ISSUE THREAD

**Issue by KhaledKhaled0909** [8bitPit/Niagara-Issues#2614]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

So I suggest to be able to change naiagara bottom with external icon packs like normal apps and apps icons if I choose it to open any app.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your suggestion.
Full customization of the button isn't currently planned, but we did discuss ways to enhance which icon is selected and how it's displayed. We'll keep you posted on any updates.

**Comment by rudism** [comment]
I am interested in this too. I have assigned the tap action to a specific app (Fossify Phone), which was not given its own icon so I had customized it with a phone icon, but after assigning it as the tap action the Niagara button is showing an open book icon for some reason. I would have expected it to use the custom icon I assigned to the tap action app, or at the very least the original icon (which was just the generic empty circle in the outline icon pack). I'm not sure where the open book icon is even coming from.

**Comment by KhaledKhaled0909** [comment]
Exactly it would be much better to customize it with the same icons like main apps.

**Comment by TFackler** [comment]
Thanks for the suggestions; we will likely never offer any icon to be selected (as in from any third-party icon pack) since that would lead to some big inconsistencies, looks-wise.

We would rather like to see an option to choose the icon for the button from a list of Anycons is a good idea. Please see #2672 for that request.

We also plan on improving the categorization algorithm used to select the Niagara button icon based on the selected tap action.

I will close this ticket since #2672 seems to capture a better solution.
