### ISSUE TITLE
Ability to order clock, Niagara widgets, widget stack, media controls, favorites

### ISSUE THREAD

**Issue by EtzBetz** [8bitPit/Niagara-Issues#2622]
### Is your feature request related to a problem?

Most widgets do have a background color, which often clashes with wallpapers when the widget is placed in the middle of the screen.

I usually place my things somewhat on the middle, customizing it a bit to fit the wallpaper aesthetics. But I often already had the issue where it would still clash in some way, no matter how I'd position it. I also dislike having to placing it very low so that the list ends up scrolling.

Here's an example and how I'm not able to fix it also on the maximum top height.

![Screenshot_20240312-162513](https://github.com/8bitPit/Niagara-Issues/assets/12349529/dba65e7c-1ebf-43b7-ad25-94001f6bda43)
![Screenshot_20240312-162534](https://github.com/8bitPit/Niagara-Issues/assets/12349529/2f489d2e-e2ea-4219-b20c-c5d262227809)

### Describe the solution you'd like

I would like if one was able to order the clock, Niagara widgets, widget stack, media controls and favorites in a custom order.

If I could sort those, they wouldn't interfere with wallpapers as much.

In general I think this could be a handsome feature and could be integrated somewhat easily by just displaying it similarly to the favorite sorting thing, or in Niagara settings, also just in a sorting list for those 5 things.

If I was able to place the widget stack below favorites, it wouldn't clash with the wallpaper.

And also the default sorting could still be like this and users wouldn't have to care.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey, thanks for your suggestion. 
Right now, adding a custom order option isn't feasible due to some other priorities and the limited impact / reach it might have. But I've noted your suggestion down and if more folks bring it up later on, we can definitely take another look. In the meantime, if your main concern is the visual mismatch between the widget and wallpaper, consider using a widget stack with a widget that matches better or is smaller or even an empty widget.
