### ISSUE TITLE
Remove set default app nag

### ISSUE THREAD

**Issue by milesmcclane** [8bitPit/Niagara-Issues#2663]
### Describe the bug

You cannot remove the nag plastered over the home screen when Niagara is not set as default launcher. 

### Steps to reproduce

1. Dont set Niagara as default
2. See nag urging you to set it as default 
3. Search to remove nag without setting as default
4. Option doesn't exist. 

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Total launcher, launchair, kiss

### Device name

Pixel 8

### Android version

Android 14

**Comment by TFackler** [comment]
Could you please explain why you want to use Niagara Launcher without using it like an actual launcher?
Not setting Niagara Launcher as the default launcher will lead to the stock launcher opening when you press home.

**Comment by milesmcclane** [comment]
I use total launcher because I like to have a specific home screen, which is highly customised. I use and love Niagara as a separate ui to put my fun apps and my running apps (love the open when BT device  is connected). 

Basically I love both launchers but can only have one default.  I do change between the two as the default but that method messes things up a bit. 

I would prefer to use Niagara as an auxiliary launcher. The nag just frustrates the otherwise very pleasant experience. 

I am a paid user if it helps!

**Comment by TFackler** [comment]
Hi Miles,

I understand your use case now. While it isn't the intended way to use Niagara, it seems it fits your need and we are glad you like Niagara as an auxiliary launcher.

You can use the secret command `/suppresssetlauncherprompt` (type it into Niagara's app search and press enter) or click this link on your phone: [/suppress-set-launcher-prompt](https://niagaralauncher.app/app-link/secret-command?cmd=suppresssetlauncherprompt).

Let me know if you have further questions, otherwise I will mark the ticket as done.

**Comment by milesmcclane** [comment]
Thanks! Appreciated. Keep up the excellent work.
