### ISSUE TITLE
Sort apps alphabetically in folder

### ISSUE THREAD

**Issue by bjorne900** [8bitPit/Niagara-Issues#2664]
### Describe the solution you'd like

Option to automatically sort apps alphabetically in a folder.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestion.
We don't plan to implement this feature at the moment due to our [design philosophy](https://help.niagaralauncher.app/article/8-niagaras-design-principles#:~:text=has%20to%20be%E2%80%A6-,Simple,-%3A%20It%20is) and a perceived low impact/reach. This evaluation might change in the future if more requests come in, but for now, I'll close the ticket. I appreciate your understanding.

**Comment by TFackler** [comment]
Please see #2930
