### ISSUE TITLE
Add more blurred wallpapers

### ISSUE THREAD

**Issue by stuartglossop** [8bitPit/Niagara-Issues#269]
Please add more blur wallpapers and give members the opportunity to also add them

**Comment by 8bitPit** [comment]
I will add more, but giving everyone access could bloat the album & cause legal issues.

**Comment by stuartglossop** [comment]
Sounds very sensible. I am using muzei and it works well with Niagara

**Comment by Martin5001** [comment]
Would it be legal to take current wallpaper set by the user and add a blur filter on top of it in another layer? Then we could toggle blur on and off on any wallpaper.

**Comment by 8bitPit** [comment]
@Martin5001 I believe so. Because you can already achieve this with the help of third party apps (like [this](https://play.google.com/store/apps/details?id=dk.appdictive.blurwallpaper) one, for example), I'm still not sure if blurring the wallpaper should also be implemented in Niagara.
(related issue: #14)

**Comment by 8bitPit** [comment]
Added then a while ago :)

**Comment by 8bitPit** [comment]
Here's a preview:
https://twitter.com/NiagaraLauncher/status/1293569507361988608
https://twitter.com/NiagaraLauncher/status/1292119124106252289
https://twitter.com/NiagaraLauncher/status/1291393637910220802
