### ISSUE TITLE
Option to sort favourites by usage

### ISSUE THREAD

**Issue by jakcharvat** [8bitPit/Niagara-Issues#27]
Pretty self explanatory. To be honest I'm just too lazy to set up their order, do this would help me 😂

**Comment by 8bitPit** [comment]
You could remove all your favorites. The most used apps section is sorted by usage

**Comment by jakcharvat** [comment]
Good Point lol

**Comment by cauerego** [comment]
i still could not see this working.

perhaps there should be a visual clue it's thinking about the suggestions.

or it could start suggesting right away based on data that should already be available by the os! :)

and does it make sense to you suggest new ways to think about this issue in here or in a new issue?

since these are not critical, i'll just leave the ideas here for now:

- most used apps should go on bottom, for easier one hand access.

- perhaps group up apps often used together, around same time.

- change app position based on context. if i'm at home WiFi or on the move. if it's night versus day. etc.
