### ISSUE TITLE
Turn off third-party icon pack borders around unsupported apps' icons

### ISSUE THREAD

**Issue by ErikLandskov** [8bitPit/Niagara-Issues#2705]
### Describe the solution you'd like

The circle around default app icons looks pretty bad next to the icons from packs. Any way to turn that off would be great.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Could you please send a screenshot of what you are talking about?

**Comment by ErikLandskov** [comment]
Hello,

Take a look at the icon for "Strong" here. It doesn't have a good icon from
my icon pack so it uses the default which gets this circle around it. It
looks much worse than if the circle wasn't there. All default icons have
this.

Thanks!
- Erik

**Comment by TFackler** [comment]
Hi Erik,

Thanks for the response, but the image you tried to attach was not included in your message on GitHub.
I assume you mean icons like these (note the second "Calendar" and the "Cats&Soup" app):

![image](https://github.com/8bitPit/Niagara-Issues/assets/38538728/1cf2e813-1eef-4678-97a8-8ad8c0d98fd1)

Adding the functionality of disabling these borders supplied by the icon pack would lead to even less consistent setups, so we do not plan on adding a toggle for this behavior.

You can, however, change these icons manually if you want. To do that, long-press the app whose icon you want to use the default icon for instead of the border version > tap the icon in the top left > More icon packs > Default. To revert the change, edit the icon again > select the option in the top left

**Comment by ErikLandskov** [comment]
Thanks so much for the reply. I didn't realize I could work around it like
that, so I'll do that. That makes total sense.

Best,
Erik

**Comment by TFackler** [comment]
Since there exists a workaround for this request, I will close this issue.
