### ISSUE TITLE
Tap Mediaplayer Widget doesn't open running Media App

### ISSUE THREAD

**Issue by hoo84** [8bitPit/Niagara-Issues#2713]
### Describe the bug

When you tap the mediaplayer widget the running media app doesn't open, which did work in past versions iirc. https://drive.google.com/file/d/1XFcyTRys07hCkKUXm3_VKqRXy7JpukXd/view?usp=drivesdk

### Steps to reproduce

1. Start media playback
2. Swipe up from the bottom to get to the home screen
3. Tap mediaplayer widget to open running media player 
4. Media player doesn't open

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Pixel 8 running Android 15 Beta 2.1

### Android version

Android 14

### Screenshots / Screen recordings

https://drive.google.com/file/d/1XFcyTRys07hCkKUXm3_VKqRXy7JpukXd/view?usp=drivesdk

**Comment by TFackler** [comment]
Thanks for reporting this.
We are aware of the issue which affects not only the media player widget but also all other notifications displayed within Niagara Launcher.
The issue stems from an upgrade to a newer SDK and an issue with that and the Android APIs.

We are working on a hotfix and the issue should be fixed with coming version 1.12.2.

**Comment by 8bitPit** [comment]
Fixed in [v.1.12.2](https://github.com/8bitPit/Niagara-Issues/releases)
