### ISSUE TITLE
Clock alignment in home page

### ISSUE THREAD

**Issue by contact-maximux** [8bitPit/Niagara-Issues#2723]
### Is your feature request related to a problem?

Due to camera punch hole. I sometime think it will be better If I could align clock like

- Middle
- Left
- Right
It will ease for all camera punch hole user.

### Describe the solution you'd like

Ad option for alignment of home page clokc to LEFT< RIGHT<< CENTER

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thank you for the suggestion.

We do not plan on adding an option to align the clock differently since we are not fond of adding toggles, and since we think that for most setups, a differently aligned clock would look worse.

However, you can use any clock widget instead of the clock and even build custom clocks, including ones that are centered or right-aligned, using a custom widget app like [KWGT](https://play.google.com/store/apps/details?id=org.kustom.widget). 
For more, please refer to our help article: [Custom Clock](https://help.niagaralauncher.app/article/23-custom-clock).

**Comment by contact-maximux** [comment]
No worries, Still you won my heart. Could you guys think about adding color background rectangle under date, day, battery, weather. Still thanks

**Comment by TFackler** [comment]
Do you mean underneath the row of the Niagara at a glance widget to separate the widget and the list of favorite apps, or do you mean below the actual widgets so that the information itself is surrounded by color?
(I hope this description is understandable)

In both cases I do not think we will add such functionality as a feature to Niagara Launcher, the main reason being that we want to keep Niagara Launcher simple and reduce the number of settings and toggles as much as possible. For one feature the overhead and complexity might seem small, but if we did that for a bunch of features it would get convoluted very quickly.

**Comment by contact-maximux** [comment]
purely convinced. I dont know why I could not think like that. Thanks for launcher. 
Your happy premium member since 2021 niagra launched. :)

**Comment by TFackler** [comment]
Thanks for the suggestions, for your understanding, and for supporting Niagara's development 💙

 If you have any other suggestions for us, please let us know :)
We are always on the lookout to improve Niagara Launcher.
