### ISSUE TITLE
Shortcut problem for new user

### ISSUE THREAD

**Issue by contact-maximux** [8bitPit/Niagara-Issues#2725]
### Is your feature request related to a problem?

Two short cut

1. Swipe for notification
2. Swipe down for search
Now a days many mobile OS oppo, vivo, Iphone offer 

**- Swipe down for search**

### Describe the solution you'd like

- Add configurable option for swap shortcut for 
- Search and notification
User must be able to 
- Search by swipe down and notification panel for swipe up
- Search by swipe up and notification panel for swipe down

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by contact-maximux** [comment]
nobody se my issue

**Comment by TFackler** [comment]
Thanks for the suggestion.

The default behavior in Niagara Launcher is to swipe up for search and swipe down to access Android's notification shade.
Do I understand you correctly that you want to swap those two gestures?

If so, then sadly, we will not be adding this functionality since we believe that adding too many customization options for small preferences will make Niagara Launcher a lot more complex. For more information, please read about our [Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles).

Feel free to elaborate.
