### ISSUE TITLE
Battery percentage widget is lost between date and weather

### ISSUE THREAD

**Issue by contact-maximux** [8bitPit/Niagara-Issues#2727]
### Is your feature request related to a problem?

Although is may look beautiful But i never see my phone battery usuing battery home page widget. I always see by swipe down and notification.
Why 

> Because battery percentage is non distinguishable at home page, see below image
![image](https://github.com/8bitPit/Niagara-Issues/assets/171569223/dc2b9ea5-824e-4790-9862-48749207e438)

- Waether is distinguished by weather icon
- There is no separator between battery percentage and date

It becomes more hard when date format is MMM DD like, see example
![image](https://github.com/8bitPit/Niagara-Issues/assets/171569223/9949c968-3449-4c8e-9c5d-12833cc200f1)

### Describe the solution you'd like

Add any separator like
- battery icon
- any character 
- any pictorial separator

at arrow space in picture
![image](https://github.com/8bitPit/Niagara-Issues/assets/171569223/b9a767fb-b5ab-4aa1-911d-2187d62fd211)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned
Thanks 
you premium user since 2021

**Comment by TFackler** [comment]
Thanks for the elaborate feature request. While we have had multiple similar requests in the past, we have changed our minds a little bit and agree that some visual separator between the date and battery percentage could help improve readability.

Since this is technically a duplicate, I will forward the discussion to the old ticket and re-open it: #1688
