### ISSUE TITLE
Niagara button shows incorrect icon

### ISSUE THREAD

**Issue by camina-drummer** [8bitPit/Niagara-Issues#2757]
Selecting Todoist shows a book instead of the Todoist icon, many other apps with their own non-generic icons also show generic incorrect icons instead. This is using the outline version of the icons.

**Comment by TFackler** [comment]
Thanks for reporting this.

We are aware of this inconsistency and are working on a fix.

The issue is that we do not use our Anycons categorization algorithm for the Niagara button yet, because the categorization requires us to send data to our servers, which we only want to do if the user explicitly allows it. Since the Niagara button is a rather simple feature, we want to avoid requesting an additional permission before it can be used.

We plan to improve the categorization of the algorithm for picking the icon for the Niagara button and are also considering allowing the user to select the icon manually from our Anycons (#2672).

Do you personally want it to select the correct icon automatically, or do you want to select it manually or both?

**Comment by camina-drummer** [comment]
Understood, thanks for the explanation. I'd prefer manual selection.

-------- Original Message --------
