### ISSUE TITLE
Extend the alphabet scroll area.

### ISSUE THREAD

**Issue by DominikAgejev** [8bitPit/Niagara-Issues#2764]
### Is your feature request related to a problem?

Yes, I frequently miss the scrollable alphabet area because it is too small. 

When using the phone with my right hand I have to do violence to my thumb to squish it enough to touch the very edge.

When using my left hand I have to extend my thumb just a bit too far to be comfortable.

When using both hands it's not a problem to scroll with the right thumb.

### Describe the solution you'd like

Extend the touch area for the alphabet scroll by 50% at least, doubling it would probably be better. Whatever you conclude is the sweetspot I'll be satisfied with, but as it is it it's definitely too small.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for the suggestion.

Do I understand correctly that you cannot reach the alphabet in the horizontal direction, meaning you can't comfortably reach the far edges of the screen?

Please also note that you can scroll on both sides of the screen. On the left, we do not show the alphabet by default, but if you touch the left edge, it will appear on the right and react to the movement on the left edge.

Once you have touched the alphabet scroller, you can move your fingers as much inwards as you want, as long as you keep pressing the alphabet. 

With both of these options, we do not think that making the touch target for the alphabet larger since would obscure apps as well as custom widgets, which is why we will not enlarge it.
