### ISSUE TITLE
Hide games automatically from the list 

### ISSUE THREAD

**Issue by adrienrichmond** [8bitPit/Niagara-Issues#2922]
### Is your feature request related to a problem?

This feature would be interesting to avoid having to hide each manually installed game. 

### Describe the solution you'd like

When the game is installed, allow an option to be activated in the launcher to hide this category automatically. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your suggestion.
I'm sorry to say Impact and Reach aren't high enough here to warrant implementation since there already are ways of hiding apps or removing them from first glance. There are however other tickets that might address this issue([see here](https://github.com/8bitPit/Niagara-Issues/issues/2621#:~:text=Automatically%20hide%20apps%20contained%20within%20a%20folder%20(Exclusive%20folders)) for example) in the future. We'll reopen this if something should change.
