### ISSUE TITLE
Linux Desktop UI

### ISSUE THREAD

**Issue by AlexandrosLiaskos** [8bitPit/Niagara-Issues#3005]
### Describe the solution you'd like

Make it a "desktop" UI for Arch Linux and it will make you the best developers on the planet!!
It's 100% the most efficient and useful UI for androids, and I would love it in my Arch too!

**Comment by TFackler** [comment]
Thanks for the suggestion. Sadly, we do not plan to re-create the Niagara Launcher experience on other types of devices at this point in time.

Since we build Niagara Launcher for Android natively, we would need to re-develop the entire launcher from scratch. In our eyes, the outcome is not worth the effort.
That's why, sadly, we will not create a version for Arch Linux.
