### ISSUE TITLE
Greeting Widgets

### ISSUE THREAD

**Issue by 3b1g** [8bitPit/Niagara-Issues#3029]
### Is your feature request related to a problem?

I feel so motivated when I see good quotes and greetings. 

### Describe the solution you'd like

Hey there! I’m enjoying the Momentum Browser extension on my Edge browser, and it would just make my day to see some positive mantras and cheerful greetings like “Good Morning!” along with some meaningful quotes. **Just like momentum extension, It would be so nice when I saw the quotes and other stuff with the clock widgets on the Homepage, just like I saw the widgets like agenda, weather, and battery widgets.** 
![Screenshot_20241118-224051](https://github.com/user-attachments/assets/29ae36db-c47e-4cc1-84d9-db6bb1bec76e)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for this suggestion.

Sometimes, positive quotes can positive affect your everyday life. However, we do not think this functionality should be included by default in an Android Launcher, since the main objective is how you interact with your phone.

We recommend using any app that lets you create a custom or quote widget and add this to Niagara Launcher. Please check out [KWGT](https://play.google.com/store/apps/details?id=org.kustom.widget&hl=en) or something like [Quotes Widget](https://play.google.com/store/apps/details?id=com.ashwin.apps.android.quoteswidget&hl=en).

You can then add the widget by long-pressing the clock > Add custom widget > select the app.
