### ISSUE TITLE
Swipe down for search 

### ISSUE THREAD

**Issue by bdcrisman** [8bitPit/Niagara-Issues#3037]
### Describe the solution you'd like

An option in Niagara settings for swipe down for search. 

OneUI's Good Lock and iPhone both have the option to swipe down for search. What is nice about this is that it immediately puts your thumbs in position on the keyboard to start typing, making swipe to search to result very fast. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by contact-maximux** [comment]
I raised decade ago. Ignored
https://github.com/8bitPit/Niagara-Issues/issues/2725

**Comment by TFackler** [comment]
Thanks for suggesting this.

We already have an option to swipe up to open the search, which you can enable by going to Niagara settings > features > search > enable "Swipe up to search".

Is there any particular reason why you are not using that option?

**Comment by bdcrisman** [comment]
Hi there, I already use "swipe up to search" and while it works fine, I switch between Android and iPhone often, and I find "swipe down to search" to be faster as it puts your thumbs in position to type.

**Comment by TFackler** [comment]
Thanks for the answer.

While I understand the benefit of this change, we do not think adding a toggle for it is warranted since only a few people will benefit from it.
We also try to add only a few customization options to keep Niagara Launcher simple and intuitive.

You can read more about our [Design Philosophy](https://help.niagaralauncher.app/article/8-niagaras-design-principles)

**Comment by bdcrisman** [comment]
Understood. Worth a try at least. Thanks for the response and keep up the great work!
