### ISSUE TITLE
Sudden Freezing, Lagging, and Non-Responsive Behavior

### ISSUE THREAD

**Issue by Nick20-Hudson** [8bitPit/Niagara-Issues#3044]
### Describe the bug

Hello, dear Niagara Launcher team,

I have been using Niagara Launcher intermittently since 2018. Most recently, I have been actively using it since August 2024. My phone is a Samsung Galaxy A24, 4G, 6/128 model. It runs on Android version 14 with One UI 6.1 (fully updated to the latest version).

The issue is as follows: Sometimes, the interface freezes, lags, and becomes unresponsive. It’s impossible to move the screen. This typically happens when battery saver mode is enabled or when I receive a SIM card call. The temporary solution is simply turning the screen off and on again, but I would prefer not to experience this issue at all.

Best regards.

### Steps to reproduce

...

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung Galaxy A24 

### Android version

Android 14

**Comment by TFackler** [comment]
Thanks for reporting this issue.

Please check whether this description fits what you are experiencing:

❓ Niagara freezing/unresponsive / Tap in favorites opens app above
We are aware of issues with Niagara's user interface freezing. At the same time, the launcher itself keeps working, leading to the impression that the launcher is unresponsive and different apps opening than the one users tapped on.

We have reproduced the issue on some devices. This is just one cause, and it seems there are others. If you have a consistent set of steps leading to this behavior, please let us know.

Help us investigate:

We would also appreciate you sharing your device information [on GitHub](https://github.com/8bitPit/Niagara-Issues/issues/2595) so that we can pinpoint the issue more accurately, namely:

Android version
Device name
The flavor of Android running on your device (OneUI, MIUI, OxygenOS, etc.)
The version of Niagara Launcher installed
Possible workarounds:

go to your system settings
tap Accessibility
tap Niagara Launcher
tap the toggle and allow Niagara Launcher accessibility access
or

force-stop Niagara Launcher (should fix the issue momentarily)
Possible causes:

Our current theory is that the issue appears on devices running Android 14. When the screen is locked and another application takes charge of its awake state, Niagara Launcher and other third-party launchers have issues realizing they are in the foreground after unlocking the device and thus will not update their UI while staying responsive to actions.

This takeover was reproduced via Tasker opening an app in the background while the device screen is turned off, using Google Assistant, and receiving a call.

[More information on GitHub](https://github.com/8bitPit/Niagara-Issues/issues/2595)
