### ISSUE TITLE
home button not showing in navigation bar

### ISSUE THREAD

**Issue by yournannyisgee** [8bitPit/Niagara-Issues#3052]
### Describe the bug

I got Niagra pro and out of nowhere the home button just disappeared even tried factory resetting and reinstalling Niagra and nothing. had some sort of problem like this in the past but still nothing, any idea on what it might be?

### Steps to reproduce

not sure how to 

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Fire HD8+

### Android version

Android 9 (Pie)

### Screenshots / Screen recordings

![IMG_20241208_150725](https://github.com/user-attachments/assets/2a7c807e-d0aa-4306-b5d9-b19777238a50)

**Comment by TFackler** [comment]
Thanks for reporting this issue.

Since the issue also occurs on other third-party launchers the cause seems to be an incompatibility between the system and third-party launchers.

Did you recently apply an update to your system or device?

Please try to change the launcher to the default option and see if the home button reappears.

Sadly, there is not a lot we can do on our end if the issue is caused by the system.
