### ISSUE TITLE
Option to change the background to Blurred Album Art

### ISSUE THREAD

**Issue by DroidFreak32** [8bitPit/Niagara-Issues#31]
When there's music playing, the wallpaper changes to the album art, blurred (if there's no album art, the default wallpaper is shown).
This can be as an option in the settings so users who don't want it , or if it has some performance overhead noticeable in lower-end devices, they can disable it.

Here's a screenshot of how it might look like.

[![Screenshot_20180901-142245.png](https://s33.postimg.cc/gu2zh8nm7/Screenshot_20180901-142245.png)](https://postimg.cc/image/at5ak60zv/)

**Comment by 8bitPit** [comment]
Cool idea! I hope you understand that this is just an aesthetic feature and it will take a good amount of time to implement it. Anyway, that's very creative!

**Comment by DroidFreak32** [comment]
Sure! Not a problem.

**Comment by 8bitPit** [comment]
Hey again. I thought about this feature for some days and came to the conclusion not to add it. Showing a blurred album art would not be useful, it would just be eye candy. Because it could mess with some setups of some users adding a toggle would be necessary, as you suggested. However I want to keep Niagara simple with an overseeable amount of toggles (See #808 for one of the reasons). Sorry for not implementing this.
