### ISSUE TITLE
Larger letter in app list while scrolling

### ISSUE THREAD

**Issue by pradyw** [8bitPit/Niagara-Issues#323]
If currently selected alphabet has a bit large (prominent) font on blank space above apps that will be good to see.

**Comment by 8bitPit** [comment]
I agree

**Comment by 8bitPit** [comment]
Hey again. Because this would add a probably weird looking animation to the app list when the letter gets smaller, when the user releases the scrollbar (apps above the letter would move down) and because this would be only a minor cosmetic optimization, I decided to not implement this feature. Sorry.
