### ISSUE TITLE
Notification tray opens too early

### ISSUE THREAD

**Issue by yossi2010** [8bitPit/Niagara-Issues#341]
Swiping up and down rapidly will cause the notification shade to drop down even though you are not fully scrolled all the way up.
Maybe the trigger could be something like the elastic pull to refresh in Instagram so it will be more reliable?

I encountered a weird bug where there would be empty gaps between the favorites after going back home from the app drawer reentering the app drawer and back fixed it. I do not know how to replicate this but I think it would be nice for you to know that it's a possibility.

I think it had something to do with a few of the items just not animating into place and staying in their animation starting position.

Thanks.

**Comment by 8bitPit** [comment]
> Swiping up and down rapidly will cause the notification shade to drop down even though you are not fully scrolled all the way up.
It only happens when you swipe really fast, so it shouldn't be

**Comment by 8bitPit** [comment]
> Swiping up and down rapidly will cause the notification shade to drop down even though you are not fully scrolled all the way up.

You have to swipe really fast though, so you would be at the top in the next frame. Anyway, I'll search for a way to enhance it.

> Maybe the trigger could be something like the elastic pull to refresh in Instagram so it will be more reliable?

I believe a pull to refresh wouldn't fit, since the notification tray should open directly while swiping, not after the animation of the trigger finished / after releasing your finger.
 

> I encountered a weird bug where there would be empty gaps between the favorites after going back home from the app drawer reentering the app drawer and back fixed it.

Thanks for letting me know, I'll try to find the bug.
