### ISSUE TITLE
Last results aligned on the bottom

### ISSUE THREAD

**Issue by lepa22** [8bitPit/Niagara-Issues#36]
When scrolling in the slider drawer the last three results (for w, x, y in the following image) are gradually aligned on the bottom (t is for reference). 

![niagara-scroll-last](https://user-images.githubusercontent.com/16370046/44948087-69ae0980-ae20-11e8-9199-a211d9c4d4b3.jpg)

**Comment by 8bitPit** [comment]
That not a real bug. The problem is, it would look even worse, if YouTube (in your example) is aligned at the top. The problem is when those other apps become visible when you let go. The last app wouldn’t be at the bottom anymore, it would look akward, something like that:
![image](https://user-images.githubusercontent.com/9284845/44948992-85b5a900-ae28-11e8-89eb-19569065618e.png)

**Comment by lepa22** [comment]
Ok, you are right. I also think changing this would be worse.

**Comment by lepa22** [comment]
Ok, you are right. I also think changing this would be worse.
