### ISSUE TITLE
Add "tap to hide favs" 

### ISSUE THREAD

**Issue by rafaric** [8bitPit/Niagara-Issues#395]
As suggestion could you add the possibility for hide or show the favs and/or frecuent apps when you tap on free space of home screen. This could make the home even more minimalistic.

**Comment by 8bitPit** [comment]
Yeah, something like that could be cool.

**Comment by 8bitPit** [comment]
The app search will have a new "empty state" in the future (that shows up when you haven't typed anything in yet). App suggestions and recently  installed apps will show up there. Moreover, the Google button may have an option to open a folder instead of the Google search. In this way there is no need to add an extra toggle and you could achieve the desired effect nevertheless. I'll close this issue for now, but don't hesitate to reply if you want to discuss it further.
