### ISSUE TITLE
Set Custom Weather App Link

### ISSUE THREAD

**Issue by cbosdell** [8bitPit/Niagara-Issues#407]
Really enjoying this launcher but would like to request an option to choose the weather app opened when clicking on the weather icon/temp.  To be clear I don't mean for it to pull weather data from a different app I just want it to be able to open the weather app of my choosing when I click on the weather info since I prefer to use Weather Underground.  

Thank you for considering! :)

**Comment by 8bitPit** [comment]
Great idea, thanks for suggesting it.

**Comment by 8bitPit** [comment]
Hey again, @cbosdell. The new weather widget now offers a expandable dialog:
https://medium.com/niagara-launcher/hows-the-weather-5ecf3b183b0e
In my opinion that works better than custom widgets, because weather data is in sync with the small widget.

**Comment by Montell2099** [comment]
> Hey again, @cbosdell. The new weather widget now offers a expandable dialog:
> https://medium.com/niagara-launcher/hows-the-weather-5ecf3b183b0e
> **In my opinion that works better than custom widgets**, because weather data is in sync with the small widget.

With all due respect, he wasn't asking about custom widgets — just to be able to customize the weather app of your choice to open when tapping the weather icon — or perhaps the "More" text in the new weather widget.

I'd very much like to have this option as well, since I don't really like having the web browser opening when I want to see more weather data. Especially since their app only is available in a few countries, if you don't go find the APK for yourself to install it that way.

But I'd prefer sticking with my Google weather app for now, and at least be able to choose for myself what app to open when desiring detailed weather info. Other than that, the widget in itself works & looks good and fulfills its purpose.

**Comment by 8bitPit** [comment]
> With all due respect, he wasn't asking about custom widgets — just to be able to customize the weather app of your choice to open when tapping the weather icon — or perhaps the "More" text in the new weather widget.

Yes, I thought disaplying Dark Sky's website is a better solution, because then you can make sure both Niagara's weather widget and the advanced weather info are providing weather forecast for the same location and from the same sources. However I can see now, that it would be more comfortable  for some to open another app when tapping on the widget. Thanks for your explanation.

**Comment by malysek** [comment]
Personally, I would say that the quality of the Launcher with its own weather settings will be appreciated especially by those who have their own weather stations - such as Netatmo, or WeatherFlow ....

**Comment by 8bitPit** [comment]
@malysek yup. Until this gets implemented, maybe you could place a widget from Netatmo on your home screen.

**Comment by malysek** [comment]
I could certainly, but I prefer another Widget.  Don't worry about it, Peter, I certainly will advise, it was just a suggestion.  95% of your Launcher users don't own the Weather Station.

**Comment by arnabak** [comment]
With Dark Sky shut down, is it possible to revisit this topic? 

Maybe keep the widget as it is using the Dark Sky API but allow users to set their own weather provider when they click the "More" button at the bottom of the widget. 

For me at least, clicking "More" brings me here:

![Screenshot_20200805-093404](https://user-images.githubusercontent.com/69250087/89419417-576d3200-d6ff-11ea-8bc2-0642e068367a.png)

**Comment by 8bitPit** [comment]
Because tapping on the weather icon also opens the agenda view (we merged multiple clickable items into one to make tapping on it easier), I fear it would be akward if there's also a toggle to undo that and open a weather app instead. Furthermore, you can tap on the weather forecast in the advanced view to get a more detailed forecast via Dark Sky's website. If tapping on it would bring you to another weather app instead the data doesn't necessarily match (because of different forecasting methods) which would be an unpleasant user experience as well. That's why I'm closing this issue for now.
