### ISSUE TITLE
Swiping away notification doesn't work / Notification not dismissing on swipe

### ISSUE THREAD

**Issue by JaylanT** [8bitPit/Niagara-Issues#428]
Swiping away a notification in the notification preview accessed by swiping right on an app doesn't work. A box with "Dismiss" and a message icon appears, but clicking on either of them does nothing. The bottom box corners also extend outside the rounded preview popup.

**Comment by JaylanT** [comment]
Reboot seems to have fixed the problem.

**Comment by 8bitPit** [comment]
Thanks for reposting, I am trying to reproduce the issue.

**Comment by JaylanT** [comment]
I've also been unable to reproduce this issue. Not sure how it happened in the first place either.

**Comment by ascended1** [comment]
Would it be possible to add the option to swipe the other way to dismiss? As of now you can only swipe to the right.

**Comment by 8bitPit** [comment]
Hi @ascended1, I'm trying to keeping the amount of toggles to a minimum to guarantee a simple experience (more on that here: #808). For me, this options seems a bit redundant, because if you swap the gestures the other one would be harder to access to you (if that's the reason why you want them to be swapped). Moreover, you can also open the app action menu (by swiping to the right). There, you can dismiss notifications from both directions.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device (with v0.34.1)? If so, feel free to open the ticket again.
