### ISSUE TITLE
Hide hidden apps from search as well

### ISSUE THREAD

**Issue by bencherianskaria** [8bitPit/Niagara-Issues#468]
Kindly give an option to remove or not showing apps which are hidden in search menu. Example if i hide Pubg it still accessed by someone by searching in app search icon. 

Or kindly add an option to hide the search icon itself please

**Comment by 8bitPit** [comment]
Yeah, maybe I'll add an option to hide apps completely

**Comment by bencherianskaria** [comment]
Thanks , much appreciated .

**Comment by Rod911** [comment]
Problem is, that will only stop listing the hidden apps. Apps will be visible in other launchers or search apps.
Not much can be done from Niagara to prevent that.

**Comment by paddynski** [comment]
Hidden apps should not be included in Search. Can always add an option to include them in Search of you want this feature.

**Comment by 8bitPit** [comment]
We decided not to make hidden apps disappear from search. However, you can rename and change their icons to disguise them: https://help.niagaralauncher.app/article/97-edit-app-icons-and-names.

**Comment by AndyL964** [comment]
> We decided not to make hidden apps disappear from search. However, you can rename and change their icons to disguise them: https://help.niagaralauncher.app/article/97-edit-app-icons-and-names.
Maybe you can reconsider?

I tried to rename text while still making it readable using special formatting (eg. bubble, zaigo, and upsidedown/reversed text) but Niagara can still recognize the letters.

I use Niagara Dots icon pack as well so it's hard to tell apart the apps if they have the same name.

Cases where I'd like to hide apps include those that don't serve a purpose when opened (eg. printing apps and upgrade unlockers), are just there to provide system functions/automatic log in (eg. Facebook, Google search), or stock apps I'd like to replace.

For the stock apps example, you might tell since we one would be hidden and the other not

**Comment by AndyL964** [comment]
> We decided not to make hidden apps disappear from search. However, you can rename and change their icons to disguise them: https://help.niagaralauncher.app/article/97-edit-app-icons-and-names.

Maybe you can reconsider?

I tried to rename text while still making it readable using special formatting (eg. bubble, zaigo, and upsidedown/reversed text) but Niagara can still recognize the letters.

I use Niagara Dots icon pack as well so it's hard to tell apart the apps if they have the same name.

Cases where I'd like to hide apps include those that don't serve a purpose when opened (eg. printing apps and upgrade unlockers), are just there to provide system functions/automatic log in (eg. Facebook, Google search), or stock apps I'd like to replace.

For the stock apps example, you might say I can tell since one would be hidden and another not but I have reason to hide the replacsment as well (eg. if I put in pop-up folder, access by long tapping the clock/agenda widgets/text in quick settings panel, etc.).

**Comment by 8bitPit** [comment]
That's a tricky use case indeed, thanks for your input @AndyL964. How about manually changing all apps' icons to the default ones and using emojis for their names for those apps you don't want to appear in search? 

> but I have reason to hide the replacsment as well (eg. if I put in pop-up folder, access by long tapping the clock/agenda widgets/text in quick settings panel, etc.).
I see. If those are apps you regularly use, isn't it better to list those apps in search?

**Comment by AndyL964** [comment]
How would changing the icons change anything?

The entire name would have to be emojis only or else any letter sequences
searched up would show it, but if I do this I won't be able to recognize
those apps if I look for them in Hidden Apps in the future.

If they serve no purpose (eg. a printer app whose function can only be
accessed through share menu), are commonly used (eg. favorites list of
Niagara button), can be accessed through widgets (eg. Niagara widgets:
clock > clock app and agenda > calendar app, search without results > play
store app) then there's no reason really for those apps to show in search
cause I would know exactly where they are.

**Comment by 8bitPit** [comment]
Yes, I mean emojis only. Then, those apps don't show up in search (except if you search for emojis).

**Comment by AndyL964** [comment]
Yeah then I guess it works. A bit of a rough solution though. Apart from
looking having trouble finding the app when you go look for it in the
Hidden Apps list, it's not very pleasant to see it show up in the settings
preview and Recents Apps pop-up.

But I do understand why you're hesitant to add it. It's a minor
inconvenience at best.

**Comment by 8bitPit** [comment]
Agreed, it's a rough solution. I hope it's still alright, as we don't plan on supporting this use case.
