### ISSUE TITLE
Move recent apps to search bar

### ISSUE THREAD

**Issue by maskyad** [8bitPit/Niagara-Issues#57]
You can move the recent/ most used apps to the top of the search bar. This way you will keep the clean look of mainscreen.

https://imgur.com/a/mTxxM2d

**Comment by 8bitPit** [comment]
Thanks for your suggestion, I personally like recent apps on my favorite section, but you can disable them if you want to. But yeah, good idea! Probably new apps should be shown when opening the search screen as well!

**Comment by zach-perl** [comment]
Adding onto this, I really love how the OnePlus launcher has implemented this feature. Now when the search for apps screen is opened, instead of the entire screen being wasted blank space, the space immediately below the search bar is used to display categories (the most useful being "recent searches" and "new installs" and they also include categories for social apps, music, games, etc but I think that is less useful than the recent searches and new installs. This way opening search immediately shows you (below the selector for which category you want to see) 8-10 apps that are either your most recent searches, or, if you select it, recently installed apps. Utilizes otherwise wasted space and adds tons of efficiency for any app that you frequently search. This is literally the one feature that makes me second guess/switch back to that launcher, and especially if the categories were similarly added in this location could add a new way to get to apps without taking away from the minimalism on the home screen that we all love.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
