### ISSUE TITLE
Get weather from netatmo

### ISSUE THREAD

**Issue by paaland** [8bitPit/Niagara-Issues#587]
Lots of people have netatmo weather stations. I'd love the weather to be fetched from my station instead of Google since that's always wrong. Also customize the weather link to an app or URL.

**Comment by 8bitPit** [comment]
Thanks for the info @paaland, I know the Google API is pretty bad, I will try to support more providers at some point.

**Comment by 8bitPit** [comment]
Hey again. Niagara Launcher lets you now place widgets below the clock, I'm sure there are several netatmo widgets on Android to choose from. Because this request is a bit too specific a weather data will not be displayerd from netatmo "natively", but I think this is a could compromise.

Btw, this issue might interest you: #407
