### ISSUE TITLE
Hidden apps (lock)

### ISSUE THREAD

**Issue by princeth3333** [8bitPit/Niagara-Issues#613]
It would be good if you add a lock to the hidden apps drawer. Also add a quick launch gesture in the home page.

**Comment by 8bitPit** [comment]
You can access hidden apps quickly by using app search. Furthermore please visit #332 for more information about locking apps.

**Comment by anirban2229945** [comment]
Dear Developer,
I found a bug in your recent most patch of Niagara Launcher.
Steps to reproduce:

1.Hide > 200 apps or > 150 apps
2.Go to Niagara Settings.
3.Click on Hidden Apps.
4.List of hidden apps appear for a few nanoseconds and then auto-closes.
5.Not possible for humans to see or work with Hidden Apps
if
{
HiddenApps.COUNT() >= 150
}

Hope these info's will help you to provide a quick fix update on Play Store.

Niagara is the best launcher I have seen since days of the earliest Android OS and it carries a sentimental value also for me.

Pls fix ASAP, thnx in advance.

Anirban

**Comment by 8bitPit** [comment]
@anirban2229945 thanks for letting me know, I'll try to fix this.
