### ISSUE TITLE
Double tap to lock screen

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#63]
This is issue is open for discussion & new ideas.

Implementing the screen lock feature is a bit problematic, because:
1.	It requires an accessibility service (for devices not running Android P)
2.	Where do you want to double tap? Maybe the user has a full list of favorites, so you the only free space is at the top. However, that’s hard to reach. Tapping on an app seems like another option, BUT: measuring a double tap requires waiting for a short amount of time after a single tap to differentiate between the two taps. In other words: you would have a delay (about 500ms) every time you open an app.

**Comment by krishnivas** [comment]
How about double tap nav bar similar to the feature in some custom ROMs? Or double tap home screen or back button?

**Comment by 8bitPit** [comment]
@krishnivas, unfortunately I have no control over the navigation bar.

**Comment by juegomeister** [comment]
How about a double tap on the alphabet navigation? Should be able to react to a tap immediately and wait for a second tap, so rather than waiting 500ms before opening an app (as mentioned initially), it would be jump to alphabet spot and wait 500ms after for a tap in the same spot on alphabet, where a tap on an app, or different spot in the alphabet is just another single tap? I don't know if that's possible, but just a suggestion of what I think might be a solution.

**Comment by 8bitPit** [comment]
@krishnivas 

> Or double tap home screen or back button?

Oh sorry, missed that. I believe that would be the best way to implement double tap to sleep!

**Comment by SventraPopizz** [comment]
If you end up implementing this, try to use Nova launcher's implementation where you let the user select the way to lock the screen, like using root so the fingerprint sensor will still work after the lock with double tap

**Comment by cauerego** [comment]
i **love** the soft lock. missed it from one plus when I had to move forward (it's still my backup phone) and now i miss it from accessibility options on pie (had to downgrade phone, reason why i found Niagara).

and i believe it would be a great addition to Niagara... but...

only if done by oss community or another Dev on the team.

i'm glad to see you find this problematic to implement, because it is. too much. it would remove focus from more important features and bugs.

if we need it so much, people, just use another app for it, already! here's a couple of suggestions: X home bar or https://play.google.com/store/apps/details?id=com.simi.screenlock

as for how to implement it, copy from the x. gestures or even buttons on the bottom. it might make sense to eventually replace the navigation bar, Android should let launchers customize it in the future, eventually.

**Comment by nidnme** [comment]
Double tap to home screen or back button is nice idea.

**Comment by fante76** [comment]
Double tap is like double click on pc, so amount between 300ms and 500ms should be enough.
Better place for me to tap is home page where there are no icons. UI on my lg g6 does so.

**Comment by imam123ci** [comment]
How about make floating button to lock, not real double tap but i think it's less problematic and easier than double tap ??

**Comment by rituraj22** [comment]
I am on custom  ROM, so just an option to double tap on empty space to launch custom shortcut would do. Later you can implement accessibility service, if you wish.

**Comment by colbycdev** [comment]
@cauerego So how about those who don't have the ram to run a bunch of background apps? It's easier to just have one. 

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by colbycdev** [comment]
@imam123ci This would work great, @8bitPit 

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cauerego** [comment]
@colbycdev funny you say that now. #117 https://github.com/8bitPit/Niagara-Issues/issues/117#issuecomment-451783115

however, i think i was both pretty clear i do want the soft lock and that it should never become a priority for such an app with only 1 dev. 4 months in, look at how much was done (quite a lot) and how many features were added.

finally, there's a mid range of people today, who will become low end soon enough, who are able to benefit from Android pie native soft lock.

**Comment by bala7s** [comment]
There are some UXes where double tap on the status bar locks the screen. Asus UX is an example. So tapping on the top of the screen, above the clock shouldn't be an issue.

**Comment by 8bitPit** [comment]
@bala7s It shouldn't be but it's hard to reach on most devices. Instead of reaching to the top, I would feel more comfortable to turn it off with the power button.

**Comment by kmbrc5** [comment]
@8bitPit  First of all nice work! Just a comment about it, for some LG users the power button is behind of some devices and actually the double tap it is a time savior to lock off the screen. I read some comments above about double tap in the alphabetic navigation if you consider this won't affect the UX

**Comment by bluemonday91** [comment]
@bala7s yeah, sure, maybe for small devices, but aiming the status bar is going against the flow of the market, since the current trend is tall phones with 18:9 aspect ratio.

I'm no expert in app development, let alone programming, but couldn't the dev like write a code that determines the safe spots for lock based on aspect ratio and amount of favourite apps? I wonder how laborious would that be, if possible at all.

**Comment by Dedisurya** [comment]
I think that is good idea. And will be the one as the best launcher, because can be helpful for smartphone which is broken at power button. There are many smartphone when using so long time than so hot, and than the power button is can not be used. So, double touch to lock screen and turn off device is so great idea.

**Comment by paijojo** [comment]
I hope niagara launcher has a display shutdown feature by providing a padlock symbol on the home screen

**Comment by paijojo** [comment]
using the feature to tap the screen to turn off the screen will not be a problem for any smartphone, that is by providing a lock-shaped application icon on the home screen, and not needing a double tap.

**Comment by paijojo** [comment]
Easy right.

**Comment by paijojo** [comment]
How to activating this feature ?.

**Comment by paijojo** [comment]
tell me whether this feature can be used. How to ?

**Comment by 8bitPit** [comment]
@paijojo 

> using the feature to tap the screen to turn off the screen will not be a problem for any smartphone, that is by providing a lock-shaped application icon on the home screen, and not needing a double tap.

good idea, that would also work

> tell me whether this feature can be used. How to ?

It hasn't been implemented yet.

**Comment by romavonk** [comment]
Why not "swipe up" to lock screen?
Like "swipe down" calls the notification bar.
It can be done in the middle of the screen next to the favorite apps (conform "swipe down").
No need for special threatment of tapping (tap now opens a favorite app).

**Comment by JianyueZ** [comment]
Hey! Great thanks for making this fantastic launcher!

I would prefer the both sides of favourite apps (like an above comment, using the alphabet area, and also the area near the left edge)

And in addition, is it a good idea to do "palm lock"? To lock screen by covering it with hand palm.

**Comment by JohnCale47** [comment]
What about Lock Screen button which replaces the existing google app button at the bottom ?

**Comment by 8bitPit** [comment]
@JohnCale47 I think assigning a double tap gesture to the button would work great.

**Comment by astroVibes** [comment]
Ciao ragazzi, se aggiungete un altro pulsante invece di sostituire il pulsante Google?
Penso che ci sia abbastanza spazio per entrambi

**Comment by 8bitPit** [comment]
@astroVibes There is enough space, but in my opinion, two buttons wouldn't look good. However, you can still use the button to open Google, it would just get a second gesture (double tap) to lock the screen.

**Comment by romavonk** [comment]
If you want an icon/button, use an app like "Screen off (pro)" from Auron and add it to your favorites.
I would prefer swiping up in the favorites area. 
It saves space, no delays needed (double tap detection).
Trick already done: swiping down opens the notification panel.
Adding two finger swipe up / down for 2 custom actions (like e.g. Nova Launcher) would add a great value to the launcher. I would even want to pay for it ;-)

**Comment by KamalKhazany** [comment]
This app is my daily driver! So please add this feature!
Thanks

**Comment by mrajendray** [comment]
How about swipe gesture or long hold on Google app button

**Comment by Methotrex8** [comment]
Hey @8bitpit! It's me again. I like the alphabet because it is such a simple way to get to any app. Thus, my suggestion is to put the locking mechanism in it, too! You could put it at the bottom or top of the alphabet (a toggle might be good for this), so a person just needs to press the alphabet and rest his/her fingers at the spot where the lock is. Once the person let's go, then it's the trigger to lock the phone. I think it makes sense since the alphabet, imho, is the heart of the minimalist design, which is why I'm exploiting it in every suggestion I make.

**Comment by 8bitPit** [comment]
@mrajendray I think this would feel more intuitive:
> I think assigning a double tap gesture to the button would work great.

**Comment by 8bitPit** [comment]
@Methotrex8 thanks for the creative idea, that could also work well. The only concern I have, is that users accidentally lock their screens. I'll test your idea when I start work on the feature.

**Comment by 8bitPit** [comment]
Until this feature has been implemented, you can also use an app that lets you lock the screen when launching it: https://play.google.com/store/apps/details?id=com.chamika.screenoff
Disclaimer: Someone in Niagara's Telegram chat told me about this app, I haven't tried it for myself yet.

**Comment by Methotrex8** [comment]
I'm using something like that right now (pre-installed), and it works for me. I keep it as the first favorite app, so I have access to it right away. It actually works great, so I'm not one to totally push for a lock mechanism right now. Anyhoo, keep up the great work!

(I assume that other users are suggesting a lock mechanism because they want to avoid having to download yet another app.)

**Comment by 8bitPit** [comment]
@Methotrex8 thanks for letting me know :)

**Comment by Montell2099** [comment]
I think the suggestion from @juegomeister is the most simplistic one without adding any extra UI elements, double-tapping on the alphabet bar within a certain time frame.

Maybe not the most intuitive implementation, but I don't think people will be double-tapping the alphabet very often & be left confused on why their phone just got locked.

**Comment by Kristianruiz24k** [comment]
how about swiping the alphabet all the way to the bottom locks the screen?

**Comment by kr-kumar** [comment]
I really love the minimalist design of the app. But double tap to screen lock is very nice to have feature.
Others already suggested about the button.
My take on this what about a custom button/joystick with bunch of gestures.
Double tap - Screen lock.
Single tap - Open a custom task.
Hold - bunch of other options.
Swipe - left, right, up,down open diff. apps
Sample - https://cdn4.vectorstock.com/i/1000x1000/59/38/joystick-ui-button-design-vector-1035938.jpg

**Comment by JLM709** [comment]
Add a tap zone to the right of the clock. It's a dead zone and the area can be used to double tap and lock.

**Comment by akastanis** [comment]
I think an even simpler solution would be a 'single' tap on the home button to lock the screen.  It seems that you'd avoid the timing/waiting issues with a double tap.  Nova and AIO launcher both provide this option.  It's nice since the home button is always in reach.

**Comment by 8bitPit** [comment]
@akastanis unfortunately a home button press can't be executed easily when gesture navigation has been turned on, you'd have to do an akward shorter, slower swipe up gesture to trigger the same event that fires when you press the home button.

**Comment by yashpalgoyal1304** [comment]
I have read other suggestions too, and atm I cant understand clearly what they mean. So, I am writing mine, sorry if it is repeated.

Can we have a Niagara widget, which can be added in the favourites itself. And we can have its behaviour adjustable in the Niagara settings. I think that would be easiest to implement without any many changes required to other part of the application. 

Also, if placing one more favourite feels like taking up extra space to some users, then the widget can be given the shape of a bar (like separator bar) for them.

**Comment by ZephyrMathi** [comment]
> This is issue is open for discussion & new ideas.
> Implementing the screen lock feature is a bit problematic, because:
> 
> It requires an accessibility service (for devices not running Android P)
> Where do you want to double tap? Maybe the user has a full list of favorites, so you the only free space is at the top. However, that’s hard to reach. Tapping on an app seems like another option, BUT: measuring a double tap requires waiting for a short amount of time after a single tap to differentiate between the two taps. In other words: you would have a delay (about 500ms) every time you open an app.

In my home screen I have an widget + 8 apps and then at the bottom I have about 1/2 an inch free , that is an great place for double tap trigger as I mostly rest my thumb floating above that area , Just my suggestion based on my usage . I believe this was the case when I first used the launcher before you added support for 9 apps or I might be wrong .

**Comment by UserDave-boop** [comment]
Could we not Swype right to left over any app in the list to lock the screen rather than a double tap etc?

**Comment by Rod911** [comment]
@UserDave-boop Right to left is already used to dismiss the app's notifications

**Comment by UserDave-boop** [comment]
Ah my apologies! I've clearly not used that 😁

**Comment by 8bitPit** [comment]
Yeah, @juegomeister thanks for your awesome idea :)
