### ISSUE TITLE
Allow to select language

### ISSUE THREAD

**Issue by disacrol** [8bitPit/Niagara-Issues#656]
Suggest to add an option in settings for the user to change the display language.
This would be helpful in cases where native language translation is not available but the user is more comfortable with languages other than English.

In my particular case, now that my native language is applied, I wish I could force English language sometimes to more easily open bug reports describing the correct names and options of the UI in English.

**Comment by AZMPlay** [comment]
+1

**Comment by Rod911** [comment]
This would be more of a 'developer mode' setting than a normal use case right?

**Comment by 8bitPit** [comment]
@disacrol yeah, could be helpful for some.

**Comment by timm0e** [comment]
> @disacrol yeah, could be helpful for some.

E.g. when providing support for another language than the one you're currently using

**Comment by 8bitPit** [comment]
Hey again. I don’t want to make this a feature because of the following reasons:
1. No other launcher has a language chooser, I think that’s not much requested 
2. Android has a smart multilingual language system. A chooser would only let you have one system language and implementing their system would be overkill.
3. I see no reasons (except for debugging purposes) why you want to change the language of just one app. But that are just my thoughts, as always, feel free to share your thoughts on this.

That's why I'm closing this issue.
