### ISSUE TITLE
Choose default clock/calendar app

### ISSUE THREAD

**Issue by joshiain** [8bitPit/Niagara-Issues#676]
I understand this may be a niche request. But some organisations require a work profile to be set up using android device policy. This means there can be 2 Google Calendar apps on a device. Where the work profile calendar is unable to share events with your main calendar.

Adding an option to choose which Calendar app opens when clicking on the date in the home screen would be very handy.

**Comment by ButtsBrow** [comment]
I like the look of your launcher. Just used your tip to clear default clock app' now opens the Google clock app'.
Thanks

**Comment by disacrol** [comment]
@8bitPit if I understood correctly, what he is suggesting it to be able to select the calendar app each time you tap the date widget, and not having an option in settings to switch the calendar app to use. It's this functionality you plan to implement in the future?

**Comment by 8bitPit** [comment]
Thanks the explanation @disacrol, I misread his comment. Sorry @joshiain. Basically that would be a folder which opens up when you tap on the calendar. The same concept could also be applied to the Google Search button (maybe should be renamed to Niagara button, because it wouldn't only open Google anymore), or the clock & weather icon. Even widgets could be added to those folders. 
But that's just an idea for now, it would require the categorization & widget system, which take a long time by themselves.

**Comment by martinpengellyphillips** [comment]
I also want to select my work calendar as the default one to open when clicking the date widget. Currently this isn't possible because the work calendar is in a work profile and doesn't appear as an option when selecting default.

Related to the discussion above might be #1335 - you could imagine two pages of favourites that you can swipe between. Each page could optionally have its own widget configuration to support easily switching context.

**Comment by 8bitPit** [comment]
Because Niagara Launcher now has its own calendar agenda which shows events from all of your calendar apps, we won't add the option to open the work profile calendar when you tap on the date. Niagara Launcher may soon also show work profile events in the agenda widget, but this feature requires Android 10 and the organizations IT Admin has to grant the permission to make work profile calendar events on personal profiles.
For setting another clock app as default, there's now a separate ticket (https://github.com/8bitPit/Niagara-Issues/issues/295), that's why I'm closing this.
