### ISSUE TITLE
Choose default wallpaper app again (reset default)

### ISSUE THREAD

**Issue by svavaiesu** [8bitPit/Niagara-Issues#682]
Once you select your wallpaper default app, there is no way to change it from the settings.
You should be able to change individual options to default and not have to clear everything

**Comment by 8bitPit** [comment]
Unfortunately Android did a poor job on implementing the app picker for app categories. You'll have to go to the app info to the wallpaper app you set as default, and go "Open by default" > "Clear defaults". I'll probably implement a custom default app system at some point.

**Comment by Bullnados** [comment]
Is it possible place a simple link with description to these Settings?

**Comment by 8bitPit** [comment]
Where would you place it exactly?

**Comment by svavaiesu** [comment]
In Niagara Settings page, under Look maybe

**Comment by rd836** [comment]
I've tried to find the best issue to tack this request into, so will put it here. 
If not the right pace, then please relocate it.

In the Settings area, below our last letter, where the small circle takes us, we see the title "Settings" then the icon with "Niagara settings" followed by an icon and "Wallpapers."

Since for me using the Wallpapers is a once in a lifetime (of the phone) event, can it be put _in_ the Niagara settings?  In other words, all I want to see is "Niagara settings".  If I were to want to tinker with the Wallpaper, I'd prefer it be _inside_ the Niagara settings. Or let it be a Hidden app, to be gotten to like any other Hidden app.

**Comment by PaulReiber** [comment]
Happy to provide instructions for getting this reset.

Right now, to reset this, you will have to:
-> open the phones settings gear
-> scroll down to apps
-> open that - "apps".
-> Within apps, open its settings panel.
-> choose "show system apps"
-> Now you see ALL the apps. Find the one you had selected, open its settings
-> scroll down and click on "Set as Default".  
-> If it says "None set as default" that wasn't the right app.  
-> Whichever is currently set as default will have a link "Open by default" 
-> so click that "Open by default" then click "Clear defaults"

...there, wasn't that easy?

**Comment by Martin5001** [comment]
> Unfortunately Android did a poor job on implementing the app picker for app categories. You'll have to go to the app info to the wallpaper app you set as default, and go "Open by default" > "Clear defaults". I'll probably implement a custom default app system at some point.

I've seen one app called Sharedr do this (it has "clear defaults" button in its settings) so I did some research and figured this might be helpful: https://stackoverflow.com/questions/40264673/how-to-reset-default-app-programmatically-which-user-previously-chooses-as-open
(Niagara could run this reset every time the wallpaper button in Niagara Settings is pressed.)

**Comment by Maxr1998** [comment]
The next release will try to open the Google Wallpapers app by default (as it did previously), and if that fails, always show a chooser of all wallpaper selection apps.

**Comment by Maxr1998** [comment]
(Actually, 1.6.1 :wink:)
