### ISSUE TITLE
Wallpaper misaligned (not centered, cropped, scaled)

### ISSUE THREAD

**Issue by Aceaceq** [8bitPit/Niagara-Issues#688]
Niagara doesn't center the wallpaper anymore, it moves it to far left.

**Comment by 8bitPit** [comment]
Could you please provide a screenshot? Also, please tell me, which device you use.

**Comment by Aceaceq** [comment]
I use xperia E5.
https://imgur.com/a/PRGgC1N
It used to center my wallpaper, now it just moves it to the left.

**Comment by 8bitPit** [comment]
So every time you change the wallpaper. the launcher misaligns them? Does it align correctly when setting the wallpaper with [Google photos](https://play.google.com/store/apps/details?id=com.google.android.apps.photos&hl=en)?

**Comment by Aceaceq** [comment]
Yes it does

**Comment by Aceaceq** [comment]
It doesn't.

**Comment by 8bitPit** [comment]
Please refer to: https://niagaralauncher.helpscoutdocs.com/article/36-wallpaper-bugs

**Comment by 8bitPit** [comment]
I'm reopening the issue because in some cases (e.g., when using a custom Samsung theme), users can't work around this issue using Google Photos.

**Comment by 2zqa** [comment]
Glad to hear this issue has been re-opened, this issue pops up with most, if not all apps that auto-set a wallpaper (popular example: backdrops).

Please don't forget to actually re-open this issue, it still appears as closed.

**Comment by 8bitPit** [comment]
Thanks a lot for all the additional details and screenshots @2zqa 😀 I recently tried to fix this, but it turned out to be more tricky than I thought:
> This can happen with wallpapers that are wider than the phone's screen width. The problem with wide wallpapers is that either the launcher or the wallpaper provider app has to do the centering (if both do it, the wallpaper will also be off-centered). Niagara Launcher could do the centering, but most Android launchers such as Google's Launcher3, Pixel Launcher, and Nova Launcher don't center the wallpaper; they left-align it (to simplify the explanation, we disregard parallax scrolling). Because of this, most wallpaper apps such as Google Photos and Google Wallpapers crop the wallpaper in such a way that it looks centered for you even though it's technically left-aligned. If we'd now begin to center the wallpaper (like Samsung's OneUI Home Launcher does, for example), apps that wallpapers that get "center-cropped" would now be off-center to the right. Because most launchers left-align it and, therefore, most wallpaper apps crop them, we decided to also left-align them. [[Source](https://help.niagaralauncher.app/article/36-wallpaper-bugs)]

Originally, I forgot to re-open this issue, but now I believe the wallpaper app should do the centering for the reasons above.

**Comment by 2zqa** [comment]
I see what you mean now. Indeed, it seems that a bunch of wallpaper apps all have their own way of setting and cropping the wallpaper. My findings, using LineageOS' Trebuchet launcher:

* Google wallpapers: When aligning and setting the wallpaper in the app, it will remove everything to the left of the viewport only.
* AOSP wallpapers: Not entirely sure. When aligning and setting the wallpaper in the app, it seems to check how many pixels there are falling off the screen to the left and the right. Whichever is the smallest, it will apply the same amount of margin to the other side. So if there are 500px not visible on the left/right and 0px on the other, the image will be precisely fit to the screen. But I'm not entirely sure about this.
* Backdrops: Applies the entire wallpaper.
* Abstruct: Applies the entire wallpaper.
* Walli: Crops the wallpaper to the resolution of your screen. Will never scroll.
* Zedge: Crops the wallpaper to the resolution of your screen. Will never scroll.
* Walpy: Crops the wallpaper to the resolution of your screen. Will never scroll.
* Gallery (com.simplemobiletools.gallery): Allows user to crop to either square or resolution of screen (seems to slightly get it wrong, parallax effect still slightly there)

Okay, so clearly Backdrops and Abstruct are the exception rather than the norm. I guess I should contact these app developers instead of you.

Except if maybe, and I know this goes against Rule 3 of the feature request guide, there could be a setting for this.

- [x] Simple: Easy to configure and easy to use. As few settings & toggles as possible.
- [x] Impactful:  Either appealing for many or necessary for some.
- [x] Universal: Has to work everywhere: in every country, on all phones.
- [x] Independent: It doesn't add complexity if it's not being used.

The reason that I am requesting this is because clearly nobody agrees on how wallpapers should be set. Some crop the left side, others crop in inexplicable ways, others just take the screen resolution, and even launchers don't agree like you said (OneUI, launcher3). And since this is a custom launcher, which in the end is something a user installs because they wish to customize their phone, *and* since wallpapers are the core thing most people use to customize their look and feel, I suppose this would be a welcome feature. But I would understand if this wouldn't be added as well. If so, I will leave this issue to rest.

**Comment by 8bitPit** [comment]
Apologies for my late reply, and again, thank you very much for going into such detail @2zqa! With v1.4, we now provide the option to offset wallpapers to circumvent this issue; I hope this helps.
