### ISSUE TITLE
[Feature Request] Move music controls

### ISSUE THREAD

**Issue by TheSorton** [8bitPit/Niagara-Issues#693]
I would like an option to align the music controls to the left to better fit with the rest of the UI

**Comment by 8bitPit** [comment]
Centered icons make it easier to tap on them without pressing the wrong control button.

**Comment by TheSorton** [comment]
That's understandable hence why it could be a toggle.

**Comment by 8bitPit** [comment]
Yeah, I'm not a fan of adding settings for layout tweaks. It makes the UI harder to maintain (e.g. sometimes I would have to adjust both layouts in case of changes). Moreover, I don't know anymore, how the player looks an a device, since the user can choose one. That's for example problematic when designing other layouts which should also fit the same style. layouts which  Furthermore it adds another toggle to Niagara's settings.
