### ISSUE TITLE
Disable most used apps 

### ISSUE THREAD

**Issue by Kazim01** [8bitPit/Niagara-Issues#695]
It takes us away from screens minimalist view. All apps are one tap away from the alphabet list if we get a hang of it.

Would appreciate an option to disable most used apps.

**Comment by 8bitPit** [comment]
You can either long press each app separately and tap "stop suggesting" or you can go to Niagara's settings and toggle "limit most used apps"

**Comment by matanui159** [comment]
I disagree with these options personally. "Limit most used apps" Apparently only limits it to two apps instead of removing it, and I don't want to keep selecting "stop suggesting" every time a new app is suggested. Also it makes it difficult to go back if I ever decide I do want suggested apps.

Also I noticed you mentioned in #318 that the idea of the suggested apps is to add favorites the user may have forgotten. However, I find two issues with this:
1. "smart" features are good and all, but sometimes I want to be in control and have it consistently stay like that without something changing it because it "thinks" that's what I want
2. some apps I do use a lot but I intentionally didn't put in my favorites because I want to stop using them so much (eg. games and YouTube)

Maybe instead of the "limit most used apps" option you could have a drop down with "All", "Limited", "None" and maybe another option with more (I've seen feature requests to have more suggestions)?

**Comment by Kazim01** [comment]
Agreed. However, in my experience the most used apps suggestions does ntk
update itself of you block an app from it. So, after initial blocking of
few apps, I haven't had to bother with it again and things have been very
consistent.

I can't see any other option to reset this without resetting the launcher.
