### ISSUE TITLE
App list background tint

### ISSUE THREAD

**Issue by halxinate** [8bitPit/Niagara-Issues#705]
I have live wallpaper scrolling under the finger while scrolling the app list and changing the color from white to black (Earth globe). Labels are hard to see. An option to use a selectable color background overlay would be golen.

**Comment by 8bitPit** [comment]
I thought about something similar. How about adding a transparent "scrim" which has the the most prominent color in your wallpaper in the app list? Stock android (8.1+) does that on the lockscreen already.
Sometimes it doesn't look that good, e.g.: https://imgur.com/gallery/hRVIE That's why I also should add the option to change the tint to black.

**Comment by halxinate** [comment]
I would just allow the user to set the color like a hex value (e.g. #1fa0a0a0). That would satisfy any possible taste :)

**Comment by 8bitPit** [comment]
In my opinion, a just a single color looks a bit out of place, transitioning from a wallpaper to the color would look weird.

**Comment by 8bitPit** [comment]
Oh, didn't see that your example color included a hex val for alphas. Yeah that would work.

**Comment by Zilchaz** [comment]
Not a fan of tint. How about blur background?

**Comment by Novbert** [comment]
Actually I would prefer having an option to get the wallpaper blurred/darkened by overlay all the time (like the sample wallpapers in the google play page), even on the home screen. The way the home screen is arranged is the same as the app list is, so if there are visibility issues in the app list, the same issues appear on the home screen as well. 
In my experience the launcher is currently only usable with dark wallpapers.

**Comment by 8bitPit** [comment]
@Novbert Yes, it's as hard to read the favorite app labels as it is for apps which are in the app list. However, you're accessing favorites so often, that you don't have to read their names in order to access them. Btw, apps like "Blur wallpaper" or [Muzei](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei&hl=de) let you do that pretty easily.

**Comment by Novbert** [comment]
That's true, but 3rd party blurring/darkening solutions don't work with animated/live wallpapers. For example I love maxelus' [Galaxy pack](https://goo.gl/pqkvoQ), but I can only use one of the 30 presets with Niagara as all other presets are too bright, making app names nigh unreadable.

**Comment by vebulous** [comment]
I am very late to this party, but would like to chime in. I currently have implemented a fancy KLWP (kustom live wallpaper) and would very much agree that some sort of tint/shade/blur would be nice.
- Blur is out of the question tho, too resource intensive and casting permissions for such a small thing.
- A tinted (average background color) overlay is also too resource intensive (would probably look nice)
- Selectable alpha+color hexadecimal overlay would be awesome
- Optional pure black box would be better than nothing.

Off topic: i could easily do ALL of these inside KLWP but would need to set it up with some sort of trigger. Unfortunately, opening the app menu doesn't trigger a "screen horizontal swipe/scroll" event for KLWP to use as a trigger. So that could be another topic for another day.

Otherwise, i love Niagra. Keep up the good work.

**Comment by 8bitPit** [comment]
Hi @vebulous, thanks for your list, I'd say the wallpaper should either be blurred or tinted with the color that Niagara also uses to tint the search button, for example. By the way, Niagara Launcher sends a trigger to KLWP whenever the list changes (e.g. von favorites to all apps list). Here's how you can listen for the trigger: https://niagaralauncher.helpscoutdocs.com/article/59-klwp-integration

**Comment by vebulous** [comment]
> Hi @vebulous, thanks for your list, I'd say the wallpaper should either be blurred or tinted with the color that Niagara also uses to tint the search button, for example. By the way, Niagara Launcher sends a trigger to KLWP whenever the list changes (e.g. von favorites to all apps list). Here's how you can listen for the trigger: https://niagaralauncher.helpscoutdocs.com/article/59-klwp-integration

This is EXACTLY what I needed. I shoulda looked deeper into this, but was distracted with other things. Thank you very much for pointing this out. Now I can implement any and all of the above scenaries with a simple broadcast trigger. This makes me happy.

There is one last issue I have with KLWP+Niagara that I'll need to figure out. The widgets/favorites area does not allow touch triggers on KLWP, so i can only tough the upper 40% of the screen. I'll open up a different thread for this when the time is right.

**Comment by 8bitPit** [comment]
Awesome @vebulous glad it helped :)

**Comment by 8bitPit** [comment]
Added in v.1.5 🎉
