### ISSUE TITLE
Show App-Version

### ISSUE THREAD

**Issue by Christian97EM** [8bitPit/Niagara-Issues#706]
Show app version of the respective app in the info card

I need this info more often and this would save the way to the settings

**Comment by 8bitPit** [comment]
Thanks for the request. Like @Maxr1998 said, most users don't care about the app version. I suppose that's why it's listed under "Advanced" in Android's settings. However, you could install an app called [Applications info](https://play.google.com/store/apps/details?id=com.majeur.applicationsinfo&hl=de) which lets you see each all app versions at a glance.

**Comment by Christian97EM** [comment]
Okay, it was just a Schnappsidee ^^
