### ISSUE TITLE
Pressing home doesn't take you to favorites

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#708]
> Do you know why pressing home button, didn't take to the home page, but to the drawer?
Is there an option to change this strange behavior of the home button?
Actually I need to do 2 swipe gesture to go to my favorite apps, after launching an app from the drawer...

>It should take you directly to your favorite apps if it took you more than ~7 seconds to return to Niagara

>Unfortunately in my case it doesn't work. Even after 20 seconds

**Comment by J-Gian** [comment]
I noticed a thing: the problem is generated by Xiaomi's gestures (MIUI 10.2.1.0 stable, Android P, Mi Mix 2S).

When you try to go home (favorites) with swipe-up gesture, the 7 seconds time-out never works.

If you deactivate screen gestures and use classics android buttons bar, the time-out works in the right way. 

It's a pity lose gesture options.

**Comment by 8bitPit** [comment]
@J-Gian, can you still reproduce the issue in v0.7.3?

**Comment by J-Gian** [comment]
> @J-Gian, can you still reproduce the issue in v0.7.3 (or 0.7.3a4)?

I'm trying v0.7.3 just now and it works fine.

No moro issue even with Xiaomi's gestures. Thank you so much!
