### ISSUE TITLE
I think I'm waiting so long.

### ISSUE THREAD

**Issue by jook1356** [8bitPit/Niagara-Issues#721]
I've been waiting for the solution of non-english sort not support. But I think I waited so long time. I think, developers don't know how important of non-english sort function is, because maybe developers' don't use non-english language.

I am not using Niagara launcher because non-english sort function is not working :(

I have a intention that I'm going to buy the donate version, if you release donate version on play store. So please fix this problem please.

I can't wait for the time that using this great launcher :)

**Comment by 8bitPit** [comment]
Thanks for your reminder. If you're referring to Pinyin support, it isn't easy for me to support it at all. Firstly, there is no 1:1 translation. Some libraries try word matching at first and if the word wasn't found in the match table, each symbol will be "romanized" individually. It's hard for me to test the process, since I can't read Chinese.
If you want to, you can add further comments at #234.
