### ISSUE TITLE
close right swipe menu after using

### ISSUE THREAD

**Issue by heqyoufree** [8bitPit/Niagara-Issues#745]
When I use right swipe menu to toggle ShadowsocksR, the menu would not close automatically.

**Comment by 8bitPit** [comment]
I'm sorry what do you mean that it doesn't close automatically? After opening a shortcut / notification?

**Comment by heqyoufree** [comment]
Yes, after opening a shortcut. I use the menu to toggle my VPN and after the shortcut is opened the menu would not close. I have to tap somewhere else to close the menu.

**Comment by 8bitPit** [comment]
Gotcha. Do other launchers close the shortcut menu after toggling your VPN?

**Comment by heqyoufree** [comment]
I have not use other launchers that have this function but it will be great if it close after using.

**Comment by disacrol** [comment]
Usually app shortcuts launch an activity of the app in foreground, but some specific apps like timers or VPNs may have shortcuts to trigger a background service. I'd guess that's related: Niagara may not specificaly close the menu on tap since an app will be launched anyway, but it might have to in case nothing is triggered on the foreground.

**Comment by disacrol** [comment]
@heqyoufree can you share which VPN app you're using?

**Comment by 8bitPit** [comment]
To better plan ahead and give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that are unlikely to be implemented this or next year (2021 & 2022). This is one of those, unfortunately. I'm sorry.
