### ISSUE TITLE
Search by their name on Play store

### ISSUE THREAD

**Issue by laggingreflex** [8bitPit/Niagara-Issues#753]
**Is your feature request related to a problem? Please describe.**

Some apps don't have the same name when installed as they do when they show up on Play store. E.g. "Boost for Reddit" on Play Store just shows up as "Boost" when installed. 

So when searching for "reddit" this "Boost" doesn't show up. 

**Describe the solution you'd like**

Search should use the names of the app they use on Play store. 

**Additional context**

Possibly related: https://github.com/8bitPit/Niagara-Issues/issues/145

**Comment by 8bitPit** [comment]
That's a good example. The feature could be implemented by parsing the Play Store site after an app was downloaded or pre-shipping the Play Store names from most popular apps. Hope you can understand that's a low priority feature though, because it isn't essential, I would say it's a neat little enhancement which could be useful for some apps.

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/647
