### ISSUE TITLE
Always show most recent apps in most-used app suggestions

### ISSUE THREAD

**Issue by scatterthought** [8bitPit/Niagara-Issues#756]
Sometimes I go from an app to the launcher, and I want to go right back to the app I was previously in. If it's not a favourite or a suggested app, I find myself scrolling through the list again to find and start it (I'm now conditioned to believe that Niagara Launcher's scrolling app list is always faster than cycling through Android's slow Recent Apps list). 

To this end, I would love to have the most recent apps show up in the suggestions (just one or two of them). This would make it blazing fast to swap between two apps that you're trying to use at the same time. Also, if you accidentally press the home button and leave an app, it would be easy to return to it.

Apologies if this has been suggested elsewhere. I searched the requests, but didn't see anything that sounded like this suggestion. Thanks for the great work!

**Comment by 8bitPit** [comment]
Thanks for your kind words :)
No, your request is no duplicate, thanks for searching.
Quite some time ago, I believe it was a year before the launcher was released, Niagara suggested recently used instead of most used apps. However I noticed that using Android's recent app menu, makes it redundant. Pressing the square button on the navbar and selecting your app from there is quite fast. Pro tip: If you're using Android 7+ you can switch between your last two apps by double tapping the square button even faster!

**Comment by scatterthought** [comment]
Thanks for the tip! I didn't know about the fast switching via double tap. I'd still love to see the most recent app in the suggestions, for those times when you accidentally back out of something, but I wouldn't consider it a high priority. Probably only worth doing it if were super easy to implement. Cheers!

**Comment by 8bitPit** [comment]
You're welcome. I came to the conclusion to not add the feature, because it would add another toggle to the settings and I want to keep it simple. I'll partly explain it in #808 why I want to keep the amount of switches minimal.

**Comment by scatterthought** [comment]
I agree. Since you told me about the double-tap on the recent button, I use it all of the time. ;-)

I'm much more interested in the #441, which I think will improve overall usability.
