### ISSUE TITLE
tuck the Niagara Wallpapers into the Niagara Settings

### ISSUE THREAD

**Issue by rd836** [8bitPit/Niagara-Issues#773]
Recapping the suggestion I've tacked onto two other issues, and #682 and #765, expressed in different ways.

Most succinctly:

Please tuck the Niagara Wallpapers _into_ the Niagara Settings, so there is only one item visible pertaining to Niagara.

In more detail:

In the Settings area, below our last letter, where the small circle takes us, we see the title "Settings" then the icon with "Niagara settings" followed by an icon and "Wallpapers."

Since for me using the Wallpapers is a once in a lifetime (of the phone) event, can it be put _in_ the Niagara settings? In other words, all I want to see is "Niagara settings". If I were to want to tinker with the Wallpaper, I'd prefer it be _inside_ the Niagara settings. Or let it be a Hidden app, to be gotten to like any other Hidden app.

**Comment by Bushmills** [comment]
Why? Isn't there a wallpaper selection feature in the Android settings already?

**Comment by rd836** [comment]
I've hidden the Android Wallpapers, but can't hide or rename Niagara's Wallpapers.

**Comment by 8bitPit** [comment]
I believe a lot of people don’t change their wallpapers regularly, I guess they just don’t care about the icon at the bottom, but I do understand that it can bother you. However, there is a very passionate showcase community. They want to change their backgrounds in a fast way, since they’re constantly changing their setups. They idea of being able to hide the icon from the list sounds like a good compromise for me.

**Comment by 8bitPit** [comment]
Well, I changed my mind :P Because you can also change the wallpaper by opening your wallpaper app, so users who often change it still have a way to reach it easily. This change as already been made in or 0.27/28 can't remember the exact release 😅
