### ISSUE TITLE
Hide app labels / app names / remove icon labels

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#79]
This issue is open, so you can share your thoughts it.

I tried hiding app names (in the favorite section) and noticed it was awkward. E.g., launching apps feels odd bc you don't tap on the label, instead you go for the icon, but they are placed on the left and reaching the top one feels uncomfortable. The labels also do function as visual guidelines.

It would look like this, in my opionion that layout is unbalanced:
![image](https://user-images.githubusercontent.com/9284845/45575183-dbe80a80-b872-11e8-823b-b79f1a8fce5e.png)

**Comment by sfosdal** [comment]
I believe there is a place for this feature.Perhaps not by itself, but here is a mock-up of what I was thinking about

**Comment by 8bitPit** [comment]
@sfosdal thanks for your mockup. There would be no place for showing incoming notifications though (you could place a dot next to the icon, but it wouldn't be that informative).

**Comment by sfosdal** [comment]
ah. that makes sense.

**Comment by sfosdal** [comment]
Btw, am really loving the new rename feature.

**Comment by sfosdal** [comment]
A feature to remove all renamed apps, and/or reset all "recommended apps"
(ie unhide)  would be nice.

**Comment by 8bitPit** [comment]
@sfosdal I agree, could you please open another issue on GitHub?

**Comment by Blue64Chevy** [comment]
I figured out a way to remove the labels from the favorites icons. Press and hold on an app, choose "rename", use the backspace key to clear the app name. Then press the spacebar key one time and save. This will save the app with no label. Enjoy!

**Comment by krismalfettone** [comment]
Labels hidden with the alphabet hidden. Feels very clean to me.  However being able to swap from the left side to the right side would be a welcome feature as well.

**Comment by sfosdal** [comment]
Using the alphabet from the left side already works on for me. The ui is on
the right, but you can still use it from the left.

**Comment by krismalfettone** [comment]
Ah you are right.  But I would love to be able to to put my labelless icons on the right :)

**Comment by cauerego** [comment]
> @sfosdal thanks for your mockup. There would be no place for showing incoming notifications though (you could place a dot next to the icon, but it wouldn't be that informative).

why no room? you can just move stuff around at will. i think this "cleaner" design makes a lot of sense, given the labels are there mostly for aesthetics...

the main question, though: is it really just visual? perhaps there's some practical stuff to say on leaving the labels on. for one, i prefer the launcher with minimum toggles configurable settings, and labels on is definitely the best option to please the majority of people (at least with a first impact). also, even if we do get used to labelless, truth is there will be unknown apps in our friends screens. and, for that, when showing up or lending the device to someone, there's a very practical utility to the labels. even if a minor utility it could be even critical.

so, i don't know. i'd say this is one of those things to be left for version 1.0 or 2.0 and using AB testing when the scale is large enough for meaningful data.

**Comment by 8bitPit** [comment]
> why no room? you can just move stuff around at will.

@cauerego you're right, but breaking the centered design by moving one app and showing just text for the app which has a notification the app that has attached would look odd.

**Comment by cauerego** [comment]
in my mind, i believe it would look fine. :)

**Comment by nidnme** [comment]
@8bitpit  honestly i agree with your opinion. It will destroy the functionality and design aspect.

**Comment by r2dn3** [comment]
I understand that you think it's awkward, but I think it can be combined with a calendar in the middle to literally have everything in the screen.

Even if it wasn't able to, I think the option should be there, because I would use it.

**Comment by honeytothemoney** [comment]
I'd love a have the option for a grid as home page. I know it's not as pretty and that's why I'm suggesting to have the option in settings. I have too many icons that I need and hate having to scroll down. It would be more accessible to me like this:
![47679560_2144584078926697_4270980002436087808_n](https://user-images.githubusercontent.com/39282345/49495842-5ef57d00-f832-11e8-93e1-99dd0bfc2d52.jpg)

**Comment by 8bitPit** [comment]
@honeytothemoney I believe a grid based design would break Niagara, see: #81.
To access apps faster, folders will be available at some point: #13

**Comment by cramseyio** [comment]
Hey all - new here. I recently downloaded and am loving this launcher. Thought I'd try and help contribute.

Personally, I like the look and feel of hidden names (currently, I rename all of my apps with a space to hide the name). I am still able to click where the app name would have been to launch the app, which feels natural to me and is easy to reach, without having to look at the names constantly. Another hidden bonus is that notifications are more visible because they take the space of the name until you view them.

If there was a "hide app name" option which simply hid the names and kept the launcher as-is, that would be awesome. Apps would still show up under the appropriate alphabet letter (this doesn't work if you rename to a space currently), you can already long press on an app to see more info which would include the name if you need to look at it. Just my 2 cents. Thanks for a great launcher!

**Comment by disacrol** [comment]
@8bitPit I also share that view, and prefer Niagara uncluttered from all sort of customization options, keeping it tweakable just as far as most people would want without breaking functionality. Also, I wouldn't myself hide names on the home screen. I prefer how it looks right now.
However, Niagara users on telegram keep asking for this feature, and it looks to me a lot of these people insist on showcasing their setups with all favorites renamed to an empty space just to get that minimalistic look, even though all favorites get placed in the "#" drawer section.
You see, people often stick with Niagara for its minimalistic approach, and I mean not only for having fewer customization options, but mostly for how it looks on the eye and feels on day-to-day usage.
Now as I understand this launcher was developed having single hand usage is mind, and it would for sure feel uncomfortable to reach the first items at the top if only the icon on the left is shown (although this is likely not a problem for left-handed). But this is, in my honest opinion, a feature that should be seriously considered to be added in Niagara settings, not only because it fits its minimalistic look, but also for its high demand by the users. Of course, disabled by default. And I mean an option to hide favorites names, not names in the drawer - that surely doesn't make sense and people don't look interested in that.
One last remark - it may be uncomfortable in some devices for right-handed users, but that would be an option for the user to enable/disable. I don't see why would this specific issue be tagged 'problematic'. But that's just my opinion.

**Comment by 8bitPit** [comment]
@cramseyio & @disacrol thank you both for your comments. I appreciate you wrote in such detail :)
I still don't want to add a toggle which let's you hide the app names explicitly, BUT how about introducing a transparency slider with color sliders, after this issue has been implemented: https://github.com/8bitPit/Niagara-Issues/issues/20. In mo opinion that would be a neat compromise.

**Comment by RockBoyEmy** [comment]
I'd say it would be nice. Could you not implement it so that even thought there is no text, the user doesn't have to tap the icon, but the whole "tile"?

**Comment by RockBoyEmy** [comment]
I love this idea with the transparency slider, it'd be indeed a pretty good compromise

**Comment by cramseyio** [comment]
A thought I had on the transparency slider - would it be for all text or just favorites? Part of the appeal (for me) of the concept of hiding the names is that you'd have no text shown for your favorites but you'd still see the text when you go through the alphabet to find non-favorited/less-used apps. If all the text was transparent (hidden), that may make it more difficult to find apps you don't use frequently.

**Comment by 8bitPit** [comment]
Valid point @cramseyio. So two different sliders would be needed. Then, a separate toggle for hiding just the favorite app labels would be better. Okay, guys you win XD

**Comment by IdmFoundInHim** [comment]
> Labels hidden with the alphabet hidden. Feels very clean to me. However being able to swap from the left side to the right side would be a welcome feature as well.
> _from https://github.com/8bitPit/Niagara-Issues/issues/79#issuecomment-429480726_

@krismalfettone See Issue #788 

---
Since nobody has mentioned it, the ability to hide labels on favorites _is_ now in Niagara. Are we waiting to close this issue until a transparency slider is implemented?

**Comment by 8bitPit** [comment]
> Are we waiting to close this issue until a transparency slider is implemented?
Nope, I just forgot to close the issue, thanks for reminding me :)

**Comment by 8bitPit** [comment]
Implemented in v.0.7.5a4

**Comment by paijojo** [comment]
it should be set to hide applications on the menu, but the application remains in the favorites list on the home screen.

**Comment by 8bitPit** [comment]
@paijojo do you mean something like that: https://github.com/8bitPit/Niagara-Issues/issues/440

**Comment by TFackler** [comment]
Just wanted to let people who stumble upon this how to actually achieve hiding the app names in your favorite app list (in v0.15.2).

Go to the bottom of the all apps list > Launcher Settings > Look > Text > check "Hide app names"

**Comment by 5ebbe** [comment]
> Just wanted to let people who stumble upon this how to actually achieve hiding the app names in your favorite app list (in v0.15.2).
> 
> Go to the bottom of the all apps list > Launcher Settings > Look > Text > check "Hide app names"

Thanks for posting this. I'd miss it otherwise 😂 Using the Niagara icon pack together with no names on favorites makes it really minimalistic. Next level would be transparent icons. They're there - but you can see them! 😂
![Uploading Screenshot_20220901-081516.png…]()
This makes me think about the possibility to maybe change the transparency on icons and text alike? Now maybe that already exists...

**Comment by 5ebbe** [comment]
![Screenshot_20220901-081516](https://user-images.githubusercontent.com/78618567/187845530-62a25913-604d-4375-b52a-33b1943de198.png)
No names on favorites with Nigara icon pack. Next level of minimalizm!

**Comment by TFackler** [comment]
@5ebbe 
Nice setup, there is so much going on in the wallpaper and you can see all of it :)

We looked into hiding app icons completely for favorites, but we really didn't like the way it looks. That's where Niagara Dots originates from. You can read more about this in #140
