### ISSUE TITLE
Cosutomize space between clock/weather widget and favourites 

### ISSUE THREAD

**Issue by hriddhidey** [8bitPit/Niagara-Issues#796]
The new 0.7.6a patch let's the user customize the space between the clock/weather widget and the top of the screen by long press and drag.

I'd really appreciate a similar feature to customize the space between the clock/weather widget and the favourites list. The two widgets and the first favourite are not equally spaced out. It's not a huge deal, but it kinda hurts my OCD, so was really hoping that could be customized/equalled.

**Comment by ancienttowers1** [comment]
Developer: Niagara looks amazingly beautiful, I do think it is going to be the, "new" Nova Prime. My phone is old, it warrants Novas Prime features honestly.
    HOWEVER...with such BEE-UTIFUL new Smartphones coming out in 2019, and most companies trying their best to satiate the ultra picky, "OCD", esthetic driven buyers - it seems a HUGE priority in buying a new pocket PC, is the screen. Virtually no borders and some actually are oozing over the edges.
    I said all that for not, but to make a positive point about the way Niagara looks once implemented onto one of the mega-screens...with excess vertical height, conservative horizons and widths to match.
    Soon, I will possibly end up with a supermodel pocket PC and when I do...it's Niagara, right from the get go. 

Sorry, I got caught up there. I was just going to express to the poster regarding his OCD. It just made me lol, because I TOO do the same thing. Except I only curse out loud and act like someone is giving a crap. HA!
     Ok, mr developer(s?). It is so obvious this guy (up above my response), loves your wizardry, mathematical, coding genius.
    You MUST give him the pleasure of quenching his OCD. TRUST ME, I studied medicine for a long time and worked in a hospital setting for eons. Don't be the person who exacerbated the OCD guys internal neuroses. Landing him in my care. Hell no. So be the SOLUTION. 

OKAY, I do act the clown, but I truly mean what I said about Nigga, I meant Niagara. It is simply beautiful and sleek. Minimal. To the eyes, we crave beauty AND minimal use of design...at least we have for several decades. 
Peace guys

**Comment by 8bitPit** [comment]
@hriddhidey thank you both for the request and the wholesome comment. Widget's will be supported in the near future, so you could replace the clock with a custom widget, e.g. with [7 Time](https://play.google.com/store/apps/details?id=com.codescape.seventime). More information about widget support can be found here: #117

**Comment by hriddhidey** [comment]
@8bitPit I'm not quite sure I could convey my request clearly. I'm not requesting for widgets or a replacement for the existing clock. I'm asking for whitespace padding-top above the favourites list so it doesn't look like it's too close to the clock (or whatever widget you may replace it with).

**Comment by 8bitPit** [comment]
@hriddhidey I'm sorry, my last comment worded confusingly. I meant, that you can customize the style of the clock by picking a custom widget and adjust the bottom padding by changing the height of the widget for example. I'm hesitating to add your requested feature as a dedicated option, because I don't want to overburden the user with options. One slider isn't much, but adding more and more customization options could get out of hand quickly, so I'm trying to focus on the essentials instead.

**Comment by hriddhidey** [comment]
@8bitPit that makes a lot of sense. Thanks a ton for clarifying!

**Comment by 8bitPit** [comment]
Great :D
