### ISSUE TITLE
align favorites to middle/bottom

### ISSUE THREAD

**Issue by terezo** [8bitPit/Niagara-Issues#808]
Hello,

What about stacking an favorite apps from bottom first (like bottom gravity or so). I think it would be more handy to have them closer to bottom of the screen to conveniently reach them. I would suggest time and date stick to top of the stack too. I use to click on time, and especially date quite often, to look at the calendar.

**Comment by 8bitPit** [comment]
Hi, with the latest alpha version from the Play Store, you can make the space above the clock larger, so every app will be easier to reach: https://github.com/8bitPit/Niagara-Issues/issues/112

**Comment by terezo** [comment]
Thanks! Just received that update and trying it out. Great to see that feature.

I have got one idea, wouldn't it be better if that app recycler has an fixed size instead of scrolling up together with time? In other words, time would have fixed position.

**Comment by 8bitPit** [comment]
Thanks for the suggestion. However, I believe it could visually weird, because the list would get cropped oft by an invisible line after scrolling to the bottom. Moreover, it would be difficult to navigate through the list when space is limited, e.g. when you're in split screen mode.

**Comment by terezo** [comment]
I do not see problem with first invisible cropping line. Eg. on my android P I already have such line on bottom of the list, above my see thru navigation bar. 

I do not know how often users use split screen. Anyway I do not see any problem with it, when I tryied.

I think this is just manner of personal opinion :)

**Comment by 8bitPit** [comment]
>	I do not know how often users use split screen

In my opinion, a good option should work in all kinds of circumstances. It would feel half-backed otherwise. Furthermore, I believe adding a toggle for all kinds of stuff is often problematic. You lose control of designing good user experience. Think of it like a combination tree. If you add 10 switches for example, there are 1024 possible combinations of their states they could be in. Niagara should feel polished regardless of the user’s settings, every switch makes the overall experience harder to maintain. That’s why I want to keep it as simple as possible. So, I would suggest using the inbuilt slider and align the favorites to the bottom.

**Comment by 8bitPit** [comment]
Closing for the above reasons.
