### ISSUE TITLE
Grid app drawer?

### ISSUE THREAD

**Issue by kshitijsubedi** [8bitPit/Niagara-Issues#81]
Instead of listed app icons how about grids.
Personally i feel uncomfortable with list display its really hard to locate app. If grid drawer would be there then scroll alphabet bar for apps would be more convenient.

**Comment by 8bitPit** [comment]
Sry, but that's against the launchers design. It would collide with the clean look and the notification previews for example

**Comment by gustperz** [comment]
You could keep the home as it is that is beautiful and simple, and the application drawer can have the two options list and grid, adding to the home all applications with pending notifications. #152 
I would love to have that in the future.

**Comment by yossi2010** [comment]
I'd love an option for a two or three column grid in the favorites without labels.

**Comment by 8bitPit** [comment]
@gustperz & @yossi2010  Yeah, but two different designs are more complicated to handle as a user & as the dev.

**Comment by neosushi68** [comment]
Hello. I'm a ux designer. I totally agree with @bitpit. I wouldn't add anything that collides with the Launchers unique design. I'd rather suggest using a different Launchers for your use case. Niagara is unique and such a change could kill the initial design idea behind. Please stick to the target design and enhance in things that are beneficial to the apps main intent.

**Comment by nidnme** [comment]
Agree with neosushi,
Im not an app developer or designer. But i will kill the uniqueness of launcher. This design philosophy is very unique and fresh looking.  there is no need for grid

**Comment by colbycdev** [comment]
It's not an app launcher with this design; it's a glorified app drawer

**Comment by 8bitPit** [comment]
If you're holding your phone like in the picture on the left, you can't use another finger for gestures.

![image](https://user-images.githubusercontent.com/9284845/50541713-a52cca80-0bab-11e9-93dc-d1f545c41aca.png)

**Comment by paijojo** [comment]
in appearance, what is used now is correct. simple, clean, unique. this is the best concept.

**Comment by paijojo** [comment]
do not need to follow the concept and arrangement of the usual and most launchers. everyone is tired of the ordinary and the most. most launchers with the usual concept are no longer used, there are not many who download them. everyone is bored with that monotonous look. it's time to move on to simple but fun concepts like the one carried by Niagara launcher. actually there is already a launcher that looks similar to the concept of the display of this launcher, namely Evie launcher. I have use evie Launcher and I really like the simplicity and uniqueness. but unfortunately Evie Launcher is still poor in features. evie launcher does not have a tap feature to turn off the screen, there is no feature locking the application using a password, etc, so that it still feels less satisfying in features.
