### ISSUE TITLE
Show favorites at the top of all apps list

### ISSUE THREAD

**Issue by josh1244** [8bitPit/Niagara-Issues#829]
So I really like the UI navigation in this launcher but I would like to be able to scroll up to my favorited apps. So when are I slide my finger vertically on the screen it brings me to the different letters but it does not put favorited above A. It just stops at A. So i propose to put *Ed above A

**Comment by 8bitPit** [comment]
I thought about the same some time ago and decided not to show the favorites above all apps. Aside from implementation issues, I would like to have it “symmetrical”: so, when you can access your favorites by scrolling up from the app list, you should also be able to scroll down from your favorites to see all your apps. The later would be problematic, because a lot of people want to have a clean main screen without the app list below. Furthermore, I couldn’t add a swipe up gesture anymore: https://github.com/8bitPit/Niagara-Issues/issues/122.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
