### ISSUE TITLE
Ignore stop words in sort order

### ISSUE THREAD

**Issue by stuaxo** [8bitPit/Niagara-Issues#833]
Hi, 
  I would like to be able to ignore stop words in the sort order. 

I couldn't find The National Lottery app as I didn't know the app name included “The" so was looking under 'N'.

**Comment by disacrol** [comment]
Just a personal opinion here: I'd consider that option a tad too specific for a launcher meant to remain minimalistic.

Specially because in such cases, you could add well press the search button and start typing 'National' or something.

And ignoring stop words by default could be confusing for a user that may expect them.

Again, I'm not saying your request should be denied - I just felt like giving my opinion 😉

**Comment by stuaxo** [comment]
OT:  I didnt know there was a search until I saw your reply and I've been using this launcher for a few months now.

**Comment by stuaxo** [comment]
I think iTunes was my real world inspiration for this.

**Comment by disacrol** [comment]
Yeah, iTunes is optimized like that since stop words are so often found on song titles, I guess.

**Comment by stuaxo** [comment]
I'm not sure what the right solution is, but I know that I only have a fuzzy idea of what apps I don't use often are called and don't want to search all the time.

**Comment by 8bitPit** [comment]
In your case, I would rename the app to "National Lottery", that can be done long pressing the app.

**Comment by stuaxo** [comment]
Cheers, I'm too lazy to find all the apps with stop words at the beginning and rename them.   I don't really use apps apart from the few on the frontscreen often enough to make it worthwhile.

Thanks for looking at this, will close.
