### ISSUE TITLE
Some widgets are squished in latest beta

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#873]
The shape of the search bar explains it all lol
https://photos.app.goo.gl/ZRhHSvRnPQC8znR2A

**Comment by 587saboor** [comment]
Lol just realized that happens with only sesame search widget so like idrk if i should close this, up to u Peter 😂

**Comment by 8bitPit** [comment]
Thanks @587saboor I can reproduce the issue. It's very likely that there is a bug in Niagara, because the issue doesn't happen on other launchers afaik.

**Comment by 8bitPit** [comment]
I've done some testing and it seems that the widget should have the maximally available width, it shows up improperly otherwise. I've opened two issues on Sesame's issue page (also on Github): https://github.com/SesameCrew/sesame_issues/issues/67 & https://github.com/SesameCrew/sesame_issues/issues/66
