### ISSUE TITLE
Integrate with Sesame

### ISSUE THREAD

**Issue by fookitt** [8bitPit/Niagara-Issues#88]
[Link to app](https://play.google.com/store/apps/details?id=ninja.sesame.app.edge&hl=en_AU)

Would be nice so that we can customize the shortcuts for the apps and better search functions. Unsure if its a Nova only extension.

**Comment by 8bitPit** [comment]
I believe integrating it to search is a “nova exclusive” feature. As soon as Niagara supports “legacy” shortcuts, adding Sesame shortcuts to the homescreen should work though. See #62 for that.

**Comment by praveen2203** [comment]
I believe sesame is better for searching through our phones. If I could make it launch by pressing home button instead of default search, it would be the best launcher out there.

I simple launcher shortcut will do without the integration. Workaround is to keep a sesame shortcut in favorites.

**Comment by kr428** [comment]
> I believe sesame is better for searching through our phones. If I could make it launch by pressing home button instead of default search, it would be the best launcher out there.
> 

Same here, same setup; this kind of integration would perfectly do.

**Comment by kagbodji** [comment]
There he's been discussion on the sesame thread about such integration. It seems the devs there are planning to provide an API any launcher can use. In addition, they seem willing to work directly with launcher developers to integrate. Hope to see a collaboration between these two teams in the best future! https://www.reddit.com/r/sesame/comments/aercay/are_you_guys_open_for_integration_with_other/

**Comment by 8bitPit** [comment]
@kagbodji thanks for letting me know, looking forward to working with them :)

**Comment by scarfa** [comment]
> @kagbodji thanks for letting me know, looking forward to working with them :)

Lawnchair launcher just integrated Sesame Shortcuts so it's not a Nova exclusive anymore.

**Comment by Martin5001** [comment]
This is probably NOT Nova exclusive feature as Lawnchair2 (latest version is currently available as APK only) integrates with Sesame and is referencing to Sesame integration library in their About section.

**Comment by fredskis** [comment]
This is pretty much the major piece missing from Niagara being a perfect launcher for me. Even better if a gesture like "swipe up on homescreen" could launch Sesame!

**Comment by fredskis** [comment]
> That could collide with scrolling when more than 8 favourite apps are selected. 

Is that any different than the current swipe down to expand notification shade?

**Comment by Martin5001** [comment]
I've tested this with longer list of favourites and the notification shade does not open if you are scrolling there, which is good because it prevents it from being opened accidentally. But if you were to use the same behaviour for the swipe up gesture, then you would have to scroll all the way down to the end of the list first, because it's needed to determine if the user wants to scroll or to trigger a gesture action.
But I am not a developer, maybe this can be solved in a way that I don't know about.

**Comment by hookshot1** [comment]
While swiping right to get sesame options would be ideal, I would love to just see the middle button tap at the bottom launch a sesame search instead of the integrated search in Niagra (Like you can do with nova). It'd be nice to have the option in the settings for this.

In addition to the obvious shorcuts, sesame's search bar will let you add search domains (app store, music, translate, maps...) so that you don't have to path around for your hottest search locations.

**Comment by 8bitPit** [comment]
Implemented in v0.30.
