### ISSUE TITLE
Single tap to show app/favorite list

### ISSUE THREAD

**Issue by jiopla4** [8bitPit/Niagara-Issues#891]
Hi, I' m in love with this new Launcher, and I'm in love with its minimalistic style. Only one thing missing: It would be great, for my taste, if the app list was hidden until you tap on the screen. So that you can watch entirly your wallpaper and also get your app list whenever you want with a single tap!

**Comment by 8bitPit** [comment]
Thank you for the kind words and for your request. To maintain a simple interface, I would like to keep the number of options as small as possible (see the comment at #808 for more info). However, I think you can achieve similar results like your requests by hiding the alphabet from the main screen and removing all your favorites and suggestions. I know it’s not ideal, because you don’t have any favorites that way. It is planned to include recently searched apps in the search screen, so you could navigate to often searched apps fast by just pressing the home button.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
