### ISSUE TITLE
option to center built in clock/date widget

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#895]
inspired by the ability to put widgets to the center with the latest alpha build, why not have an option to put clock/date widget be centered :p

**Comment by GeorgeSpelvin** [comment]
Or for the new widgets to be full-width?  Just added my shopping list widget and it's 2/3 width and left-justified.

**Comment by 587saboor** [comment]
@GeorgeSpelvin the new widgets are already able to be full width

**Comment by Rod911** [comment]
@GeorgeSpelvin 

> - You can choose between three widget horizontal alignment modes: default, filled and centered.
> - They are accessible by typing in hidden commands in Niagara’s search: “/widget default”, “/widget centered” and “/widget filled” respectively (every command is case insensitive and can be written without spaces).
> - Depending on your feedback they will also be accessible in the final version, but most likely with proper toggles to switch between them.
> - “Filled” goes almost edge to edge; it can be used for advanced widget setups. It is recommended to hide the alphabet on the main screen to prevent overlapping.

**Comment by GeorgeSpelvin** [comment]
Thanks, Rod.  "/widget filled" did nothing but "/widgetfilled" worked.  Unfortunately, the widget needs too much room vertically to be practical which is why I'm really hoping for an official widget page to be added.  Then I can use most of that page for my shopping list and the rest for the points card widget for quicker access, allowing the main Niagara screen to be super tidy.

**Comment by 8bitPit** [comment]
@587saboor, I'm merging the issue with: #188

**Comment by 8bitPit** [comment]
Merged with #188

**Comment by 8bitPit** [comment]
@GeorgeSpelvin feel free to join this discussion: https://github.com/8bitPit/Niagara-Issues/issues/117
