### ISSUE TITLE
3 home screen pages

### ISSUE THREAD

**Issue by eche779** [8bitPit/Niagara-Issues#913]
Great app. Please add the option to have more home screen pages, like one right and one left to have compatibility with KLWP for example or for widgets.

**Comment by 8bitPit** [comment]
I'm sorry @eche779, in my opionion the concept of having multiple screens doesn't apply well to Niagara. The launcher should remain simple & easy to use. Mreover, most gestures to switch to another screen are already taken or will be taken (e.g. swipe to the left, right, up or down, see #122 for the last one). Instead of a widget page, widgets can be placed inside app swipe menus in the future (see #117 for more info). For KLWP, I recommend removing some favorites and maybe dragging down the whole favorite list to the bottom (by holding on the clock). By the way, there is also a command to hide elements from KLWP while having the app list open: https://www.reddit.com/r/kustom/comments/bowoyg/about_br/

**Comment by eche779** [comment]
OK, I understand ...

I just share with you a screenshot in which I think the swipe right or left is possible below the favorites. 



Le 15 juin 2019 à 23:37, à 23:37, Peter <notifications@github.com> a écrit:

**Comment by 8bitPit** [comment]
@eche779: sorry, but a can't see the screenshot.

**Comment by 8bitPit** [comment]
I'll close this issue for now, but feel free to reply or open this issue again.
