### ISSUE TITLE
License for Redistribution

### ISSUE THREAD

**Issue by JoshuaDoes** [8bitPit/Niagara-Issues#915]
Hi, lovely launcher you've got here!

It's such a good launcher in fact, that I was wondering if maybe you'd be open to the idea of creating a license to allow redistribution of the launcher under certain circumstances. In this particular circumstance, I'm looking to see about including Niagara in my custom Android firmware called [Renouveau](https://github.com/RenouveauOS), which means "renewal" in French. And as the custom firmware's main goal is renewing one's Android experience, I believe Niagara fits the bill perfectly.

Should permission be granted either through a redistribution license or simply a given consent, the APK of Niagara would be redistributed through the ``android_vendor_renouveau`` repository for anyone who builds the firmware from source, as well as through any official and unofficial downloads of the Renouveau firmware.

Thanks in advance,
Joshua

**Comment by 8bitPit** [comment]
Thanks Joshua, Renouveau sounds like a wonderful project 😊
Because Niagara is relatively new and because I don’t have precise plans about Niagara’s future yet, I can’t promise you the rights for sharing Niagara forever, but I agree that you can share and distribute the APKs from GitHub for now. While I would like to see this issue-repo linked you don’t have to. Hope I could help you. Have a great time coding on your firmware.
Have fun working on your project, thanks for asking!

**Comment by JoshuaDoes** [comment]
Thank you very much!

I believe it'll be a great way to introduce people to this launcher and get their devices going strong. I'll go ahead and add the necessary things to get this rolling now. I will link this issue as well so anyone checking out the source code will come back here and see.

**Comment by 8bitPit** [comment]
Great :)
