### ISSUE TITLE
Edit mode: Widget vs apps context menu inconsistency

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#943]
**Is your feature request related to a problem? Please describe.**
When I tap an app icon while in edit mode, it automatically opens context menu so no need to long press. But when I want to remove widget I must long press, otherwise it just opens the widget app.

**Describe the solution you'd like**
I think widget should open the context menu on tap, not long press, too so it would be more consistent.

**Comment by 8bitPit** [comment]
Yup, it's inconsistent. I thought about removing the option to just tap on an app to open its settings, because the long press gesture should be associated with settings. When just tapping on an app I prefer that a message pops up that reads: "Hold on an app to open its settings" A couple of users might even learn the gesture that way (You can also enter edit mode without having long pressed once in Niagara). Believe it or not, but some people out there don't know about the gesture.

**Comment by 8bitPit** [comment]
This has been implemented in v0.8.2
