### ISSUE TITLE
design elements

### ISSUE THREAD

**Issue by emijomo89** [8bitPit/Niagara-Issues#945]
Hello! I love the launcher and I have a couple of suggestions that really could take it the last stretch to make it perfect. 

I get that the point of the launcher is to be minimalistic and not a lot of clutter, so I understand and respect that you don't include widgets and other features and that's actually what drew me to it more.

I have 3 suggestions only:
**1.** That the margins of the alphabet on the right and the apps on the left is the same on both sides, for symmetry purposes. 
**2.** The inclusion of a google search bar (not just search button - as it currently is it looks like an afterthought rather than a design element), either in the top or at the bottom. 
**3.** The use of notification dots for the apps instead of/in conjunction with the current method.
See an attached image of how my proposals would look like:
![image](https://user-images.githubusercontent.com/53441277/62061644-a67fad80-b1f5-11e9-88f1-081d3bd21799.png)
A fourth suggestion would be the possible inclusion of a left pane with some sort of google feed or google now support, or even any feed that you can get on it (Microsoft news or flipboard) but I see that this has been requested before. 

Please consider these and  let me know what you think
Thank you!

**Comment by emijomo89** [comment]
As an alternate suggestion, you could use the smaller margin size for both.

**Comment by emijomo89** [comment]
Another idea, the possibility that the alphabet can be hideable by a swipe to the right to hide it and to the left to bring it back.

**Comment by 8bitPit** [comment]
Hey @emijomo89 , thanks a bunch for all your suggestions. I'll go through one by one:

1. The margins are purposefully not the same in order to balance out the layout. Because the app icons and scrollbar areas are drastically different a symmetrical layout wouldn't look that good to my mind. Moreover, an invisible scrollbar shows up when tapping on the left space, so the margins couldn't be reduced. On the other hand, the app list would suffer from a larger margin on the right on small screens.
2. The button can definitively be improved. I’d like to replace it with a “Niagara button” from where you can launch any app of your choice, not just Google. However, I’m not getting the advantages from having a bar instead of a button, apart from being more prominent.
3. https://github.com/8bitPit/Niagara-Issues/issues/800
4. Sorry, I’m currently not planning to integrate Google Now. You can read more about this here: https://github.com/8bitPit/Niagara-Issues/issues/3
 5. The alphabet can already be hidden. It doesn’t work the same way that you suggested, but in my opinion, one option is enough.

Wish you a nice weekend 😃

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
