### ISSUE TITLE
Hide the notice that says “Set Niagara as default launcher”

### ISSUE THREAD

**Issue by Vanrice-x** [8bitPit/Niagara-Issues#949]
Hey,guys, I had a problem when using Niagara, because of I am using Huawei Mate20(Chinese version) ,sadly they blocked Third-party launcher, I can't set Niagara as the default launcher, but I solved this problem temporarily by using Fluid Navigation. Colud you guys hide the following notice, "Set Niagara as default launcher" ,please ,THX SO MUCH!!I really enjoy using Niagara launcher!
![Screenshot_20190802_160229](https://user-images.githubusercontent.com/53599113/62356272-45344300-b543-11e9-9086-8740e0de2bf6.jpg)

**Comment by 8bitPit** [comment]
@Vanrice-x sorry for the inconvenience. Maybe I'll add a button to not show it again or something similar. Because this issue does affect a very small user base, it doesn't get a high priority.

**Comment by Vanrice-x** [comment]
@8bitPit First of all , thank you for notice my issue ,I know it's only affect a small user base ,but I still hope that you can add the Button ASAP ,I really appreciate that ,thx again !

**Comment by 8bitPit** [comment]
👍 I'll reopen this issue though, so I can track which features have been implemented and which ones have not.

**Comment by mirfalltnixein** [comment]
Hi! I'd like an option like this as well.

My use case is opening a different launcher based on whether I'm at work or not. I do this using Tasker and Autotools. It requires me to set Autotools as default launcher, which then decides on the launcher to open when I hit the home button. 

Sadly, because Niagara isn't the default that way I'm stuck with that message. A lot of launchers have an option to disable similar prompts, I'd very much appreciate this here as well. Thanks!

**Comment by 8bitPit** [comment]
Hi, interesting use case. I'll probably add a [hidden command](https://github.com/8bitPit/Niagara-Issues/issues/698), that disables the "Set as default" message. Sick user name btw 😉

**Comment by mirfalltnixein** [comment]
Thanks, and thanks! I'm looking forward to it!

**Comment by 8bitPit** [comment]
Maybe we could add a hidden command that is accessible via Niagara's search to hide the notice. It would work like this: You open Niagara's app search and enter /hideHomeNotice and the message would stop showing up. What do you think?

**Comment by shmykelsa** [comment]
@8bitPit I think it would make so much sense.

**Comment by chrismin13** [comment]
+1 for this request! I'm using Niagara as my secondary launcher, as I really love the scrolling alphabet, but I still prefer a traditional layout for my homescreen sometimes. I don't think however that it would be a good idea to add it as a hidden command, since that's a little tricky to find. An option in the settings would be ok as well, but I understand you don't want to be cluttering them up with useless features. Instead, I think it would be quite intuitive if you could hold the notification and hide it permanently! 

Let me know what you think, and thank you for the wonderful launcher!

**Comment by 8bitPit** [comment]
Great news, this can now be done with the [secret command](https://help.niagaralauncher.app/article/74-entering-hidden-commands) `/suppress set launcher prompt` 🎉

**Comment by 8bitPit** [comment]
This feature was added in v0.34.0. You can already try it out before it hits Google Play: https://github.com/8bitPit/Niagara-Issues/releases

**Comment by 0-BlackSpectrum-0** [comment]
This message is still there, how do I remove it?
nvm found it, my bad
