### ISSUE TITLE
Detailed suggestion for category implementation

### ISSUE THREAD

**Issue by pionearly** [8bitPit/Niagara-Issues#950]
Different app categories have been suggested multiple times already, I wish to add an idea as to how they could be implemented, which might help decide on a version or give new ideas for coding, or it may just tickle someone's fancy but be ignored, that's fine as well. 

Idea: Apps being sorted manually or automatically using Googles play store categories if possible but with manual override. Nothing too fancy so far.

Add to this an option to allow an app to only be in one category simultaneously or in multiple ones (makes manual sorting easier imo). 

Implementation: by having a gesture (easiest would be a simple horizontal swipe I guess) to switch between categorized home screens. 

First one would be the default with all apps in its list as it is now, then when switching to another category, it would show a second set of favourites, selectable only from the assigned category. 

It would again have another a list below, just as it is now or would be on the default screen, but only showing apps from said category. Repeat for every category the user selects, resulting in the Niagara fallS instead of just one fall. 

I am no developer so I don't know how feasible this is, but I hope my suggestion was detailed enough to give you some ideas 😊

**Comment by Martin5001** [comment]
This could be nicely combined with #165.

**Comment by 8bitPit** [comment]
Hey @pionearly, thanks for going so much into detail. Here are my thoughts on this: 

> Apps being sorted manually or automatically using Googles play store categories if possible but with manual override. Nothing too fancy so far.

I did some experiments with Play Store categories (even before I released the launcher to the Play Store). But in my opinion there are way too many categories. I would prefer just a handful of categories but those could be made contextual. I wrote more on that [here](https://github.com/8bitPit/Niagara-Issues/issues/13): _I would also like to add another categorization features as well. Here’s the deal: it wouldn’t be one system which works the same for every category: it would be tailored to each category individually.
For example: Every app which is placed in the music category will show up above your favorites when you connect your headphones / speakers. Games could be filtered out in the app list and added at the bottom. So, they get an own section which has a controller, or something related as an icon.
A message/mail folder on the other hand can always be accessed from within the favorite list, but every app which has a notification attached will be shown in the favorites directly.
Those are just some ideas and the challenge would be to keep it simple, so it should feel intuitive how each category works._

>Add to this an option to allow an app to only be in one category simultaneously or in multiple ones (makes manual sorting easier imo).

This will be possible. 

Because the contextual categories won't cover all different types of apps, I'd like to add another folder-like feature: _Swiping opens shortcuts & notifications instead. I also thought you could add custom shortcuts / widgets & related apps there as well._

Hope you like my ideas :)

**Comment by 8bitPit** [comment]
Merged with #13
