### ISSUE TITLE
Widgets: Top padding handle

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#951]
Written by @aisymn on Telegram:
>In Edit mode, there should be total of 3 handles. First two for the widget, which will let resize it as needed. & the third for the list of apps to move up/down.
Why do we need that? The answer is, when you want your list to be close to the bottom of the screen, you drag the second handle to adjust the app list, but if affects the size of the widget area, which affects the widget's size itself. As a result, it happens that widget had to be bigger (read, zoomed in or font/icons being bigger in size) than we want it to be or the padding not being symmetrical. Which totally is aesthetic preferences, ik, but still I'd love to see some flexible options there.
If we have a third handle dedicated to app list, it'll let us adjust the position of it without interfering with widgets.

**Comment by MyChiMan** [comment]
![Screenshot_20200103-080953](https://user-images.githubusercontent.com/47807792/71711285-8eddce00-2e00-11ea-9ccd-b655bc961d25.png)


I think i have same issue described. No matter how much I pull up the whole list in edit mode everything automatically snaps back to some predestined position.
I had to install a widget "Another Widget" in response to google charging for free weather. (Don't we give them enough!)
It's actually very fiddly if i remember. I have been using your launcher for ages because of its clean simplistic look and use - however as you can see at the bottom of my favorites it no longer looks clean and simplistic.

Upon resizing the widget the margins are Much larger than the text and making it smaller is possible however the clock text also gets to small or disappears slowly out of the boundaries of the widget.

![Screenshot_20200103-082423](https://user-images.githubusercontent.com/47807792/71711697-77074980-2e02-11ea-8333-4983d2cebd24.png)

There is too much space on either side of widgets.
As you can see I have been playing with different settings on the widget however the problem persists with the space you force around a widget.
My icons are already at your smallest.

Seeing as it's possible to open edit mode by long pressing on any app or widget do we really need this wasted space? Can we shorten it especially at the top! 
Highly frustrating having that blank space there whole my favourite apps are pushed below my screen.

**Comment by disacrol** [comment]
Maybe I'm missing something, but the "move whole list" option doesn't work for you to specify exactly how further up/down the clock/at a glance widgets will go? Note that you must tap the "apply" button in the bottom right of the screen to apply any changes performed in edit mode.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
