### ISSUE TITLE
Notification Filter

### ISSUE THREAD

**Issue by avax96** [8bitPit/Niagara-Issues#953]
There are always some notifications which are not important but can't be avoided altogether. Idea is to filter out the low priority apps and the respective notifications from these apps won't pop up. they will go straight out in a predetermined area (a separate screen to the left of home)

Please try using "before" launcher. This feature is actually the one they have in their app.
It enhances the minimalistic experience.

**Comment by 8bitPit** [comment]
Hi @avax96. In fact, there is already a notification filter present, it hides low priority notifications from the homescreen. Additionally you can exclude notifications from certain apps on Android Oreo and above. All you have to do is to long press on an app, tap the *i* symbol, and go to the notification settings. Then, disable "show notification dots/badges".
Furthermore I'm against a whole new notification screen, because all notifications are already shown together in Android's notification shade. However, I'd like to bundle all messaging notifications and show them in a dedicated category: #152

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
