### ISSUE TITLE
Different icon pack for favorites menu and app drawer

### ISSUE THREAD

**Issue by RawSlugs** [8bitPit/Niagara-Issues#955]
I have a specific minimal icon pack that i use for the apps in favorites to get a clean home screen, its white lined icons.. but i want in the all apps section for it to be more colorful 

Can it be added when an custom icon is set on the home screen/favorites is doesn't change in the "app drawer" as well?

**Comment by Martin5001** [comment]
This would really help me too.

**Comment by 8bitPit** [comment]
Hey guys. I think this could also help: #440 (being able to hide favorites from the app list). Once this feature has been implemented, no additional toggles need to be added, but you could still have different icons for your favorites (via the custom icon selection menu).

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.

**Comment by Martin5001** [comment]
Hiding favourites from the app list is a good idea and would solve this pretty well, but I'd prefer it to be optional because sometimes you just automatically scroll the alphabet and don't realize at the moment so I think it might confuse someone.

(Generally I think that avoiding as much toggles as possible generally is not a good idea, although I understand you want to keep it simple, but it's possible to just set some default values but still offer the option to change – but that's more related to general concept.)

**Comment by 8bitPit** [comment]
Agreed, this should be optional. I don't think we even need a toggle though. I'd like to change the behavior of hidden apps: If you hide an app, you can still keep it as a favorite app - it's just hidden from the app list and won't be suggested below your favorites (https://github.com/8bitPit/Niagara-Issues/issues/221).

**Comment by Martin5001** [comment]
That's probably the best solution. (Note: there should definitely be some kind of guide or note so users will understand this behaviour, because usually hidden means hidden completely.)

**Comment by 8bitPit** [comment]
@Martin5001 yeah, good point.
