### ISSUE TITLE
Dedicated group for "new install", "most used", "recent used"

### ISSUE THREAD

**Issue by MarcAlx** [8bitPit/Niagara-Issues#971]
**Is your feature request related to a problem? Please describe.**

Today I think it would be useful to have access to the following lists in a consistant way (same place & easily foundable) : 
- new installed app
- mostly used (which is actually "Suggestions" I think)
- recent used

**Describe the solution you'd like**

My solution is simple : these sections could have dedicated group/place in alphabetical list. This way it would not clutter home screen.

Exemple :

Today we have : 

☆
A
B
C
D
...

With my suggestion it would be :

☆
🕙
🏆
🆕
A
B
C
D
...

Where the emojis mean: 
🕙 : Recent apps
🏆: Mostly used (if possible to implement)
🆕 : New installed apps

Of course emoji could be replaced by clean icon like the ☆ one.
 It could also be disabled from settings and visible only if it contains elements. 
Further improvement could let user replace favorites on homescreen by Recent, Mostly used...

PS Hoping that this is not a duplicated suggestion. Only found partial ideas/suggestions : 
- https://github.com/8bitPit/Niagara-Issues/issues/227
- https://github.com/8bitPit/Niagara-Issues/issues/376
- https://github.com/8bitPit/Niagara-Issues/issues/57
My suggestion is mainly related to the way these lists could be displayed easily.

**Comment by 8bitPit** [comment]
Hey @MarcAlx, thanks for the great ideas and explanation! Around one year before its release the two most recently used apps where suggested below the favorites. However, I noticed that they were redundant, because Android already has a recents screen. That's why suggestions now only show the most used apps (as you thought). Additionally, suggestions are meant to save you one tap, so to my mind they make more sense below that. Moreover, the user never knows what Niagara suggests him, so many wouldn't even scroll to the most-used-category, because they don't know if they find the app they want to open there. 
What I do like to implement is an extra section for recently installed apps. The most clean approach would be to have these apps placed in the search screen (when the user's search query is empty). In that way you can also simply ignore them. To indicate that new apps can be found there I'd show a little badge indicator on the search button. How about that?

**Comment by MarcAlx** [comment]
Thanks for all this precisions. 

> However, I noticed that they were redundant, because Android already has a recents screen.

What I understand is that recent app are useless because they are shown in the menu open with the android square button. With that in mind it's clear that recent apps are useless to display in the launcher.


> Moreover, the user never knows what Niagara suggests him, so many wouldn't even scroll to the most-used-category, because they don't know if they find the app they want to open there.

Personally my homescreen is not scrollable I have 8 icons. Users with many icons (more than 10) are likely the kind of users that want all their most used app on screen and not just the top most needed. Maybe it's ok for them to disable suggestions as in this case suggestions are no more a shortcut, because they have to scroll. What's also possible is to let people move suggestions section on top of the screen between the widget and favorites list.


> The most clean approach would be to have these apps placed in the search screen ... How about that?

It's very clean, I don't know if the badge is usefull, as users may already knows if they have newly installed app. Easy access to recently installed app is like (to me) a "no brainer" : "Where's that app I recently download ?" 
As your alphabetical menu is very practical I don't use search screen, that's why I suggests you to include recently downloaded app in there, an app in this section could be flushed after X days when the section is empty -> it goes hidden. (this suggestion is not incompatible with your search screen proposal).

**Comment by 8bitPit** [comment]
Merged with #227
