### ISSUE TITLE
Acast media image, disappears when paused

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#980]
When pausing the Acast player, suddenly the media image disappears. This does not occur with any other media players I've tried.

![Screenshot_20190903-182511](https://user-images.githubusercontent.com/43126233/64191689-4ece0500-ce79-11e9-8a65-5c325ac4a572.png)
![Screenshot_20190903-182516](https://user-images.githubusercontent.com/43126233/64191695-51c8f580-ce79-11e9-8837-6664677a0848.png)

**Comment by 8bitPit** [comment]
It seems that this is a bug by the media player, I believe they stop providing the artwork when the player pauses. You can confirm this by going to the lock and show if the wallpaper shows up there instead of the media player (This feature is not available on any Android version/ROM though, I believe it was introduced in Android 8, but I'm not sure anymore).

**Comment by 8bitPit** [comment]
Merged with #485
