### ISSUE TITLE
Navigation buttons issues on Android 10

### ISSUE THREAD

**Issue by supermueller** [8bitPit/Niagara-Issues#984]
**Describe the bug**
The navigation button for switching apps have issues on Android 10 when the launcher is in front.

The gesture for jumping back to the last used app by dragging the home button to the right does not work. It shows only a kind of ghost image but do not bring the last used app to the front. 

This will only happens with the two button navigation (known from Android Pie) is selected.

**To Reproduce**
1. Select the two buttons gesture navigation in the preferences of Android 10 (see screenshot)
2. Bring launcher to front by pressing the home button.
3. Try to switch to the last used apps by swiping the home button to the right.
4. The last used app will not show up.

**Smartphone (please complete the following information):**
* Device: Essential Phone
* Android version: Android 10

**Screenshots**

![64212301-3675de80-cea9-11e9-83f3-db1373346348](https://user-images.githubusercontent.com/2378496/64317120-0583cf80-cfb7-11e9-9e7e-e7c5ca06189f.png)

**Comment by 8bitPit** [comment]
Hey @supermueller, I could also reproduce this on my phone (I have an Essential phone, too 😁). Since Android 9/Pie, the launcher also takes care of the recents menu. However, third party launchers don't have the permission to do that: https://www.androidcentral.com/android-pie-recents-system-launchers-only. That means, Essentials launcher is responsible for the recents menu, including handling gestures. It's a bummer that I can't help. Nevertheless, thanks for the detailed bug report, it would be great if everyone provides as much information as you do.

**Comment by nmabhinandan** [comment]
I'm facing same problem in my Nokia 7 Plus (even after the December update)

**Comment by supermueller** [comment]
@8bitPit I hope it’s okay to use this thread to contact you. After 3 years I am still using my beloved Essential Phone—but now the battery capacity is very poor. Do you have experiences with changing the battery?

**Comment by 8bitPit** [comment]
@supermueller, sorry, I haven't changed its battery, I moved on to the Pixel 5, so I can test the latest Android versions as soon as they arrive. @Maxr1998 also had an Essential phone, he might be able to you help you. It's such a shame phones don't come with removable batteries anymore, especially because the hardware of phones isn't improving much anymore.

**Comment by Maxr1998** [comment]
> @8bitPit I hope it’s okay to use this thread to contact you. After 3 years I am still using my beloved Essential Phone—but now the battery capacity is very poor. Do you have experiences with changing the battery?

I haven't been using my Essential Phone for quite a while either (moved on to the Pixel 5 and now the Z fold4) but I replaced the battery in 2019 or so.

It's relatively easy all in all, except the part where you remove the screen with heat. I scratched up the underside of the glass pretty badly at the sides, which caused an relatively annoying backlight bleed after reassembling it. Also, glueing it back together isn't trivial, since the edges are very slim and I didn't manage to get consistent glue strips all around, which resulted in some slight wiggle. Thankfully, it wasn't too bad since I used a case.

I suppose all in all it doesn't hurt to try, but definitely watch a video on it first and be careful while doing the replacement.

**Comment by supermueller** [comment]
@8bitPit Thanks for forwarding this.

@Maxr1998 Thanks for sharing your experience. Theres a tutorial on ifixit, but they are also mention that removing the screen is not that easy. I am afraid that I will break it and then have to send the phone to retirement. Unfortunately there is no actual (Android) phone that IMHO can reach the aesthetic standard set by the PH-1.
